### ISSUE TITLE
XmlSwitch storeResultInSessionKey should store chosen forward in session key instead of input

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#1003]
**Reporter**
Laurens/Bastiaan

**Is your feature request related to a problem? Please describe.**
Currently it is not possible to store the outcome of the XmlSwitch pipe in a session key, when used with a stylesheet to determine the forward.

Usage of the attribute "storeResultInSessionKey" on XmlSwitch results in the input being stored in the session key.

**Describe the solution you'd like**
The actual outcome of the XmlSwitch, when used with a stylesheet, to be stored in the specified session key.

**Describe alternatives you've considered**
 There is a work around available by using a seperate XsltPipe and XmlSwitch without a stylesheet attached to it.

**Additional context**

**Comment by jacodg** [comment]
Output is always input (a switch doesn't change the message). We might need an extra attribute storeForwardInSessionKey.
