### ISSUE TITLE
Feature request: Error message "No XML input" instead of "Premature end of file" 

### ISSUE THREAD

**Issue by francisgw** [ibissource/iaf#1020]
**Is your feature request related to a problem? Please describe.**
When a XmlSwitchPipe is used and the adapter is activated via a http POST request, no XML input is used in the adapter causing the framework to give the error message "premature end of file" instead of something like "no xml input"

**Describe the solution you'd like**
A little more elaborated description of the error.

**Comment by jacodg** [comment]
This will be to specific for a general framework. It's better to add this to a Frank! developer FAQ
