### ISSUE TITLE
LocalFileSystemPipe doesn't move/copy files to the root of a drive

### ISSUE THREAD

**Issue by francisgw** [ibissource/iaf#1029]
**Describe the bug**
When the action is set to move, ladybug reports that the operation was successful while in reality nothing happened. When the action is set to copy, ladybug reports an error saying "FileNotFoundException" for the destination and "Access is denied" for the file.

**Category** 
- Frank Console
- Frank Framework
- Ladybug 

**To Reproduce**
1. Write an adapter with LocalFileSystemPipe
2. Set filename for an existing file on your computer
3. Set destination to the root: C:\
4. See when testing pipeline that neither copy or move are done

**Expected behavior**
Either both move and copy give the same error like "access is denied" or both report success and actually do the operation.

**Environment:**
 - Tomcat
 - Edge, Chrome
 - IAF Version 7.6-20200615.130305

**Comment by gvanbrakel** [comment]
To move or copy files from/to anywhere on the local filesystem, the root attribute must be specified, e.g. like "c:/". All file and folder references are relative to this root. When no root is specfied, it is equal to the 'current' directory.

**Comment by gvanbrakel** [comment]
Reopened, because the case where LocalFileSystem.root is empty was not tested.
