### ISSUE TITLE
ResultSetIteratingPipe does not have useNamedParams option as database senders

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1031]
**Describe the bug**
The ResultSetIteratingPipe misses the useNamedParams for queries that are available on the database senders. 

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
1. Create an adapter with a ResultSetIteratingPipe with useNamedParams="true"
2. Start Frank
3. See warning that ResultSetIteratingPipe "does not have an attribute [useNamedParams] to set to value [true]"

**Expected behavior**
That the ResultSetIteratingPipe has the option to use named params.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Tomcat
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.5-RC3

**Additional context**
N/A

**Comment by Laurens-makel** [comment]
Hi Ricardo,

The "useNamedParams" attribute is an attribute of the JDBC query sender base, you should use the attribute on your sender, not the pipe containing the sender.

![image](https://user-images.githubusercontent.com/37303445/92084413-a58d5800-edc7-11ea-9bc5-94fdf10b0036.png)
