### ISSUE TITLE
Flowcharts and documentation break without hardcoded success forwards

### ISSUE THREAD

**Issue by buckmaz** [ibissource/iaf#1033]
**Describe the bug**
When <**Forward name="success"** > has not been set, while a <**Forward name="exception"** > has been set, the documentation and flowcharts break. Also XmlIf pipes do not work without explicit forwards, and the firstPipe attribute cannot be omitted.

The ability to work without hardcoded forwards or FirstPipes is a welcome one, as pipes tend to be moved around and new pipes will be interposed, and this minimizes errors from incorrect forwards. However, this bug, especially for the flowcharts which are used as concise way of showing the adapter flow to e.g. testers, all but prevents us to use this functionality.

**Reporter**
Bastiaan Udo / Ali Akcan

**Category** 
 - Frank Console

**Expected behavior**
All pipes should be correctly included in the flowcharts and documentation.

**Example**
adapter code:
https://vcs.aws.insim.biz/ibissource/dm/ibis4oma/ibis4oma_oma/-/blob/master/src/main/configuration/oma/Configuration_MarkBulkMessageReady.xml

corresponding Flowchart:
https://srdzzapp0424.insim.biz/ibis4oma/iaf/api/adapters/MarkBulkMessageReady/flow

corresponding documentation
https://srdzzapp0424.insim.biz/ibis4oma/iaf/gui/#!/customView/Documentation >> oma >> MarkBulkMessageReady (full link not possible?)

**Comment by jjansenvr** [comment]
Adapter flow generation relies on the availability of explicit forwards. configuration xml is translated to a dot file bij a xslt. 

f.e. if you have a switch pipe you will need to explicitly name all forwards. 
I do not see the usecase for not using the explicit forwards, with explicit forwards we can also check the validity of the created flows.

Can you explain why you cannot use explicit forwards?

If you have a way to fix this xsl to also work without explicit forwards be my guest :)

https://github.com/ibissource/iaf/blob/9da456e90e9a1cc903e2d337267cb51ab1c97dcb/core/src/main/resources/xsl/configuration2dot.xsl

**Comment by buckmaz** [comment]
I believe the explanation as of why it's easier to work without explicit forwards is in the original post (Richard vd Stel also prefers this way of working, I believe). 

If you name explicit forwards on an XmlIfpipe, you will get a console warning, so that seems contradictive.

You seems to be of the opinion that it can't be fixed, that of course be the outcome. But then the ability to not use explicit forwards should be removed from the Framework, as it breaks other functionality, and you don't want to encourage that.

**Comment by gvanbrakel** [comment]
I agree that flowchart and documentation should work correctly for Pipelines without an explicit firstPipe setting, and for Pipes without an explicit 'success' forward. In those cases the first respectively the next Pipe of the Pipeline is chosen.
This simplifies the configuration, and makes it easier to analyze and understand.

**Comment by jjansenvr** [comment]
@gvanbrakel i think this would mean a change of approach, the xslt creates lists from-->to  pairs that are translates to  dot language. If we need to also take in account the next element when no explicit reference is available it might be better to use a programming language instead off xslt. 

in my opinion this is a nice to have and i prefer the option of using explicit forwards which  I now use as a best practice

**Comment by alisihab** [comment]
DocumentationPipe is currently not supported by the core team.
