### ISSUE TITLE
Feature request: LocalFileSystemPipe write_append option

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1043]
**Reporter**
Ricardo

**Is your feature request related to a problem? Please describe.**
I am working on an adapter that needs to store records to a file. Based on the metadata the exact file is determined. For the first record that is written to a specific, the file will not yet exist. The deprecated FilePipe has the option to write_append, but the LocalFileSystemPipe does not have that option.

**Describe the solution you'd like**
The LocalFileSystemPipe to also have the write_append option as the FilePipe.

**Describe alternatives you've considered**
N/A

**Additional context**
Workarounds are using the FilePipe or use pipes to emulate the write_append (by checking if the file exists and then route to a LocalFileSystemPipe with the write action if the file does not exist).

**Comment by gvanbrakel** [comment]
The LocalFileSystemPipe has implemented this using action="append"

**Comment by ricardovh** [comment]
Thank you, that indeed does it.
