### ISSUE TITLE
Feature request: bigint as data type for parameter

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#1051]
**Reporter**
Laurens / Richard

**Is your feature request related to a problem? Please describe.**
The parameter tag doesn't support the BIGINT data type, which forces the DB server to do data type conversion.

**Describe the solution you'd like**
Bigint data type to be added

**Describe alternatives you've considered**
None, we do not want to do data type conversion in SQL.

**Additional context**

**Comment by gvanbrakel** [comment]
Another approach could be to avoid the use of bigints in the database itself.

**Comment by Laurens-makel** [comment]
After talking to Richard / Arnold I understand what you are saying, in this particular case it was not recommended to use bigint. 

Although that doesn't take away that the data type is still missing and there might be use cases where one would like/have to work with bigints.

**Comment by jacodg** [comment]
Let's "fix" this when we have a specific use case and has become an actual problem
