### ISSUE TITLE
ResultSetIteratingPipe gives (incorrect) warning for potential SQL injections

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1058]
**Describe the bug**
When using a ResultSetIteratingPipe, the following warning is shown:
`The class [nl.nn.adapterframework.jdbc.JdbcIteratingPipeBase$MixedQuerySender] is used one or more times. Please change to [nl.nn.adapterframework.jdbc.FixedQuerySender] to avoid potential SQL injections!`

This happens because it uses a MixedQuerySender that extends the DirectQuerySender. I have set the query parameter of the ResultSetIteratingPipe, so I do not expect the warning to apply to my case and thus not to be shown.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Console
 - Frank Framework

**To Reproduce**
1. Have a ResultSetIteratingPipe with the query parameter set
2. Load the adapter
3. See warning

**Expected behavior**
No warning, as I'm using a fixed query.

**Screenshots**

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Tomcat/WebSphere
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20200909.154756

**Additional context**
N/A

**Comment by jacodg** [comment]
Met warnings.suppress.sqlInjections.<adapternaam>=true kun je deze onderdrukken.

@alisihab please contact Niels to make this more generic

**Comment by ricardovh** [comment]
I could suppress it, but I would say that if the query-attribute is set, the warning should not be given for the ResultSetIteratingPipe.

**Comment by jacodg** [comment]
There you have a punt :)
