### ISSUE TITLE
When using Exchange Mail Listener on multiple nodes, sometimes e-mails are processed twice.

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#1060]
**Describe the bug**
When you have a configuration where you have listener of type ExchangeMailListener and you deploy this configuration to multiple nodes, what happens is that the same e-mail is processed atleast twice (haven't tested with more than 2 nodes), once on each node. 

This behaviour does not happen 100% of the time.

**Reporter**
Laurens

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
See bug description

**Expected behavior**
To prevent this behaviour, I created a new database table to store the mail id's in. When a node picks up a message, it will insert the mail id in this table, when a primary key violation occurs it knows the mail is already being processed and it will exit the pipeline.

I would expect the framework to provide such mechanics to ensure that a message will only be processed once.

**Screenshots**
![image](https://user-images.githubusercontent.com/37303445/93186852-605e1400-f73f-11ea-8285-707e9c920aa4.png)

![image](https://user-images.githubusercontent.com/37303445/93186892-6c49d600-f73f-11ea-9a40-5bc1b5b9ebc6.png)

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty) Websphere
 - Browser [e.g. chrome, safari] Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6] 7.5-20191008.103430

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by ricardovh** [comment]
If you know the solution, I would like to know also. I had a similar problem some time ago, I discussed with Gerrit. Conclusion was that it should not happen, but because it is just a folder and not a database, it cannot be guaranteed that multiple nodes do not process the same message.

A possible solution Gerrit suggested back then was setting the duplicateCheck="true" on the receiver and let the messagelog handle it, but I just got word from that project that they are currently experiencing the same issue that some mails are processed twice. I haven't had the change to investigate further.

Their version: 7.6-20200421.151810.

**Comment by ricardovh** [comment]
I checked the application I received questions about. According to the messagelog, all mails have the same messageid, so I don't really understand how it works now as all mails should be duplicates according to that logic.

**Comment by jjansenvr** [comment]
@Laurens-makel  could you please inform us how this problem was fixed in ibis4input?

**Comment by Laurens-makel** [comment]
I have solved this issue in Ibis4Input by adding the following table to the database:

`	<changeSet id="CREATE-MAILS_RECEIVED" author="Laurens Mäkel">
		<createTable tableName="MAILS_RECEIVED">
			<column name="ExchangeMailID" type="varchar(512)">
				<constraints nullable="false" ></constraints>
			</column>
			<column name="MODIFIED_AT" type="timestamp" defaultValueComputed="CURRENT_TIMESTAMP"/>
		</createTable>
		<addPrimaryKey tableName="MAILS_RECEIVED" columnNames="ExchangeMailID"/>
	</changeSet>`

In the pipeline I have made sure this is the first pipe:

`<pipe
    name="StoreMailId"
    className="nl.nn.adapterframework.pipes.GenericMessageSendingPipe"
>
    <sender
        className="nl.nn.adapterframework.jdbc.FixedQuerySender"
        jmsRealm="jdbc"
        query="INSERT INTO MAILS_RECEIVED (EXCHANGEMAILID) VALUES (?)"
    />
    <param name="mailId" sessionKey="messageId"/>
    
    <forward
        name="success"
        path="Copy_EmailStream" />
    <forward
        name="exception"
        path="EXIT" />
</pipe>`


Whenever this mail id is already in the database, it will throw a unique/primary key violation exception and I redirect that exception to an exit with state success.

**Comment by jacodg** [comment]
@alisihab and @Laurens-makel  Please check if it also works with an external message log and attribute checkForDuplicates=true
