### ISSUE TITLE
NewLine not added in XsltPipe with xpathExpression

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1061]
**Describe the bug**
When using an XsltPipe with an xpathExpression to concatenate strings with a newline using &#xA; the newline is not added. This happens because somewhere going from the original configuration to the loaded configuration, the &#xA; is lost. In 7.5-RC4 this does not happen.

Workaround for now is to use an .xsl.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
1. Load the attached adapter in 7.5-RC4
2. Use test a pipeline to send <dummy/> to the adapter
3. See a response with new lines
4. Load the adapter in 7.6 snapshot
5. Repeat the test
6. See response without newlines
7. See Loaded configuration for missing newline.

**Expected behavior**
The newline not being replaced.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Tomcat
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20200909.154756

**Additional context**
[ConfigurationXMLnl.zip](https://github.com/ibissource/iaf/files/5223906/ConfigurationXMLnl.zip)

**Comment by alisihab** [comment]
In 7.5-RC4 the char in the attached config was resolving to decimal value after loading the config in memory. On the other hand, in the latest version of the framework the char is normalized. The existing canonicalize.xsl recognizes the new line char as a space.
It requires further investigation to solve the issue.
