### ISSUE TITLE
Statsfile IJA_Tibet2 gets extremely large on DEV

### ISSUE THREAD

**Issue by githubapreinders** [ibissource/iaf#1062]
**Describe the bug**
Statsfile IJA_Tibet2 gets extremely large on DEV

**Reporter**
Ap

**Category** 
 - Performance

**To Reproduce**
1. Go to 'https://srdzzapp0329.insim.biz/ija_tibet2/iaf/gui/#!/logging'
2. See file: ija_tibet2_stats_.......it becomes extremely large in size. Have seen it being 1.2GB ; after a deploy on DEV it starts growing rapidly. Screenshot shows the size after a fresh deploy and after removing all the older stats-files.
3. Problems arise for example when deploying new versions.

**Expected behavior**
A normal file size of the stats files. I have not seen the behaviour on TST with version 7.5-RC3

**Screenshots showing the difference between DEV and TST**

![Capture](https://user-images.githubusercontent.com/6153602/93196201-6279a000-f74a-11ea-8c5a-bcbae6e5a14d.PNG)

![Capture](https://user-images.githubusercontent.com/6153602/93196462-c2704680-f74a-11ea-8883-7818c2b8d34a.PNG)

[ija_tibet2-stats_2020W38 (1).log](https://github.com/ibissource/iaf/files/5224093/ija_tibet2-stats_2020W38.1.log)

**Environment:**
 - Application server WebSphere
 - Browser chrome
 - IAF Version 7.5 RC3, RC4

**Comment by jacodg** [comment]
Discussed with Ap. For now we increase the disk space.
