### ISSUE TITLE
Ability to write length/size of streams to log files 

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#1066]
**Reporter**
Laurens/Richard

**Is your feature request related to a problem? Please describe.**
For the Ibis4Titan project Richard would like to log the size or length of a stream to a log file, for performance anlyses.

**Describe the solution you'd like**
That you could use the SizePipe to retrieve the actual size of a stream or another solution.

**Describe alternatives you've considered**
This is what Richard tried:

<SizePipe
        name="getFileSize"
        getInputFromSessionKey="ContentStream"
        storeResultInSessionKey="FileSize"
        preserveInput="true"
>
</SizePipe>

**Additional context**
Besides this issue, it seems to be related to not seeing any size statistics anymore:

![image](https://user-images.githubusercontent.com/37303445/93224138-168e2180-f771-11ea-8577-01c400bdf61b.png)

**Comment by nielsm5** [comment]
The problem is that when you want to determine the size of a steam you will have to store/read the stream, as a non-stream, and then convert it back to a stream. Usually when you use streams, you don't want to store it.
