### ISSUE TITLE
Rotation per day on a file does not seem to work

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#1069]
**Describe the bug**
Using the LocalFileSystemPipe and rotateDays does not seem to work. After midnight a new file is created, but there is no backupfile for the previous day. 

**Reporter**
Richard van der Stel

**Category** 
 - Frank Framework

**To Reproduce**

**Expected behavior**
We want to have the file to be rotated per day.

**Screenshots**
Example : 
                        <LocalFileSystemPipe
                                getInputFromSessionKey="createDocumentLogLine"
                                name="writeCreateDocumentMessage"
                                inputFolder="${log.dir}"
                                filename="ibis4titan-createDocument.log"
                                action="append"
                                preserveInput="true"
                                rotateDays="7"
                        >

We tried to set rootDir as well with the same value, but without result.

**Environment:**
 - Application server :  WebSphere
 - Browser : chrome
 - IAF Version : IAF 7.6-20200603.093311

**Additional context**

**Comment by jacodg** [comment]
Can you recheck with current version

**Comment by alisihab** [comment]
Could not reproduce with the latest version
