### ISSUE TITLE
Feature request: XmlIf with boolean

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1074]
**Reporter**
Ricardo

**Is your feature request related to a problem? Please describe.**
I regularly need to check if a certain condition is true, in the XmlIf I can give an xpathExpression that results in a boolean (for example, count(/some/path)=0), but I need to explicitly set the expressionValue to true to go to the then exit.

**Describe the solution you'd like**
Expressions that result in "true" to be send to the then exit without having to set the expressionValue.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by alisihab** [comment]
@ricardovh Can you reproduce this and provide the configuration?

**Comment by ricardovh** [comment]
Cannot reproduce anymore.
