### ISSUE TITLE
Scheduler with locker somtimes runs on multiple nodes

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#1075]
**Describe the bug**
A scheduler with a locker should not be able to run on two nodes.

**Reporter**
jjansenvr

**Category** 

**To Reproduce**
Hard to reproduce because it works fine most of the time
Run two nodes with schedular with a locker
Related to #778

```
<scheduler>
                 <job name="BP21RENSExport" adapterName="Export BP21RENS"
           description="Run the batch everyday at specified time excluding holidays"
           cronExpression="${BP21RENS.controlCron}"
           receiverName="Scheduler-BP21RENS"
           function="sendMessage"
           active="${bp21rens.active}">
           <locker jmsRealm="jdbc" objectId="BP21RENSExport"/>
           </job>
         </scheduler>
[ibis4solife_mgr.IBISLOCK.TXT](https://github.com/ibissource/iaf/files/5247433/ibis4solife_mgr.IBISLOCK.TXT)


```
**Expected behavior**
a schedular with a lock should always prevent the other node from running the same process 

**Screenshots**

**Environment:**
 - WebSphere 8.5
 - IAF 7.5-RC2

**Additional context**
script of the ibislock table is added

**Comment by jacodg** [comment]
Can you make a test adapter to check the behavior? Maybe a WebSphere or database setting?

**Comment by gvanbrakel** [comment]
Problem might be that in this configuration the locker is of type 'T' (temporary) instead of 'P' (permanent). Temporary locks are released after the job has finished, allowing the job to run on another node, if that node has kept waiting for the lock to become available.
