### ISSUE TITLE
GUI 1.2 - de oude console wordt getoond en de successful logging probeert te openen, krijg je een 500 melding

### ISSUE THREAD

**Issue by DLeymann** [ibissource/iaf#1076]
**Describe the bug**
IAF 7.5-RC3: ibis4belasting
Running on srazzapp0359.insim.biz using IBM WebSphere Application Server/8.5
Java Version: Java(TM) SE Runtime Environment (8.0.6.0 - pxa6480sr6-20191107_01(SR6))

Optie GUI1.2 laat de oude interface van de console zien.
Als men kiest voor GUI1.2 en dan de logging van een adaptor (bv. Fxf3dispatcher) probeert te openen, krijgt men een 500 melding (zie screenshots)

**Reporter**
David Leymann

**Category** 
 - Frank Console
 - Frank Framework

**To Reproduce**
1. Go to acc environment to open console: https://srazzapp0359.insim.biz/ibis4belasting/iaf/gui/#!/login
2. Login - IAF Interactive Console
3. Click on 'GUI1.2'
4. Select Fxf3Dispatcher
5. Select logging (successful logging)
6. See error 500 melding
7. Return to adaptor (back)
8. Select Error logging - this opens fine!
[IAF 7.5 GUI 1.2 bug open success logging fails 500.docx](https://github.com/ibissource/iaf/files/5253741/IAF.7.5.GUI.1.2.bug.open.success.logging.fails.500.docx)

**Expected behavior**
The successful logging cannot be opened in GUI1.2, yet the error logging can be opened.

**Screenshots**
- see attachment

**Environment:**
 - IAF Version [e.g. 7.5 RC3, 7.6]

**Additional context**

**Comment by nielsm5** [comment]
Hi,

There appears to be a space behind `DESC ` in your `DeploymentSpecifics.properties` files, which is why the framework cannot parse it. We won't fix this in the 7.5 but will improve the warning in newer releases.

Please remove the tailing space
