### ISSUE TITLE
IAF 7.5 opens with "Loading..." message and hangs 

### ISSUE THREAD

**Issue by DLeymann** [ibissource/iaf#1077]
**Describe the bug**
IAF 7.5 opens with "Loading..." message and hangs until F5 is clicked.

**Reporter**
David Leymann

**Category** 
 - Frank Console
 - Frank Framework

**To Reproduce**
1. Go to acc environment to open console: https://srazzapp0359.insim.biz/ibis4belasting/iaf/gui/#!/login
2. Login - IAF Interactive Console
3. Loading... shows in top left screen
4. Hangs sometimes until the user presses F5 to refresh it. 
5. IAF Console appears finally

**Expected behavior**
Login and console appears directly

**Screenshots**
[IAF 7.5 GUI 1.2 bug open success logging fails 500.docx](https://github.com/ibissource/iaf/files/5253769/IAF.7.5.GUI.1.2.bug.open.success.logging.fails.500.docx)

**Environment:**
IAF 7.5-RC3: ibis4belasting
Running on srazzapp0359.insim.biz using IBM WebSphere Application Server/8.5
Java Version: Java(TM) SE Runtime Environment (8.0.6.0 - pxa6480sr6-20191107_01(SR6))

**Additional context**
None

**Comment by nielsm5** [comment]
Login behavior has changed in the 7.5-RC4. Is it possible to test this with the latest release?
