### ISSUE TITLE
ibisdoc.xsd does not permit a <Receiver> without a name attribute

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#1087]
**Describe the bug**
Niels told me that a ``<Receiver>`` element does not need a name. But when I omit the name of a ``<Receiver>``, my text editor Visual Studio Code warns me. There is a red marker at the ``<Receiver>``, indicating that ibisdoc.xsd is not satisfied.

**Reporter**
Martijn Dirkse

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
1. Open a Frank configuration in Visual Studio Code. It should have a ``<Receiver>``.
2. Delete the name attribute of a receiver.

**Expected behavior**
When you do not add a name to your ``<Receiver>``, then there should be no marker in your text editor.

**Screenshots**

**Environment:**
 - Visual Studio Code
 - Not applicable
 - Unknown

**Additional context**
When you write Frank configs, it is good practice to name your elements with care. The more you have to name, the more difficult it is to find good names. So it is important not to name ``<Receiver>`` elements.

**Comment by gvanbrakel** [comment]
An adapter can have multiple receivers, and therefor the name of the receiver is often used to identify it.
The current code is not smart enough to find a 'default' receiver

**Comment by jacodg** [comment]
We can make the name attribute optional in the XSD, in that case we need to make sure that the generated receiver names will be unique when there is more than one receiver.

**Comment by mhdirkse** [comment]
Gerrit and me are working on a new implementation of the Frank!Doc. I take the responsibility that we will fix this issue in the course of our project.

**Comment by jjansenvr** [comment]
outdated? can we close this?

**Comment by jjansenvr** [comment]
@mhdirkse can we close this issue?

**Comment by mhdirkse** [comment]
I tested that with the Frank!Doc, a receiver without a name is permitted now. I close this issue.
