### ISSUE TITLE
Stubbing with multiple receivers gives only one stubbed receiver

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1102]
**Describe the bug**
When having an adapter with multiple receivers (for example multiple ApiListeners with different uriPattern-properties), only one receiver is stubbed. I would expect both to be stubbed.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
1. Create an adapter with multiple receivers
2. Set the property stub4testtool to true and start your server
3. See only one stubbed receiver+original receivers

**Expected behavior**
All receivers to be stubbed

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Tomcat
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20200925.120005

**Additional context**
N/A

**Comment by jacodg** [comment]
Can you experiment with stub4testtool.xsl to see whether you can get the desired situation?

**Comment by ricardovh** [comment]
I'll see what I can do, but that will probably be next month.

**Comment by mhdirkse** [comment]
In the Frank!Manual, section Getting Started, I have a picture that shows the receivers within an adapter. I saw more receivers than I expected. I wrote an issue about this in the Frank!Manual project: https://github.com/ibissource/frank-manual/issues/60. It comes down to reverting the change that was proposed in the present issue. Ricardo van Holst has agreed in a phone call.
