### ISSUE TITLE
Json2XmlValidator (xml to json) doesn't handle newlines correct

### ISSUE THREAD

**Issue by laura-dimitra** [ibissource/iaf#1106]
**Describe the bug**

This is the message which will be transformed by the Json2XmlValidator (please note the newlines)
```
<EdifactEnvelopeResponse xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:WAF="http://wearefrank.nl">
<edifactMessage>UNA:+.? '
UNB+UNOC:1+I000000000000000+I000000000000000+200528:1608+PMB0000001-149++++++1'
XYZ
UNZ+5+PMB0000001-149'</edifactMessage>
</EdifactEnvelopeResponse>
```

This is the output after passing the Json2XmlValidator:

```
{
"edifactMessage": "UNA:+.? '\nUNB+UNOC:1+I000000000000000+I000000000000000+200528:1608+PMB0000001-149++++++1'\nXYZ\nUNZ+5+PMB0000001-149'"
}
```

It shows \n, but doesn't give newlines. Can you fix this?

(P.S. To make my info complete, the xslt which created the newlines used `<xsl:text>&#xa;</xsl:text>` to create them)

**Reporter**
Laura Nauta-Timp

**Category** 
 - Frank Framework FF! 7.6-20200909.154756
[Pipeline DownloadEdifactEnvelope.zip](https://github.com/ibissource/iaf/files/5304214/Pipeline.DownloadEdifactEnvelope.zip)

**Comment by Laurens-makel** [comment]
Hi Laura,

This is correct behaviour, according to the specification.

http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf
![image](https://user-images.githubusercontent.com/37303445/94780198-5d625500-03c8-11eb-83ad-881a748d7dbf.png)
