### ISSUE TITLE
Option to hide all warnings in the console

### ISSUE THREAD

**Issue by francisgw** [ibissource/iaf#1128]
**Reporter**
Francis

**Is your feature request related to a problem? Please describe.**
Sometimes it can be the case that there are too many warnings that clutter the console overview.

**Describe the solution you'd like**
I'd like to have an option to hide or fold/minimize the warnings so you have a quicker access to the configurations and adapters.

![image](https://user-images.githubusercontent.com/67001993/95336106-901cb980-08b0-11eb-983a-a82153af8a74.png)

**Comment by jacodg** [comment]
Already fixed
