### ISSUE TITLE
FixedQuerySender attribute "scalar" - No warning if the query result is not a scalar

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#1139]
**Reporter**
Martijn Dirkse

**Is your feature request related to a problem? Please describe.**
When you use a `<FixedQuerySender>` with attribute `scalar=true`, then you request a scalar result from the Frank!Framework. However, when you make a mistake and the query result is not a scalar, then you get no error and no warning. The Frank!Framework chooses an arbitrary scalar from the query result as the response and continues normally. I tried this, see attached .zip file.
[tryAttributeScalar.zip](https://github.com/ibissource/iaf/files/5369954/tryAttributeScalar.zip)

I also saw no clue in Ladybug that something was wrong, see the following image: 
![image](https://user-images.githubusercontent.com/6784732/95835817-fdac6800-0d3e-11eb-84d2-4d2ef5cac762.png)

**Describe the solution you'd like**
If you set `scalar=true` but the query being executed has not a scalar result, then the Frank!Framework should produce an error. A Java exception is the most visible way to give this feedback to the user. If this breaks backwards compatibility, at least an error should be visible in Ladybug.

**Describe alternatives you've considered**

**Additional context**
The attached .zip file runs with the Frank!Runner.

**Comment by alisihab** [comment]
By definition of the scalar attribute 'When true, the value of the first column of the first row (or the startrow) is returned as the only result, as a simple non-xml value' any result-set can be scalar.

**Comment by mhdirkse** [comment]
I am curious. Are you going to change the behavior of the FF! ?

**Comment by gvanbrakel** [comment]
We'll provide a warning in the logging, stating more rows are available

**Comment by mhdirkse** [comment]
I checked that the warning is indeed written in the log.
