### ISSUE TITLE
Get Spring error message in JVM console (again) on start-up error

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#1159]
**Describe the bug**
When something really bad happens at start-up (like ActiveMQ classes not found) no error is written to the log file or system out while in the past you would see an error message and/or stacktrace (for example when using Frank!Runner) in your terminal / command prompt.

**Reporter**
Jaco de Groot

**Category** 
Use following Tags to categorize your bug report
 - Frank!Framework

**To Reproduce**
1. Remove a vital jar
2. Start you Frank!
3. See that no error is reported in the logfile or your terminal / command prompt
4. Go to GUI 3.0
5. See that your Frank! hasn't started and showing the error screen
6. See only an error in the log saying the context is not found but no message explaining the real cause

**Expected behavior**
I would expect to find an error message explaining the real cause.

**Screenshots**
\-

**Environment:**
 - Tomcat
 - IAF 7.6-SNAPSHOT

**Additional context**
\-

**Comment by nielsm5** [comment]
This might have been fixed in #1207. Is it possible to test this again?

**Comment by jacodg** [comment]
I did some testing by adding <arg value="-Dapplication.server.type.custom=ACTIVEMQ"/> to the build.xml of frank-runner/examples/Frank2Example3/build.xml and adding ff.version to frank-runner.properties and tested with a number of framework versions.

With versions 7.1, 7.2, 7.3-RC1, 7.5 and 7.6-20201216.082101 I can not find the problem at the command prompt, console or any logfile.

With versions 5.5 and 7.0-RC3 I can also not find the problem at the command prompt, console or any logfile after start-up, but after that I can click on "click here to start the ConfigurationServlet" and then it will show me java.lang.NoClassDefFoundError: javax/transaction/SystemException

**Comment by jacodg** [comment]
Last week I noticed some errors go to Tomcat's localhost.&lt;date>.log and made a change to the Frank!Runner to make them show up in the Tomcat console window:

https://github.com/ibissource/frank-runner/commit/9fc32830ceaba8b147a88842397a642c3acdfcb8

I've tested that change by breaking springIbisTestTool.xml (also tested breaking springCommon.xml but errors in this file didn't go to localhost.&lt;date>.log).

I see now see that my change in the Frank!Runner also makes the NoClassDefFoundError I mention in this issue appear in the Tomcat console window.

It would still be nice to see the error in the Frank!Console. I probably didn't look in the localhost.&lt;date>.log for this issue as I don't often look in this logfile and expect Frank related issues in the Frank specific logfiles.

**Comment by nielsm5** [comment]
The exception shows up in catalina.out (which when using eclipse is mapped to the console). When running Tomcat as a service (usually) there's no console, so it's being written to a file in stead. Since you're not running Tomcat headless, you can print everything to the console instead by setting the following property in `conf/logging.properties`:

`org.apache.catalina.core.ContainerBase.[Catalina].[localhost].handlers = java.util.logging.ConsoleHandler`

**Comment by nielsm5** [comment]
Found 1 scenario where nothing was logged to the Ibis log but only to the servlet.out log.
