### ISSUE TITLE
SSL-exception on http-sender when setting allowSelfSignedCertificaties to false and verifyHostname to true

### ISSUE THREAD

**Issue by githubapreinders** [ibissource/iaf#1162]
**Het probleem**
Ik heb onderzoek gedaan naar de SSL exceptie die ontstaat wanneer je de security van een httpSender verhoogt in de Ibis. De property allowSelfSignedCertificates=false en verifyHostName=true worden dan gezet. Daaruit kwam het volgende voort:
•	Marcel Hijma heeft me verzekerd dat alles op Websphere-niveau goed stond. We hebben ook alle certificaten bekeken dus dat is in orde. Ricardo kreeg hetzelfde te horen van Deepak maar dit is dus werkelijk onderzocht.
•	Vanuit versie 7.5RC3 (op SapCD-tst) als vanuit 7.0RC2 (op SapHana-tst) krijgen we met dezelfde url dezelfde SSL-exception. Lokaal is deze url goed te bereiken.
•	Ricardo vermoedt nu dat de fout op Websphere+FF niveau ligt

**Reporter**
Ap Reinders

**Category** 
Use following Tags to categorize your bug report
* - Frank Framework

**Reproduceren**
Zie begeleidende mail met screenshots en onderzoeksbeschrijving.

**Comment by gvanbrakel** [comment]
I could locally reproduce the problem, and could solve it by adding the proper truststore

**Comment by gvanbrakel** [comment]
Ap vraagt of er al schot in zit:
Hoi Gerrit! Is er al nieuws rondom #1162 Ibis4sapHana connectiefouten?

**Comment by gvanbrakel** [comment]
Op de server waarop ibis4saphana draait, lijkt op 5-10-2020 de java.security file te zijn aangepast, waardoor onder andere de default security provider is veranderd. In een backup file van 27-04-2020 is dat:
``security.provider.1=com.ibm.jsse2.IBMJSSEProvider2`` 
In de nieuwe file is het:
``security.provider.1=com.ibm.crypto.pkcs11impl.provider.IBMPKCS11Impl``

**Comment by gvanbrakel** [comment]
Ibis4saphana draait op een oude versie van het framework, waarin het aanmaken van SSL connecties niet helemaal goed gaat. Dat is niet erg als je niet heel erg strikt bent op de security (i.e. verifyHostname=false, allowSelfSignedCertificates=true), maar als je dat wel bent, is het een probleem. Ricardo vraagt: “moet ik echt upgraden, of kan ik ook wat settings zetten, en werkt het dan ook”. Het punt daarbij is dat hij wel verifyHostname=true, allowSelfSignedCertificates=false zet, dus wel goede security wil hebben. Die krijg je niet als als je niet van de bedoelde SSLConnectionFactory gebruik maakt, of je moet die dan ook weer op een andere (niet standaard) manier gaan configureren.
Bottom line is dat als je goede security wil hebben, je dan moet upgraden, bijvoorbeeld naar de laatste versie van de 7.5 branch (op dit moment 7.5 RC4, versie 7.5 komt er binnenkort aan)

**Comment by gvanbrakel** [comment]
Ricardo schrijft:
Ondertussen is ibis4saphana naar 7.5 gebracht, maar krijgen nog steeds de "(SSLException) SSLSocketFactory is null. This can occur if javax.net.ssl.SSLSocketFactory.getDefault() is called to create a socket and javax.net.ssl.* properties are not set."

Bijgevoegd ook de stack-trace. Als je zelf wil testen, op https://srdzzapp0437.insim.biz/ibis4saphana zijn 2 TestHTTPS-adapters die je kan gebruiken. Eentje roept de ibisdoc op die machine aan (zal als er geen SSL fouten zijn een 401 geven wegens missende authenticatie), de ander roept de HTTPListener op ibis4testIAF binnen NN aan en die zou zonder SLL fout goed moeten gaan omdat dezelfde call vanuit ibis4testIAF zelf ook gedaan wordt.

Aangezien HTTPS vanuit ibis4testIAF naar zichzelf wel goed gaat, vermoed ik dat het probleem aan de Websphere-kant zit, maar ik heb geen idee waar dat dan in zit en uit de eerdere mailwisseling blijkt dat Marcel en Deepak daar al naar gekeken hebben.

Kan jij hier nogmaals een blik op werpen en als het toch aan Websphere ligt, weet je dan toevallig waar ik Marcel of Deepak kan laten kijken voor wat er fout is?

**Comment by gvanbrakel** [comment]
Heb aan Marcel Hijma geschreven:
Naar aanleiding van onderstaande mail, en mijn eerdere mail over Issue #1186 ‘no javax.net.debug possible anymore in Ibis’ hierbij de vraag om te proberen op srdzzapp0437 wasap04 de javax.net.debug aan te zetten om dit probleem te analyseren.

Ik zie op srdzzapp0437 in /opt/data/WAS/wasap04/lib de file log4j-1.2.16 staan. Zou je die kunnen verwijderen? Hij is daar niet nodig, en hij conflicteert met de versie van log4j die door het framework gebruikt wordt, en ik kan me goed voorstellen dat dat een oorzaak van het javax.net.debug probleem is.

**Comment by nielsm5** [comment]
Naar mijn weten krijg je de `(SSLException) SSLSocketFactory is null` fout wanneer websphere geen (juiste) SSLSocketFactory kan maken. Eg; wanneer een van de SSL properties niet goed staat. Denk aan de `javax.net.ssl.*` zoals in de foutmelding staat maar ook `ssl.TrustManagerFactory.*` en `ssl.KeyManagerFactory.*`.

**Comment by gvanbrakel** [comment]
There appeared to be a custom setting of javax.net.ssl.trustStore in server.xml, that overrules the standard WAS truststore
Marcel Hijma removed this setting, and then it appeared to work
