### ISSUE TITLE
Make it possible to log to a custom file with the LogSender

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#1166]
**Reporter**
Jaco de Groot

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Make it possible to log to a custom file with the LogSender. Currently the LogSender always writes the info to the default Frank! logfile. But in case you need to do "heartbeat logging" from your adapter you don't want to pollute the default logfile. You would like te specify a diffent logfile like frank2example-myheartbeat.log. It would also be nice to be able to specify some log4j properties like the pattern layout, file rotation and file size.

**Describe alternatives you've considered**
1. Have the Frank! developer write a custom log4j4ibis.xml but this will lead to problems in the future when changes are done on this file on framework level and the Frank! developer doesn't update his custom log4j4ibis.xml.

2. Use the FileSender. But this needs too much configuration for a simple job, for example (doing only a poor mans file rotation):

			<pipe className="nl.nn.adapterframework.pipes.PutSystemDateInSession" dateFormat="yyyy-MM-dd HH:mm:ss" name="GlobalDateTime" sessionKey="dateTimeStamp">
				<forward name="success" path="renameOrAddTofile"/>
			</pipe>
			
			<pipe className="nl.nn.adapterframework.pipes.XmlSwitch" getInputFromFixedValue="&lt;dummy/&gt;" name="renameOrAddTofile" serviceSelectionStylesheetFilename="ExceptionLogCount/xsl/checkTime.xsl">
				<param name="dateTimeStamp" sessionKey="dateTimeStamp"/>
			
				<forward name="rename" path="renameFile"/>
				<forward name="write" path="writeFile"/>
			</pipe>
					
			<pipe className="nl.nn.adapterframework.pipes.MoveFilePipe" filename="${log.dir}/ija_tibet2-exceptionlogcount.log" getInputFromSessionKey="formatQuery" move2dir="${log.dir}" move2file="ija_tibet2-exceptionlogcount.log.1" name="renameFile" numberOfBackups="0" overwrite="yes">
					
				<forward name="success" path="writeFile"/>
			</pipe>
				
			<pipe className="nl.nn.adapterframework.pipes.GenericMessageSendingPipe" getInputFromSessionKey="formatQuery" name="writeFile">
				<sender actions="write_append" className="nl.nn.adapterframework.senders.FileSender" fileName="${query.log}"/>

				<forward name="success" path="EXIT"/>
			</pipe>

**Additional context**
\-

**Comment by nielsm5** [comment]
You can use the LocalFileSystemPipe (or Sender) which has `rotateDays` and `RotateSize` attributes so you can keep appending to a file.

**Comment by jacodg** [comment]
Ah, nice! That is enough for my situation, I now use the following:

			<LocalFileSystemPipe
				name="AppendToFile"
				root="${log.dir}"
				filename="${instance.name.lc}-errorstorecount.log"
				action="append"
				rotateSize="1048576"
				numberOfBackups="9"
				>
				<Forward name="success" path="EXIT"/>
			</LocalFileSystemPipe>
