### ISSUE TITLE
Several XML errors occur when using Exchange Listener

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#1167]
**Describe the bug**
I have multiple adapters using the Exchange Mail Listener to process emails. Sometimes when my pipeline runs successful, the email is moved to the configured errorFolder instead of processedFolder.

As you can see, Ladybug reports that the pipeline ran successfully:
![image](https://user-images.githubusercontent.com/37303445/96576330-5301ef80-12d2-11eb-978c-393a6f2294d1.png)

When I inspect my log file I see the following line:
![image](https://user-images.githubusercontent.com/37303445/96576505-9197aa00-12d2-11eb-8bd2-9abd06c3c706.png)

I am not sure what is causing this but I am seeing other errors related to XML parsing/handling in the Exchange Listener:
![image](https://user-images.githubusercontent.com/37303445/96576638-c146b200-12d2-11eb-9ed6-77ffe9e17b94.png)

**Reporter**
Laurens Mäkel

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
Please see IBIS4INPUT or contact me and I'll show you.

**Expected behavior**
No XML parsing/handling errors to occur and the email to be moved to the correct folder.

**Screenshots**

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty) Websphere
 - Browser [e.g. chrome, safari] Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6] 7.5-20191008.103430

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
This problem has been fixed in the 7.5 RC1 version. Please upgrade to 7.5 RC4 or later.
