### ISSUE TITLE
Remove log4j warning on org.apache.cxf.common.logging.LogUtils

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#1170]
**Describe the bug**
Remove the following from the output in the terminal / command prompt at startup:
log4j:WARN No appenders could be found for logger (org.apache.cxf.common.logging.LogUtils).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Reporter**
Jaco de Groot

**Category** 
 - Frank Framework

**To Reproduce**
1. Start one of the examples of the Frank!Runner or run iaf-test in Eclipse
2. See the warning in the command prompt window or Eclipse console

**Expected behavior**
No warning

**Screenshots**
\-

**Environment:**
 - Tomcat
 - IAF 7.6-SNAPSHOT

**Additional context**
\-

**Comment by nielsm5** [comment]
This is a Log4j 1.2 error, caused by the ladybug which still uses an older version of Log4j.

**Comment by nielsm5** [comment]
Created an issue on ibissource/ibis-ladybug#48

**Comment by jacodg** [comment]
While replacing Log4j with Slf4j in Ladybug and testing locally with IAF (having no log4j 1.2 dependency in IAF anymore) I noticed a lot of CXF logging output in the console. After some investigation it turned out that using org.apache.cxf.common.logging.Slf4jLogger in org.apache.cxf.Logger and using capital L in the filename fixed the problem and also solves the warning when having log4j 1.2 dependency in IAF). CXF logging can now also be configured from log4j4ibis.xml
