### ISSUE TITLE
staleconnection exception is not retried

### ISSUE THREAD

**Issue by BonnoSmeele** [ibissource/iaf#1172]
**Describe the bug**
For the ibis4oma project we use the latest framework and a MS sql database. Every now and then we run into a stale connection exception:

Caused by: nl.nn.adapterframework.jdbc.JdbcException: [nl.nn.adapterframework.jdbc.FixedQuerySender] [StoreBulkMessageSender] cannot open connection on datasource [jdbc/ibis4oma]: (StaleConnectionException): (SQLException) SQLState [08S01]: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "Connection reset ClientConnectionId:3d6ea1cf-748d-4770-a75c-fb6aa1711e4a". DSRA0010E: SQL State = 08S01, Error Code = 0: (IOException) Connection reset ClientConnectionId:3d6ea1cf-748d-4770-a75c-fb6aa1711e4a
... 5 lines omitted ...  **(can be found in splunk index=ea sourcetype=ibis:oma env="prd" StaleConnectionException)**

In this case the unit of work is rollbacked and a manual action is required to reprocess it.  We have taken steps to limit the amount of stale exception errors(optimized DB and ibis adapter code) The exception is now much rarer but still happens from time to time.

In case of a stale connection exception i would expect the FF to resume the unit of work with a new connection instead of discarding it.

**Reporter**
Bonno Smeele

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
Unreproducible at the moment

**Expected behavior**
In case of a stale exception error i expect the FF to use another connection to finish the current operation. Instead the entire unit of work is discarded

**Screenshots**
splunk link

https://splunk.insim.biz/en-US/app/NN_NL_EA/search?earliest=-24h%40h&latest=now&q=search%20index%3Dea%20sourcetype%3Dibis%3Aoma%20env%3D%22prd%22%20StaleConnectionException&display.page.search.mode=fast&dispatch.sample_ratio=1&display.general.type=events&sid=1603261449.6208718_9E245381-AEB8-43F0-ABE8-34F6DAC787C3

**Environment:**
 - Application server WebSphere
 - Browser  NA
 - IAF Version 7.6-20200722.094609

**Additional context**

10/20/2012:05:37.931 PM | 2020-10-20 12:05:37,931 WARN  [MQReceiver_ReceiveMessage[6]] [mid [ID:c3e2d840d8d4d7f14040404040404040d8b27a10ce9cab06]] pipes.GenericMessageSendingPipe - Pipe [StoreBulkMessagePipe] msgId [ID:c3e2d840d8d4d7f14040404040404040d8b27a10ce9cab06] exception occured, forwarding to exception-forward [ReturnErrorMessageCheckDataSource], exception: nl.nn.adapterframework.core.SenderException: cannot get StatementSet: [nl.nn.adapterframework.jdbc.FixedQuerySender] [StoreBulkMessageSender] cannot open connection on datasource [jdbc/ibis4oma]: (StaleConnectionException): (SQLException) SQLState [08S01]: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "Connection reset ClientConnectionId:3d6ea1cf-748d-4770-a75c-fb6aa1711e4a". DSRA0010E: SQL State = 08S01, Error Code = 0: (IOException) Connection reset ClientConnectionId:3d6ea1cf-748d-4770-a75c-fb6aa1711e4a 	at nl.nn.adapterframework.jdbc.FixedQuerySender.openBlock(FixedQuerySender.java:79) ~[ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.jdbc.FixedQuerySender.openBlock(FixedQuerySender.java:45) ~[ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.jdbc.FixedQuerySender$$FastClassBySpringCGLIB$$ed3e925b.invoke(<generated>) ~[ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at nl.nn.adapterframework.jdbc.FixedQuerySender$$EnhancerBySpringCGLIB$$5e249af3.openBlock(<generated>) ~[ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.jdbc.JdbcSenderBase.sendMessage(JdbcSenderBase.java:116) ~[ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.jdbc.JdbcSenderBase.sendMessage(JdbcSenderBase.java:127) ~[ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.pipes.MessageSendingPipe.sendMessage(MessageSendingPipe.java:835) ~[ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.pipes.MessageSendingPipe.doPipe(MessageSendingPipe.java:594) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.pipes.MessageSendingPipe$$FastClassBySpringCGLIB$$b131b2cb.invoke(<generated>) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at nl.nn.adapterframework.pipes.GenericMessageSendingPipe$$EnhancerBySpringCGLIB$$f50fbc4c.doPipe(<generated>) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.processors.CorePipeProcessor.processPipe(CorePipeProcessor.java:32) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.processors.CheckMessageSizePipeProcessor.processPipe(CheckMessageSizePipeProcessor.java:37) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.processors.LockerPipeProcessor.processPipe(LockerPipeProcessor.java:60) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.processors.TransactionAttributePipeProcessor.processPipe(TransactionAttributePipeProcessor.java:61) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor.processPipe(CheckSemaphorePipeProcessor.java:57) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor$$FastClassBySpringCGLIB$$3159a29c.invoke(<generated>) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:84) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeGetInputFrom(IbisDebuggerAdvice.java:143) [ibis-adapterframework-ladybug-7.6-20200722.094609.jar:7.6-20200722.094609] 	at sun.reflect.GeneratedMethodAccessor554.invoke(Unknown Source) ~[?:?] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[?:1.8.0] 	at java.lang.reflect.Method.invoke(Method.java:508) ~[?:1.8.0] 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor$$EnhancerBySpringCGLIB$$216f4e96.processPipe(<generated>) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.processors.InputOutputPipeProcessor.processPipe(InputOutputPipeProcessor.java:80) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.processors.InputOutputPipeProcessor$$FastClassBySpringCGLIB$$feb9be85.invoke(<generated>) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:84) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeInputOutputAbort(IbisDebuggerAdvice.java:117) [ibis-adapterframework-ladybug-7.6-20200722.094609.jar:7.6-20200722.094609] 	at sun.reflect.GeneratedMethodAccessor553.invoke(Unknown Source) ~[?:?] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[?:1.8.0] 	at java.lang.reflect.Method.invoke(Method.java:508) ~[?:1.8.0] 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at nl.nn.adapterframework.processors.InputOutputPipeProcessor$$EnhancerBySpringCGLIB$$2587dbf1.processPipe(<generated>) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.processors.MonitoringPipeProcessor.processPipe(MonitoringPipeProcessor.java:81) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.processors.CorePipeLineProcessor.processPipeLine(CorePipeLineProcessor.java:165) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.processors.CorePipeLineProcessor$$FastClassBySpringCGLIB$$cf1091e5.invoke(<generated>) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:84) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeLineInputOutputAbort(IbisDebuggerAdvice.java:87) [ibis-adapterframework-ladybug-7.6-20200722.094609.jar:7.6-20200722.094609] 	at sun.reflect.GeneratedMethodAccessor565.invoke(Unknown Source) ~[?:?] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[?:1.8.0] 	at java.lang.reflect.Method.invoke(Method.java:508) ~[?:1.8.0] 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) [spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at nl.nn.adapterframework.processors.CorePipeLineProcessor$$EnhancerBySpringCGLIB$$83b7211.processPipeLine(<generated>) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.processors.LockerPipeLineProcessor.processPipeLine(LockerPipeLineProcessor.java:70) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.processors.TransactionAttributePipeLineProcessor.processPipeLine(TransactionAttributePipeLineProcessor.java:49) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.processors.CachePipeLineProcessor.processPipeLine(CachePipeLineProcessor.java:39) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.processors.InputOutputPipeLineProcessor.processPipeLine(InputOutputPipeLineProcessor.java:48) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.core.PipeLine.process(PipeLine.java:536) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.core.Adapter.processMessageWithExceptions(Adapter.java:674) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.receivers.ReceiverBase.processMessageInAdapter(ReceiverBase.java:1205) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.receivers.ReceiverBase.processRawMessage(ReceiverBase.java:995) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.receivers.ReceiverBase.processRawMessage(ReceiverBase.java:950) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.receivers.ReceiverBase.processRawMessage(ReceiverBase.java:942) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.unmanaged.SpringJmsConnector.onMessage(SpringJmsConnector.java:278) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:719) [spring-jms-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:679) [spring-jms-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:649) [spring-jms-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:317) [spring-jms-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at nl.nn.adapterframework.jms.IbisMessageListenerContainer.doReceiveAndExecute(IbisMessageListenerContainer.java:93) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:235) [spring-jms-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at nl.nn.adapterframework.jms.IbisMessageListenerContainer.receiveAndExecute(IbisMessageListenerContainer.java:87) [ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1168) [spring-jms-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1160) [spring-jms-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1057) [spring-jms-4.3.25.RELEASE.jar:4.3.25.RELEASE] 	at java.lang.Thread.run(Thread.java:818) [?:2.9 (11-06-2019)] Caused by: nl.nn.adapterframework.jdbc.JdbcException: [nl.nn.adapterframework.jdbc.FixedQuerySender] [StoreBulkMessageSender] cannot open connection on datasource [jdbc/ibis4oma]: (StaleConnectionException): (SQLException) SQLState [08S01]: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "Connection reset ClientConnectionId:3d6ea1cf-748d-4770-a75c-fb6aa1711e4a". DSRA0010E: SQL State = 08S01, Error Code = 0: (IOException) Connection reset ClientConnectionId:3d6ea1cf-748d-4770-a75c-fb6aa1711e4a 	at nl.nn.adapterframework.jdbc.JdbcFacade.getConnection(JdbcFacade.java:249) ~[ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.jdbc.JdbcFacade.getConnectionWithTimeout(JdbcFacade.java:261) ~[ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.jdbc.JdbcQuerySenderBase.getConnectionForSendMessage(JdbcQuerySenderBase.java:254) ~[ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.jdbc.FixedQuerySender.openBlock(FixedQuerySender.java:73) ~[ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	... 102 more Caused by: com.ibm.websphere.ce.cm.StaleConnectionException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "Connection reset ClientConnectionId:3d6ea1cf-748d-4770-a75c-fb6aa1711e4a". DSRA0010E: SQL State = 08S01, Error Code = 0 	at sun.reflect.GeneratedConstructorAccessor188.newInstance(Unknown Source) ~[?:?] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57) ~[?:1.8.0] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:437) ~[?:1.8.0] 	at com.ibm.websphere.rsadapter.GenericDataStoreHelper.mapExceptionHelper(GenericDataStoreHelper.java:629) ~[rsahelpers.jar:WAS855.SERV1 [cf172005.01]] 	at com.ibm.websphere.rsadapter.GenericDataStoreHelper.mapException(GenericDataStoreHelper.java:688) ~[rsahelpers.jar:WAS855.SERV1 [cf172005.01]] 	at com.ibm.ws.rsadapter.AdapterUtil.mapException(AdapterUtil.java:2267) ~[com.ibm.ws.runtime.jar:?] 	at com.ibm.ws.rsadapter.spi.WSRdbDataSource.getPooledConnection(WSRdbDataSource.java:2158) ~[com.ibm.ws.runtime.jar:?] 	at com.ibm.ws.rsadapter.spi.WSManagedConnectionFactoryImpl.getConnection(WSManagedConnectionFactoryImpl.java:1809) ~[com.ibm.ws.runtime.jar:?] 	at com.ibm.ws.rsadapter.spi.WSManagedConnectionFactoryImpl.createManagedConnection(WSManagedConnectionFactoryImpl.java:1579) ~[com.ibm.ws.runtime.jar:?] 	at com.ibm.ws.rsadapter.spi.WSManagedConnectionFactoryImpl.createManagedConnection(WSManagedConnectionFactoryImpl.java:1129) ~[com.ibm.ws.runtime.jar:?] 	at com.ibm.ejs.j2c.FreePool.createManagedConnectionWithMCWrapper(FreePool.java:2168) ~[com.ibm.ws.runtime.jar:?] 	at com.ibm.ejs.j2c.FreePool.createOrWaitForConnection(FreePool.java:1838) ~[com.ibm.ws.runtime.jar:?] 	at com.ibm.ejs.j2c.PoolManager.reserve(PoolManager.java:3837) ~[com.ibm.ws.runtime.jar:?] 	at com.ibm.ejs.j2c.PoolManager.reserve(PoolManager.java:3085) ~[com.ibm.ws.runtime.jar:?] 	at com.ibm.ejs.j2c.ConnectionManager.allocateMCWrapper(ConnectionManager.java:1554) ~[com.ibm.ws.runtime.jar:?] 	at com.ibm.ejs.j2c.ConnectionManager.allocateConnection(ConnectionManager.java:1033) ~[com.ibm.ws.runtime.jar:?] 	at com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection(WSJdbcDataSource.java:644) ~[com.ibm.ws.runtime.jar:?] 	at com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection(WSJdbcDataSource.java:611) ~[com.ibm.ws.runtime.jar:?] 	at nl.nn.adapterframework.jdbc.JdbcFacade.getConnection(JdbcFacade.java:247) ~[ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.jdbc.JdbcFacade.getConnectionWithTimeout(JdbcFacade.java:261) ~[ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.jdbc.JdbcQuerySenderBase.getConnectionForSendMessage(JdbcQuerySenderBase.java:254) ~[ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	at nl.nn.adapterframework.jdbc.FixedQuerySender.openBlock(FixedQuerySender.java:73) ~[ibis-adapterframework-core-7.6-20200722.094609.jar:7.6-20200722.094609] 	... 102 more
-- | --

**Comment by gvanbrakel** [comment]
The request will be retried if the Receiver of the Adapter is transacted. Then the message read will be rollbacked to the situation it was before, and it will be tried again. 
I think that what you would like is that every transaction that is borrowed from the pool is tested before it is used. We currently do not provide that functionality, but I think it is possible to configure such behaviour in WebSphere.

**Comment by BonnoSmeele** [comment]
Hi Gerrit,

The question is really, why is the transaction roll backed when a new conenction could be used to finish it.

**Comment by gvanbrakel** [comment]
This is not simple, because 
- the StaleConnectionException is a WebSphere specific class, handling it requires WebSphere specific coding.
- it is tricky not to rollback the transaction after a transaction that is not explicitly recoverable
