### ISSUE TITLE
parent adapter starts before child adapters are started (separate configs)

### ISSUE THREAD

**Issue by BonnoSmeele** [ibissource/iaf#1174]
**Reporter**
Bonno Smeele

**Is your feature request related to a problem? Please describe.**

https://jira.nn-group.com/browse/DLMI-815

For the ibis4oma we use a parent config with about 10-15 child configs. After a restart the parent starts sending messages to child config adapters before they are up and running.

Normally the parent adapter wont start until all the child adapters are up(a check is done on all the receivers). In this case we are using variable addressing in the parent config:

			<SenderPipe 
				name="SendToFTConfig_Rebranding"
				storeResultInSessionKey="REBRANDED_MESSAGE"
				getInputFromSessionKey="SPLIT_MESSAGE"
			>
				<IbisLocalSender 
					name="SendToFTConfig_Rebranding"
					javaListenerSessionKey="FTConfig_Rebranding"
				>
					<Param name="SYSTEM_ID" 	sessionKey="SYSTEM_ID"/>
					<Param name="PROCESS_ID" 	sessionKey="PROCESS_ID"/>		
				</IbisLocalSender>
				<Forward name="success" path="RetrieveDefaultTLEPipe" />
				<Documentation><![CDATA[<p style="color:blue;">Sends input to FT config and adapter for rebranding.]]></Documentation>
			</SenderPipe>

Receiver name is stored in a sessionkey and used to call the child adapter.

repository for ibis4oma:
https://vcs.aws.insim.biz/ibissource/dm/ibis4oma
parent config repository:
https://vcs.aws.insim.biz/ibissource/dm/ibis4oma/ibis4oma_oma/-/tree/master
parent adapter:
https://vcs.aws.insim.biz/ibissource/dm/ibis4oma/ibis4oma_oma/-/blob/master/src/main/configuration/oma/Configuration_SplitMessageProcessor.xml
child config example:
https://vcs.aws.insim.biz/ibissource/dm/ibis4oma/ibis4oma_ft_vzb

Note: The adapters that are used in the child config are actually located in the parent config. They are configured using local variables during statup to instantiate. Its not that important, they use a regular local receiver.

**Describe the solution you'd like**
I want the adapter in the parent configuration to only start processing messages after the child configs are up and running.
This will prevent the parent adapter from starting sending messages to receivers that are not up and running and creating exceptions. Perhaps a check can be done that all child configs are up and running.

**Describe alternatives you've considered**
Rearranging the start up sequence using the configurations.names property in the deploymentspecific. This wont work however because as a parent config the oma config needs to be started before the child config. Putting the child config first leads to:

 Configuration [ft_alfa] - failed to locate parent configuration [oma]

**Additional context**
error:
020-09-28 06:19:13.949 : ERROR: Receiver [SplitMessageReceiver] Exception in message processing: Pipe [SendToFTConfig_Rebranding] msgId
[41791] caught exception: could not find JavaListener [ALFA_Rebranding]

**Comment by gvanbrakel** [comment]
The parent adapter can only wait for child adapters to have started if it knows for which adapters to wait. 
It cannot determine this for a IbisLocalSender with a dynamic endpoint.
You could add additional 'dummy' IbisLocalSenders with static endpoints to your configuration, just to tell the parent what it's children are.

**Comment by jjansenvr** [comment]
We can fix this by making the startup order to start child configs before parent configs?

Adding localsenders will take away the "usefulness" of the dynamic /variable java sender
- you needs to adjust the parrent adapter to add a new child, you might as well use static java sender
- when a child breaks, the parent stops working for all children (we only want to fix this at startup

**Comment by jjansenvr** [comment]
fixed by not using dynamic local sender in combination with parent child config
