### ISSUE TITLE
no javax.net.debug possible anymore in Ibis

### ISSUE THREAD

**Issue by mhijma** [ibissource/iaf#1186]
HI looks like since (one of the) latest framworks debugging does not work anymore while on older IBIS framework it still works
-Djavax.net.debug=ssl,handshake,data,trustmanager     of -Djavax.net.debug=all     dont show any output anymore in SystemOut.log (or any other log) .     We use this option quite a lot so we need it (in fact at the moment for IBIS4OMA)

**Comment by nielsm5** [comment]
Classes inside `javax.net` package would not write to Log4J2 appenders (which we use). Most probably they would output debug messages to `STDOUT` or `STDERR` streams of the running java process. 
I tested this locally with Tomcat (and openjdk 8) and the expected messages are logged to the `STDOUT`. 

It is possible that the application you're using is not using the supplied Java keystore or truststore, or there is non available?

**Comment by gvanbrakel** [comment]
Marcel schreef op 1-2-2021:

Uiteraard heb ik alle mogelijke logs toen al afgefietst…

En ik gebruik die trace optie heel vaak en die komt dan netjes in onze WAS SystemOut terecht

EN sinds deze IAF versie klaarblijkelijk niet meer.

**Comment by gvanbrakel** [comment]
Discussed: will re do the test on WebSphere

**Comment by gvanbrakel** [comment]
Tested on WebSphere 8.5.5.17 in Docker.
I configured JVM javax.net.debug as a JVM custom property
Both the values 'all' and 'ssl,handshake,data,trustmanager' yield ssl debug information in SystemOut.log

**Comment by gvanbrakel** [comment]
potential clues/solution:
https://stackoverflow.com/questions/55246502/ibm-was-7-5-sslexception-sslsocketfactory-is-null
That says 'The problem was resolved editing the java.security file of JRE, changing the following lines:'
```
# Default JSSE socket factories
ssl.SocketFactory.provider=com.ibm.jsse2.SSLSocketFactoryImpl
ssl.ServerSocketFactory.provider=com.ibm.jsse2.SSLServerSocketFactoryImpl
# WebSphere socket factories (in cryptosf.jar)
#ssl.SocketFactory.provider=com.ibm.websphere.ssl.protocol.SSLSocketFactory
#ssl.ServerSocketFactory.provider=com.ibm.websphere.ssl.protocol.SSLServerSocketFactory
```

**Comment by gvanbrakel** [comment]
Marcel Hijma thinks it is related to framework versions. 
He showed for 7.5 RC3 ibis4cervis that ssl debug is working
It did not work for 7.5 ibis4saphana.
He will check a number of other 7.5 / 7.5 RC3 / 7.5 RC4 ibisses

**Comment by gvanbrakel** [comment]
Marcel confirmed the correct operation on IBIS4ADN running on 7.6-20201112.110830
