### ISSUE TITLE
Feature request: LocalFileSystem Pipe/Sender rename directory function

### ISSUE THREAD

**Issue by francisgw** [ibissource/iaf#1189]
**Reporter**
Francis

**Is your feature request related to a problem? Please describe.**
For the ManageFileSystem adapter to be thorough, it would be nice to also have the ability to rename a directory. The workaround now is deleting a directory and then making the directory anew, but you also need to delete all files and subdirectories first (see #1188).

**Describe the solution you'd like**
A simple rename action for folders.

**Describe alternatives you've considered**
See mentioned workaround.

**Comment by jacodg** [comment]
Bibi has today tested ManageFileSystem adapter that is now part of F!F with an input as the following:

<manageFileSystemREQ>
    <rename>
        <filename>fileOrFolderName</filename>
        <destination>newFileOrFolderName</destination>
    </rename>
</manageFileSystemREQ>

And was able to rename both a file and a folder without a workaround being present in the ManageFileSystem adapter
