### ISSUE TITLE
OutOfMemoryException MIN/MAX function with only NULLs Oracle database

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1191]
**Describe the bug**
When using a query with a MIN or MAX (and possibly other functions) a GROUP BY and the column only contains NULLs, I get OutOfMemoryExceptions. This does not happen locally with Tomcat. The error is present in both calls from adapters as via Execute Query.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
1. Have a DB with a table with some rows, with one column consisting of only NULLs
2. Execute a query with a MIN() or MAX() function on the column that contains all NULLS
3. Get heap space error

**Expected behavior**
Get the null="true" attribute as happens with Tomcat.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): WebSphere
 - Browser [e.g. chrome, safari]: N/A
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20201021.120101
- Database: Oracle

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)
[Stacktrace.txt](https://github.com/ibissource/iaf/files/5422365/Stacktrace.txt)

**Comment by gvanbrakel** [comment]
There appears to be an endless loop in JdbcUtil.warningsToXml(). Promise to solve that shortly
