### ISSUE TITLE
Feature Request: Add xs namespace to XmlIfPipe (and possible other pipes)

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1202]
**Reporter**
Ricardo

**Is your feature request related to a problem? Please describe.**
I want to do some boolean-check using an XmlIfPipe, for which the field can be 0/1/false/true. Xpath contains a function xs:boolean() to convert the 0/1 to false/true, making the check a lot easier. However, the xs namespace is not available for the XmlIfPipe xpathExpression attribute.

**Describe the solution you'd like**
To have the xs namespace available in the XmlIfPipe and other pipes for which the xpathExpression attribute can be set.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gvanbrakel** [comment]
XmlIfPipe should support namespaceDefs attribute like XsltSender does
