### ISSUE TITLE
Test a Pipeline fails without error on ZIP file

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1219]
**Describe the bug**
When using a ZIP file to use "Test a Pipeline" and an error occurs with the ZIP, no error message is shown, only a green bar.

**Reporter**
Ricardo/Bibi

**Category** 
Use following Tags to categorize your bug report
 - Frank Console

**To Reproduce**
1. Open Test a Pipeline
2. Use .zip file (will be send per mail) on any adapter
3. Get green bar

**Expected behavior**
A clear and concise error of why the file could not be processed.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Tomcat
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20201021.120101

**Additional context**
N/A

**Comment by gvanbrakel** [comment]
I tested with ibis4sapbp on TST, which is running on 7.5RC2. It appears that there the file (either zip or txt) is not recognized in test a pipeline: the error message says: 'Please specify a file or message!'
I tested also on ibis4example, which is running on 7.6 snapshot. There a small zip file I created myself is executed without a problem. The zipfile that was sent by mail, however, indeed fails without any trace.
