### ISSUE TITLE
Erroneously warns of non existing columns in frank console

### ISSUE THREAD

**Issue by VBPham** [ibissource/iaf#1224]
**Describe the bug**
Console warns of non existing columns who are present and used even when message are processed by adapter with messagestores. in both old and new gui 

in iaf 7.6-20201028.131511

**Reporter**
Vinh Ban Pham

**Category** 
Use following Tags to categorize your bug report
 - Frank Console or
 - Frank Framework

**To Reproduce**
1. Upgrade to 7.6-20201028.131511
2. open Frank console
3. See warnings

**Expected behavior**
No warnings when columns are indeed there

**Screenshots**
attached 
![image](https://user-images.githubusercontent.com/24545406/97878647-3082c400-1d1f-11eb-9391-1f967a154540.png)

**Environment:**
 - presumably OTAP, but Test for now

**Comment by nielsm5** [comment]
When using a MSSQL database
