### ISSUE TITLE
Cmissender doesnt get stubbed locally with new beautiful formatting

### ISSUE THREAD

**Issue by VBPham** [ibissource/iaf#1225]
**Describe the bug**
Cmissender could be missing from uglify_lookup.xml which could be the reason why its not getting stubbed locally

in iaf 7.6-20201028.131511

**Reporter**
Vinh Ban Pham

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
1. Make adapter with cmissender in beautiful format e.g. 

`<SenderPipe name="Find Call CMIS"
      active="${active.cmis}"
      storeResultInSessionKey="CMIS_Output">
   <CmisSender name="findCallCmis"`

2. start ibis locally and see that cmissender is not stubbed with

<sender className="nl.nn.adapterframework.senders.IbisJavaSender"
                       serviceName="testtool-Call CMIS Archive"/>

**Expected behavior**
Cmissender written in new "beautiful" format is stubbed when starting the ibis locally

**Screenshots**
na

**Environment:**
 -Local machine (win10, chrome browser)

**Additional context**
na

**Comment by ricardovh** [comment]
Fixed in #1345
