### ISSUE TITLE
InstanceAlreadyExistsException on updating configuration

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1237]
**Describe the bug**
When updating a configuration using the DatabaseClassLoader, I sometimes get an error when loading.

`error during unmarshalling configuration from file [Configuration.xml] with digester-rules-file [digester-rules.xml] in element [adapter]: (SaxException) line [103] column [17] : (InvocationTargetException): (UnableToRegisterMBeanException) Unable to register MBean [[...]] with object name [...]; nested exception is javax.management.InstanceAlreadyExistsException: (InstanceAlreadyExistsException) ...`

This seems to happen when the updated configuration is loaded with a transaction still in progress. Reloading the configuration is not possible, only a complete restart solves the issue.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Console
 - Frank Framework

**To Reproduce**
Unfortunately unknown

**Expected behavior**
No error.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): WebSphere
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20201030.100621

**Additional context**
N/A

**Comment by nielsm5** [comment]
Websphere lijkt aan onze mbean implementatie te zitten, en niet alle attributen juist over te nemen. Tijdens registratie zetten wij OVERWRITE EXISTING, de melding zegt ALREADY EXISTS. Lijkt er op dat er een fout zit in Websphere bij het overkopieren van de mbean properties ...
