### ISSUE TITLE
Cannot determine number of messages in errorstore, NullPointerException

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#1256]
**Describe the bug**
The ibis4titan.log files show a lot these nullpointerExceptions:

2020-11-11 09:03:27,344 WARN [WebContainer : 7] null api.ShowConfigurationStatus - Cannot determine number of messages in errorstore
nl.nn.adapterframework.core.ListenerException: cannot determine message count: (NullPointerException)

**Reporter**
Richard van der Stel

**Category** 
 - Frank Console
 - Frank Framework

**To Reproduce**
1. Go to logging
2. Click on ibis4titan.log
3. Scroll down to nullpointerException

**Expected behavior**
no nullpointers

**Screenshots**
see attachment for stacktrace

**Environment:**
 - Application server Websphere
 - Browser n.a.
 - IAF Version : FF! 7.6-20201110.095003

**Additional context**
see attachment for stacktrace
[NullPointerException.txt](https://github.com/ibissource/iaf/files/5522717/NullPointerException.txt)

**Comment by gvanbrakel** [comment]
Appears to be a local issue with the prepared statement cache. Expected to be solved by a restart

**Comment by alisihab** [comment]
I have the same issue on tomcat.
[st.txt](https://github.com/ibissource/iaf/files/5535448/st.txt)
