### ISSUE TITLE
500 error on ibisdoc GET call on local frank

### ISSUE THREAD

**Issue by diedekerkhof** [ibissource/iaf#1262]
**Describe the bug**
When doing a get on ibisdoc in local frank enviroment (http://localhost/rest/ibisdoc/ibisdoc.json) it sometimes returns a 500 error.

**Reporter**
Diederik Kerkhof

**Category** 
 - Frank Framework

**To Reproduce**
1. Start up Frank2Example4 in the frankrunner
2. Go to http://localhost/frank-flow/
3. Press f12to see console output
3. Refresh page until a 500 get error occurs on the ibisdoc (http://localhost/rest/ibisdoc/ibisdoc.xsd)

**Expected behavior**
Always return the ibisdoc

**Environment:**
 - Application server (Frankrunner)
 - Browser [not related]
 - IAF Version [7.6-20201113.095020]

**Additional Information**
- Added log file from frank about the error: [frank2example4.log](https://github.com/ibissource/iaf/files/5536350/frank2example4.log)

**Comment by gvanbrakel** [comment]
Will be fixed in rework of IbisDoc

**Comment by jacodg** [comment]
Should be fixed when you use /iaf/api/frankdoc/files/frankdoc.json

See also https://ibis4example.ibissource.org/iaf/api/frankdoc/files/frankdoc.json
