### ISSUE TITLE
Resending errors programmatically 

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#1268]
**Reporter**
jjansenvr (jeroen)

**Is your feature request related to a problem? Please describe.**
Example: 
Incoming FF message on my adapter -- >
a http sender -- >
the backend system is not responsive -- >
extreme amount of error messages in my errorstore to resend manually

**Describe the solution you'd like**
II would like to trigger resending of messages from a specific error store based on a schedule.

Two possible solutions:

- Add an errorResend **function** to the scheduler taking a **query** to select the richt slotid and potentially other selectors to specify the records to resend
- Create a resendSender that will resend an error message based on a query or list of errormessageId's, this will allow the developer to add extra functionality to inform service management about the result of the resend action.

**Describe alternatives you've considered**
Manually resend error messages via the console (max 100 per page) 

**Additional context**
as discussed during core meeting 16-11-2020

**Comment by jacodg** [comment]
ResendErrorPipe

**Comment by gvanbrakel** [comment]
retryCount should be reset somehow when a message is retried.
It might be an option to store this count in the database table.
