### ISSUE TITLE
Confusing version indications in Frank Console

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#1271]
**Describe the bug**
The Frank Console has in two places an indication of a version, what seems to be the version of the framework:
1) At the top of the screen, e.g. FF! 7.6-20201105.094427: Ibis4Test
2) At the 'Information' screen: e.g. FF! 7.6-20201113.112750: Ibis4Test

**Reporter**
Gerrit

**Category** 
Use following Tags to categorize your bug report
 - Frank Console
 - Frank Framework

**To Reproduce**
1. Go to Ibis4TestIAF
2. Click on 'Information; 
3. See that the version displayed in the information box differs from the version on the background 

**Expected behavior**
Versions to be the same, or have a clear explanation of what the version refers to.

**Screenshots**
![image](https://user-images.githubusercontent.com/4170104/99508430-dcb1e500-2984-11eb-9366-70b629cb65b7.png)

**Environment:**
 - Application server: WebSphere
 - IAF Version 7.6

**Comment by alisihab** [comment]
I could not reproduce the issue by browsing Ibis4testiaf. Could it be cache related?

![image](https://user-images.githubusercontent.com/10929856/104018305-d89e8880-51b9-11eb-8ca4-89c1e1d966e8.png)

**Comment by alisihab** [comment]
does not seem to happen anymore.
