### ISSUE TITLE
"seen and continue" function for the error store

### ISSUE THREAD

**Issue by BonnoSmeele** [ibissource/iaf#1277]
**Reporter**
Bonno Smeele!

**Is your feature request related to a problem? Please describe.**
We often have messages in the error store that we do not want to resend immediately but would like to keep for future processing.
At the moment there is no way to easily store these messages and keep them seperate from new messages in the erro store.

**Describe the solution you'd like**
I would like to have a button in the error store. When i click this button the selected messages in the store get a new status like "seen" or "skipped". Messages with this status will remain in the error store but will not be seen or available in the error store for resend.

These skipped messages can be processed manually at a later time.

**Describe alternatives you've considered**

**Additional context**

**Comment by gvanbrakel** [comment]
We could solve this by introducing an additional status / errorStorage that could be called something like 'specialCase' or 'outOfProcess'

**Comment by gvanbrakel** [comment]
This has been implemented using 'Hold' status, for JdbcTableListener and all FileSystem-based listeners.
