### ISSUE TITLE
Larva test hangs for several minutes on the write of an [error]

### ISSUE THREAD

**Issue by woutervdschoot** [ibissource/iaf#1292]
**Describe the bug**
A larva test scenario will hang for a few minutes on a write action of [error]

**Reporter**
Wouter van der Schoot

**Category** 
Use following Tags to categorize your bug report
 - Larva
 - Performance

**To Reproduce**
1. Go to 'https://vcs.aws.insim.biz/ibissource/si/ibis4adn'
2. Clone all ibis4adn related projects
The test scenario in question is in ibis4adn_outbound - OutboundTrigger\scenario02-ERROR - OutboundTrigger ERROR, PRC_TYDST is not updated in OUTBOUNDTRIGGER table
3. Run this test scenario
4. The scenario will hang for several minutes on step7.sender.SendMFTMessage_Solera.write=common/MFTResponse_Error.txt
5. Eventually the scenario will complete, but step7 takes way to long

**Expected behavior**
I expect that each step would take a few seconds

**Environment:**
 - Frankrunner
 - Browser chrome
 - IAF Version 7.6-20201123.110830

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

In the same repo (ibis4adn_outbound) is the following test scenario:
ProcessOutbound_PMB_PPR\scenario07-ErrorMFT
This scenario does exactly the same as the first scenario (with the same adapters) with the following difference:

The first scenario starts the adapter from another ibislocalsender, in other words there are more nested adapters..
The ProcessOutbound scenario does NOT hang whereas the ProcessOutboundTrigger scenario does.

[Pipeline ProcessOutboundTrigger_DUURTTELANG.zip](https://github.com/ibissource/iaf/files/5597257/Pipeline.ProcessOutboundTrigger_DUURTTELANG.zip)

[Pipeline ProcessOutbound_GAATWELGOED.zip](https://github.com/ibissource/iaf/files/5597291/Pipeline.ProcessOutbound_GAATWELGOED.zip)

**Comment by jacodg** [comment]
Could you create a simple/anonymous example that we can simply copy into a random Ibis to lower the threshold to analyze this issue?

Maybe this example can afterwards be added to Ibis4TestIAF as a regression test.

**Comment by jjansenvr** [comment]
My guess is you are waiting for a timeout multiple times

One thing I used to do is change the timeout setting of the testtool, but then the testtool was still a separate project

looked in the code and this seems to be the place,
/larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java
protected static final int DEFAULT_TIMEOUT = 30000;
adjust to 
protected static final int DEFAULT_TIMEOUT = 5000; 

After discussing with the core team we decided that there must be something wrong and changing the timeout is just a workaround. In case of an error,  this error should be handled and not wait 30 seconds for the timeout. 

So the adjustment should be that when we use a stubbed sender we should not use a timeout and in places where we do not use the stubbing (by default in databasessenders , localsenders and more) the timout is still valid.

**Comment by woutervdschoot** [comment]
The attached file contains a "simple/anonymous example" for this issue
[NestedError.zip](https://github.com/ibissource/iaf/files/5665007/NestedError.zip)

1. unpack the zip file
2. Move the folder _NestedErrorConfig_ to your local **frank-runner\examples\Frank2Example1\configurations** folder
3. Move the folder _NestedErrorTest_ to your local **frank-runner\examples\Frank2Example1\tests\Example1**
4. Start the frank-runner (without setting project.dir)
5. Go to http://localhost/ 
6. Open Testing/Larva
7. Run the NestedErrorTest\Scenario01-ERROR
8. Wait :P
 
![image](https://user-images.githubusercontent.com/64192487/101615393-5d0cb880-3a0e-11eb-997e-e9b9a87f5a80.png)
