### ISSUE TITLE
Add Message support to PipeLineSession

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#1297]
**Reporter**
Gerrit

**Is your feature request related to a problem? Please describe.**
Currently pipes often expect session variables to be of a specific type, like String or byte array. This conflicts with the storeResultInSessionKey option, because the results of pipes are messages.

**Describe the solution you'd like**
Handle user session variables as Messages

**Describe alternatives you've considered**

**Additional context**

**Comment by nielsm5** [comment]
Fixed in https://github.com/ibissource/iaf/pull/1640
