### ISSUE TITLE
Missing element in WSDL 

### ISSUE THREAD

**Issue by tomavanderheijden** [ibissource/iaf#13]
If there is a missing element in the provided wsdl, the rpcrouters wsdl will tell you that you are missing an element, but no errors will return from testtool and there will be no validation. It is weird that this doesnt give an extra warning or error.

**Comment by jjansenvr** [comment]
Tom please recheck this issue, do not know if it is still a problem

**Comment by tomavanderheijden** [comment]
Can't reproduce it.
