### ISSUE TITLE
Filter Timestamp werkt niet (MessageLog)

### ISSUE THREAD

**Issue by DLeymann** [ibissource/iaf#1301]
Describe the bug
De filter Timestamp filtert niet op MessageLog scherm

Reporter
David Leymann - Nationale Nederlanden.

Category
Frank Console
To Reproduce

Adaptor>MessageLog - op dit scherm staan de filters ID, Timestamp. Filter ID werkt wel. Invoer in Timestamp reageert niet op lijst.

Expected behavior
Timestamp filter werkt en laat zien de rijen vanaf de timestamp

Screenshots
Geen

Environment:
IAF 7.5-RC3: ibis4belasting
Running on srazzapp0359.insim.biz using IBM WebSphere Application Server/8.5
Java Version: Java(TM) SE Runtime Environment (8.0.6.0 - pxa6480sr6-20191107_01(SR6))
Browser: MS Edge Version 87.0.664.47 (Official build) (64-bit)

Additional context
Geen.

**Comment by gvanbrakel** [comment]
This problem has been solved in the 7.5 release (i.e. the latest version of the 7.5 branch, that has been relased 2020-11-13)
