### ISSUE TITLE
EWS Listener -> (IllegalStateException) Connection is still allocated

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#1305]
**Describe the bug**
Whenever a configuration containing an ExchangeMailListener is reloaded it keeps throwing (IllegalStateException) Connection is still allocated.

**Reporter**
Laurens Mäkel

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
1. See 401 input

**Expected behavior**
Connection to be properly closed when stopping the adapter.

**Screenshots**
![image](https://user-images.githubusercontent.com/37303445/100619589-b04f7e80-331d-11eb-9c47-a0d179c4a2dc.png)

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty) WebSphere
 - Browser [e.g. chrome, safari] Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6] 7.6-20201127.153142

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
Same as #1212

**Comment by Laurens-makel** [comment]
I've attached the log file containing the IllegalStateException errors.


[ibis4input.txt](https://github.com/ibissource/iaf/files/5622029/ibis4input.txt)
