### ISSUE TITLE
Error store resending/performance issues

### ISSUE THREAD

**Issue by BonnoSmeele** [ibissource/iaf#1321]
**Describe the bug**
When something goes into error with an errorstorage configured, the incoming message is saved and can be retried/deleted from error storage.

When deleting no tracing is possible, for this a different ticket is already created.
When retrying it's possible to process items more than once and select all works wierd. Besides that performance is below expectations.

In case you have messages being retries and you refresh the page, it's possible to retry the same message.
In case you use multiple nodes, it's possible that all nodes process the same message.
In case multiple users retry messages, it's possible that the same message is processed multiple times.
This causes duplicate output which is highly unwanted.

~~When clicking select all, it does not only select all visible records, but also selects all earlier accessed records. When for example opening error storage page 1, then page 3 and then page 5 and click 'select all' and 'retry selected'. Then first all page 1 messages are retried, then page 3 and then page 5.~~ (see #1355)

When messages are being retried, it's being done with 1 thread leading to 1 message at a time. For the engageone process we use 15 threads for speed. 1 thread is not enough to process a daily load. Therefore is not usable to recover 1 day of errors.

**Reporter**
Bonno Smeele for Jeri Tjalsma
**Category** 
Use following Tags to categorize your bug report
 - Frank Console
-Frank Framework

**To Reproduce**
Should be reproducable by sending messages to the error store

**Expected behavior**
- prevent duplicate messages being sent from error store during recovery
- fix bugs with selection in console
- enable multiple threads on error store resending to speed up processing

**Screenshots**

**Environment:**
 - Websphere
 - any browser
 - FF! 7.6-20200722.094609

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
Currently messages are 'retried' as described above: by retrying them individually. I suggest this to change the way of retrying, for Listeners that support it, by moving the messages from the 'errorStorage' to the 'input' queue. This can be implemented for all FileSystem based Listeners (DirectoryListener, ExchangeMailListener, ...) by moving from 'errorFolder' to 'inputFolder'. It can also be implemented for the JdbcTableListener, by updating the status from 'statusError' to 'statusAvailable'.

**Comment by BonnoSmeele** [comment]
In the case of a jdbc table listener, would it be an idea to create a retryQuery property in the jdsbclistener that can be used to reset errors entries in the table? This query could be executed when the retry button is pressed.

For instance, at the moment we have this error query in the listener:

updateStatusToErrorQuery="UPDATE OUTPUTSET SET OUTPUTSET_STATUS = 4 WHERE OUTPUTSET_ID = ?"
with this key field:
keyField="OUTPUTSET_ID" 
This could correlate all the IDs from the selected messages in the error store with the JDBC listener tabler and set them to a "ready" status.


Apart from this suggestion there is also the problem of the UI selecting messages for retrying from pages that have been visited manually in the error store. This is not intuitive:

"When clicking select all, it does not only select all visible records, but also selects all earlier accessed records. When for example opening error storage page 1, then page 3 and then page 5 and click 'select all' and 'retry selected'. Then first all page 1 messages are retried, then page 3 and then page 5."

**Comment by gvanbrakel** [comment]
Made separate ticket #1355 for the 'Select All' issue
