### ISSUE TITLE
Log more/all activity of ApiListeners

### ISSUE THREAD

**Issue by buckmaz** [ibissource/iaf#1325]
**Reporter**
Bastiaan Udo

**Is your feature request related to a problem? Please describe.**
Request from Jeri Tjalsma as PO of ibis4oma

**Describe the solution you'd like**
At the moment, the ApiListener does not seem to log much. Expand logging in case something goes wrong. Currently it's very hard to determine why requests get denied somewhere in the chain.

We've seen Accept header being unacceptable (405) without any logging
We've seen method being unauthorized (403) without any logging.
We've seen endpoint not being authorized (401) without any logging.
We've seen wrong password used (401), only error logged, not userId

We would like info logging of all requests: endpoint, method, userId, timestamp and duration.
We would like error logging of all failing requests: endpoint, method, userId, timestamp and duration. Possible with reason of failing.

**Describe alternatives you've considered**
We thought it best resolved in the IAF

**Additional context**
I spoke to Ali, he said this functionality was already conferred over within the IAF core team, but not yet planned.

**Comment by jacodg** [comment]
Higher than 4XX is a warning might be a good default
