### ISSUE TITLE
Ibis4Test on Tomcat with Tibco/EMS on AWS

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#1330]
**Reporter**
Gerrit, on behalf of Miel Hoppenbrouwers

**Is your feature request related to a problem? Please describe.**
There are rumors that it would be hard or even impossible to run Ibis on Tomcat with Tibco/EMS on AWS. It would be a good idea to disprove these rumors, by installing and running iaf-test in this setup.

**Describe the solution you'd like**
Extend the deployment of Ibis4TestIAF to AWS, with Tibco included

**Describe alternatives you've considered**

**Additional context**

**Comment by gvanbrakel** [comment]
Mail of Miel to his product owner:

Marcel Hijma, Websphere specialist, told me it is impossible to get the combination of Tomcat + Tibco/EMS (where messages go from one system to the other) working. And Tomcat is the way to deploy IBIS applications in AWS (because NN does not want to user WebSphere anymore). 

That would be a problem for the MRBD solution for Retail, so it is important to check if there really is a problem.

Gerrit is addressing this question within WeAreFrank. We may need set something up together with WeAreFrank to get this tested – before we start developing with MongoDB.

**Comment by gvanbrakel** [comment]
Aanvullende informatie: Shibnath zegt dat het centrale “spoc” team een IBIS in AWS draaiend zou hebben gehad, met LDAP en EMS connecties.
We weten echter geen details. Of er werkelijk ook een EMS bericht is verwerkt bv.
Betrokken persoon was  Druenen, F.J. van (Fabian) <fvandruenen@nn-group.com>

[Druenen, F.J. van (Fabian)
At this moment we are trying to move Tibet2 to openliberty(closure to IBM WAS) on a EC2 container
Tomcat is a servlet container & openliberty application EE container. No transaction monitors config are needed ships with openliberty
We are trying EC2 because transition from on-prem to full cloud we need to restructure Tibet2 and that's not the scope (yet)
We are trying to discover the do/dont with the ibis-framework on EC2 of K8s etc. Also the management of the adapters vs pods are still a challenge

**Comment by jacodg** [comment]
@VBPham gerrit will discuss and assign this to you
