### ISSUE TITLE
blockSize is ignored in ResultSetIteratingPipe

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#1349]
**Describe the bug**
Since we upgraded to IAF 7.6-20201118.153744, the blockSize in the ResultSetIteratingPipe is ignored. Now we get only one record instead of mutliple records. The result of the select SQL statement is more than one record.

**Reporter**
Richard van der Stel

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**

**Expected behavior**
The resultset should iterate in blocks over the total set. For instance, the total set is 100 and the blocksize is 10. Then the resultsetiteratingpipe should read 10 records each time and pass them to the next pipe, a localibissender. 

**Screenshots**
Here you can see that the blockSize=5. There are 11 records in the database table.
Because the blockSize is ignored, you see 11 Sender ProcessQueryDocumentStatusRecord lines. 
This should be 3 lines (2 * 5 =10 + 1)
![image](https://user-images.githubusercontent.com/35798481/102619367-a1016b00-413c-11eb-9618-349abbe4ed30.png)

**Environment:**
 - Application server (Tomcat/WebSphere)
 - Browser [chrome]
 - IAF Version [7.6-20201118.153744]

**Additional context**
I have an adapter with a larva test available.

**Comment by gvanbrakel** [comment]
Workaround could be to use FixedQuerySender and ForEachChildElementPipe. When the attribute streamingActive=true is set on the ForEachChildElementPipe, records will be processed when they are read, so not all records will be read in to memory before processing is started.
