### ISSUE TITLE
Jobs not created when using V2 config

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1350]
**Describe the bug**
When using the V2 config and validating against https://ibis4example.ibissource.org/rest/ibisdoc/ibisdoc.xsd, creating a job is done using a <Job> element in the Configuration/Module. When loading the config, the Job is not created, because the \<job\> needs to be a child of \<scheduler\>, but that element is not created.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
1. Load the attached configuration
2. Check the Scheduler page in the console
3. Don't see the job
4. Open the Show configurations page
5. See the job without parent scheduler element

**Expected behavior**
To have the job being created correctly. This can be done by either:
- create the scheduler-element as part of canonicalize.xsl
- remove the need for the scheduler-element completely (keep for backwards compatibility)
- fix this in the new upcoming XSD

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Tomcat
 - Browser [e.g. chrome, safari]: N/A
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20201217.135711

**Additional context**

[ConfigurationSchedule.txt](https://github.com/ibissource/iaf/files/5716204/ConfigurationSchedule.txt)

**Comment by jacodg** [comment]
Waiting for new Frank!Doc (Martijn is working on it)
