### ISSUE TITLE
ibisdoc url in webservices tab not shown with correct name (ibis4example)

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#1360]
**Describe the bug**
The link for the ibisdoc has the name "restlistener" 

**Reporter**
Jeroen

**To Reproduce**
https://ibis4example.ibissource.org/iaf/gui/#!/webservices

**Expected behavior**
The link should be based on the service name not on the implementation

**Screenshots**
![image](https://user-images.githubusercontent.com/3921911/103515294-bd0c4880-4e6e-11eb-8ded-b11b7f12a12f.png)

**Comment by gvanbrakel** [comment]
We now appear to focus on changing the name of the receiver. Another approach might be to include the name of the Adapter in the label at the webservices page. After all, a Receiver is just a Receiver of the Adapter.
