### ISSUE TITLE
Duplicate message processing due to non robust processing, and absence of warnings

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#1363]
**Describe the bug**
In my situation I have two adapters, the first adapter takes a message over HTTP and splits this message into multiple individual messages, stores them in the Message Store to be processed by the second adapter.

In this case the first adapter splitted the message into three individual messages:
![image](https://user-images.githubusercontent.com/37303445/103537052-f1463000-4e93-11eb-96ae-5f4e14dac492.png)

In my second adapter I configured the receiver as following:
```
 <receiver name="TitanPOST_Subsets_Processor_Receiver" numThreads="2">
	<listener className="nl.nn.adapterframework.jdbc.MessageStoreListener"
		name="TitanPOST_Subsets_Processor_Listener"
		jmsRealm="jdbc"
		slotId="Ibis4Navigator/ArchiveDocumentsSubset"
	/>
	<errorStorage className="nl.nn.adapterframework.jdbc.JdbcTransactionalStorage"
		name="TitanPOST_Subsets_Processor_Listener_ErrorStorage"
		jmsRealm="jdbc"
		slotId="Ibis4Navigator/ArchiveDocumentsSubsetError"
	/>
</receiver>
```

I also added a locker element configured as following to the pipeline because multiple nodes were processing the same message:

`<Locker name="Locker" jmsRealm="jdbc" objectId="TitanPOST_Subsets_Processor" />`

I would expect **173097, 173098, 173099** to be processed once

When I look in Ladybug, I see that message **173098** is proccessed **twice** on the same node.
 
![image](https://user-images.githubusercontent.com/37303445/103537376-96f99f00-4e94-11eb-9b26-8aa43f717bab.png)

**Reporter**
Laurens Mäkel

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
416 Navigator & Input chain

**Expected behavior**
First of all, I expect that it wouldnt be nescescarry for a Locker element to prevent the same message being processed twice on different nodes.

Secondly, I expect that the MessageStoreListener will process a message only once, maybe it's related to the facts that I am using two threads to process messages but I expect that when I configure numThreads is more as 1 and I do not configure numThreadsPolling (which has a default value of 1), that there would be 1 polling call to retrieve all messages to be processed and spread them out over the available threads.

**Screenshots**
See above.

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty) Websphere
 - Browser [e.g. chrome, safari] Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6] 7.6-20201217.094031

**Additional context**
-

**Comment by Laurens-makel** [comment]
I have retried the same scenario a three more times and it gives me the exact same results, it always seems to be the second message that is stored in the message store that is processed twice:

**Test 1:**

Store individual messages (3 in total):
![image](https://user-images.githubusercontent.com/37303445/103538454-834f3800-4e96-11eb-9d97-7ef314ff5231.png)

Message with id ending in 108 is processed twice:
![image](https://user-images.githubusercontent.com/37303445/103538488-9235ea80-4e96-11eb-844a-2d8b1d4ffea8.png)


**Test 2:**

Store individual messages (3 in total):
![image](https://user-images.githubusercontent.com/37303445/103538628-d9bc7680-4e96-11eb-9d25-26080aab8294.png)

Message with id ending in 117 is processed twice:
![image](https://user-images.githubusercontent.com/37303445/103538647-e6d96580-4e96-11eb-97ff-89e6177729db.png)


**Test 3:**

Store individual messages (3 in total):
![image](https://user-images.githubusercontent.com/37303445/103538797-3324a580-4e97-11eb-92f2-8d044a0def4d.png)

Message with id ending in 126 is processed twice:
![image](https://user-images.githubusercontent.com/37303445/103538820-3cae0d80-4e97-11eb-86d9-2fc4cc0954a3.png)

**Comment by gvanbrakel** [comment]
A locker on the pipeline does not help in this situation. It prevents that the pipeline is running multiple times, but has no influence on the message being selected or not.
What could happens is:
a) one thread sees the message and starts processing it, but before this thread has set the status to 'inProcess' the next thread already sees it as available. (This is not the case, no status 'inProcess' used in this configuration, but the situation should be fixed anyway)
b) The lock does not work, because there is no transaction. The locking of the row works with a SELECT FOR UPDATE. This only holds, however, for the duration of a transaction. 

To solve the issue in this configuration, `transactionAttribute="Required"` must be set for the Receiver.

To fix the potential problem under a), a fix will have to be made in the framework: setMessageStateToInProcess(), now called in PullingListenerContainer.231 must be executed before the pollToken is released, now on PullingListenerContainer.220

**Comment by Laurens-makel** [comment]
Thank you @gvanbrakel, adding the following to the receiver fixed the problem:

 `transactionAttribute="Required"`

I removed the Locker and tested the solution again, it process every message once, even when executed on multiple nodes, just like expected.

**Comment by gvanbrakel** [comment]
Reopen the issue, to improve robustness of moving to status 'inProcess', and display appropriate warnings where possible
