### ISSUE TITLE
Undocumented behavior active attribute

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1374]
**Describe the bug**
In configurations it is possible to enable/disable parts using the active attribute and set it to true or false. The IbisDoc only has this attribute for Pipes (via AbstractPipe) and a small set of other objects, but the active attribute is processed for all elements in https://github.com/ibissource/iaf/blob/master/core/src/main/resources/xml/xsl/active.xsl.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**

**Expected behavior**
Have the docs to describe the active attribute for all elements. This would require adding the active attribute to the objects that currently don't have it, as the docs are generated from the code.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty); N/A
 - Browser [e.g. chrome, safari]: N/A
 - IAF Version [e.g. 7.5 RC3, 7.6]: all

**Additional context**
N/A

**Comment by jacodg** [comment]
Attribute active needs to be added to every FrankElement (the active attribute is managed by the active.xsl)
