### ISSUE TITLE
Build fails on Azure

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#1384]
**Describe the bug**
Test for DateUtils and FlowDiagram fail on Azure.

**Reporter**
Jaco

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
1. Go to https://ibis4testiaf.visualstudio.com/MyFirstProject/_build?definitionId=1
2. See failure from 2020-12-14

**Environment:**
 - Azure
 - IAF Version 7.6

**Comment by mhdirkse** [comment]
The build also fails on my development PC. I tried building in MinGW and building in a DOS command window.

**Comment by nielsm5** [comment]
> The build also fails on my development PC. I tried building in MinGW and building in a DOS command window.

Could you elaborate which tests fail?

**Comment by mhdirkse** [comment]
[ERROR] Errors:
[ERROR]   FlowDiagramTest.canInitDefaultWithoutErrors:33 ▒ IO failed to open vizjs file ...
[ERROR]   FlowDiagramTest.canInitSVGWithoutErrors:50 ▒ IO failed to open vizjs file for ...
[ERROR]   FlowDiagramTest.getUnknownFormat ▒  Unexpected exception, expected<java.lang.I...
[INFO]
[ERROR] Tests run: 3272, Failures: 0, Errors: 3, Skipped: 158

**Comment by mhdirkse** [comment]
Oh, I did not see it was closed already. I will merge my branch with master and try my test again.

**Comment by mhdirkse** [comment]
Merging does not fix my issue. But my issue is also covered by issue #1402 . Therefore this issue does not need reopening. Niels, the info you requested is in issue #1402 as well.
