### ISSUE TITLE
CheckReload executed even when no config has DatabaseClassLoader

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1390]
**Reporter**
Ricardo

**Is your feature request related to a problem? Please describe.**
When having an Frank that has no configurations loaded using a DatabaseClassLoader, the CheckReload is still executed every minute and queries the database for active configurations. This might lead to errors if there is no database/no ibisconfig table (as is currently happening on https://ibis4example.ibissource.org/iaf/gui/#!/scheduler). 

**Describe the solution you'd like**
A check to be executed before the query to check if there are configurations for which a reload might make sense.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nielsm5** [comment]
Solved in https://github.com/ibissource/iaf/pull/2726
