### ISSUE TITLE
Log different message on locker

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1407]
**Reporter**
Ricardo

**Is your feature request related to a problem? Please describe.**
When using a job with a locker, a "error while setting lock:" is shown in the console each time the node could not obtain the lock because of a Unique constraint violation. This is not really an error as the job is executed on another machine, but might confuse users that are less familiar with the working of the framework.

**Describe the solution you'd like**
Do not log the message with error in the text, but something like: "Job not executed, locked by another process". Maybe also log in the executions in the console, so that the console has a complete log so that it is easier to see which machine executed the job.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jacodg** [comment]
Warning (not error) in Locker should be "could not obtain lock"

It would be nice to have a message that shows that a job has executed either with or without having obtained a lock
