### ISSUE TITLE
Feedback function of FF! does not work

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#1416]
**Describe the bug**
When I go to ibis4example and use the feedback function, I get an error dialog when I press "send".

**Reporter**
Martijn Dirkse

**Category** 
Use following Tags to categorize your bug report
 - Frank Console

**To Reproduce**
1. Go to ibis4example.
2. Press the stars.
3. Fill in some data in the form that appears.
4. Press "send".
5. The attached error dialog appears.
![feedbackBroken](https://user-images.githubusercontent.com/6784732/105684059-b82e3800-5ef4-11eb-8da0-9076e31bd4e8.jpg)

**Expected behavior**
No error dialog appears. The contents written in the form appears as a text file in ftp://ibissource.org/feedback

**Screenshots**
See attachment.

**Environment:**
- Browsing ibis4example.
- 
**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Werkt weer!
