### ISSUE TITLE
MessageStoreListener commiting transaction fails on SQL Server causing messages to be processed twice and deadlocks on table

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#1417]
**Describe the bug**
It seems that messages are picked up twice due to transactional issues with MS SQL DBMS. As you can see the messages with 70 and 71 are processed twice, immediately after the first has finished with state = success.

StorageId | EndTime | Duration | Name | CorrelationId | Status | NrChpts | EstMemUsage | StorageSize
-- | -- | -- | -- | -- | -- | -- | -- | --
8657 | 2021-01-25 11:16:42.332 | 4284 | Pipeline TitanPOST_Subsets_Processor | 183570 | Success | 215 | 2198966 | 1167702
8656 | 2021-01-25 11:16:40.490 | 4903 | Pipeline TitanPOST_Subsets_Processor | 183571 | Success | 215 | 2198798 | 1167694
8655 | 2021-01-25 11:16:37.781 | 15921 | Pipeline TitanPOST_Subsets_Processor | 183570 | Success | 214 | 2187966 | 1167633
8654 | 2021-01-25 11:16:35.189 | 13325 | Pipeline TitanPOST_Subsets_Processor | 183571 | Success | 214 | 2193294 | 1167657

**Reporter**
Laurens Mäkel

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
Please contact me and I'll show you.

**Expected behavior**
The transaction to be commited without exceptions when the pipeline is finished succesfull.

**Screenshots**

**Environment:**
 - Application server: [e.g. Tomcat/WebSphere/JBOSS/Jetty] Websphere 8.5
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql,PostgreSQL] MSSQL
 - Browser: [e.g. Chrome, Safari, Edge] Chrome
 - IAF Version: [e.g. 7.5, 7.6] 7.6-20201217.094031:

**Additional context**
See attached log files.
[stacktrace.txt](https://github.com/ibissource/iaf/files/5865987/stacktrace.txt)
[system-out.txt](https://github.com/ibissource/iaf/files/5865988/system-out.txt)

**Comment by gvanbrakel** [comment]
the ladybug overview shown shows that the PipeLine executed twice sucessfully. The SystemOut shows messages concerning rollback. If a rollback happens due to some issue in the receiver-part, this will not be observable in the Ladybug status. So therefor it could be that the Pipeline is legitemately executed twice.

**Comment by Laurens-makel** [comment]
When I shared my screen with you Gerrit, we noticed that during commiting the transaction it runs into an exception whilst the configured has state="success" configured.. 

So no, the transaction is not commited twice.

I was asked by chat to share my receiver configuration so here you go:

`<receiver name="TitanPOST_Subsets_Processor_Receiver"
                   numThreads="2"
                   pollInterval="5"
                   transactionAttribute="Required">
			         <listener className="nl.nn.adapterframework.jdbc.MessageStoreListener"
                      name="TitanPOST_Subsets_Processor_Listener"
                      jmsRealm="jdbc"
                      slotId="Ibis4Navigator/ArchiveDocumentsSubset"/>
			         <errorStorage className="nl.nn.adapterframework.jdbc.JdbcTransactionalStorage"
                          name="TitanPOST_Subsets_Processor_Listener_ErrorStorage"
                          jmsRealm="jdbc"
                          slotId="Ibis4Navigator/ArchiveDocumentsSubsetError"/>
		       </receiver>`

**Comment by gvanbrakel** [comment]
It appears that the problem is that the Receiver is transacted, while the PipeLine cannot honor rollbacks.
Therefor the Receiver should not be transacted, but shoud use an inProcessState setting.
