### ISSUE TITLE
Use default datasource instead of firstDataSourceJmsRealm

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#1420]
**Reporter**
Ali

**Is your feature request related to a problem? Please describe.**
In number of places(e.g. ConfigurationUtils) firstDataSourceJmsRealm is used. 

**Describe the solution you'd like**
Use default datasource instead.

**Describe alternatives you've considered**

**Additional context**

**Comment by nielsm5** [comment]
Fix a few bugs in #1415 and hopefully also solves #648
