### ISSUE TITLE
IndexOutOfBoundsException when running iaf-test

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#1453]
**Describe the bug**
When running the larva tests of iaf-test, an IndexOutOfBoundsException occurs when running the ApiWsdlGenerator-tests

**Reporter**
Gerrit

**Category** 
Use following Tags to categorize your bug report
 - Ladybug (debugging tool) --> This project has it's own repository. Please report issues in [ibissource/ibis-ladybug](https://github.com/ibissource/ibis-ladybug/issues)
 - Larva (unit test tool)

**To Reproduce**
1. Go to iaf-test
2. Run ApiWsdlGenerator-tests
3. See errors in console

**Expected behavior**
No stacktraces in console

**Screenshots**
```
java.lang.IndexOutOfBoundsException: Index: 21, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at nl.nn.testtool.Report.addCheckpoint(Report.java:332)
	at nl.nn.testtool.Report.checkpoint(Report.java:276)
	at nl.nn.testtool.TestTool.checkpoint(TestTool.java:241)
	at nl.nn.testtool.TestTool.abortpoint(TestTool.java:507)
	at nl.nn.ibistesttool.Debugger.pipeLineAbort(Debugger.java:95)
	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeLineInputOutputAbort(IbisDebuggerAdvice.java:108)
```
**Environment:**
 - Application server: Tomcat
 - DBMS: any
 - IAF Version: 7.6
 - ibis-ladybug version 2.0.15-20210106.180557

**Additional context**
see also https://github.com/ibissource/ibis-ladybug/issues/60

**Comment by gvanbrakel** [comment]
The problem does not appear anymore in the latest iaf build, but it might be a good idea to reproduce it with a version of early February, and fix the ladybug code handling the situation.

**Comment by jacodg** [comment]
I just reproduced it with latest version of master and tested the fix in Ladybug. PR #1570 has been submitted and linked to this issue.

P.s. another exception is still visible in the Tomcat console when running ApiWsdlGenerator-tests
