### ISSUE TITLE
Field name is not column name while using "columnsReturned" 

### ISSUE THREAD

**Issue by Bibi0803** [ibissource/iaf#1468]
**Describe the bug**
While using "columnsReturned" in FixedQuerySender, the field name is "GENERATED_KEYS" instead of the column name "RECORDID" in DEV environment. Locally using H2 database (but same IAF version), the field name keeps the same as "RECORDID".

**Reporter**
Bibi

**Category** 
 - Frank Framework

**Expected behavior**
Field name should be the same as column name, in this example is "RECORDID".

**Screenshots**
Local environment:
![afbeelding](https://user-images.githubusercontent.com/60199670/107745722-02951e80-6d15-11eb-90c1-9c12aba859b4.png)
Dev environment:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/60199670/107745965-67507900-6d15-11eb-8ca3-f77d8ea4d7e8.png)

**Environment:**
 - Application server:  WebSphere
 - DBMS:  MSSQL
 - Browser:  Edge
 - IAF Version:  7.5-RC1

**Comment by gvanbrakel** [comment]
These names are set by the JDBC driver, it is hard to change this behaviour.
I think it is best not to rely on the names in this case.

**Comment by jacodg** [comment]
Limited support for generated keys in SQL Server:

https://docs.microsoft.com/en-us/sql/connect/jdbc/using-auto-generated-keys?view=sql-server-ver15
