### ISSUE TITLE
ParallelSenders not working as expected

### ISSUE THREAD

**Issue by gitsharp** [ibissource/iaf#1469]
We have implemented the ParallelSenders in a configuration to allow for Parallel-processing. Noticing a longer than expected processing time and looking into the logs I have noticed that it seems that the sub-adapters are still waiting on each other. 
Figure 1 shows the adapter with a duration of 30702. The startime was 2021-02-12 09:55:20.421

![figure1](https://user-images.githubusercontent.com/5115225/107763282-accd7000-6d2e-11eb-827b-bdd61948761e.jpg)
)

Looking at fig 2 (Green) one can see the first message received time 
and fig 2 (Red) one can see the timestamp when the second message was received. (It is always after the first message was processed. All other messages has a delay in regards to the previous message that was processed
![figure2](https://user-images.githubusercontent.com/5115225/107763831-7e03c980-6d2f-11eb-9969-3bf2f34c7c9e.jpg)

and fig3 shows a snippet of my configuration
![figure3](https://user-images.githubusercontent.com/5115225/107763877-8a882200-6d2f-11eb-9db2-a1ec299bd6f6.jpg)

As stated. I expected that all messages would be received with on nearly the same moment.
in my case there is a 5sec delay.

**Comment by gvanbrakel** [comment]
Reported by Barry
IAF version 7.4

**Comment by nielsm5** [comment]
There's a known 5 second overhead in the creation of a new adapter. This has been fixed in version 7.5
Could you please upgrade the Frank!Framework version and test this again?
