### ISSUE TITLE
Configuration [IAF_WebControl] liquibase validation failed

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#1481]
**Describe the bug**
The framework's changeset validation fails.

[stacktrace.txt](https://github.com/ibissource/iaf/files/5989850/stacktrace.txt)

**Reporter**
Laurens

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - Application server: [e.g. Tomcat/WebSphere/JBOSS/Jetty] Websphere
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql,PostgreSQL] Oracle
 - Browser: [e.g. Chrome, Safari, Edge] Chrome
 - IAF Version: [e.g. 7.5, 7.6] Current: 7.6-20201217.094031 Previous: 7.6-20201216.150803

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
Error message:
1 change sets check sum
IAF_DatabaseChangelog.xml::IAF_Util:1::Niels Meijer was: 7:4a9c70190e4678c16c7d392b8ecff571 but is now: 7:06e389c27d177c1210c24ac6fbf21899
