### ISSUE TITLE
Option to auto-hide environment variables

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1492]
**Reporter**
Ricardo

**Is your feature request related to a problem? Please describe.**
While working on the container images, the only viable way to inject secrets into the container, is via the environment (see #1486). To hide these properties from the GUI, the server would need to set properties.hide, which might override anything set in .properties-files. 

**Describe the solution you'd like**
A property properties.hide.environment to automatically hide all properties that are set via environment variables. The effective properties.hide would then be properties.hide+environment variables if properties.hide.environment=true and just properties.hide if properties.hide.environment!=true.

**Describe alternatives you've considered**
A separate properties.hide.server to be set by the server, and an effective.properties.hide=${properties.hide},${properties.hide.server}

**Additional context**
N/A

**Comment by jacodg** [comment]
We are will solve this in another way, see PR #1874
