### ISSUE TITLE
Increase base lock cleanup frequency

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1501]
**Reporter**
Ricardo

**Is your feature request related to a problem? Please describe.**
When using a lock, the check+cleanup if their retention has expired is only done once per day. This might be unwanted behavior, as it would potentially block jobs for a day even when retention of the job is just the minimum of 1 hour.

Increasing the frequency will also increase the ibisstore cleanup frequency, which might be unwanted, so maybe a separation of those two functions is also required.

**Describe the solution you'd like**
Increased frequency of the ibislock-table cleanup.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nielsm5** [comment]
You could change the `cleanup.database.cron` property to increase the cleanup interval

**Comment by ricardovh** [comment]
> You could change the `cleanup.database.cron` property to increase the cleanup interval

I could, but this would also trigger the cleanup of the ibisstore table as both are part of the same job. When the frequency is increased, the amount of data to cleanup from the ibisstore would also be reduced, so that would compensate for the increased amount of executions.

**Comment by ricardovh** [comment]
No longer required, changes to cleanup make it no longer a problem if cleanup is done at the same time for locker and messagelog
