### ISSUE TITLE
I would like to add web pages to my frank!Config

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#1505]
**Reporter**
Jeroen Jansen van Rosendaal

**Is your feature request related to a problem? Please describe.**
As the Frank!Framework's implementations use more and more webpages for application of functional management purposes.
At this moment you need to add your pages to the a specific folder in the Frank!Config which means you will have to deploy the application to publish new webpages. 
   

**Describe the solution you'd like**
It would be nice to be able to deploy your webpages with your Frank Config, so your webpages can be maintained with the same flexibility.

**Describe alternatives you've considered**
deploying the aplication for every web change

**Additional context**
talked to Niels about possibilities

**Comment by Laurens-makel** [comment]
Possible workaround is to create an adapter, similair to the UploadFiles one, to replace the current deployed web app with a new one.

This what we do for the Navigator project to patch small fixes on TST and test possible frontend fixes without going through the whole CI/CD proces.

**Comment by nielsm5** [comment]
Each configuration could get a `WebContent` folder, and a [dynamic servlet](https://github.com/ibissource/frank-flow/blob/master/src/main/java/org/ibissource/frankflow/FrontendServlet.java) which listens to all traffic going to `/webcontent/<configName>/*`... Difficulty is deciding when to enable/disable such a dynamic endpoint or have it always enabled and returning a 404 if no WebContent is found.

**Comment by Laurens-makel** [comment]
Just wondering, what is the big advantage of doing it like that compared to my work-around?

For the end-user its still the same amount (maybe even more, also reloading the configuration) of 'work'/'steps' to update the web application.

**Comment by nielsm5** [comment]
> Just wondering, what is the big advantage of doing it like that compared to my work-around?
> 
> For the end-user its still the same amount (maybe even more, also reloading the configuration) of 'work'/'steps' to update the web application.

I think it should be part of the application, the user should not have to maintain / use adapters to achieve this.
