### ISSUE TITLE
RestSender is not sending JSON body to endpoint (POST request)

### ISSUE THREAD

**Issue by pswapnil1987** [ibissource/iaf#1516]
**Describe the bug**
I am trying to send JSON body to WSO2-HDN endpoint with POST type using RestSender but the response I am getting is as if I am not sending the JSON body. I tried with 2 methods:
1. Json body is input to senderpipe
2. Json body is set as inputMessageParam
It doesn't work in both the cases.

If I send JSON generated by IBIS via postman to same endpoint, it works fine and I receive a success message.

**Reporter**
Swapnil Prabhavalkar (NN ILS)

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
1. Try to send json body with RestSender with POST type

**Expected behavior**
JSON body should go through and successful response should be obtained

**Screenshots**

**Environment:**
 - Application server: Tomcat/WebSphere
 - DBMS: NA
 - IAF Version: 7.6-20210215.151612

**Additional context**
Can't provide actual code, as it requires certificates, private keys and tokens to be obtained.

**Comment by nielsm5** [comment]
In order to send a raw json body use `postType='RAW'`. The input of the sender will be used as data to send.

**Comment by pswapnil1987** [comment]
Hi Neils, 

Thank you. Setting contentType="application/json" did the trick for me.
