### ISSUE TITLE
BatchFileTransformerPipe documentation

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1560]
**Reporter**
Ricardo

**Is your feature request related to a problem? Please describe.**
When using the BatchFileTransformerPipe, there is no clear documentation in the IbisDoc on how to use its child elements, despite the Java classes having IbisDoc in them, making it difficult to use the pipe without an example to copy from.

**Describe the solution you'd like**
The child elements of the BatchFileTransformerPipe also being part of the IbisDoc.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by jacodg** [comment]
We hope that the new Frank!Doc will give enough information. There's now "Nested children" info available. Information on class level will soon be implemented.
