### ISSUE TITLE
Simple CSV file import

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#1576]
**Reporter**
Jeroen Jansen van Rosendaal

**Is your feature request related to a problem? Please describe.**
unclear spaghetti of file handling pipes

**Describe the solution you'd like**
While reading a csv file I want to be able to simply process and transform the file line by line to XML.

it should have two options for determining the xml element names :
- use first line as a header
- give values for header in listener
```

a,b,c
1,2,3
4,5,6

<a>1</a><b>2</b><c>3</c>
<a>4</a><b>5</b><c>6</c>


```
- should be able to use this in a streaming fashion
- quoted and unquoted values
- decode special characters
- exception handling when data and header are not matching

**Describe alternatives you've considered**
using batch transformer pipe

**Additional context**

**Comment by rvdstel** [comment]
I would like to add support for reading in blocks of multiple lines. 
Processing in blocks is more efficient than processing each record separately, for instance when inserting these records into a database table.
