### ISSUE TITLE
Log messages contain type information in 7.6

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1607]
**Describe the bug**
Since 7.6 the logging of messages has changed, log messages now contain `nl.nn.adapterframework.stream.Message@6f54f70c: java.lang.String:` before the actual message is displayed. This shows both in the DEBUG if the entire message is logged in the .log-file, or when the LogSender is used.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
1. Run an adapter with DEBUG logging to log the messages
2. Use test a pipeline to process a message
3. See the message in the logging
4. It starts with `nl.nn.adapterframework.stream.Message@6f54f70c: java.lang.String:` before the actual message

**Expected behavior**
Not have `nl.nn.adapterframework.stream.Message@6f54f70c: java.lang.String:` before the actual message

**Screenshots**
N/A

**Environment:**
 - Application server: [e.g. Tomcat/WebSphere/JBOSS/Jetty]: Tomcat
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql,PostgreSQL]: N/A
 - Browser: [e.g. Chrome, Safari, Edge]: N/A
 - IAF Version: [e.g. 7.5, 7.6]: 7.6-RC1

**Additional context**
N/A

**Comment by jacodg** [comment]
Can you specify the exact problem that results from this change?

**Comment by ricardovh** [comment]
I'm not sure if it will result in actual problems, depends on what is done with the logfiles by the user. For human users it will not matter, but if the logfiles are used in for example Splunk this might require a change in the processing to ensure the correct parts to be extracted.

If not considered a bug, it might be worth at least mentioning the change in the release notes.

**Comment by nielsm5** [comment]
Fixed in #1806
