### ISSUE TITLE
openapi spec misses the header info 

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#1608]
**Describe the bug**
within an applictaieon we use a http header x-messageId for duplicate check purposes

the x-messageid header is not represented in the generated openapi spec

**Reporter**
Jeroen Jansen van Rosendaal

**To Reproduce**
Create an api endpoint with _messageIdHeader="x-messageid"_ on the listener, this should result in mentining the x-messageheader in the openapi spec

```
<Adapter name="TestAPI(Post)" description="testAPI">
        <Receiver name="TestAPI" checkForDuplicates="true" transactionAttribute="Required">
            <ApiListener name="TestAPI_listener" uriPattern="my/tests" method="POST" consumes="JSON" produces="JSON" messageIdHeader="x-messageid"/>
            <JdbcMessageLog name="dpchk" jmsRealm="jdbc" slotId="${instance.name}/dpchk/tests"/>
        </Receiver>
```
[hcf_complianceFacts_POST_openapi.json.txt](https://github.com/ibissource/iaf/files/6188312/hcf_complianceFacts_POST_openapi.json.txt)

**Expected behavior**

      parameters:
        - in: header
          name: x-messageid
          schema:
            type: string
            format: uuid
          required: true

**Screenshots**

**Comment by jjansenvr** [comment]
We might need a place to define our header and cookie params for openapi generation purposes

**Comment by alisihab** [comment]
> We might need a place to define our header and cookie params for openapi generation purposes

Apilistener has two new properties headerParams and cookieParams. These params are expected to be comma separated list.
