### ISSUE TITLE
Test a pipeline reports Server Error while Ladybug doesn't show exception

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#1611]
**Describe the bug**

When using test a pipeline with the following pipeline and giving an input message that isn't an existing file name the test a pipeline will report a Server Error and not show the output of the pipeline. But when viewing the report in Ladybug it doesn't show red crosses and sender and pipeline give the string "Could not capture message: (java.io.IOException) Cannot open file [Dummy.txtx]" as output.

````
		<Pipeline>
			<SenderPipe
				name="FileSenderPipe"
				>
				<LocalFileSystemSender
					action="read"
				/>
			</SenderPipe>
			<EchoPipe
				name="EchoPipe"
			/>
			<Exit path="EXIT" state="success"/>
		</Pipeline>
````

**Reporter**
Jaco de Groot

**Category** 
 - Frank Console
 - Frank Framework

**To Reproduce**
1. Create an adapter with a pipeline like above
2. Start your Frank
3. Do test a pipeline like described above

**Expected behavior**
Test a pipeline and Ladybug should have the same output / result.

**Screenshots**
\-

**Environment:**
 - Tomcat
 - Firefox
 - FF! 7.7-20210322.171617: Frank2Example1

**Additional context**
\-

**Comment by gvanbrakel** [comment]
Exception occurs in PipeLineResult.getResult().asString(). At that time, the PipeLine has already 'finished', with an InputStream as result. 
I adjusted testAPipeLine, now a better error message is presented.
An approach to be able to see this message in Ladybug, would be to extend MessageCapturer.toWriter() and MessageCapturer.toOutputStream() with a parameter Consumer<Throwable>, to get notified of an exception that has occurred
