### ISSUE TITLE
Stubbing with message and forward

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1614]
**Reporter**
Ricardo

**Is your feature request related to a problem? Please describe.**
As part of #1580 we discussed a more generic stubbing mechanism for pipes like that, requiring the possibility to set both message and forward to use.

**Describe the solution you'd like**
A way to set both message and forward from Larva tests. Ideally this would not require a modified message containing both message and forward.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jjansenvr** [comment]
property per pipe to set the forward in your test case (f.e. adapter.{pipeName}.pipeForward={forwardname} )
pipe replacement internally  xmlSwitch forwards to {forwardname}


low prio
