### ISSUE TITLE
CVS parser pipe needs an option to remove double quotes around strings

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#1618]
**Reporter**
Jeroen Jansen van Rosendaal

**Is your feature request related to a problem? Please describe.**
CVS ParserPipe could use an option to remove double quotes around input strings
  
**Describe the solution you'd like**
Add an option to remove the quotes from quoted values

```
a; b; c
123,"abc",999
```

**now**
```
<a>123</a><b>"abc"</b><c>999<c/>
```

**setting remove quotes around quoted values i would like to this answer**
```
<a>123</a><b>abc</b><c>999<c/>
```

**Describe alternatives you've considered**

**Additional context**

**Comment by alisihab** [comment]
not an issue that is the way it works

**Comment by alisihab** [comment]
The issue is created because of a misunderstanding. Csvparserpipe will remove the "" surronding from the value of a cell.("cell" -> cell). In case "" required in the output then the input should be surrounded by triple double quotes e.g. """cell""" which will result in "cell"
