### ISSUE TITLE
Very long load time for frank console in Firefox

### ISSUE THREAD

**Issue by lenardvandermaas** [ibissource/iaf#1624]
**Describe the bug**
When loading the frank console in Firefox, it takes a long time, up to 40 seconds before everything is loaded. This is something that occurs when the ibis has the bare minimum to run.

**Reporter**
Lenard van der Maas

**Category** 
 - Frank Console

**To Reproduce**
1. Install the frank runner
2. Start one of the example franks
3. Open Firefox
4. Go to http://localhost/iaf/gui/#!/status

**Expected behavior**
The frank console will load in a normal amount of time, like 10 seconds maximum.

**Screenshots**

**Environment:**
 - Application server: Tomcat
 - DBMS: H2
 - Browser: Firefox
 - IAF Version: any

**Additional context**
Further testing revealed that the framework version has nothing to do with this, but it's rather the firefox version that effect this. Up to version 60.0.1 the console loads properly, the next version I found available was 73.0.1, in that version the problem is present.
The network tab in Firefox shows that there are gaps between requests, causing the issue. I don't know what causes the gaps and I don't know which request specifically the gaps appear between, it seemed random.

**Comment by nielsm5** [comment]
I can't reproduce this with an ibis with 300 adapters. Which configurations are you using?

**Comment by nielsm5** [comment]
Appears that the Pace ain't completing, todo:
- Upgrade Pace
- Add timeout to broadcase `initializeFrankConsole` after 5 ish seconds when pace is > 75%
