### ISSUE TITLE
CsvIteratorPipe

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1633]
**Reporter**
Ricardo

**Is your feature request related to a problem? Please describe.**
In 7.6 a CsvParserPipe has been added. I think in most cases, users want to iterate over the records in the csv. This is now possible, but requires 2-3 pipes (LocalFileSystemPipe to read the file, CsvParserPipe to parse it, ForEachChildElementPipe to iterate). Also all nice things like automatic moving after processing now needs to be done manually, while the FileLineIteratorPipe handles that all for the developer.

**Describe the solution you'd like**
A CsvIteratorPipe that iterates over the csv-records. It should have the same options as the CsvParserPipe.

If possible, both inputting the csv directly as message/stream or a filename to the csv-file should also be supported.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by gvanbrakel** [comment]
You could use a DirectoryListener in your receiver, that would to the automatic moving.
Next you can just use the CsvParserPipe just before the ForEachChildElementPipe. That is not that much of a haslle, is it?

**Comment by ricardovh** [comment]
A DirectoryListenter would give me the automatic moving but only gives me the filename (according to the doc), which would still require me to read the file with a LocalFileSystemPipe. 

There are also be cases where I cannot use the DirectoryListener, such as scheduled jobs and MFT, but still want to be able to directly iterate over the csv without additional pipes. 

It also seems strange to me to have several iterating pipes for files (BatchFileTransformerPipe, FileLineIteratorPipe), but not one for a file format for which I think it is very likely to iterate over. 

Using the FileLineIteratorPipe and have the CsvParserPipe as first pipe in the sub-adapter is a bit of a hassle if the csv contains a header, as that information cannot be used anymore, so the header needs to be set manually and itemNoSessionKey needs to be passed around to skip the first line.

**Comment by jjansenvr** [comment]
do we want to create a CSV manager for the batchtransformerpipe or do we want the developers to use separate building blocks

**Comment by jacodg** [comment]
First use the CsvParserPipe  and then the ForEachChildElementPipe
