### ISSUE TITLE
IbisDoc uri

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1638]
**Reporter**
Ricardo

**Is your feature request related to a problem? Please describe.**
When browsing the IbisDoc at https://ibis4example.ibissource.org/iaf/ibisdoc/, I always stay on https://ibis4example.ibissource.org/iaf/ibisdoc/, no matter which object I view. When sharing documentation, people have to browse to the correct item themselves.

**Describe the solution you'd like**
Include the type and object in the uri when browsing, so that users can directly share the documentation for the correct object. For example, it could be something like:
https://ibis4example.ibissource.org/iaf/ibisdoc/ <- Shows current start with nothing selected
https://ibis4example.ibissource.org/iaf/ibisdoc/{Type} <- Also shows the list for that type
https://ibis4example.ibissource.org/iaf/ibisdoc/{Type}/{Object} <- Shows the object

Maybe searches should also be included in the URL.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jacodg** [comment]
Solved in new Frank!Doc (to be released soon)
