### ISSUE TITLE
FxfXmlInputValidator cannot validate if filename exists in input.

### ISSUE THREAD

**Issue by Moulib1978** [ibissource/iaf#1639]
**Describe the bug**
If <ClientFilename> and <ServerFilename> are empty then FxfXmlInputValidator should throw an exception as no file is there in input.
**Reporter**
Mouli Banerjee

IAF Version: 7.6-RC2-20210329.124839

**Comment by gvanbrakel** [comment]
Problem experienced is with FxfXmlValidator in receive mode. The received input contains all elements that are required by the WSDL, but some of the elements are empty. This does not make the message invalid according to the XSD

**Comment by Moulib1978** [comment]
So is there any other mode where  FxfXmlValidator can check filename are filled or not? Or is it not possible to make ClientFileName/ServerFileName mandatory field?
