### ISSUE TITLE
ibisdoc.xsd restrictions

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1663]
**Describe the issue**
All attributes in the ibisdoc.xsd are of type string, but some have additional restrictions (integer/boolean, enumerations) and elements that should have (at least) one child element to make sense (such as SenderPipes  that should have a Sender) do not set the minOccurs of that child element to 1. To help developers that use auto-complete or validation based on the .xsd, these additonal restrictions should also be included.

Maybe also the default values for attributes should be specified in the .xsd. The default is included in the documentation annotation in the .xsd, but it is not coded into the attribute.
 
**Reporter**
Ricardo

**To Reproduce**
N/A

**Screenshots**
N/A

**Configuration**
```
N/A
```

**Input**
```
N/A
```

**Environment**
```
N/A
```

**Additional Environment**
 - DBMS:  N/A
 - Browser: N/A

**Additional Context**
N/A

**Comment by nielsm5** [comment]
Already implemented in the new version of the Frank!Doc
