### ISSUE TITLE
7.6 breaking changes not in release notes

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1667]
**Describe the issue**
The list of (potentially) breaking changes for 7.6 is not complete. I have a project that uses both a custom web.xml (for custom roles) and a custom log4j4ibis.xml (for custom log configuration), but both files need changes after upgrading to 7.6 that are not mentioned in the release notes.

The web.xml needs to be updated because RestEasy has been replaced with CXF-RS, the custom log4j4ibis needs to be updated because of the change from log4j to log4j2.

I think it would be good to mention those changes in the release notes, as I've spend several hours with several people to figure out an issue that resulted from not updating the web.xml when upgrading from 7.5 to 7.6.

I also think it would be good to allow easier customization for those files, as additional roles and logging configurations are quite common.

**Reporter**
Ricardo

**To Reproduce**
N/A

**Screenshots**
N/A

**Configuration**
N/A

**Input**
N/A

**Environment**
N/A

**Additional Environment**
 - DBMS: N/A
 - Browser: N/A

**Additional Context**
N/A

**Comment by nielsm5** [comment]
If you override a piece of code, whether it's a properties file or a java file, it will almost never be 100% backwards compatible. Unfortunately we cannot comment on every file we 'touch' in between releases. If you don't use custom code and something breaks, it's considered non-backwards compatible, and added to the release notes. If you use custom code, it's almost certain something is going to break.

**Comment by ricardovh** [comment]
But those files needed changes in major ways (log4j replaced by log4j2, RestEasy replaced by CXF-RS), which I would expect to be mentioned in some way. Maybe not in the release notes as file X or Y has broken, but even the replacements are not mentioned.

I know we don't want to promote using custom code too much, but I think we should inform people about major changes that might break with common custom code changes.

**Comment by nielsm5** [comment]
When you use custom code (not just java files!) you change the behaviour of the framework in a way we cannot anticipate. You can make changes to properties and attributes, those are configurable. In order words, we allow the end-user to make these changes.

If you change functionally that alters the way the framework operates, it is difficult for us to analyse potential problems. We cannot guarantee the correct working of a product that looks like the Frank!Framework, but works differently. 

Therefore we encourage people to create an issue, and not use custom code, how simple or small the change may be. If you do decide to change something, you are responsible for your change also after an upgrade. For instance, if you want a custom log configuration, you have to make sure that after an upgrade the file is consistent with the framework version you are using.
