### ISSUE TITLE
Issue with UnzipPipe 7.6-RC1

### ISSUE THREAD

**Issue by laura-dimitra** [ibissource/iaf#1674]
**Describe the issue**
In ibis4publishing was in previous versions the UnzipPipe included as custom code (see attatchment), after upgrading to 7.6-RC1 I deleted the custom code and while checking my Larva tests on my local environment I got an error: "nl.nn.adapterframework.core.PipeRunException: cannot unzip: (IOException) Stream closed" (see screenshot and ladybugreport as well).

**Reporter**
Laura Nauta-Timp

If you have any questions, please contact me.
[Pipeline HandleDiPoDLFile_ZippedXMLFile.zip](https://github.com/ibissource/iaf/files/6270665/Pipeline.HandleDiPoDLFile_ZippedXMLFile.zip)
![Error in UnzipPipe](https://user-images.githubusercontent.com/30295058/113848355-abea1500-9798-11eb-968e-7d5cbd2c6e23.PNG)

[UnzipPipe.java - previous used custom code.txt](https://github.com/ibissource/iaf/files/6270681/UnzipPipe.java.-.previous.used.custom.code.txt)

**Comment by gvanbrakel** [comment]
Configuration uses collectResults=true, use of zis ont line 209 misses call to dontClose() like on line241
