### ISSUE TITLE
Inconsistent attribute "filename" across different pipes

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#1685]
**Describe the issue**
Whilst replacing the deprecated FilePipe I had to replace it with a FixedResultPipe and ran into the fact that the attribute "fileName" has different casing as the LocalFileSystemPipe's attribute "filename".

FixedResultPipe:
![image](https://user-images.githubusercontent.com/37303445/114042686-f0071380-9885-11eb-9f78-5b21b01cf8ff.png)

LocalFileSystemPipe:
![image](https://user-images.githubusercontent.com/37303445/114042798-07460100-9886-11eb-9538-160fefc9cc65.png)

**Reporter**
Laurens Mäkel

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql,PostgreSQL] Not relevant
 - Browser: [e.g. Chrome, Safari, Edge, Firefox] Not relevant

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
All occurrences of ``fileName`` should be changed into ``filename``, with a warning when the attribute ``fileName`` is used.

**Comment by Laurens-makel** [comment]
![image](https://user-images.githubusercontent.com/37303445/115205571-fef98b80-a0f9-11eb-97ee-a3218bbe7824.png)

As you can read in the warnings, it mentions the following: 
`attribute 'setFileNameSessionKey' is replaced with 'setFilenameSessionKey'`

These are the names of the methods in Java, not the names of the attributes a Frank developer should use.

**Comment by Laurens-makel** [comment]
@alisihab @gvanbrakel 
I think this issue has not been resolved, see my previous comment and the following:

All occurences in only the core module have been replaced.

There are still occurences with "fileName' in Aspose module.. for example:
line 61 @ https://github.com/ibissource/iaf/blob/master/aspose/src/main/java/nl/nn/adapterframework/extensions/aspose/pipe/PdfPipe.java
