### ISSUE TITLE
FxFWrapper unwrap generates wrong filename

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1751]
**Describe the issue**
When using the FxFWrapper to unwrap messages, the outputted filename is based on the ClientFilename element, but there are multiple problems with this:
- It contains the filename as known on the source system, which might not match the filename as delivered in the ServerFilename
- The path can contain \ as path separator, which results in the complete contents of ClientFilename being used as filename instead of only the part after the last /

**Reporter**
Ricardo

**To Reproduce**
1. Create an adapter with an FxfWrapper with direction unwrap
2. Put in the example message listed below
3. Output is '/opt/data/WAS/wasap01/fxf-work/NNX00000/in/E:\Source\FilenameXYZ' instead of expected '/opt/data/WAS/wasap01/fxf-work/NNX00000/in/Filename'

**Screenshots**
N/A

**Configuration**
```
<inputWrapper className="nl.nn.adapterframework.extensions.fxf.FxfWrapperPipe" direction="unwrap" storeResultInSessionKey="inputAdress"/>
```

**Input**
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
<SOAP-ENV:Body>
<ns0:OnCompletedTransferNotify_Action xmlns:ns0="http://nn.nl/XSD/Infrastructure/Transfer/FileTransfer/1/OnCompletedTransferNotify/1">
<ns0:TransferFlowId>NNT00000</ns0:TransferFlowId>
<ns0:UserData>NNT00000-ibis4x</ns0:UserData>
<ns0:ClientFilename>E:\Source\FilenameXYZ</ns0:ClientFilename>
<ns0:ServerFilename>/opt/data/FXF/IBIS4X/NNX00000/in/Filename</ns0:ServerFilename>
<ns0:LocalTransactionID>I000000000</ns0:LocalTransactionID>
</ns0:OnCompletedTransferNotify_Action>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

**Environment**
```
FF! 7.6-20201123.110830: 
Running on  using IBM WebSphere Application Server/9.0.5.3
Java Version: Java(TM) SE Runtime Environment (8.0.6.6 - pxa6480sr6fp6ifix-20200317_01(SR6 FP6+IJ22800+IJ23014+IJ23018))
Heap size: 754M, total JVM memory: 2048M
Free disk space: 2GB, total disk space: 2GB
Up since: 2021-04-23 12:09:36 (6d)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]: Oracle
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]: Chrome

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
Sounds like MFT is not configured correctly. Not something we should work around

**Comment by ricardovh** [comment]
As discussed.

**Comment by ricardovh** [comment]
Discussed with Jeroen, preferred solution would be to have an attribute on the wrapper to determine which filename to use.

**Comment by jacodg** [comment]
Make insensitive to forward and backward slashes for determining filename
Add attribute to switch to alternative filename
