### ISSUE TITLE
Open API spec generator adds secondary success response to 500 internal server error 

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#1756]
**Describe the issue**
My adapter could give two success responses, its either "Hey Im still busy, check back later" or "Hey I am done, here you go".

I have configured my Json2XmlInputValidator with the responseRoot attribute with references to the root of both success responses in my XSD file.

This does not work... when configured like this, the response definition for 200 OK stays empty.
![image](https://user-images.githubusercontent.com/37303445/116699778-4ae3e480-a9c6-11eb-99c7-264b662d9768.png)

When responseRoot attribute is added to according exit that is taken by the pipeline, it adds 'SuccessResponse' to 200 and 'BusyResponse' to 202 but also to 500!
![image](https://user-images.githubusercontent.com/37303445/116700019-94ccca80-a9c6-11eb-854f-37a368991228.png)

![image](https://user-images.githubusercontent.com/37303445/116699540-f93b5a00-a9c5-11eb-954a-38a4d73cd0e0.png)

This caused by the following:
![image](https://user-images.githubusercontent.com/37303445/116700105-b1690280-a9c6-11eb-9077-99bf53034c96.png)

I can fix the Open API spec by removing 'BusyResponse' from the 'responseRoot' attribute from my InputValidator, but that will break the functionality of my pipeline..

**Reporter**
Laurens

**To Reproduce**
Message me for the config

**Screenshots**

**Configuration**
```
            <exits>
                <exit path="READY" state="success" code="200" responseRoot="SuccessResponse" />
                <exit path="BUSY"  state="success" code="202" responseRoot="BusyResponse" />
                <exit path="NotModified" state="success" code="304" empty="true" />
                <exit path="BadRequest" state="error" code="400" empty="true" />
                <exit path="NotAuthorized" state="error" code="401" empty="true" />
                <exit path="NotAllowed" state="error" code="403" empty="true" />
                <exit path="ServerError" state="error" code="500" />
            </exits>

            <Json2XmlInputValidator
                warn="false"
                schema="Document_GET/xsd/input.xsd"
                root="GUID"
                storeResultInSessionKey="OriginalXML" 
                responseRoot="SuccessResponse,BusyResponse"
            >
                <param name="GUID" sessionKey="GUID"/>	

                <forward name="success" path="Select_Document" />
                <forward name="failure" path="ServerError"/>
            </Json2XmlInputValidator>
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7-20210416.101648: Ibis4Navigator
Running on MACHINE using Apache Tomcat/9.0.39
Java Version: OpenJDK Runtime Environment (1.8.0_252-b09)
Heap size: 531M, total JVM memory: 942M
Free disk space: 84GB, total disk space: 237GB
Up since: 2021-04-30 14:47:54 (28m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL] SQL Server + H2
 - Browser: [e.g. Chrome, Safari, Edge, Firefox] Any

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by alisihab** [comment]
There are two possible root elements specified in the responseRoot attribute. Both are for successful responses. 
Setting responseRoot attribute means validating the output root element with the specified element names. For the exit states, 200 and 202 the validation will hold. However, the validation will fail for the exit state 500 if the output does not have one of followings as root element SuccessResponse, BusyResponse. For the completeness it is required to have one more responseRoot(e.g ErrorResponse) for the error exit states.

**Comment by jacodg** [comment]
With empty="true" on the 500 exit the validator will be ignored and the Open api schema will be correct. If you want to validate you   can add an extra schema
