### ISSUE TITLE
In Ladybug the current pipe throws an exception that belongs to the pipe after current pipe

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#1763]
**Describe the issue**
My Fixed Query Sender throws an XpathException for XSL file Magdat.xsl but this XSL file is not used in the pipe throwing the exception. The XSL file is used by the pipe coming after current pipe.

It is very unclear what exactly is going wrong and makes it impossible to debug this exception with Ladybug.

![image](https://user-images.githubusercontent.com/37303445/116860247-91715300-ac01-11eb-8d17-765ea3b4c959.png)
![image](https://user-images.githubusercontent.com/37303445/116860279-9c2be800-ac01-11eb-9810-dc91c50e1d48.png)

Stacktrace debug logging 
[ladybug-stacktrace-debug.txt](https://github.com/ibissource/iaf/files/6413975/ladybug-stacktrace-debug.txt)

The exception does not occur at all when 'streaming.auto=false' is used!?

In the exception it references to line 78 in the XSL file that throws an error, at this line the securityClasses parameter is being used. This parameter contains the result of the fixed query sender which is currently throwing the exception. With streaming.auto=false this does not occur.
![image](https://user-images.githubusercontent.com/37303445/116862559-3c374080-ac05-11eb-9a82-e64a8d2aca17.png)

**Reporter**
Laurens

**To Reproduce**
Contact me please.

**Screenshots**

**Configuration**
```

			<pipe name="SelectSecurityClasses" className="nl.nn.adapterframework.pipes.SenderPipe" preserveInput="true" storeResultInSessionKey="securityClasses">
				<sender
					className="nl.nn.adapterframework.jdbc.FixedQuerySender"
					jmsRealm="jdbc"
					queryType="select"
					query="SELECT SECURITY_CLASS_VALUE, ADDITIONAL_ROLE_NAME FROM SCHEMA_SECURITY_CLASS_ROLES
					INNER JOIN SECURITY_CLASSES ON SCHEMA_SECURITY_CLASS_ROLES.SECURITY_CLASS_ID = SECURITY_CLASSES.SECURITY_CLASS_ID
					INNER JOIN ADDITIONAL_ROLES ON SCHEMA_SECURITY_CLASS_ROLES.ADDITIONAL_ROLE_ID = ADDITIONAL_ROLES.ADDITIONAL_ROLE_ID
					WHERE SCHEMA_ID = (SELECT SCHEMA_ID FROM SCHEMAS WHERE SCHEMA_NAME = ?)"
				>
					<param name="SCHEMA_NAME" sessionKey="schemaName" />
				</sender>

				<forward name="success" path="Magdat" />
			</pipe>
				
			<pipe name="Magdat" className="nl.nn.adapterframework.pipes.XsltPipe"
				styleSheetName="MagdatMetaDataSchema/xsl/Magdat.xsl"
			>
				<param name="schemaName" sessionKey="schemaName" />
				<param name="archiveId" sessionKey="archiveId" />
				<param name="otap" value="${otap.stage}" />
				<param name="DLID" value="${dl.repository}"/>
				<param name="NNID" value="${nn.repository}"/>
				<param name="securityClasses" sessionKey="securityClasses" type="domdoc" />
				
				<forward name="success" path="EXIT" />
			</pipe>
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7-20210416.101648: Ibis4Navigator
Running on LPZWNL000022035 using Apache Tomcat/9.0.39
Java Version: OpenJDK Runtime Environment (1.8.0_252-b09)
Heap size: 406M, total JVM memory: 662M
Free disk space: 81GB, total disk space: 237GB
Up since: 2021-05-03 11:20:57 (2m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL] sql server h2
 - Browser: [e.g. Chrome, Safari, Edge, Firefox] chrome

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
Could you test again with the latest 7.7-SNAPSHOT version? PR #1770 probably fixes the problem.

**Comment by Laurens-makel** [comment]
Issue still occurs in latest version

![image](https://user-images.githubusercontent.com/37303445/118513403-f796c380-b733-11eb-9b63-97e2667b8077.png)

**Comment by Laurens-makel** [comment]
Why is this closed?

Issue still occurs.

**Comment by nielsm5** [comment]
The linked PR has been merged, which auto-closes the corresponding issue.

**Comment by Laurens-makel** [comment]
Tested with FF! 7.7-20210518.141042, still occurs.
