### ISSUE TITLE
Stub4testtool adapter receiver-stub copies active attribute

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1765]
**Describe the issue**
When stubbing an adapter on which all receivers have an active attribute that is not locally set, the resulting adapter has no stub-receiver. In 7.5 this was not a problem as the stub created a new receiver, while in >7.6 (https://github.com/ibissource/iaf/commit/edd3ab8488dbd2ea151d9be235142b45bcf7936a) it takes those attributes from the first receiver. Because of this, the active attribute is copied, resulting in no receiver being created.

**Reporter**
Ricardo/Laura

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
Can you try to fix this yourself?
