### ISSUE TITLE
Ladybug: "One or more reports are in progress for more than 5 minuts"

### ISSUE THREAD

**Issue by laura-dimitra** [ibissource/iaf#1766]
**Describe the issue**
Some Ladybugreports are for more than half an hour in progress (and the Larva test is already finished a long time ago)

**Reporter**
Laura Nauta-Timp

**To Reproduce**
I think the screenshots and the ladybugreport are clear enough, but if you need more info please contact me and I'll show you.
(Or run ibis4pub scenario '\getdoc\12_ProcessDocumentRR\scenario01 for a clear example)

**Screenshots**
In the two screenshots you see the error message, the current time (half an hour later). I'll add the ladybugreport in which is in progress as well.
[Pipeline ProcessDocumentRR (2).zip](https://github.com/ibissource/iaf/files/6414465/Pipeline.ProcessDocumentRR.2.zip)
![Ladybug](https://user-images.githubusercontent.com/30295058/116869482-1ca61500-ac11-11eb-8ef5-912fdd939351.PNG)
![Ladybug 2](https://user-images.githubusercontent.com/30295058/116869485-1d3eab80-ac11-11eb-99cf-76b7171e9f39.PNG)

**Environment**
LOC

**Comment by laura-dimitra** [comment]
FF version: FF! 7.7-20210429.144344

**Comment by laura-dimitra** [comment]
En wellicht ook netjes om "5 minuts" aan te passen naar "5 minutes"

**Comment by jacodg** [comment]
Hi Laura, can you retest with a little newer version of the Framework? PR https://github.com/ibissource/iaf/pull/1742 might solve your issue. It was merged by Niels 11 days ago.

I fixed the "5 minuts" typo in Ladybug project last week but I still need to create a PR in FF to upgrade Ladybug to a version with this fix.
