### ISSUE TITLE
Every pipe gives "has forward [success] which is already registered" warning

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1778]
**Describe the issue**
Every pipe gives "has forward [success] which is already registered" warning, which seems incorrect as there is just one "success"-forward on each pipe and no global forwards have been defined.

**Reporter**
Ricardo

**To Reproduce**
1. Go to https://ibis4example.ibissource.org/iaf/gui/#!/status
4. See a lot of warnings

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7-SNAPSHOT: Ibis4Example
Running on vlapp05.interpar.nl using Apache Tomcat/7.0.90
Java Version: OpenJDK Runtime Environment (1.8.0_242-b08)
Heap size: 447M, total JVM memory: 992M
Free disk space: 2GB, total disk space: 17GB
Up since: 2021-05-04 15:52:40 (17h)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Already fixed
