### ISSUE TITLE
Larva FileSender breaks zip files

### ISSUE THREAD

**Issue by woutervdschoot** [ibissource/iaf#1782]
**Describe the issue**
For a larva test I use the FileSender to copy an existing zip file to another location where the unzip pipe can open it, however during this process the zip gets corrupted resulting in an exception from the unzip pipe. If I place the zip manually in the desired folder and skip the FileSender step, the unzip pipe has no problems

**Reporter**
Wouter van der Schoot

**To Reproduce**

**Screenshots**

**Configuration**
Please provide the configuration of the Pipe or Receiver with the problem.
[outbound.zip](https://github.com/ibissource/iaf/files/6433655/outbound.zip)

**Input**
[input1.zip](https://github.com/ibissource/iaf/files/6433607/input1.zip)

Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
[Pipeline FXF3Dispatcher.zip](https://github.com/ibissource/iaf/files/6433622/Pipeline.FXF3Dispatcher.zip)

FileSender setup:

common.properties:

GCSzip1.create.className=nl.nn.adapterframework.testtool.FileSender
GCSzip1.create.filename=D:/Temp/ibis4psdocuments/NNX0123456/in/input1.zip
GCSzip1.create.overwrite=true
GCSzip1.create.checkDelete=false

Step In scenario:

step3.GCSzip1.create.write 							= ../in/input1.zip

**Environment**
FF! 7.6-RC1: ibis4psdocuments
Running on LPZWNL000014416 using Apache Tomcat/9.0.39
Java Version: OpenJDK Runtime Environment (1.8.0_252-b09)
Heap size: 207M, total JVM memory: 492M
Free disk space: 82GB, total disk space: 237GB
Up since: 2021-05-07 08:43:34 (1m)

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)
[testtool.zip](https://github.com/ibissource/iaf/files/6433681/testtool.zip)

**Comment by gvanbrakel** [comment]
Wouter, could you fill the section 'Environment' as instructed?

**Comment by alisihab** [comment]
@woutervdschoot Could you try setting scenario.resolveProperties=false in your scenario as a workaround?

**Comment by jacodg** [comment]
I received the following example from Wouter:

[FileSenderBreaksZip_Example.zip](https://github.com/ibissource/iaf/files/7179536/FileSenderBreaksZip_Example.zip)

This scenario can be placed in frank-runner\examples\Frank2Example1\tests\Example1. After running this scenario the zip has been copied to  ${log.dir}/frankrunner/example/dummy.zip. The copied file cannot be opened

**Comment by jacodg** [comment]
The "problem" is that the default encoding used by the FileSender to write a "message" (in this case the bytes of the zip) in UTF-8 while Larva reads a message (in this case a zip) by default with encoding ISO-8859-1 (unless the file extension is .xml, .wsdl or .utf8, see https://github.com/ibissource/iaf/blob/master/larva/src/main/java/nl/nn/adapterframework/testtool/TestTool.java#L2968). You can fix the scenario by adding:

file.create.encoding=ISO-8859-1

At this moment I don't see an easy change we can do to set the encoding of the FileSender automatically to the right value for your usecase without breaking backwards compatibility or specifying a list of filename extensions that should use a different encoding than UTF-8 (would be impossible to create a complete list).
