### ISSUE TITLE
Json2XmlInputValidator fails when there are two responseRoot's.

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#1785]
**Describe the issue**
The Json2XmlInputValidator has two responseroots:  responseRoot="FindDocuments_Response,FindDocuments_Error"
When validating the response output, it seems that always the last responseRoot is expected.

When the input is a normal "FindDocuments_Response", we get an XML failure:
Validation using Json2XmlValidator with 'FindDocuments_GET_4/xsd/Archiving_Document_4_FindDocuments_1_GET.xsd' failed:
/FindDocuments_Response: Illegal element 'Paging'. Element(s) 'FindDocuments_Error' expected.
/FindDocuments_Response: Illegal element 'SearchResult'. Element(s) 'FindDocuments_Error' expected.
/FindDocuments_Response: Element(s) 'FindDocuments_Error' not found

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/35798481/117420855-42d3f980-af1e-11eb-88ec-0c47ae7b0285.png)

**Configuration**
[Configuration_FindDocuments_4_GET.zip](https://github.com/ibissource/iaf/files/6440125/Configuration_FindDocuments_4_GET.zip)

**Input**
see Additional Context

**Environment**
FF! 7.7-20210505.130333: Ibis4Titan
Running on LPZWNL000022420 using Apache Tomcat/8.5.34
Java Version: Java(TM) SE Runtime Environment (1.8.0_60-b27)
Heap size: 841M, total JVM memory: 1518M
Free disk space: 7GB, total disk space: 236GB
Up since: 2021-05-07 09:29:54 (47m)

**Additional Environment**
 - DBMS: H2
 - Browser: Chrome

**Additional Context**
ladybug report:
[Pipeline FindDocuments(GET) (1).zip](https://github.com/ibissource/iaf/files/6440113/Pipeline.FindDocuments.GET.1.zip)

**Comment by alisihab** [comment]
XmlValidatorContentHandler startElement method needs to be updated
