### ISSUE TITLE
status codes must be unique for OpenAPISchema

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#1791]
**Describe the issue**
Each pipeline exit can have a status code and responseRoot element, that are used in validation and generation of OpenAPISchema and WSDL. For OpenAPI Schema generation, the status code are expected to be unique. Exits with duplicate codes are ignored in OpenAPI Schema generation. I would expect either:
- both exits /  responseRoots to be present in the schema
- to get ConfigurationWarning

**Reporter**
Gerrit

**To Reproduce**

**Screenshots**

**Configuration**
```
			<exits>
				<exit path="EXIT" state="success" code="200" responseRoot="normalReply" />
				<exit path="SpecialExit" state="success" code="200" responseRoot="specialReply" />
				<exit path="BadRequest" state="error" code="400" responseRoot="InputValidationFailure" />
				<exit path="ServerError" state="error" code="500" />
			</exits>

```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7-SNAPSHOT: Ibis4Test
Running on LPZWNL000040524 using Apache Tomcat/9.0.43
Java Version: OpenJDK Runtime Environment (1.8.0_41-b04)
Heap size: 131M, total JVM memory: 247M
Free disk space: 291GB, total disk space: 476GB
Up since: 2021-05-10 10:16:23 (9m)
```

**Additional Environment**

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
It appears to be logical that status code must be unique over all exits
