### ISSUE TITLE
WSDL generation cannot handle multiple response roots

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#1792]
**Describe the issue**
If multiple elements are specified for a response, either as a comma sperated list in a outputSoapBody attribute of a SoapInputValidator, or as a comma separated list in a soapBody attribute of a SoapOutputValidator, the comma separated list is copied as is in a generated WSDL. I would expect either:
- a combined element type to be generated in the WSDL
- or a warning to be issued

**Reporter**
Gerrit

**To Reproduce**
1. Go to iaf-test -> Webservices -> Available WSDL's -> Soapvalidator
2. Click on WSDL
3. See that the generated WSDL contains: `<wsdl:output message="tns:Message_Item_Response,SpecialResponse,InputValidationFailure,OutputValidationFailure"/>`

**Screenshots**

**Configuration**
```
<inputValidator className="nl.nn.adapterframework.soap.SoapValidator" schemaLocation="urn:items /Validators/xsd/Items.xsd" soapBody="Item_Request" outputSoapBody="Item_Response,SpecialResponse,InputValidationFailure,OutputValidationFailure" allowPlainXml="true"
	rootElementSessionKey="receivedRootElement" rootNamespaceSessionKey="receivedRootNamespace" soapVersion="auto" >
	<forward name="failure" path="InputValidationFailure" />
	<forward name="outputFailure" path="OutputValidationFailure" />
</inputValidator>

```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7-SNAPSHOT: Ibis4Test
Running on LPZWNL000040524 using Apache Tomcat/9.0.43
Java Version: OpenJDK Runtime Environment (1.8.0_41-b04)
Heap size: 139M, total JVM memory: 247M
Free disk space: 291GB, total disk space: 476GB
Up since: 2021-05-10 10:31:22 (19m)
```

**Comment by jacodg** [comment]
For WSDL generation use only the first element from the list of response root field
Document it in the Frank!Doc of the response root
