### ISSUE TITLE
Determine 'external address of ibis' in Wsdl generation

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#1798]
**Describe the issue**
When a WSDL is generated, the adress that is generated is the string 'external address of ibis'. This should contain the real external address of the ibis, or contain at least the right context path.

**Reporter**
Gerrit

**To Reproduce**
1. Go to iaf-test -> Webservices -> Available WSDL's -> Soapvalidator
2. Click on WSDL
3. See that the soap port contains the line: `<soap:address location="external address of ibis"/>`

**Screenshots**

**Configuration**
```
```

**Input**
```
```

**Environment**
```
FF! 7.7-20210505.130333: Ibis4Test
Running on srdzzapp0455 using IBM WebSphere Application Server/9.0.5.7
Java Version: Java(TM) SE Runtime Environment (8.0.6.26 - pxa6480sr6fp26-20210216_01(SR6 FP26))
Heap size: 407M, total JVM memory: 512M
Free disk space: 1GB, total disk space: 2GB
Up since: 2021-05-10 17:46:41 (42m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jjansenvr** [comment]
For the openapi specification we have a similar issue, we want to implement a specific property in the ibis to set the actual endpoint name (load balancer of DNS name.) This would be nice to implement here asswell

**Comment by gvanbrakel** [comment]
[ConfigurationServiceDispatcher.xml.txt](https://github.com/ibissource/iaf/files/6521147/ConfigurationServiceDispatcher.xml.txt)
[encapsulateResult.xslt.txt](https://github.com/ibissource/iaf/files/6521148/encapsulateResult.xslt.txt)
[encapsulateResult.xslt.txt](https://github.com/ibissource/iaf/files/6521149/encapsulateResult.xslt.txt)
[ConfigurationServiceDispatcher.xml.txt](https://github.com/ibissource/iaf/files/6521150/ConfigurationServiceDispatcher.xml.txt)
