### ISSUE TITLE
Streaming DB - SessionKey of fixed query pipe is filled with result of nested(ladybug) pipe

### ISSUE THREAD

**Issue by BonnoSmeele** [ibissource/iaf#1823]
**Describe the issue**
We recently upgraded to a 7.7 version. One of our fixedquery pipes is no longer saving the results to the sessionkey(storeResultInSessionKey). Instead the result is taken from the next pipe(XSLT pipe in this case).

These pipes appear nested in the ladybug, see atteched screenshot.
![image](https://user-images.githubusercontent.com/73215587/118661775-b8c64380-b7ef-11eb-8e20-00bd41b039c1.png)

Additionally the process is not immediately visible in ladybug, but can only be seen after opening it with "report in progress"

**Reporter**
Bonno Smeele

**To Reproduce**
1. install https://vcs.aws.insim.biz/ibissource/dm/ibis4oma/ibis4oma. run the ibis4oma_oma config
2. run the first markbulkmessage testcase with larva
3. go to the ladybug testtool
4. open the report in progress,  open **BulkMsgFlow_CountBulkMessages** pipe
**Screenshots**

**Configuration**
```
			<SenderPipe 
				name="BulkMsgFlow_CountBulkMessages"
				storeResultInSessionKey="BulkMessageCount"
			>
				<FixedQuerySender 
					name="BulkMsgFlow_CountBulkMessages"
					datasourceName="jdbc/ibis4oma"
					queryType="select"
					query="SELECT COUNT(*) AS BULKMSGCOUNT
							FROM BULK_MESSAGE
							WHERE BATCH_ID=? AND MESSAGE_BATCHSET_ID IS NULL"
				>	
					<Param name="BATCH_ID" 	sessionKey="BATCH_ID" />
				</FixedQuerySender>
				<Forward name="exception" path="create_SetAdapterGenericError" />
				<Forward name="success" path="LogBulkMessageCount" />
				<Documentation>Resets single bulkmessages for given batchId to STATUS_ID=0 and BATCH_ID=NULL when one or more linked splitmessages have status_id=1 or 2.</Documentation>
			</SenderPipe>

			<XsltPipe 
				name="LogBulkMessageCount"
				styleSheetName="MarkBulkMessageReady/xsl/createBulkMsgMessage.xsl"
			>
				<Param name="MessageType" 		value="MessagesInBatch" />
				<Param name="BulkMessageCount" 	sessionKey="BulkMessageCount" xpathExpression="result/rowset/row/field[@name='BULKMSGCOUNT']" type="integer" />
				<Param name="BATCH_ID" 			sessionKey="BATCH_ID" />
				<Param name="SYSTEM_ID" 		sessionKey="SYSTEM_ID" />
				<Param name="PROCESS_ID" 		sessionKey="PROCESS_ID" />
				<Forward name="exception" 	path="create_SetAdapterGenericError" />
				<Forward name="success" path="writeBulkMsgNoMessages" />
			</XsltPipe>


```

**Input**
[Pipeline MarkBulkMessageReady_Processing.zip](https://github.com/ibissource/iaf/files/6501786/Pipeline.MarkBulkMessageReady_Processing.zip)

**Environment**
```
FF! 7.7-20210518.141042: ibis4oma ---
Running on LPZWNL000013838 using Apache Tomcat/9.0.39
Java Version: OpenJDK Runtime Environment (1.8.0_252-b09)
Heap size: 323M, total JVM memory: 597M
Free disk space: 6GB, total disk space: 237GB
Up since: 2021-05-18 15:11:48 (39m)
```

**Additional Environment**
 - DBMS: [ mysql
 - Browser: [NA
 - Ttomcat, frank-runner

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by Laurens-makel** [comment]
Seems related to https://github.com/ibissource/iaf/issues/1763

**Comment by BonnoSmeele** [comment]
It works, thanks!
