### ISSUE TITLE
MultiParameter override in Json2XmlValidator does not work properly

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#1834]
**Describe the issue**
Xml appears to contain json array, like `<elem>[a, b]</elem>` where it should be  `<elem>a</elem><elem>b</elem>`

**Reporter**
Gerrit/Richard van der Stel

**To Reproduce**
1. Go to iaf-test
2. Add '&AttributeId=8' to /test/src/test/testtool/Validators/Items/item-ok-extra-in-get.txt
3. Run scenario '/Validators/Json2XmlValidator/scenario24 - API GET OK extra attribute'
4. See output

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7-SNAPSHOT: Ibis4Test
Running on LPZWNL000040524 using Apache Tomcat/9.0.43
Java Version: OpenJDK Runtime Environment (1.8.0_41-b04)
Heap size: 199M, total JVM memory: 247M
Free disk space: 286GB, total disk space: 476GB
Up since: 2021-05-20 16:03:17 (12m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Comment by rvdstel** [comment]
Attached ladybug report and zip with config and xsd: 
[Pipeline FindDocuments(GET) (2).zip](https://github.com/ibissource/iaf/files/6520723/Pipeline.FindDocuments.GET.2.zip)
[apilistener.zip](https://github.com/ibissource/iaf/files/6520724/apilistener.zip)

Request with two parameters with the same name "agreementNumber" :
http://localhost:8080/ibis4titan/api/archiving/documents?schemaName=NN Pensioenen&requestUserId=postman2&maxItems=10&skipCount=0&sortAttribute=issuedDate&agreementNumber=12346789.1234567890&agreementNumber=33002118

ladybug printscreen with both values of agreementNumber in one sessionkey : 
![image](https://user-images.githubusercontent.com/35798481/119096552-06bb9100-ba14-11eb-9aba-8d7aedd214a3.png)

**Comment by gvanbrakel** [comment]
Problem occurs in 'repeated elements', not in 'arrays'
