### ISSUE TITLE
Startup throws java.lang.IllegalArgumentException: A source must be provided.

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#1838]
**Describe the issue**
When starting the IBIS, I see the following stacktrace in the Tomcat console:

![image](https://user-images.githubusercontent.com/37303445/119146844-56697f00-ba4b-11eb-8171-c55faaaa89a0.png)

When doing a bit of research, this is coming from here:
https://github.com/ibissource/iaf/blob/e5c3eb1999f38223a5e908fcb1a5975270ca2da1/core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationWarnings.java#L24
![image](https://user-images.githubusercontent.com/37303445/119146917-65503180-ba4b-11eb-9c02-d503e7b6521a.png)

The odd thing is, this method is being called with a null value for source in here:
https://github.com/ibissource/iaf/blob/master/core/src/main/java/nl/nn/adapterframework/core/PipeLine.java#L673
![image](https://user-images.githubusercontent.com/37303445/119147126-992b5700-ba4b-11eb-9f50-33091f1c1bb4.png)

This exception causes that not a single configuration/adapter starts locally.

**Reporter**
Laurens

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7-20210521.141846: Ibis4Navigator
Running on LPZWNL000022035 using Apache Tomcat/9.0.39
Java Version: OpenJDK Runtime Environment (1.8.0_252-b09)
Heap size: 486M, total JVM memory: 631M
Free disk space: 86GB, total disk space: 237GB
Up since: 2021-05-21 15:24:40 (21m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Oops...
