### ISSUE TITLE
Stub4Testtool produces configuration warnings

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#1844]
**Describe the issue**
When using stubs, warnings are shown in the console:
`GenericReceiver [FindDocuments_GET] is deprecated: Please do not specify a className attribute for Receiver`
Als ik de loaded config bekijk dan zie ik dat er een testtool- receiver is toegevoegd aan de originele config.
Hierin staat een className op de receiver.

Moeten jullie iets aanpassen in het framework zodat de testtool-* goed ingevoegd wordt?

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Versie: FF! 7.7-20210525.083818
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
``
GenericReceiver [WebControlShowConfigurationStatus] is deprecated: Please do not specify a className attribute for Receiver
GenericReceiver [WebControlShowConfiguration] is deprecated: Please do not specify a className attribute for Receiver
GenericReceiver [WebControlWebservices] is deprecated: Please do not specify a className attribute for Receiver
GenericReceiver [WebControlTestPipeLine] is deprecated: Please do not specify a className attribute for Receiver
GenericReceiver [WebControlShowFlowDiagram] is deprecated: Please do not specify a className attribute for Receiver
GenericReceiver [WebControlShowEnvironmentVariables-post] is deprecated: Please do not specify a className attribute for Receiver
GenericReceiver [ManageDatabase-ws] is deprecated: Please do not specify a className attribute for Receiver
GenericReceiver [testtool-IbisDoc] is deprecated: Please do not specify a className attribute for Receiver
``

**Comment by rvdstel** [comment]
I have upgraded to a newer version FF! 7.7-20210527.152350 and used the latest stub4testtool.xsl.
The problem no longer occurs, so this issue can be closed.

**Comment by alisihab** [comment]
Then let's close
