### ISSUE TITLE
Auto-determine configurations.names

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1854]
**Describe the issue**
When using separate configurations, the value configurations.names needs to be set beforehand to set the list of configurations that will be loaded. Updating this value for a new configuration (or removing an old one) requires a restart of the server (and if not set from the server, also the properties in the .war file). It would be nice to have an option to enable an auto-determine mechanism that updates the list of configurations based on configurations in the database and/or configurations.directory and/or other places configurations can be located and loads these configurations automatically if not loaded yet. I'm not sure what to do with reloads, but as this request mainly makes sense with loading from the database and there is already a reload-mechanism for that, I think reloads are covered with that.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Such a feature already exists;
`configurations.directory.autoLoad=true` make sure you have set `configurations.directory`.
and
`configurations.autoDatabaseClassLoader=true` (which will soon be called `configurations.database.autoLoad=true`)

**Comment by ricardovh** [comment]
As indicated, feature already exists.
