### ISSUE TITLE
Cache filenames get scrambled

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#1862]
**Describe the issue**
The filenames of overflow-to-disk files of caches get strange names, apparently after the upgrade of the cache library recently

**Reporter**
Gerrit

**To Reproduce**
1. Go to iaf-test
2. Run the cache related scenarios
3. Go to the log directory
4. See filenames like: `%004fverflow%0054o%0044isk-sender%0043ache.data` and `%0050ersistent%004fverflow%0054o%0044isk-sender%0043ache.data`

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7-SNAPSHOT: Ibis4Test
Running on LPZWNL000040524 using Apache Tomcat/9.0.43
Java Version: OpenJDK Runtime Environment (1.8.0_41-b04)
Heap size: 175M, total JVM memory: 247M
Free disk space: 284GB, total disk space: 476GB
Up since: 2021-05-28 09:11:37 (8m)
```

**Comment by nielsm5** [comment]
Appears to have been a 'feature' of EhCache, see `net.sf.ehcache.DiskStorePathManager#safeName` for more info.
