### ISSUE TITLE
Stream not closed, no report in Ladyug

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#1865]
**Describe the issue**
It appears that a stream is not closed ("Waiting for stream to be read, captured and closed...") and therefore there is no record shown in Ladybug.

The first pipe LocalFileSystemPipe throws an exception:  java.io.IOException: Cannot open file 
This message is passed to the second pipe CsvParserPipe and the third pipe ForEachChildElementPipe now says "Waiting for stream to be read, captured and closed..."
The exception from the CsvParserPipe is:  nl.nn.adapterframework.core.PipeRunException: Cannot parse CSV:

All the exception handling is correct, but the report in Ladybug can only be opened with the option "Open report in progress number 1"
We would like to see a normal record in Ladybug.

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**

**Configuration**
```
	<adapter name="Streaming Test2">
		<receiver>
			<listener className="nl.nn.adapterframework.receivers.JavaListener"
				serviceName="ibis4test-Streaming2" />
		</receiver>
		<pipeline>
			<exits>
				<exit path="READY" state="success" />
			</exits>
			<pipe name="readFile"
				className="nl.nn.adapterframework.pipes.LocalFileSystemPipe"
				filename="unknownFilename.txt"
				action="read">
			</pipe>
			
			<pipe name="csvToXml"
				className="nl.nn.adapterframework.pipes.CsvParserPipe"
				fieldNames="a,b,c">
			</pipe>
		
			<pipe name="processXml"
				className="nl.nn.adapterframework.pipes.ForEachChildElementPipe">
				<sender
					className="nl.nn.adapterframework.senders.EchoSender"/>
				<forward name="success" />
			</pipe>
		</pipeline>
	</adapter>
```

**Input**
[Pipeline BulkUpdate_Importdata_ReadFile.zip](https://github.com/ibissource/iaf/files/6560754/Pipeline.BulkUpdate_Importdata_ReadFile.zip)

**Environment**
FF! 7.7-20210527.152350: Ibis4Titan
Running on LPZWNL000022420 using Apache Tomcat/8.5.34
Java Version: Java(TM) SE Runtime Environment (1.8.0_60-b27)
Heap size: 785M, total JVM memory: 1443M
Free disk space: 12GB, total disk space: 236GB
Up since: 2021-05-28 13:41:45 (34m)

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
Still occurs in FF! 7.7-20210607.095552

**Comment by rvdstel** [comment]
[Pipeline BulkUpdate_Importdata_ReadFile (1).zip](https://github.com/ibissource/iaf/files/6607782/Pipeline.BulkUpdate_Importdata_ReadFile.1.zip)

Attached a ladybug report.
The test is a normal happy flow, no exception handling.
But the report is not shown in ladybug, only with "report in progress number" I can see the report.

**Comment by jacodg** [comment]
@rvdstel is it possible for you to create a small configuration that I can easily run locally to reproduce the problem?

**Comment by rvdstel** [comment]
[ibis4titan_retention.zip](https://github.com/ibissource/iaf/files/6638455/ibis4titan_retention.zip)

I have stripped all other adapters from this config and I hope what is left will work :) 
the remaining adapter "Configuration_BulkUpdate_Importdata" is the one for which the regression larva shows no result:

Scenario-01 in "test\testtool\retention\BulkUpdate_Importdata"

**Comment by jacodg** [comment]
Thanks! In the mean time I was testing with the configuration in the description of the issue. And it seems that with that configuration F!F calls the method threadCreatepoint on Ladybug once too often (or doesn't "cancel" it). It seems to be called at the endpoint of "Pipe processXml" (just before or just after it, I'm not sure at this moment). Gerrit probably knows what I'm talking about and might know at which point F!F is doing this. I'll discuss with Gerrit.

**Comment by jacodg** [comment]
I created PR #1950 that will prevent reports from staying in progress. It will also visualize threads that didn't start and aren't cancelled:

![image](https://user-images.githubusercontent.com/2970084/123244874-986f6000-d4e4-11eb-85b9-e2b6b4239c24.png)

I think Gerrit should have a look whether he can cancel this thread so it doesn't show up in the report as an error
