### ISSUE TITLE
Job ibisstore

### ISSUE THREAD

**Issue by laura-dimitra** [ibissource/iaf#1869]
**Describe the issue**
(Sorry for writing in Dutch, I first wrote this in an email to Jaco. If you need the English version please contact me)

In het nieuwe Frank!Framework is de cleanupDatabase job iets anders dan tov het oude framwork:

DELETE FROM IBISSTORE WHERE MESSAGEKEY IN (SELECT TOP 25000 MESSAGEKEY FROM IBISSTORE WITH (readpast) WHERE TYPE IN ('L','A') AND EXPIRYDATE < [datumvanvandaag])

In de nieuwe versie wordt een SELECT TOP 25000 gedaan, dit voorkomt een timeout in het geval dat er hondderdduizenden berichten zijn.
(De oude versie gaf ook problemen gezien er een timeout ontstond als er te veel berichten waren.)

Maar: in het geval van ibis4emailhandler komen er dagelijks zo’n 50 a 60 duizend berichten bij in de tabel Ibisstore. Kortom: maar de helft wordt opgeruimd en dit veroorzaakte laatst een incident. Ik ben al met de dba'er bezig om dit op te lossen en om te kijken of er aan de db kant nog een extra handigheidje kan worden ingebouwd.

Hebben jullie hier misschien nog goede ideeën over? Of is het bijv. een mogelijkheid om de scheduler (voor de query SELECT TOP 25000…) te laten loop-en zolang er meer dan 25000 berichten zijn die aan de zoekopdracht voldoen?

**Reporter**
Laura Nauta-Timp

**Comment by gvanbrakel** [comment]
You could run the cleanup job more frequently, by changing the property 'cleanup.database.cron', e.g. to:
`cleanup.database.cron=0 45 * * * ?` 
to run it every hour

**Comment by laura-dimitra** [comment]
Hoi Gerrit, dat zou zeker een mogelijkheid zijn, bedankt. Zelf zou ik de voorkeur hebben dat dit standaard in het framework goed wordt ingeregeld; de gebruiker configureert namelijk de retention in de adapter en dan zou dit voldoende moeten zijn om de opschoning te realiseren omdat het opschonen m.i. framework functionaliteit hoort te zijn.

Bij jouw oplossing is er in mijn geval denk ik nog een probleem; de tabel wordt gelockt zolang de job draait. Er worden dus ook geen berichten meer afgehandeld/mails verstuurd. Bij emailhandler moet een deel van de berichten natuurlijk direct worden opgepakt (denk hierbij bijv. aan een wachtwoordreset waar een gebruiker op wacht). Ik verwacht dat het een probleem zou kunnen zijn als de tabel dus overdag voor meerdere minuten wordt gelockt. Het hangt er natuurlijk wel vanaf hoe lang de job duurt. Ik zou het ook even moeten navragen bij de beheerders.

**Comment by gvanbrakel** [comment]
Je kan de cleanup job natuurlijk ook tussen 01:00 en 07:00 elk kwartier laten draaien, of zo:
`cleanup.database.cron=0 0,15,30,45 1-7 * * ?`
