### ISSUE TITLE
Invalid Console warnings on boolean attributes

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#1872]
**Describe the issue**
The consoles shows warnings that are most probably not correct: 
CsvParserPipe [csvToXml] does not have an attribute [fileContainsHeader] to set to value [true]

There is an attribute fileContainsHeader in the class CsvParserPipe.

And probably more console warnings on other boolean attributes.

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/35798481/120323280-a0712100-c2e5-11eb-804a-979b9acd0b29.png)

**Configuration**

            <pipe name="csvToXml"
                  className="nl.nn.adapterframework.pipes.CsvParserPipe"
                  fileContainsHeader="true"
                  fieldSeparator=";"
            >
                <forward name="exception"   path="fail:selectNumberOfQueryRecords"/>
                <forward name="success"     path="processBlocks"/>
            </pipe>

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
FF! 7.7-20210527.152350: Ibis4Titan
Running on LPZWNL000022420 using Apache Tomcat/8.5.34
Java Version: Java(TM) SE Runtime Environment (1.8.0_60-b27)
Heap size: 1150M, total JVM memory: 1534M
Free disk space: 12GB, total disk space: 236GB
Up since: 2021-06-01 14:08:25 (20m)

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
Configuration [retention] - LocalFileSystemPipe [readFile] does not have an attribute [move2dirAfterError] to set to value [D:/temp/BulkUpdate/error]
 Configuration [retention] - LocalFileSystemPipe [readFile] does not have an attribute [removeDuplicates] to set to value [true]
 Configuration [retention] - LocalFileSystemPipe [readFile] does not have an attribute [escapeXml] to set to value [true]
 Configuration [retention] - LocalFileSystemPipe [readFile] does not have an attribute [messageType] to set to value [contents]
