### ISSUE TITLE
Option in CsvParserPipe to get upper/lower-case xml elements when using fileContainsHeader

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#1876]
**Describe the issue**
When the CsvParserPipe uses the fileContainsHeader option, the headernames are translated to XML elements.
However, when the headerline can contain upper and lowercase headers, the consecutive xslt parsers need to deal with these cases. It would be nice to have an option to get all the xml elements in upper-case, or lower-case, regardless of the case of the headernames. This way, the xslt always gets upper-case (or lowercase) without having to convert the case.

Example:
input: header1, HEADER2, HeAdEr3
 
ouput:
&lt;HEADER1/&gt;
&lt;HEADER2/&gt;
&lt;HEADER3/&gt;

Another new option:
when using fieldNames, to override the names in the headerline, the CsvParserPipe does not skip the headerline. It assumes that when using fieldNames there is no headerline. 
It would be nice to be able to have an option to skip the header line as well when using fieldNames to override the headernames.

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**

**Configuration**

**Input**

**Environment**
FF! 7.7-20210527.152350: Ibis4Titan
Running on LPZWNL000022420 using Apache Tomcat/8.5.34
Java Version: Java(TM) SE Runtime Environment (1.8.0_60-b27)
Heap size: 532M, total JVM memory: 1430M
Free disk space: 12GB, total disk space: 236GB
Up since: 2021-06-02 12:51:54 (43m)

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by alisihab** [comment]
when the first line of the file is used as header, changing the header case does not work
