### ISSUE TITLE
XsltPipe (IOException) Stream closed

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#1880]
**Describe the issue**
I am running an XSLT with a few parameters but it fails with IOException Stream Closed.

[ibis4navigator (2).log](https://github.com/ibissource/iaf/files/6606786/ibis4navigator.2.log)
c

When I look in Ladybug and try to inspect the parameters, one of the parameters shows the following message:
![image](https://user-images.githubusercontent.com/37303445/120976565-be6dd400-c772-11eb-8e59-4139d62c24f3.png)

This sessionKey is created and filled a few pipes earlier:
![image](https://user-images.githubusercontent.com/37303445/120976890-0c82d780-c773-11eb-83eb-e2ecd07b03c0.png)

For some odd reason it still throws a streaming exception:
![image](https://user-images.githubusercontent.com/37303445/120976966-20c6d480-c773-11eb-9dd9-2df79de0b53b.png)

**Reporter**
Laurens 

**To Reproduce**
Please contact me

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7-20210525.083818: Ibis4Navigator
Running on srazzapp0474.insim.biz using IBM WebSphere Application Server/8.5
Java Version: Java(TM) SE Runtime Environment (8.0.6.0 - pxa6480sr6-20191107_01(SR6))
Heap size: 1088M, total JVM memory: 2048M
Free disk space: 9GB, total disk space: 10GB
Up since: 2021-06-04 12:36:54 (2d)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL] 
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
Could you upgrade to the latest version of the framework and retest? This problem might be already solved by PR #1867

**Comment by Laurens-makel** [comment]
Issue also occurs with FF! 7.7-20210604.145654

**Comment by Laurens-makel** [comment]
Turns out that the stream is passed as input to a sub adapter and has been closed by the sub adapter.

Fixed by adding preserveInput=true so stream is not passed to sub adapter and stays open.
