### ISSUE TITLE
JsonPipe evaluates empty element to json empty object

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#1882]
**Describe the issue**
When transforming an XML to a JSON format <a></a> ==> a: {} instead of a: ""

**Reporter**
jjansenvr / Swapil

**To Reproduce**
Implement a JSONPipe provide it with a xml with empty values.
 

**Screenshots**

**Configuration**
```
<pipe name="ConvertJson2Xml"
                  className="nl.nn.adapterframework.pipes.JsonPipe">
	           <forward name="success" path="verifyTitanResponse"/>
</pipe>
```

**Input**
```
<foo>
<bar>value</bar>
<bar1></bar1>
<bar2></bar2>
<bar3></bar3>
</foo>
```

**Environment**
```
IAF 7.6-20200421.151810: ibis4webforms test
```

**Additional Environment**
na

**Additional Context**
Workaround is to implement a Json validator instead, using a schema will give more control over output

The code of the JSONPipe needs to be refactored, it uses the wrong libraries

**Comment by nielsm5** [comment]
Don't forget to remove the `org.json` dependency

**Comment by gvanbrakel** [comment]
Problem can be solved by setting version="2"
