### ISSUE TITLE
ibisdoc.xsd regular expressions are not compliant

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#1885]
**Describe the issue**
Regular expressions used are not according to http://www.regular-expressions.info/xml.html making validation of xsd fail

**Reporter**
JJvR

**To Reproduce**
download https://ibis4example.ibissource.org/iaf/api/frankdoc/files/frankdoc.xsd
validate in parser or xml tool like xmlspy

**Additional Context**
these restriction patterns give errors in xmlspy
```
<xs:simpleType name="frankBoolean">
    <xs:restriction base="xs:string">
      <xs:pattern value="(true|false)|(\$\{[^\}]+\})" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="frankInt">
    <xs:restriction base="xs:string">
      <xs:pattern value="((\+|-)?[0-9]+)|(\$\{[^\}]+\})" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="variableRef">
    <xs:restriction base="xs:string">
      <xs:pattern value="\$\{[^\}]+\}" />
    </xs:restriction>
  </xs:simpleType>
```

**Comment by jjansenvr** [comment]
the part matching the replacement variables "${myvar}" seems to be the problem 
\$\{[^\}]+\}

**Comment by mhdirkse** [comment]
Als ik frankdoc.xsd open in mijn browser en dan zoek op de string "${[^}]+}" (zonder de quotes), dan heb ik geen match. Jeroen, ik zal contact opnemen om uit te zoeken hoe je aan je citaten komt.

**Comment by jjansenvr** [comment]
![image](https://user-images.githubusercontent.com/3921911/121181938-d7ee4900-c862-11eb-8d3d-5940e5cacb56.png)

**Comment by jjansenvr** [comment]
myvar=true
${myvar} ==> true
!${stubbed} ==> false

**Comment by mhdirkse** [comment]
I propose we close this issue. The only part that remains is addressing the !-operator. This is in a dedicated issue, namely #1898.
