### ISSUE TITLE
ForEachChildElementPipe with blocks generates empty block tags

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1890]
**Describe the issue**
When using the ForEachChildElementPipe with a (small) blockSize, the ForEachChildElementPipe keeps iterating to a StackOverflowException (or other Exception that occurs). The iteration does not seem to process to the next element, but keeps iterating over the same element over and over again, and eacht time it adds an <block></block> to the original message. This error does not occur in 7.5.1, but is new in 7.6 and 7.7.

**Reporter**
Ricardo

**To Reproduce**
1. Use below configuration
2. Use Test a pipeline with the below input
3. Get error
4. Check Ladybug to see pipe keep iterating

**Screenshots**

**Configuration**
```
<module>
	<adapter name="Repro2" description="Repro2">
		<receiver name="Repro2"
			className="nl.nn.adapterframework.receivers.GenericReceiver">
			<listener name="Repro2" className="nl.nn.adapterframework.receivers.JavaListener"/>
		</receiver>

		<pipeline firstPipe="ForEachEcho">

			<exits>
				<exit path="READY" state="success"/>
				<exit path="FAILED" state="failure"/>
			</exits>

			<pipe name="ForEachEcho"
				className="nl.nn.adapterframework.pipes.ForEachChildElementPipe"
				blockSize="1"
				outputType="xml"
				collectResults="false">
					<sender className="nl.nn.adapterframework.senders.EchoSender"/>
				<forward name="success" path="READY"/>
			</pipe>
		</pipeline>
	</adapter>
</module>
```

**Input**
```
<?xml version="1.0" encoding="UTF-8"?>
<Test>
	<Child><name>X</name></Child>
	<Child><name>Y</name></Child>
	<Child><name>Z</name></Child>
</Test>
```

**Environment**
```
FF! 7.7-20210608.182006: ibis4repro
Running on LPZWNL000014943 using Apache Tomcat/9.0.39
Java Version: OpenJDK Runtime Environment (1.8.0_252-b09)
Heap size: 327M, total JVM memory: 518M
Free disk space: 71GB, total disk space: 237GB
Up since: 2021-06-09 11:51:43 (47s)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]: N/A
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]: N/A

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by ricardovh** [comment]
Issue is solved in reproduction given above, but still persists in other configurations (shared with team by mail).

**Comment by gvanbrakel** [comment]
Ricardo wrote by mail:

Ik zag dat je 1890 had opgelost en in mijn reproductiescenario is het probleem opgelost, maar ik heb het probleem nog steeds bij de ibis waar ik er oorspronkelijk tegenaan liep. Bijgevoegd een Ladybug report en de ibis+betreffende configuratie (probleem treed op in scenario 01). Ik heb met de Frank!runner gedraaid op versie 7.6-RC3-20210621.170518 en 7.7-20210622.135432.

**Comment by gvanbrakel** [comment]
There appears now a trailing `<block></block>` in the second iteration
