### ISSUE TITLE
Adapter overview empty because of NPE in Adapter class

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#1937]
**Describe the issue**
Our DEV environment was not in use for a long time and we are going to use it for automated testing in the future. In preparation for this change we had a look at our environment and it seemed our database state was not as expected. I dropped all objects in the application schema, including the ibisconfig table containing all running configurations. At this point the adapter overview was still working.

I re-uploaded all configurations and pressed the reload config button on the "All" tab, after a while I got some warnings saying that some configurations didnt startup correctly because of missing propertes for DEV environment. The attached web application was able to call the services but in the adapter overview no adapters were shown at all.

When I opened F12 the API call to the adapters endpoint failed with a 500 error. In the logging I find the following NPE:
![image](https://user-images.githubusercontent.com/37303445/122901402-ccfce380-d34d-11eb-8c7c-1e9e1703c80b.png)

[stacktrace-adapteroverview.txt](https://github.com/ibissource/iaf/files/6693042/stacktrace-adapteroverview.txt)

I tried restarting the JVM but no luck, this error still occurs after a JVM restart. We only see this kind of behaviour on our DEV environment after clearing all our tables.

**Reporter**
Laurens

**To Reproduce**
Not sure exactly, try as I wrote before.

**Screenshots**
![image](https://user-images.githubusercontent.com/37303445/122901506-e56cfe00-d34d-11eb-804b-4bdfc73d2f1e.png)

**Environment**
```
FF! 7.7-20210525.083818: Ibis4Navigator
Running on srdzzapp0437.insim.biz using IBM WebSphere Application Server/8.5
Java Version: Java(TM) SE Runtime Environment (8.0.6.25 - pxa6480sr6fp25-20210115_01(SR6 FP25))
Heap size: 843M, total JVM memory: 2048M
Free disk space: 1GB, total disk space: 2GB
Up since: 2021-06-22 11:20:59 (14m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL] Oracle + MSSQL
 - Browser: [e.g. Chrome, Safari, Edge, Firefox] Chrome

**Comment by nielsm5** [comment]
Should have been fixed in #1853
