### ISSUE TITLE
GUI 3.0 messagelog browser does not have Filter on message text

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1948]
**Describe the issue**
The message log browser in the old GUI 1.2 has the option to search in message text, but in GUI 3.0 this option is no longer available.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jjansenvr** [comment]
check if problem exists in 7.6

**Comment by ricardovh** [comment]
> check if also exists in 7.6

Also exists in 7.6
