### ISSUE TITLE
GUI 3.0 messagelog/errorstore browsers have no filters

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#1949]
**Describe the issue**
The messagelog and errorstore browsers do not have filters anymore. In 7.5.1 the filters are there, in 7.6 and 7.7 they are gone.

**Reporter**
Ricardo

**To Reproduce**
1. Go to an adapter with a messagelog/errorstore
2. Open the messagelog/errorstore
3. See no filter options

**Screenshots**
![image](https://user-images.githubusercontent.com/57142353/123232415-6dcbda00-d4d9-11eb-8b5c-b08cfa2c7289.png)

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7-20210622.135432: *********
Running on LPZWNL000014943 using Apache Tomcat/9.0.39
Java Version: OpenJDK Runtime Environment (1.8.0_252-b09)
Heap size: 253M, total JVM memory: 669M
Free disk space: 76GB, total disk space: 237GB
Up since: 2021-06-24 10:25:56 (20m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]: Chrome

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jjansenvr** [comment]
check if also exists in 7.6

**Comment by ricardovh** [comment]
> check if also exists in 7.6

Also exists in 7.6

**Comment by alisihab** [comment]
The filters are in Display Filters section. If the pane is expanded with the arrow key on the right, the filters will become visible.
See image below.
![image](https://user-images.githubusercontent.com/10929856/129898142-c549dd5d-7ba2-4dd1-96e5-f7f258ee4d8a.png)

**Comment by ricardovh** [comment]
Filters are indeed present in the Display Filters section, but this section is collapsed by default. To improve visibility, open it by default?

**Comment by alisihab** [comment]
Expanding the filters by default would be too prominent. We could improve the user-friendliness by putting the filters on top of each column right under the header. Moreover, the indivudual action buttons could be put in one line by replacing the texts as tooltip.
