### ISSUE TITLE
cannot open stream: (IOException) Stream closed

### ISSUE THREAD

**Issue by Moulib1978** [ibissource/iaf#1954]
**Describe the issue**
For the solution of issue https://github.com/ibissource/iaf/issues/1897,  I have used the new FF version in Ibis4oma.

**FF! 7.7-20210624.162049: ibis4oma ---
Running on LPZWNL000024275 using Apache Tomcat/9.0.39
Java Version: OpenJDK Runtime Environment (1.8.0_252-b09)
Heap size: 378M, total JVM memory: 591M
Free disk space: 100GB, total disk space: 237GB
Up since: 2021-06-25 10:47:48 (30m)**

Errormessage :  **cannot open stream: (IOException) Stream closed**

<pipe className="nl.nn.adapterframework.pipes.Base64Pipe" name="ConvertInputStreamMultipart1ToBase64Encoded" **getInputFromSessionKey="multipart1"** preserveInput="true" storeResultInSessionKey="Base64EncodedMultipart1">

In ladybug, getInputFromSessionKey="multipart1" is empty.

But if I see pipe name="**CheckIfMultipartSessionKeysExist**" ---

here **sessionKey="multipart1"**  is filled with value "testeroni"

But in pipe name="ConvertInputStreamMultipart1ToBase64Encoded", **getInputFromSessionKey**="multipart1" is empty

**Reporter**
Mouli

[Pipeline EngageoneTraxBuilder (2).zip](https://github.com/ibissource/iaf/files/6715116/Pipeline.EngageoneTraxBuilder.2.zip)

**Comment by gvanbrakel** [comment]
The sessionKey multipart1 contains a stream (that can only be read once), that is consumed by CheckIfMultipartSessionKeysExist.
Solutions could be to change the structure of the adapter, so that the sessionKey value is read only once.
Alternatively, we could provide an option like 'preserveOutput'

**Comment by Laurens-makel** [comment]
In the context of this adapter a switch is being made on basis of whether this session key exists or not, it is not meant to consume the stream in "CheckIfMultipartSesionKeyExist".

Is there an alternative way of checking if a session key exists/is filled without consuming the actual stream?

**Comment by Moulib1978** [comment]
Is the following line reads the stream first time?
<param name="multipart1" sessionKey="multipart1" defaultValue="NoMultiPart1"/>

After that we cannot use this sessionkey to read gain?

So then first I have to store the stream from sessionKey="multipart1" in another sessionkey and that I can use throughout the pipeline ?

CheckIfMultipartSesionKeyExist is the XSLT pipe which creates an output like <status>OneFile</status> based on results of multiparts and next pipe is the switch pipe which switches based on status value.
