### ISSUE TITLE
XsltSender cannot find [String: TLE/OUTPUTSTUK/RP020.xsl] in scope [nl.nn.adapterframework.senders.XsltSender@22bdb88a]

### ISSUE THREAD

**Issue by Moulib1978** [ibissource/iaf#1959]
**Problem**
We are getting the following error.
nl.nn.adapterframework.core.PipeRunException: Pipe [SendToFTConfig_TLE] msgId [5014904] caught exception: IbisLocalSender [SendToFTConfig_TLE] exception calling JavaListener [FTSendersListener_TLE]: Pipe [ROSY_TLE] msgId [5014904] caught exception: IbisLocalSender [ROSY_TLE] exception calling JavaListener [ROSY_TLE]: Pipe [Mapping_TLE_Outputstuk] msgId [5014904] Exception on transforming input: XsltSender [Mapping_TLE_Outputstuk] Exception on transforming input: XsltSender [Mapping_TLE_Outputstuk] Exception on creating transformerHandler chain: XsltSender [Mapping_TLE_Outputstuk] cannot find [String: TLE/OUTPUTSTUK/RP020.xsl] in scope [nl.nn.adapterframework.senders.XsltSender@22bdb88a]

Framework information : 
**FF! 7.7-20210624.162049: ibis4oma ---
Running on LPZWNL000024275 using Apache Tomcat/9.0.39
Java Version: OpenJDK Runtime Environment (1.8.0_252-b09)
Heap size: 263M, total JVM memory: 455M
Free disk space: 99GB, total disk space: 237GB
Up since: 2021-06-25 15:44:41 (2d)**

**Reporter**
Mouli Banerjee

Ali sent me a custom java file <HttpSender.java> **only for local test**. This issue is solved with this custom file.

Waiting for an upgraded framework version to be applied on OTAP.

**Comment by alisihab** [comment]
(ClassCastException) nl.nn.adapterframework.stream.Message cannot be cast to java.lang.String

still occurs

**Comment by alisihab** [comment]
movefilepipe, unzippipe has session get and cast to string
