### ISSUE TITLE
Send queue message does not support queuename in destination 

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#1968]
**Describe the issue**
Send queue message does not support queue name in destination, it always does a JNDI lookup on the server

**Reporter**
JJansenvr

**Additional Context**
a extra checkbox to enable lookup destination

**Comment by jjansenvr** [comment]
Error occurred browsing messages: (NameNotFoundException) Context: IUFjava_BU_06_HA_AS_V9.0/nodes/AppSrv01/servers/wasap20, name: P2P.GROUPIT.ibis4mq2emsmig.MQ2EMSFFTemplate.Action: First component in name P2P.GROUPIT.ibis4mq2emsmig.MQ2EMSFFTemplate.Action not found.: (NotFound) IDL:omg.org/CosNaming/NamingContext/NotFound:1.0

**Comment by ricardovh** [comment]
I think this has already been solved, see #1744

**Comment by jacodg** [comment]
This will still be an issue In 7.5.1 which we decided not to solve
