### ISSUE TITLE
Add XmlFileElementIteratorPipe's ElementChain functionality to the ForEachChildElementPipe

### ISSUE THREAD

**Issue by woutervdschoot** [ibissource/iaf#2010]
**Describe the issue**
The pipe XmlFileElementIteratorPipe is deprecated and will be deleted someday to be replaced by the ForEachChildElementPipe, however, XmlFileElementIteratorPipe  contains the ElementChain functionality that ForEachChildElementPipe does not.

**Reporter**
Wouter van der Schoot

**Comment by nielsm5** [comment]
The use of `containerElement` and `targetElement` are not 1 on 1 compatible with the old `elementName` and `elementChain`.
You can however achieve the same results by selecting new elements to iterate over, see #2014.

Note: The result might differ slightly an as such in senders/sub-adapters you might need to adjust the input by changing the `xPathExpressions`
