### ISSUE TITLE
Add thread ID to pipeline session

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#2013]
**Describe the issue**
When interacting with the filesystem in a multi threaded environment it can happen that multiple threads interact with a file/folder on the same moment and causing unexpected behaviour.

To prevent this from happening we would like to use something like the following type of paths:

/temp/{ThreadId}/conversion/

Which will give each thread its own folder to work in.

Although currently a thread id or something is not available in the pipeline session, please add.

**Reporter**
Laurens

**Comment by jacodg** [comment]
Use the FileSystemListener with the inProcessFolder attribute

**Comment by Laurens-makel** [comment]
I am writing to the filesystem, not listening.

**Comment by gvanbrakel** [comment]
You could also use the messageid to achieve a similar separation

**Comment by Laurens-makel** [comment]
I was assuming that threads woud be re-used but it seems that every message is processed with a fresh new thread, resulting in a new ID.
