### ISSUE TITLE
(ObjectClosedException) DSRA9110E: ResultSet is closed.

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#2015]
**Describe the issue**
nl.nn.adapterframework.core.PipeRunException: Pipe [Get records to be processed from database and iterate] msgId [testmessage0ace0850-691f75d3_17a80abe413_-405a] caught exception: (ObjectClosedException) DSRA9110E: ResultSet is closed.

**Reporter**
Swapnil / jjansenvr

**To Reproduce**

**Screenshots**

**Configuration**
```
<pipe name="Get records to be processed from database and iterate" className="nl.nn.adapterframework.jdbc.ResultSetIteratingPipe"
 jmsRealm="jdbc" query="SELECT * FROM COLLECTIONS_RECORDSTORE WHERE TARGET = 'SAP FICO' AND STATUS = 'ToBeProcessed' AND FILTERINGREASON='NONE'  ORDER BY ID" 
styleSheetName="xsl/generic/CreateMessage.xsl" 
collectResults="false" 
ignoreExceptions="true">
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)
[resultset_closed_log.txt](https://github.com/ibissource/iaf/files/6801368/resultset_closed_log.txt)

**Comment by gvanbrakel** [comment]
Could you provide a ladybug report to see what actually happens?

**Comment by jjansenvr** [comment]
The problem has changed a little but is not solved after 1 iteration the resultset is closed.
