### ISSUE TITLE
Add possiblity to generate SHA-256 checksum

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#2016]
**Describe the issue**
For data tracability purposes we would like to store the SHA-256 checksum of a file in our database.

Currently the framework does not seem to support generating SHA-256 hashes, please add a pipe to do such thing.

**Reporter**
Laurens

**Comment by jjansenvr** [comment]
what do you need other than ChecksumPipe?

**Comment by Laurens-makel** [comment]
Did not know this pipe exists :) 

Thanks! Will close this issue.
