### ISSUE TITLE
Include full classdoc in Frank!Doc (json)

### ISSUE THREAD

**Issue by nielsm5** [ibissource/iaf#2032]
**Describe the issue**
We would like to have the ability to see the full classdoc in the Frank!Doc. This is an extension for the JSON not the XSD.

The first sentence for the XSD should split on `. ` (dot - whitespace) and not on `.` (dot)

**Comment by mhdirkse** [comment]
In the website, do you always want to see the whole JavaDoc? Or should the user have a button like "see more..." / "see less..." to choose whether to see the full JavaDoc or only the first sentence?

**Comment by nielsm5** [comment]
#2114
