### ISSUE TITLE
Support for documenting Parameters of Senders and Pipes in Frank!Doc

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#2035]
**Describe the issue**
To be able to document parameters, two javadoc annotations are proposed:
- @ff.Parameters: to document the generic behaviour of parameters, like 'every parameter is added as an header to the request'
- @ff.Parameter: to document individual parameters, like: 'parameter destination is used as the target for the copy operation'

**Reporter**
Core team

**Comment by nielsm5** [comment]
#2169
