### ISSUE TITLE
Add ability to detect when a plural-config-child tries to use the default classname attribute

### ISSUE THREAD

**Issue by nielsm5** [ibissource/iaf#2046]
**Describe the issue**
Een Frank element kan meerdere config children hebben met dezelfde role name. Als er meerdere config children een role name delen, dan kunnen er meerdere kandidaten zijn voor het default element van de generieke element optie. Er wordt voor “plural” config children nooit een default ingevuld voor het className attribute van de generieke element optie en er is ook geen warning dat er iets aan de hand is. Gewenst is om een generieke element optie te maken en om ook een warning te schrijven dat er geen syntax 2 is voor de conflicterende elementen.

**Comment by mhdirkse** [comment]
Dit issue is opgelost met PR https://github.com/ibissource/iaf/pull/2165
