### ISSUE TITLE
Provider org.apache.cxf.jaxws.spi.ProviderImpl could not be instantiated

### ISSUE THREAD

**Issue by nielsm5** [ibissource/iaf#2060]
**Describe the issue**
After the CXF upgrade to version `3.4.4` the following error occured:
Provider org.apache.cxf.jaxws.spi.ProviderImpl could not be instantiated = javax.xml.ws.spi.Provider:
See https://issues.apache.org/jira/browse/CXF-8258 for more info.

This error message indicates that there are multiple versions of javax/xml/ws/spi/ServiceDelegate(jax-ws api) in the environment and are loaded by different classloaders.

**Reporter**
Core-Team

See attached [stacktrace cxf.txt](https://github.com/ibissource/iaf/files/6869693/stacktrace.cxf.probleem.txt).

**Comment by nielsm5** [comment]
A fixpack is available for WAS9;
- https://www.ibm.com/support/pages/latest-fix-packs-websphere-application-server
- https://stackoverflow.com/questions/40265783/websphere-javax-xml-ws-spi-provider-provider-org-apache-axis2-jaxws-spi-provi
- https://www.ibm.com/support/pages/apar/PK96989

**Comment by nielsm5** [comment]
We use JAX-WS 2.2.
See: https://www.ibm.com/docs/en/was-liberty/base?topic=features-java-web-services-22

**Comment by gvanbrakel** [comment]
PR does not solve the problem
