### ISSUE TITLE
unable to retrieve schedules from database : LoadDatabaseSchedules

### ISSUE THREAD

**Issue by Moulib1978** [ibissource/iaf#2069]
**Describe the issue**
We can see this problem in T

**unable to retrieve schedules from database: (SQLException): (ResourceException) addSync: caught Exception: (RollbackException) Transaction rolled back**
**Reporter**
Mouli Banerjee

**Screenshots**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/79903269/127173369-17bd6c90-ba48-41f2-9ec1-284229f2c962.png)

Current FF version on T : FF! 7.7-20210723.100106
[SystemOut (1).log](https://github.com/ibissource/iaf/files/6887398/SystemOut.1.log)

**Comment by nielsm5** [comment]
Could you also attach/mail the ibis log files?

**Comment by nielsm5** [comment]
This really seems like a Websphere issue, I've noticed the datasource connection had to be setup every single time. Now it should remember the datasource and only open/close the connection.
