### ISSUE TITLE
exception checking for existence of table [IBISLOCK]

### ISSUE THREAD

**Issue by Moulib1978** [ibissource/iaf#2072]
**Describe the issue**
exception checking for existence of table [IBISLOCK]: (SQLException): (ResourceException) addSync: caught Exception: (RollbackException) Transaction rolled back

**Reporter**
Mouli Banerjee

**Screenshots**
![cleanupdb](https://user-images.githubusercontent.com/79903269/127179196-ff50b79f-feca-412a-b9bf-c444b50fe663.png)

FF version : FF! 7.7-20210507.133143: ibis4oma 20210520_0753-7ca42407-master-484
[SystemOut (1).log](https://github.com/ibissource/iaf/files/6887389/SystemOut.1.log)

**Comment by nielsm5** [comment]
Could you also attach/mail the ibis log files?

**Comment by nielsm5** [comment]
This problem is indirectly caused by the Websphere TX not being able to get a SQL connection.

**Comment by nielsm5** [comment]
Flagging this as done, as the code has had some minor rework which should prevent this from happening.
