### ISSUE TITLE
Generate WSDL generates WSDL with errors

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#2074]
**Describe the issue**
This WSDL has been copy pasted from one of our IBIS applications and XML spy complains about the following:

![image](https://user-images.githubusercontent.com/37303445/127188066-bdbb2e54-64d1-4b3d-bd9a-f9a615ebd59e.png)

![image](https://user-images.githubusercontent.com/37303445/127188032-8cdbca96-d71e-4eec-a49d-38c78959208a.png)

**Reporter**
Laurens

**To Reproduce**
Replace the.client with the commonly used values, just masked them for public usage.,

https://srtzzapp0406.the.client/ibis4publishing/rest/webservices/Publishing-incoming%20FF%20TIBCO.wsdl

**Configuration**
```
See loaded config
```

**Environment**
```
IAF 7.5-RC3: ibis4publishing
Running on srtzzapp0406.the.client using IBM WebSphere Application Server/8.5
Java Version: Java(TM) SE Runtime Environment (8.0.6.25 - pxa6480sr6fp25-20210115_01(SR6 FP25))
Heap size: 2369M, total JVM memory: 3920M
Free disk space: 8GB, total disk space: 10GB
Up since: 2021-07-09 11:19:34 (4d)
```

**Comment by gvanbrakel** [comment]
The problem appears to be caused by the XSD from which the WSDL is generated, that does not contain a namespace. Is that correct?
