### ISSUE TITLE
Two reports in Ladybug when adapter is triggered by scheduler

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#2078]
**Describe the issue**
With the configuration below I experience the following issues:
- When my adapter is triggered by the scheduler it results in two reports in Ladybug whereas when I trigger the adapter with test a pipeline manually I only see one report. When I go back to 7.6-RC2 I also see only one report in Ladybug when the adapter is triggerd by the scheduler.
- One of the checkpoints shows: <-- no outputstream could be provided
- One of the checkpoints is red and shows: Waiting for stream to be read, captured and closed...

**Reporter**
Jaco de Groot

**To Reproduce**
Start the configuration below and see that two reports are created every 10 minutes like in the screenshot below

**Screenshots**
![image](https://user-images.githubusercontent.com/2970084/127324745-6ac0808d-1425-4637-8eee-1768813dd170.png)

Open a report an see that output of "Pipe Post temperature to ThingsBoard" is <-- no outputstream could be provided. And that Sender Post temperature to ThingsBoard-sender is red and it's message is: Waiting for stream to be read, captured and closed...

**Configuration**
```
<Configuration name="Povis demo">
	<Adapter name="Update temperature" description="Get current temperature in Amsterdam from from OpenWeather every 10 minutes and post it to ThingsBoard">
		<Receiver name="Update temperature">
			<JavaListener name="Update temperature"/>
		</Receiver>
		<Pipeline>
			<FixedResultPipe name="Discard input" returnString=""/>
			<SenderPipe name="Get temperature from OpenWeather">
				<HttpSender
					url="http://api.openweathermap.org/data/2.5/weather?q=Amsterdam&amp;units=metric&amp;mode=xml&amp;appid=<insert api key here>"
				/>
			</SenderPipe>
			<XsltPipe
				name="Xml to Json"
				xpathExpression="concat('{&quot;temperature&quot;:', /current/temperature/@value, '}')"
			/>
			<SenderPipe name="Post temperature to ThingsBoard">
				<HttpSender
					url="https://demo.thingsboard.io/api/v1/<insert api key here>/telemetry"
					methodType="POST"
					contentType="application/json"
				/>
			</SenderPipe>
		</Pipeline>
	</Adapter>
	<scheduler>
		<Job
			description="Update temperature every 10 minutes"
			name="Update temperature"
			adapterName="Update temperature"
			receiverName="Update temperature"
			function="sendMessage"
			interval="600000"
		/>
	</scheduler>
</Configuration>
```

**Input**
No input message required

**Environment**
```
FF! 7.7-20210719.163234: Frank2Povis
Running on LPZWNL000040359 using Apache Tomcat/9.0.50
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 239M, total JVM memory: 693M
Free disk space: 196GB, total disk space: 475GB
Up since: 2021-07-28 14:34:30 (16m) 
```

**Additional Environment**
\-

**Additional Context**
\-

**Comment by nielsm5** [comment]
Created a followup issue #2112 to tackle the XsltPipe issue.
