### ISSUE TITLE
Test a pipeline with multi-file ZIP gives "An exception occurred while processing zip file: Stream closed"

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2093]
**Describe the issue**
When using Test a pipeline with a ZIP file that contains multiple files, only 1 file is processed and the error "An exception occurred while processing zip file: Stream closed" is shown in the GUI.

**Reporter**
Ricardo

**To Reproduce**
1. Go to 'https://ibis4example.ibissource.org/iaf/gui/#!/test-pipeline'
2. Choose the HelloWorld adapter in the dropdown
3. Choose the attached zip-file to upload
4. Press Send
5. Get error
6. Check Ladybug to see only 1 file processed

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
[temp.zip](https://github.com/ibissource/iaf/files/6931846/temp.zip)

**Environment**
```
FF! 7.7-SNAPSHOT: Ibis4Example
Running on vlapp05.interpar.nl using Apache Tomcat/7.0.90
Java Version: OpenJDK Runtime Environment (1.8.0_242-b08)
Heap size: 343M, total JVM memory: 1068M
Free disk space: 181MB, total disk space: 17GB
Up since: 2021-08-03 10:42:32 (1d)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by ricardovh** [comment]
Also present in 7.6.

**Comment by nielsm5** [comment]
Link #2109 (7.6 branch)
