### ISSUE TITLE
Feature request: Simplify XmlSwitchPipe with session keys

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2095]
**Describe the issue**
The XmlSwitchPipe has an attribute sessionKey and getInputFromSessionKey, which I find quite confusing, as they have different behaviors. I think usage would be simplified if the sessionKey-attribute could be deprecated in some way, using the getInputFromSessionKey. I'm not sure how this could be done while keeping compatbile with the current XmlSwitchPipe-implementation. 

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Duplicate of #806
