### ISSUE TITLE
Ladybug AOP config issues

### ISSUE THREAD

**Issue by nielsm5** [ibissource/iaf#2112]
**1) Config not capturing method**
In the AOP config the following: 
```
<aop:around
	pointcut=
		"
		execution(
			*
			nl.nn.adapterframework.stream.IStreamingSender.sendMessage(
				nl.nn.adapterframework.stream.Message, 
				nl.nn.adapterframework.core.PipeLineSession, 
				nl.nn.adapterframework.core.IForwardTarget
			)
		)
	 	and
	 	args(message, session, next)
	 	"
	method="debugStreamingSenderInputOutputAbort"
	arg-names="message, session, next"
/>
```
Does not seem to capture the XsltSender created by the XsltPipe. This seems to be because the Sender is autowired but not created through spring. See: https://github.com/ibissource/iaf/blob/master/core/src/main/java/nl/nn/adapterframework/pipes/XsltPipe.java#L66

Creating the sender through Spring will display it in the Ladybug, however it's displayed as a Sender in a Pipe (which is technically correct, but not functionally) See:
![image](https://user-images.githubusercontent.com/4375703/129192879-7e1df7bd-82c5-4580-8265-5eeb35105f9e.png)

**2) Multiple EchoPipes are captured as if they are ran in a different thread**
```
<EchoPipe name="echo1"/>
<EchoPipe name="echo2"/>
<EchoPipe name="echo3"/>
```
![image](https://user-images.githubusercontent.com/4375703/129191203-0afa4474-9c64-43cd-be95-6420771ef345.png)

**Comment by gvanbrakel** [comment]
The EchoPipes are not run in a different thread, but each provide an OutputStream to their predescessor
