### ISSUE TITLE
Deprecate XsltPipe sessionKey attribute?

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2149]
**Describe the issue**
The xsltPipe contains the attribute sessionKey which duplicates the behavior of preserveInput=true and storeResultInSessionKey=X. As the preserveInput+storeResultInSessionKey are supported from AbstractPipe , making it the standard way of working for this behavior, and the sessionKey attribute only working from the XsltPipe, I propose to deprecate the sessionKey attribute.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jjansenvr** [comment]
sessionKey needs to be deprecated
