### ISSUE TITLE
Ibis4Navigator. Staging and archiving of editable PDF documents with embedded custom NN fonts result in empty PDF documents.

### ISSUE THREAD

**Issue by sojourn99** [ibissource/iaf#2157]
**Describe the issue**
Ibis4Navigator. Staging and archiving of editable PDF documents with embedded custom NN fonts result in empty PDF documents.
There is no problem storing the PDF in the staging database. When I run custom Java code to read the Blob field and save it as PDF, the result is exactly the same as the original. It seems something goes wrong retrieving the Blob. 

**Reporter**
Alex Berg

**To Reproduce**
A PDF file to reproduce this issue can be requested from the reporter.

1. Drag the PDF file in the Navigator client front-end
2. Note that the PDF in the viewer part of the screen has no visible content.
3. Download the document.
4. Open the downloaded file in Adobe Acrobat Reader
5. Note that the PDF has no content. 
6. Open Document Properties tab Fonts, and note that the fonts are not embedded.
7. Error in Acrobat Reader: "Cannot extract the embedded font 'NNDagnyText-Regular'. Some characters may not display or print correctly."

**Screenshots**

**Configuration**
Adapter Document_GET_viewpdf in configuration Staging

	<pipe name="Select_Document" className="nl.nn.adapterframework.pipes.SenderPipe">
		<sender className="nl.nn.adapterframework.jdbc.FixedQuerySender" 
			queryType="select" 
			jmsRealm="jdbc_stg"
			blobsCompressed="false"
			scalar="true"
			query="SELECT CONVERTED_DOCUMENT FROM CONVERTED_DOCUMENTS WHERE CONVERSION_ID = ?"
			blobCharset="ISO-8859-1"
		>
			<param name="documentId" sessionKey="documentId"/>
		</sender>

		<forward name="success" path="READY" />
		<forward name="exception" path="ServerError" />
	</pipe>

**Input**
A PDF file to reproduce this issue can be requested from the reporter.

**Environment**
FF! 7.7-20210525.083818: Ibis4Navigator
Running on srazzapp0474.insim.biz using IBM WebSphere Application Server/8.5
Java Version: Java(TM) SE Runtime Environment (8.0.6.25 - pxa6480sr6fp25-20210115_01(SR6 FP25))
Heap size: 662M, total JVM memory: 4096M
Free disk space: 9GB, total disk space: 10GB
Up since: 2021-08-24 12:17:18 (2d)

**Additional Environment**
 - DBMS: MSSQL jdbc/stagingDB
 - Browser: Chrome

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
If it has a BOM it want to be processed with the supplied charset. Forcing a different charset (ie by setting the `charset` attribute) it will override the default. If you have not supplied any charsets and you're reading the PDF it will attemt to use the BOM to determine the charset. Clearly sounds like a charset issue to me. Will try to analyse what's going on on Monday.

**Comment by jjansenvr** [comment]
could you test without the **blobCharset="ISO-8859-1"** because this will attempt to convert the binary information to a string

**Comment by sojourn99** [comment]
Testing without blobCharset results in empty PDF's, also for PDF's without BOM.

**Comment by nielsm5** [comment]
I'm assuming that you only removed it in 1 place, to my knowledge it's used throughout the entire configuration/flow.

I think the reason this was required in the past was because the ApiListener could not handle binary data.
This has been fixed in #1554 and #2090. (Specifically the changes made to `StreamUtil.copyReaderToWriter(..)` to return binary data and `parseContentAsMessage(..)` to retrieve binary data.

Is it possible to remove all charset references, and let the framework try to determine the required charset? I'm unsure if PDF's already stored in the database will be parsed with the correct charset. You mentioned that you manually tried to retrieve the PDF's and it was successful, so I'm hopeful.

**Comment by sojourn99** [comment]
What is the iaf version with fix #2090 ?

**Comment by alisihab** [comment]
7.7-20210816.115354 or any newer version has that fix.

**Comment by sojourn99** [comment]
I have tested with iaf version 7.7-20210816.115354. 
With blobCharset removed in the pipe that stores the document, and the pipe that retrieves the document I get this error:

`<errorMessage timestamp="Thu Sep 02 12:13:35 CEST 2021" originator="IAF 7.7-20210816.115354" message="Pipe [Store_Unconverted_Document_In_Database] msgId [0a721c4d--2b002900_17ba5fc248c_-7ff1] : [nl.nn.adapterframework.jdbc.FixedQuerySender] [Store_Unconverted_Document_In_Database-sender] got exception sending message: unknown inputstream [class [B] for parameter [CONVERTED_DOCUMENT]">
  <location class="nl.nn.adapterframework.pipes.SenderPipe" name="Store_Unconverted_Document_In_Database" />
  <details>nl.nn.adapterframework.core.SenderException: [nl.nn.adapterframework.jdbc.FixedQuerySender] [Store_Unconverted_Document_In_Database-sender] got exception sending message: unknown inputstream [class [B] for parameter [CONVERTED_DOCUMENT]&#xD;
	at nl.nn.adapterframework.jdbc.JdbcQuerySenderBase.executeStatementSet(JdbcQuerySenderBase.java:385)&#xD;
	at nl.nn.adapterframework.jdbc.FixedQuerySender.sendMessage(FixedQuerySender.java:132)&#xD;
	at nl.nn.adapterframework.jdbc.FixedQuerySender$$FastClassBySpringCGLIB$$ed3e925b.invoke(&lt;generated&gt;)&#xD;` 

The configuration:
`<pipe className="nl.nn.adapterframework.pipes.SenderPipe" name="Store_Unconverted_Document_In_Database">
<sender blobsCompressed="false" className="nl.nn.adapterframework.jdbc.FixedQuerySender" jmsRealm="jdbc_stg" query="INSERT INTO CONVERTED_DOCUMENTS (CONVERSION_ID, DOCUMENT_NAME, CONVERTED_DOCUMENT, META_DATA, TARGET_SCHEMA, NOTIFICATION_ADDRESS, GUID, SOURCE, SOURCE_DOCUMENT_ID, SOURCE_TRANSACTION_ID, REQUEST_USER_ID, NUMBER_OF_PAGES, ARCHIVE_TYPE, TEAM) VALUES (SEQ_CONVERSION_ID.NEXTVAL,?,?,?,?,?,?,?,?,?,?,?,?,?)" useNamedParams="true">
<param defaultValue="Untitled Document" name="DOCUMENT_NAME" sessionKey="DOCUMENT_NAME"/>
<param name="CONVERTED_DOCUMENT" sessionKey="file" type="inputstream"/>
<param name="META_DATA" sessionKey="MetaDataAsJSON"/>
<param name="TARGET_SCHEMA" sessionKey="OriginalXML" xpathExpression="StageDocument/metaDataSchemaName"/>
<param name="NOTIFICATION_ADDRESS" sessionKey="OriginalXML" xpathExpression="StageDocument/notificationAddress"/>
<param name="GUID" sessionKey="GUID"/>
<param name="SOURCE" sessionKey="OriginalXML" xpathExpression="StageDocument/documentSource"/>
<param name="SOURCE_DOCUMENT_ID" sessionKey="OriginalXML" xpathExpression="StageDocument/sourceDocumentId"/>
<param name="SOURCE_TRANSACTION_ID" sessionKey="OriginalXML" xpathExpression="StageDocument/sourceTransactionId"/>
<param name="REQUEST_USER_ID" sessionKey="OriginalXML" xpathExpression="StageDocument/requestUserId"/>
<param name="amountOfPages" sessionKey="amountOfPages"/>
<param name="ARCHIVE_TYPE" sessionKey="OriginalXML" xpathExpression="StageDocument/archiveType"/>
<param name="TEAM" sessionKey="OriginalXML" xpathExpression="StageDocument/team"/>
</sender>
<forward name="success" path="Retrieve_RowNum_UnConverted_Document"/>
<forward name="exception" path="error2json"/>
</pipe>`

I get the same error with blobCharset set to "ISO-8859-1"

**Comment by nielsm5** [comment]
I'm still not convinced there's actually a framework issue. The fix would be to remove all charset references., not just in 1 part of the pipeline, but the entire application. 

The file has a BOM, which means it requires a specific charset in order to be read. You override this charset, and thus you cannot read the file anymore.

The framework is working as expected as, a charset should only be used when converting binary data to character data. Since you're only storing the file in a database and reading from this database, unless you're using a VARCHAR/CLOB field and not a BLOB, this should remain binary data. If binary data is used throughout the entire 'flow/application', there is no need for a charset. 

The reason I mentioned the 2 PR's in my previous reply was purely to indicate why you may have had to introduce the charset attribute, as a temporarily solution, in the past.

**Comment by sojourn99** [comment]
I have removed all blobCharset settings from every Ibis4Navigator configuration and tested locally with IAF version 7.7-20210816.115354.
I still get the same error processing any PDF document, with or without BOM:

{"location":"","details":"nl.nn.adapterframework.core.SenderException: [nl.nn.adapterframework.jdbc.FixedQuerySender] [Store_Unconverted_Document_In_Database-sender] got exception sending message: unknown inputstream [class [B] for parameter [CONVERTED_DOCUMENT] at nl.nn.adapterframework.jdbc.JdbcQuerySenderBase.executeStatementSet(JdbcQuerySenderBase.java:385) at nl.nn.adapterframework.jdbc.FixedQuerySender.sendMessage(FixedQuerySender.java:132) at nl.nn.adapterframework.jdbc.FixedQuerySender$$FastClassBySpringCGLIB$$ed3e925b.invoke(<generated>) at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at

The error occurs in this pipe:

<pipe className="nl.nn.adapterframework.pipes.SenderPipe" name="Store_Unconverted_Document_In_Database">
<sender blobsCompressed="false" className="nl.nn.adapterframework.jdbc.FixedQuerySender" jmsRealm="jdbc_stg" query="INSERT INTO CONVERTED_DOCUMENTS (CONVERSION_ID, DOCUMENT_NAME, CONVERTED_DOCUMENT, META_DATA, TARGET_SCHEMA, NOTIFICATION_ADDRESS, GUID, SOURCE, SOURCE_DOCUMENT_ID, SOURCE_TRANSACTION_ID, REQUEST_USER_ID, NUMBER_OF_PAGES, ARCHIVE_TYPE, TEAM) VALUES (SEQ_CONVERSION_ID.NEXTVAL,?,?,?,?,?,?,?,?,?,?,?,?,?)" useNamedParams="true">
<param defaultValue="Untitled Document" name="DOCUMENT_NAME" sessionKey="DOCUMENT_NAME"/>
<param name="CONVERTED_DOCUMENT" sessionKey="file" type="inputstream"/>
<param name="META_DATA" sessionKey="MetaDataAsJSON"/>
<param name="TARGET_SCHEMA" sessionKey="OriginalXML" xpathExpression="StageDocument/metaDataSchemaName"/>
<param name="NOTIFICATION_ADDRESS" sessionKey="OriginalXML" xpathExpression="StageDocument/notificationAddress"/>
<param name="GUID" sessionKey="GUID"/>
<param name="SOURCE" sessionKey="OriginalXML" xpathExpression="StageDocument/documentSource"/>
<param name="SOURCE_DOCUMENT_ID" sessionKey="OriginalXML" xpathExpression="StageDocument/sourceDocumentId"/>
<param name="SOURCE_TRANSACTION_ID" sessionKey="OriginalXML" xpathExpression="StageDocument/sourceTransactionId"/>
<param name="REQUEST_USER_ID" sessionKey="OriginalXML" xpathExpression="StageDocument/requestUserId"/>
<param name="amountOfPages" sessionKey="amountOfPages"/>
<param name="ARCHIVE_TYPE" sessionKey="OriginalXML" xpathExpression="StageDocument/archiveType"/>
<param name="TEAM" sessionKey="OriginalXML" xpathExpression="StageDocument/team"/>
</sender>
<forward name="success" path="Retrieve_RowNum_UnConverted_Document"/>
<forward name="exception" path="error2json"/>
</pipe>

Also, processing documents that need to be converted to PDF results in an error:

<errorMessage timestamp="Wed Sep 15 10:16:52 CEST 2021" originator="IAF 7.7-20210816.115354" message="Pipe [Store_Converted_Document_In_Database] msgId [1160] : [nl.nn.adapterframework.jdbc.FixedQuerySender] [Store_Converted_Document_In_Database-sender] got exception sending message: unknown inputstream [class [B] for parameter [CONVERTED_DOCUMENT]">
<location class="nl.nn.adapterframework.pipes.SenderPipe" name="Store_Converted_Document_In_Database" />
<details>nl.nn.adapterframework.core.SenderException: [nl.nn.adapterframework.jdbc.FixedQuerySender] [Store_Converted_Document_In_Database-sender] got exception sending message: unknown inputstream [class [B] for parameter [CONVERTED_DOCUMENT]&#xD;
at nl.nn.adapterframework.jdbc.JdbcQuerySenderBase.executeStatementSet(JdbcQuerySenderBase.java:385)&#xD;

The pipe:

<pipe className="nl.nn.adapterframework.pipes.SenderPipe" name="Store_Converted_Document_In_Database">
<sender blobsCompressed="false" className="nl.nn.adapterframework.jdbc.FixedQuerySender" jmsRealm="jdbc_stg" query="UPDATE CONVERTED_DOCUMENTS SET CONVERSION_OPTION = ?, MEDIA_TYPE = ?, DOCUMENT_NAME = ?, FAILURE_REASON = ?, PARENT_CONVERSION_ID = ?, CONVERTED_DOCUMENT = ?, NUMBER_OF_PAGES = ? WHERE GUID = ? AND CONVERSION_ID = ? " useNamedParams="true">
<param name="CONVERSION_OPTION" sessionKey="CONVERSION_OPTION" type="integer"/>
<param name="MEDIA_TYPE" sessionKey="MEDIA_TYPE"/>
<param name="DOCUMENT_NAME" sessionKey="DOCUMENT_NAME"/>
<param name="FAILURE_REASON" sessionKey="FAILURE_REASON"/>
<param name="PARENT_CONVERSION_ID" sessionKey="PARENT_ID"/>
<param name="CONVERTED_DOCUMENT" sessionKey="CONVERTED_DOCUMENT" type="inputstream"/>
<param name="NUMBER_OF_PAGES" sessionKey="NUMBER_OF_PAGES" type="integer"/>
<param name="GUID" sessionKey="GUID"/>
<param name="DocumentId" sessionKey="DocumentId"/>
</sender>
<forward name="success" path="Save_Attachments"/>
<forward name="exception" path="ERROR"/>
</pipe>

**Comment by nielsm5** [comment]
These issues have been fixed in #2328, and the parameter problems described above have been back ported to the 7.6 release.
I'm closing this issue as afaik this has been resolved. If you are still encountering issues feel free to reach out, open a new issue or reopen this one!
