### ISSUE TITLE
XSLT with import gives "(RuntimeException) Cannot lookup resource [classpath:xsl/imports/date.xsl] with protocol [classpath], no allowedProtocols"

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2167]
**Describe the issue**
I have an XSLT (1.0) that works fine in 7.5.1, but when used in 7.6 and higher, it gives a `(RuntimeException) Cannot lookup resource [classpath:xsl/imports/date.xsl] with protocol [classpath], no allowedProtocols`

The entire configuration will be send by mail, as I have not yet been able to determine what the exact reproduction is and the complete xslt does contain some customer specific information.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.6: ibis4repro
Running on LPZWNL000014943 using Apache Tomcat/9.0.50
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 159M, total JVM memory: 487M
Free disk space: 59GB, total disk space: 237GB
Up since: 2021-08-30 17:00:05 (3m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
I expect the problem can be resolved by removing the 'classpath:' prefix from the import statement
