### ISSUE TITLE
Add optional queryType field in console

### ISSUE THREAD

**Issue by nielsm5** [ibissource/iaf#2170]
**Describe the issue**
with ... as query results in `other` queryType, without the option to return the response (queryType = select)
![image](https://user-images.githubusercontent.com/4375703/131494561-9cd13854-32e3-44b9-bb33-94917ec3a5ea.png)

The backend already supports the queryType parameter, the frontend does not.

**Reporter**
Laurens

**Comment by jjansenvr** [comment]
this should work without explicitly setting this value, shouldn't we fix the backend code instead

**Comment by Laurens-makel** [comment]
I think users should have the option available to overrule the framework trying to figure out if there is a result required, in case the framework makes a wrong decision.
