### ISSUE TITLE
Missing/lost ADDITIONAL.PROPERTIES.FILE options

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2175]
**Describe the issue**
The framework uses the property ADDITIONAL.PROPERTIES.FILE to determine which property-files to load aside from the AppConstants. Pre-7.5, the list of ADDITIONAL.PROPERTIES.FILE was longer, but in #374 a lot of those property-files have been removed from the list, but some flexibility has been lost with that. This is not mentioned in the release notes, so either it should be mentioned in the release notes, or the missing options should be added back again.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
Are there specific options that you are really missing?

**Comment by ricardovh** [comment]
I'm not missing specific options at the moment.

When I created this issue I thought my properties were set on the StageSpecifics which has highest priority, but they are set from DeploymentSpecifics, so I can handle the current situation with the SideSpecifics and StageSpecifics.
