### ISSUE TITLE
Conflicting SAAJ implementation on WebSphere

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#2181]
**Describe the issue**
When running iaf-test on WebSphere, a WebSphere verification error occurs: java.lang.VerifyError: JVMVRFY012 stack shape inconsistent
``
``

**Reporter**
Please state your name. If we don't know who is reporting, a solution of the issue might be delayed.

**To Reproduce**
1. Go to Ibis4TestIAF on WebSphere, or start the WebSphere docker container with iaf-test
2. Run the scenario '/CorrelationMessageId/scenario04'
3. See error

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7-SNAPSHOT: Ibis4Test
Running on 4d2fe92977b9 using IBM WebSphere Application Server/9.0.5.7
Java Version: Java(TM) SE Runtime Environment (8.0.6.26 - pxa6480sr6fp26-20210216_01(SR6 FP26))
Heap size: 738M, total JVM memory: 913M
Free disk space: 213GB, total disk space: 251GB
Up since: 2021-09-06 17:01:49 (9m)
```

**Additional Environment**
 - DBMS: [MSSQL]
 - Browser: [Chrome]

**Additional Context**
```
nl.nn.adapterframework.core.SenderException: WebServiceSender [Test Tool WebServiceSender] to [http://localhost:9080/iaf-test/servlet/rpcrouter] httpstatus [500] reason [Internal Server Error] body [Error 500: java.lang.VerifyError: JVMVRFY012 stack shape inconsistent&#59; class=com/sun/xml/messaging/saaj/soap/SOAPDocumentImpl, method=createDocumentFragment&#40;&#41;Lorg/w3c/dom/DocumentFragment&#59;, pc=5&#59; Type Mismatch, argument 0 in signature com/sun/xml/messaging/saaj/soap/SOAPDocumentFragment.&lt;init&gt;:&#40;Lcom/sun/org/apache/xerces/internal/dom/CoreDocumentImpl&#59;&#41;V does not match
Exception Details:
  Location:
    com/sun/xml/messaging/saaj/soap/SOAPDocumentImpl.createDocumentFragment&#40;&#41;Lorg/w3c/dom/DocumentFragment&#59; @5: JBinvokespecial
  Reason:
    Type &#39;com/sun/xml/messaging/saaj/soap/SOAPDocumentImpl&#39; &#40;current frame, stack[2]&#41; is not assignable to &#39;com/sun/org/apache/xerces/internal/dom/CoreDocumentImpl&#39;
  Current Frame:
    bci: @5
    flags: { }
    locals: { &#39;com/sun/xml/messaging/saaj/soap/SOAPDocumentImpl&#39; }
    stack: { &#39;uninitialized&#39;, &#39;uninitialized&#39;, &#39;com/sun/xml/messaging/saaj/soap/SOAPDocumentImpl&#39; }
]
	at nl.nn.adapterframework.http.HttpSender.extractResult(HttpSender.java:547)
	at nl.nn.adapterframework.http.WebServiceSender.extractResult(WebServiceSender.java:145)
	at nl.nn.adapterframework.http.HttpSenderBase.sendMessage(HttpSenderBase.java:687)
	at nl.nn.adapterframework.testtool.SenderThread.run(SenderThread.java:45)
```

**Comment by gvanbrakel** [comment]
Additional line in log:
[9/13/21 16:31:49:405 CEST] 000013af soap          W   Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.

**Comment by alisihab** [comment]
https://www.ibm.com/support/pages/ibm-java-linux-howto-resolving-javalangverifyerror-jvmvrfy012-stack-shape-inconsistent

**Comment by nielsm5** [comment]
> Additional line in log:
> [9/13/21 16:31:49:405 CEST] 000013af soap W Using deprecated META-INF/services mechanism with non-standard property: javax.xml.soap.MetaFactory. Property javax.xml.soap.SAAJMetaFactory should be used instead.

This doesn't some from us, this is not used by the Frank!Framework.
