### ISSUE TITLE
multipartXml containing special characters not encoded properly

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#2187]
**Describe the issue**
When the multipartXml sessionKey is used and a name contains special characters, they are not being encoded properly. 

With the xslt we populate the xml and store it in the sessionKey multipartXml :
&lt;xsl:attribute name="name"&gt;ëAantonen eigen middelen ter hoogte van € 190_265,00.jpeg&lt;/xsl:attribute&gt

This is being returned as : 
![image](https://user-images.githubusercontent.com/35798481/132525854-ff5b8269-a4f2-4714-b47e-502cff189b90.png)

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**
In Ladybug you can see the value is still ok : 

![image](https://user-images.githubusercontent.com/35798481/132526144-a6351881-01e4-4924-963c-a5483d9ce411.png)

But in the response you will see : 

![image](https://user-images.githubusercontent.com/35798481/132526280-0e73fe4a-93ea-4947-a01e-8120f3493482.png)

**Configuration**
![image](https://user-images.githubusercontent.com/35798481/132526551-4f03003b-d0b3-4310-8bf9-50531b723850.png)

![image](https://user-images.githubusercontent.com/35798481/132526617-0d3c9983-ade1-4305-bbd4-e9ae84606939.png)

**Input**

**Environment**
FF! 7.6-RC3-20210707.181814: Ibis4Titan 395-f87fcaf1-master
Running on srazzapp0476.insim.biz using IBM WebSphere Application Server/8.5
Java Version: Java(TM) SE Runtime Environment (8.0.6.25 - pxa6480sr6fp25-20210115_01(SR6 FP25))
Heap size: 767M, total JVM memory: 1536M
Free disk space: 9GB, total disk space: 10GB
Up since: 2021-09-08 07:01:05 (9h)

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
Could you provide a ladybug report to analyze this?

**Comment by rvdstel** [comment]
[Pipeline GetDocumentAndAttributesStreaming_4.zip](https://github.com/ibissource/iaf/files/7142654/Pipeline.GetDocumentAndAttributesStreaming_4.zip)

ladybug report

**Comment by gvanbrakel** [comment]
In the ladybug report the message appears to be OK until the last checkpoint. This suggests that the problem is in the Receiver/Listener (that is not covered by ladybug). Could you provide the configuration of the Receiver and possibly your test-setup ?

**Comment by rvdstel** [comment]
Configuration receiver:
![image](https://user-images.githubusercontent.com/35798481/132944189-64f09619-56dd-4bf0-bd68-06f8b4a27102.png)

The test is with SoapUi (raw) : 
**Request :** 
POST https://srazzapp0476.insim.biz/ibis4titan/services/GetDocumentAndAttributesStreaming_4-WS HTTP/1.1
Accept-Encoding: gzip,deflate
Content-Type: multipart/related; type="application/xop+xml"; start="<rootpart@soapui.org>"; start-info="text/xml"; boundary="----=_Part_0_22813351.1631264661558"
SOAPAction: "GetDocumentAndAttributesStreaming_1"
Authorization: Basic ...
MIME-Version: 1.0
Content-Length: 1491
Host: srazzapp0476.insim.biz
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.1.1 (java 1.5)

**Response:**
HTTP/1.1 200 OK
Date: Fri, 10 Sep 2021 09:04:22 GMT
X-Powered-By: Servlet/3.0
Set-Cookie: LtpaToken2=aikSURsrqUAUDi130otde3QfRHrCAlbn+5ov7ipdlRbyuJC1SH3q9X+estVncwU6txtIKWLvYkckjMz1KDzDVepbp6pBnIbGw5/e5b7SVgqL/xWJIC7AYObfezHIKElSMZKFzpylmRWa2sT3xCYvrat5GdN/9HygBC2DowNPotQNfMzKZWkLdSSiHYSl8fIV3o3yzIjGhjSRSvbXLPLsv5/nJspg4EnnFqNA1Pj3vtauWBRQdG7NM72aoYrA6F0Ank78iWYEOE5PlyF/ysmqf17MVmqti/rE4dAbFMoM8aO3tkMTjiu3A2OGPN4BT/l1OCH3okFlaH7QkaqnjqUy1So16qyeWlfncFlagMvg4ymq7f/dftq1/lt8ZHa3gjze; Path=/; HttpOnly
Expires: Thu, 01 Dec 1994 16:00:00 GMT
Cache-Control: no-cache="set-cookie, set-cookie2"
Keep-Alive: timeout=15, max=100
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: multipart/related; type="application/xop+xml"; boundary="uuid:0c7e3be1-0355-448e-9662-07974fa69667"; start="<root.message@cxf.apache.org>"; start-info="text/xml"
Content-Language: nl-NL


--uuid:0c7e3be1-0355-448e-9662-07974fa69667
Content-Type: application/xop+xml; charset=UTF-8; type="text/xml"
Content-Transfer-Encoding: binary
Content-ID: <root.message@cxf.apache.org>

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header><MessageHeader xmlns="http://nn.nl/XSD/Generic/MessageHeader/2">
   <From>
      <Id>Ibis4Titan</Id>
   </From>
   <To>
      <Location>ESB.Archiving.BS.Document.Ibis4Titan.4.GetDocumentAndAttributesStreaming.4.Response</Location>
   </To>
   <HeaderFields>
      <CPAId>n/a</CPAId>
      <ConversationId>rn09ce.itc.intranet_0a408cbc-3dd5b281_13cee52a0e4_-7081</ConversationId>
      <MessageId>srazzapp0476.insim.biz_0ace10a7--3eb85434_17bc3c6c85f_7a2d</MessageId>
      <CorrelationId>rn09ce.itc.intranet_0a408cbc-3dd5b281_13cee52a0e4_-707f</CorrelationId>
      <Timestamp>2021-09-10T11:04:24</Timestamp>
   </HeaderFields>
   <Service>
      <Name>Document</Name>
      <Context>Ibis4Titan</Context>
      <Action>
         <Paradigm>Response</Paradigm>
         <Name>GetDocumentAndAttributesStreaming</Name>
         <Version>4</Version>
      </Action>
   </Service>
</MessageHeader>
</soapenv:Header><soapenv:Body><GetDocumentAndAttributes_Response xmlns="http://nn.nl/XSD/Archiving/Document/4/GetDocumentAndAttributesStreaming/1">
	  <schemaName>NN_Hypotheken_Regulier</schemaName>
	  <archiveDate>2021-08-11T09:21:42.836</archiveDate>
	  <issuedDate>2021-08-06</issuedDate>
	  <issuer>HDN</issuer>
	  <externalDocumentId>b1425af2-9d5b-444a-bca3-3b308143067e</externalDocumentId>
	  <internalDocumentId>RNNSURSNEN_75240115</internalDocumentId>
	  <MetaData>
		    <label name="issuedDate">2021-08-06</label>
		    <label name="archiveDate">2021-08-11T09:21:42.836</label>
		    <label name="issuer">HDN</label>
		    <label name="documentType">Verstrekken</label>
		    <label name="documentDetail">Aanvrager</label>
		    <label name="documentTitle">Ã«Aantonen eigen middelen ter hoogte van â‚¬ 190.265,00</label>
		    <label name="agreementNumber">1053027670</label>
		    <label name="documentRouting">In</label>
		    <label name="descriptionProductGroup">Hypotheken Regulier</label>
		    <label name="securityClass">Onbeveiligd</label>
		    <label name="authorizedTo"></label>
		    <label name="productCode"></label>
		    <label name="subject"></label>
		    <label name="partnerSilver"></label>
		    <label name="label">NN</label>
		    <label name="language">Nederlands</label>
		    <label name="agreementNumberType">Lening</label>
		    <label name="sourceTransactionId">1</label>
		    <label name="source">HDN</label>
		    <label name="lastModifiedDate">2021-09-08T11:15:43.627</label>
		    <label name="lastModifiedBy">Richard.Stel</label>
	  </MetaData>
	  <Remark></Remark>
	  <File>
		    <fileName>Ã«Aantonen eigen middelen ter hoogte van â‚¬ 190_265,00.jpeg</fileName>
		    <fileContent>
			      <Include xmlns="http://www.w3.org/2004/08/xop/include" href="cid:attachment"></Include>
		    </fileContent>
		    <fileSize>15750</fileSize>
		    <contentType>image/jpeg</contentType>
	  </File>
	  <Result xmlns="http://nn.nl/XSD/Generic/MessageHeader/2">
		    <Status>OK</Status>
	  </Result>
</GetDocumentAndAttributes_Response>
</soapenv:Body></soapenv:Envelope>
--uuid:0c7e3be1-0355-448e-9662-07974fa69667
Content-Type: image/jpeg
Content-Transfer-Encoding: binary
Content-ID: <Ã«Aantonen eigen middelen ter hoogte van â‚¬ 190_265,00.jpeg>

ÿØÿà

**Comment by alisihab** [comment]
After sending a Post request to the adapter everything goes fine and the response that is displayed in soap-ui has some weird characters? Could it be then the response encoding problem of soap-ui? Could you also try to send the same request with postman? Or try to change the encoding in soap-ui maybe.

**Comment by rvdstel** [comment]
You can close this issue.....

I have modified the file : SmartBear\SoapUI-5.4.0\bin\ SoapUI-5.4.0.vmoptions and added the line:
-Dfile.encoding=UTF-8

Now we see in the raw response:
Content-ID: <ëAantonen eigen middelen ter hoogte van € 190_265,00.jpeg> 

I have also tested it with postman, which gave the correct result as well:
Content-ID: <ëAantonen eigen middelen ter hoogte van € 190_265,00.jpeg>
