### ISSUE TITLE
IAF (7.5/7.6) xsltVersion issue

### ISSUE THREAD

**Issue by CBiplab** [ibissource/iaf#2204]
**Describe the issue**
We've recently upgraded the IAF version of one of our Ibises to 7.6. From then onward, we are getting the mentioned error at the mentioned pipe (switch pipe). This works fine in version 7.0-RC3

Pipe name (look at the attached TTR )-> checkFor:Updating_WGPAccount
---------------------------------------------
**ERROR->**

Pipe [checkFor:Updating_WGPAccount] msgId [ID:EMS_TST_ESB_P2P_SMALL.5F5B612A1658183485AA:6352] got exception on transformation: (XPathException) line [1]: Cannot compare xs:string to xs:integer
--------------------------------------------------

**Reporter**
Biplab Chakraborty

**Input**
Attached TTR file.
[Pipeline.SetPortalSetUpMutation.zip](https://github.com/ibissource/iaf/files/7171536/Pipeline.SetPortalSetUpMutation.zip)

**Comment by ricardovh** [comment]
The XmlSwitch uses an XSLT to process the result, and the default version has changed from 1 to 2, which have slightly different behaviors that result in the error you are getting. You can set it back to version 1 by setting `xsltVersion="1"` on the pipe, or you can add explicit conversion to your current XPath.

**Comment by CBiplab** [comment]
> The XmlSwitch uses an XSLT to process the result, and the default version has changed from 1 to 2, which have slightly different behaviors that result in the error you are getting. You can set it back to version 1 by setting `xsltVersion="1"` on the pipe, or you can add explicit conversion to your current XPath.

Hi, tried by adding xsltVersion="1" at the pipe, unfortunately it's still throwing the same exception. I've attached the ttr for your ref.

[Pipeline SetPortalSetUpMutation (1).zip](https://github.com/ibissource/iaf/files/7176759/Pipeline.SetPortalSetUpMutation.1.zip)

**Comment by alisihab** [comment]
Could you try specifying the`type`attribute for your parameters in XmlSwitch pipe? The first and the last two require `type="integer"`

**Comment by alisihab** [comment]
Add a property to override the default xslt version so that xsltVersion='1' property is no longer needed to be set in each item.

**Comment by alisihab** [comment]
requires new feature request. Therefore closing this one.
