### ISSUE TITLE
PutParametersInSession with xpathExpression with type=domdoc results in "Content is not allowed in prolog"

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2256]
**Describe the issue**
After storing (a part of) an XML in a session key using a PutParametersInSession and type="domdoc", further xpathExpressions on that session key result in "Content is not allowed in prolog" errors.

Setting type="xml"  works as intended, but I would expect type="domdoc" to not have different behavior.

The issue is present in 7.5.2, 7.6 and 7.7. 
In 7.5.2 the error is `Parameter [xmlMessageChild2] exception on transformation to get parametervalue: (ClassCastException) org.apache.xerces.dom.DocumentImpl cannot be cast to java.lang.String"`
In 7.6 and 7.7 the error is `Parameter [xmlMessageChild2] exception on transformation to get parametervalue: (XPathException): (SAXParseException) line [1] column [1]: Content is not allowed in prolog."`

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
<module>
	<adapter name="Repro" description="Repro">
		<receiver name="Repro"
			className="nl.nn.adapterframework.receivers.GenericReceiver">
			<listener name="Repro"
				className="nl.nn.adapterframework.receivers.JavaListener"/>
		</receiver>

		<pipeline firstPipe="Store">
			<exits>
				<exit path="READY" state="success"/>
			</exits>

			<pipe name="Store"
				className="nl.nn.adapterframework.pipes.PutParametersInSession">
				<param name="xmlMessageChild" xpathExpression="Test/Child[1]" type="domdoc"/>
				<forward name="success" path="Store2" />
			</pipe>

			<pipe name="Store2"
				className="nl.nn.adapterframework.pipes.PutParametersInSession">
				<param name="xmlMessageChild2" sessionKey="xmlMessageChild" xpathExpression="Child/name"/>
				<forward name="success" path="READY" />
			</pipe>
		</pipeline>
	</adapter>
</module>
```

**Input**
```
<?xml version="1.0" encoding="UTF-8"?>
<Test>
	<Child><name>X</name></Child>
	<Child><name>Y</name></Child>
	<Child><name>Z</name></Child>
</Test>
```

**Environment**
```
FF! 7.7-20210928.133035: ibis4repro
Running on LPZWNL000014943 using Apache Tomcat/9.0.50
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 261M, total JVM memory: 450M
Free disk space: 58GB, total disk space: 237GB
Up since: 2021-09-28 15:56:47 (14m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
The difference between dom-doc and xml types should be documented.

**Comment by alisihab** [comment]
Has this ever worked in earlier versions like 7.3?
