### ISSUE TITLE
Option to disable stubbing for a specific element

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2393]
**Describe the issue**
Sometimes I want to locally test a specific pipe/sender/listener without stubbing, for example a HTTP Sender for which I want to test with the actual service to verify that the sender is configured properly. The only way this is now possible, is by setting `stub4testtool.configuration` to false for a complete configuration or adding a custom stub4testtool.xsl that skips the stubbing for the specific pipe. The downside of setting stub4testtool.configuration to false is that it disables stubbing for the entire configuration, which might result in other Pipes/Senders/Listeners also not being stubbed while they cannot work not stubbed (JMS-related Listeners and Senders for example) which might result in the logging being flooded with log messages as those are tried to be started every few seconds, while a custom stub4testtool.xsl is not easily toggled as it requires a full reload and is easily missed during upgrades.

I would like to see an additional attribute `disableStubbing` that can be used to disable stubbing on the entire element and its children if set to true (otherwise follow current behavior). Default of course false, and empty values should not give errors/warnings.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
Can you please implement this in your stub4testtool.xsl?
