### ISSUE TITLE
Create variable forwards for localsenders/subadapters

### ISSUE THREAD

**Issue by BonnoSmeele** [ibissource/iaf#2398]
I would like to see a feature implemented where i can define my own exits for subadapters
This would allow me to direct messages in the main adapter from a subadapter without having to duplicate directing logic in the main adapter.  I want top be able to define forwards on localsenders and call these forwards by using ht exits in the subadapter.

Best shown by example i think.

Sender in mainadapter:

			<SenderPipe name="CallGetCase"
				storeResultInSessionKey="GetCaseOutput">				
				<IbisLocalSender 
					name="GetCaseSender"
					javaListener="GetCaseListener">
				</IbisLocalSender>
				<Forward name="success" 	path="RemoveEmptyTags" />
				<Forward name="exception"   path="BackEndError" />
				<Forward name="returntomainadapterok"                       path="continueadapter"/>
                                <Forward name="returntomainadapterfunctionalerror"   path="gotoerrorhandling"/>
			</SenderPipe>

Pipe in subadapter:
			<XmlSwitchPipe name="pipe1"
				styleSheetName="SwitchResultCode.xsl">
				<Forward name="returntomainadapterok"                       path="returntomainadapterok"/>
                                <Forward name="returntomainadapterfunctionalerror"   path="returntomainadapterfunctionalerror"/>
				<Forward name="doX" 		                                           path="doX"/>
				<Forward name="checksomemorelogic"                          path="checksomemorelogic"/>
			</XmlSwitchPipe>

forwards in subadapter:

			<Exit path="returntomainadapterok" 	                 state="success"  />
                        <Exit path="returntomainadapterfunctionalerror"  state="success"  />
                        <Exit path="EXIT" 			                                 state="success"/>
			<Exit path="BackEndError" 	state="error" 	/>
			<Exit path="Timeout"      	state="error"    />
		</Pipeline>
	</Adapter>
</Module>

The subadapters directs results by directly choosing the exit in the subadapter with the corresponding forwardpipe in the mainadapter. i don't have to duplicate data to the main adapter and i dont have to recheck results this way.

**Reporter**
Bonno Smeele

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
This functionality is already present. It makes use of the code-attribute as the name of the forward.
See https://github.com/ibissource/iaf/blob/master/test/src/main/configurations/MainConfig/ConfigurationForwardNameProvidingSenders.xml
