### ISSUE TITLE
Ladybug report keeps in progress while adapter is finished (7.6)

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2439]
**Describe the issue**
The Ladybug does not close its report and keeps it in progress, even when the adapter is already finished. Issue is present in 7.6, is not present in 7.7-20211110.163854. Might be that Ladybug needs to be updated.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.6: ibis4solife
Running on srtzzapp0445 using IBM WebSphere Application Server/9.0.5.7
Java Version: Java(TM) SE Runtime Environment (8.0.6.26 - pxa6480sr6fp26-20210216_01(SR6 FP26))
Heap size: 932M, total JVM memory: 1021M
Free disk space: 692MB, total disk space: 2GB
Up since: 2021-11-22 14:32:45 (7d) 
```

Ladybug is version 2.2-20211120.230828, but also occurred with the version natively included in 7.6. Version 2.2-20211120.230828 is used at the request of Jaco to check if it solved the issue. Issue was not solved with that version, but did show `Waiting for thread 'X' to start...` on XsltPipes and ForEachChildElementPipes.

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by ricardovh** [comment]
This ibis uses a custom springIbisTestTool as a result of #1986, see attached file:
[springIbisTestTool.txt](https://github.com/ibissource/iaf/files/7537140/springIbisTestTool.txt)

**Comment by jacodg** [comment]
I don't think this will have effect on this issue. But good to know, thanks for sharing.

**Comment by jacodg** [comment]
Ricardo tested adding latest Ladybug version to the pom.xml of a Frank with F!F 7.6. Now we still see reports in progress but when opening such a report you will see red arrows after doing Expand all. Those arrows all have "Waiting for thread 'X' to start...". I suppose we need to backport the cancel thread also to 7.6 for the latest Ladybug version to work with 7.6. Current 7.6 is using Ladybug 2.1 which doesn't include a number of fixes related to reports not being closed (see also https://github.com/ibissource/ibis-ladybug/blob/master/RELEASES.md)

**Comment by gvanbrakel** [comment]
Could you provide a configuration to test this problem?

**Comment by gvanbrakel** [comment]
It is hard to reproduce the problem locally, as the 2.2-20211120.230828 ladybug changes do not match the current interface used in the 7.6 branch
