### ISSUE TITLE
Frank!Console is jeopardized when you go to Larva

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#2453]
**Describe the issue**
The Frank!Console is jeopardized when you go to Larva. The main menu is duplicated as shown:

![image](https://user-images.githubusercontent.com/6784732/141971562-33a95820-d2de-4b12-96a4-b4d53397b3fe.png)

**Reporter**
Martijn Dirkse

**To Reproduce**
1. Browse to https://frank4example.frankframework.org
2. Click on "Testing" and "Larva". The main menu may duplicate already when you click "Testing". In that case, you may have to click "Larva" in the duplicate.

**Comment by nielsm5** [comment]
And that's exactly why it's still in beta...
