### ISSUE TITLE
Pipes give invalid "has forward [*] which is already registered" warning (7.6)

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2487]
**Describe the issue**
I think related to #1778, but for 7.6, pipes suddenly give warnings that they have forwards which are already registered. Restarting the ibis removes those warnings, but they do return after some time. Backport #1775 to 7.6?

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.6.1: *** 44-c9a87310
Running on *** using IBM WebSphere Application Server/9.0.5.7
Java Version: Java(TM) SE Runtime Environment (8.0.6.26 - pxa6480sr6fp26-20210216_01(SR6 FP26))
Heap size: 290M, total JVM memory: 377M
Free disk space: 1GB, total disk space: 2GB
Up since: 2021-11-11 15:49:23 (13d) 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Do you have any global forwards by any chance?

**Comment by ricardovh** [comment]
> Do you have any global forwards by any chance?

Yes, I have one, but the warnings are for other configurations entirely.

**Comment by jjansenvr** [comment]
Ricardo, any chance you could reproduce this on a local environment?

**Comment by ricardovh** [comment]
> Ricardo, any chance you could reproduce this on a local environment?

Not really, as I never get those warnings on my local environment and I don't really have an idea what triggers it.

**Comment by ricardovh** [comment]
> > Ricardo, any chance you could reproduce this on a local environment?
> 
> Not really, as I never get those warnings on my local environment and I don't really have an idea what triggers it.

It may have something to do with pipes failing to be configured, but I cannot say that for sure as the issue is not always triggered.

**Comment by ricardovh** [comment]
I have not seen this on 7.7 and this is not an issue that blocks the application, I no longer see a need for fixing.
