### ISSUE TITLE
Opening custom view in new tab/window redirects to adapter status page

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2495]
**Describe the issue**
When opening a custom view in a new window, the page is redirected to the Adapter status page

**Reporter**
Ricardo

**To Reproduce**
1. Go to https://ibis4example.ibissource.org/iaf/gui/#!/status
2. Right-click on 'Custom View' and open link in new tab/window or copy it and browse to it directly
3. Get redirected to adapter status page

Note: This is not only on ibis4example site, also happens when running it in Docker locally and on other instances that have a custom view.

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jjansenvr** [comment]
It is not supported in the frank console. To open a page in a new window we will have to redesign the way the console works
