### ISSUE TITLE
Ladybug throws ClassCastException nl.nn.adapterframework.stream.Message incompatible with java.lang.String (7.6.1)

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2554]
**❗ please do not add sensitive infomation in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Ladybug throws the following exception when processing a message:
`nl.nn.adapterframework.core.PipeRunException: Pipe [GetPolicyDetails: send request] msgId [ID:EMS_TST_ESB_P2P_SMALL.2110618E49DC20B8AC:87] caught exception: (ClassCastException) nl.nn.adapterframework.stream.Message incompatible with java.lang.String`

Disabling Ladybug allows the message to be processed correctly. I'm not able to check if this also occurs with 7.6.2, as I cannot upgrade the environment at this moment.

**Reporter**
Please state your name. If we don't know who is reporting, a solution of the issue might be delayed.

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.6.1
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
This appears to be a problem that is in the 7.6 as well as in the 7.7 release. It will be fixed in 7.6.2 and in the master branch (7.7)
