### ISSUE TITLE
Ladybug in Ibis4Example not loading properly (Docker related)

### ISSUE THREAD

**Issue by Burrowfield** [ibissource/iaf#2566]
**Describe the issue**
Ladybug does not load in Ibis4Example. According to Niels this has to do with the docker deployment.

**Reporter**
Daniel Langeveld

**To Reproduce**
1. Go to: https://frank4example.frankframework.org/iaf/gui/#!/testing/ladybug
2. Observe

**Screenshots**
![image](https://user-images.githubusercontent.com/1859214/147127422-85e074ab-b7fa-485c-966c-5dbefccdf949.png)

**Environment**
FF! 7.7-20211222.121243: Ibis4Example
Running on 5e7f472cb95a using Apache Tomcat/8.5.60
Java Version: OpenJDK Runtime Environment (1.8.0_275-b01)
Heap size: 314M, total JVM memory: 1768M
Free disk space: 5GB, total disk space: 50GB
Up since: 2021-12-22 15:59:00 (1h)

**Additional Context**
Ladybug report

**Comment by gvanbrakel** [comment]
issue appears to be caused by removal of context root by reverse proxy

**Comment by nielsm5** [comment]
This has been fixed ;)
