### ISSUE TITLE
Upgrade H2 test-dependency

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#2574]
**❗ please do not add sensitive infomation in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The H2 version that is used as a test-dependency in the framework contains a vulnerability. Upgrading to the latest version runs into a liquibase problem. When 'liquibase.dropAll()' is executed this fails with the message:
```
liquibase.exception.DatabaseException: liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CONSTRAINTS" not found; SQL statement:
select CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME from information_schema.constraints where constraint_schema='PUBLIC' and constraint_catalog='TEST' and constraint_type='UNIQUE' and table_name='DATABASECHANGELOGLOCK' [42102-204]
	at liquibase.Liquibase.dropAll(Liquibase.java:1833)
```

**Reporter**
Gerrit

**To Reproduce**
1. Go to iaf project
2. Run jdbc unit-tests

**Environment**
```
FF! 7.7-SNAPSHOT: Ibis4Test
Running on LPZWNL000040524 using Apache Tomcat/9.0.43
Java Version: OpenJDK Runtime Environment (1.8.0_312-b07)
Heap size: 413M, total JVM memory: 492M
Free disk space: 229GB, total disk space: 476GB
Up since: 2021-12-24 16:13:25 (1m)
```

**Additional Environment**
 - DBMS: H2
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Comment by nielsm5** [comment]
We have to wait till Liquibase releases a new version which contains: https://github.com/liquibase/liquibase/issues/2278

**Comment by nielsm5** [comment]
Still contains https://github.com/liquibase/liquibase/issues/2309
