### ISSUE TITLE
Add Frank!Flow namespace to Frank!Config xsd

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#2587]
**Describe the issue**
The Frank!Flow wants to add certain information to Frank configurations like the x and y positions of elements in a Flow diagram. We would like to add that information to the configuration xml using a separate namespace for the Frank!Flow. And be able to start a Frank configuration with attributes like flow:x and flow:y without having warnings or errors in the Frank console when running this configuration in a Frank.

**Reporter**
Jaco de Groot

**Comment by philipsens** [comment]
This extends to the settings for the flow generation. These settings can be placed in the root configuration tag and look something like this:
```xml
<Configuration 
    flow:direction="vertical"
    flow:forwardStyle="flowchart"
    flow:gridSize="50"
    >
```

**Comment by gvanbrakel** [comment]
Situation/assumptions:
- There is a schema 'FrankConfig.xsd', that describes the structure of Frank configuration files
- There is a schema 'FrankFlow.xsd', that describes the attributes that are used by the Frank!Flow
- FrankConfig.xsd does not define a target namespace
- FrankFlow.xsd does define a target namespace, that is for now assumed to be "urn:frank-flow"

Solution:
- import the FrankFlow.xsd in the FrankConfig.xsd, i.e. put on the second line:
    `<xs:import namespace="urn:frank-flow" schemaLocation="FrankFlow.xsd" />`
- create a namespace prefix 'flow:' in the FrankConfig.xsd by adding to the root element:
     `xmlns:flow="urn:frank-flow"`
- add to each root element definition the FrankFlow header attribute group:
      `<xs:attributeGroup ref="flow:FrankFlowHeader"/>`
- add to each sub element definition the FrankFlow content attribute group:
      `<xs:attributeGroup ref="flow:FrankFlowContent"/>`

- in a projects Configuration.xml, add to the root element: 
      `xsi:noNamespaceSchemaLocation="frankconfig-strict.xsd" xmlns:flow="urn:frank-flow"`
- add any header attributes to the root element. The configuration element may look like:
```
	<Configuration 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="frankconfig-strict.xsd" 
		xmlns:flow="urn:frank-flow" 
		flow:direction="vertical"
	>
```
- add any FrankFlow coordinates to elements with the flow: prefix, like:
      `<Adapter flow:x="1" flow:y="1">`


The FrankFlow.xsd can be maintained by the Frank!Flow team, following the template:
```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified" targetNamespace="urn:frank-flow">
	<xs:attributeGroup name="FrankFlowHeader">
		<!-- content of attribute group to be determined by Frank!Flow team -->
		<xs:attribute name="direction">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="vertical"/>
					<xs:enumeration value="horizontal"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="forwardStyle"/>
		<xs:attribute name="gridSize" type="xs:integer"/>
	</xs:attributeGroup>
	<xs:attributeGroup name="FrankFlowContent">
		<!-- content of attribute group to be determined by Frank!Flow team -->
		<xs:attribute name="x" type="xs:integer"/>
		<xs:attribute name="y" type="xs:integer"/>
	</xs:attributeGroup>
</xs:schema>
```

**Comment by gvanbrakel** [comment]
Disscussed with Niels, Decided on first steps
1) avoid warnings in console
2) extend FrankConfig-strict.xsd with namespace only, no FrankDoc schema, place anyAttribute on all configurable elements

**Comment by gvanbrakel** [comment]
Issue has been implemented in https://github.com/ibissource/frank-doc/pull/65
