### ISSUE TITLE
Non breaking space in a configuration results in a validation failure

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#2588]
**Describe the issue**
Having a non breaking space (c2a0 in hex) causes the xsd validation fail. 

**Reporter**
Laura/Ali

line 28 has some non breaking spaces 
[ConfigurationHelloBeautifulWorld.txt](https://github.com/ibissource/iaf/files/7802818/ConfigurationHelloBeautifulWorld.txt)

![image](https://user-images.githubusercontent.com/10929856/147952061-fb97e23c-baf9-4adf-a38e-0752da3ad8c8.png)

**Comment by gvanbrakel** [comment]
For now we are not going to address this. Solution is to remove the non-breaking spaces

**Comment by nielsm5** [comment]
Just to elaborate this a bit, you seem to be having `windows-1252` encoded characters in your file. 
If you want to parse the file as is, you will need to specify the encoding used in the file.

XML defaults to UTF-8, which is why this doesn't work.
Adding the following header will fix this:
`<?xml version="1.0" encoding="windows-1252" standalone="yes" ?>`

The best option is to not deviate from the XML standard and only use UTF-8 characters.

**Comment by laura-dimitra** [comment]
Thanks all! I removed the non-breaking spaces and this solved the problem.

The suggestion adding the header I tried as well, this caused another error: 

Configuration [xxx] - error during unmarshalling configuration from file [Configuration.xml] with digester-rules-file [digester-rules.xml] in element []: (SAXParseException) SystemId [classpath:./xxx.xml] line [1] column [61]: No more pseudo attributes are allowed.

**Comment by nielsm5** [comment]
It basically means there's already a header defined and you're trying to add a 2nd header (eq. when you're including a file).

**Comment by laura-dimitra** [comment]
Maybe there's already a header included by the framework. My configuration starts with the adapter element (not with another header)

**Comment by nielsm5** [comment]
A configuration has to start with the `configuration` element. If you start with an `adapter` element, I'm assuming you're including the file (with the `adapter` element) in different file such as `Configuration.xml` which contains the `configuration` element?

**Comment by laura-dimitra** [comment]
yes, correct

**Comment by nielsm5** [comment]
Then that file defines the encoding (for all included files as well). The previously mentioned error about pseudo attributes basically means that you're not allowed to change 'metadata' anymore as data has already been read.

In this case the configuration element (amongst possible other elements) has already been read. Therefor you cannot change the encoding that has to be used to read the file anymore.

I hope this answers your questions!

**Comment by laura-dimitra** [comment]
Yes, it does and I learned new things as well. Thanks a lot!
