### ISSUE TITLE
IAF-Test fails with MSSQL IDENTITY INSERT

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2601]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When running the IAF-Test project in combination with MSSQL, multiple testcases fail on the insertions done on the IBISTEMP table, as it attempts to insert a value in the TKEY column which is an identity column. This triggers the following exception, causing those testcases to fail:
`got exception executing query [INSERT INTO IBISTEMP (TKEY, TCHAR, TBLOB1) VALUES (NEXT VALUE FOR SEQ_IBISTEMP, 'B', 0x)]: (SQLServerException) SQLState [S0001], errorCode [544]: Cannot insert explicit value for identity column in table 'IBISTEMP' when IDENTITY_INSERT is set to OFF.`

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by alisihab** [comment]
It seems that liquibase upgrade is the cause of this issue. Table definition is changed from -CREATE TABLE [dbo].[IBISTEMP] ([TKEY] INT NOT NULL- to -CREATE TABLE IBISTEMP (TKEY int IDENTITY (1, 1) NOT NULL- with the upgrade.
