### ISSUE TITLE
Support for Multi Factor Authentication

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#2627]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
For some situations, there is a requirement that Multi Factor Authentication (MFA) must be used to authenticate to the console.
Currently, this conflicts with the requirement to be able to use Basic Authentication to authenticate for Webservices.
- Enforcing MFA to the console causes MFA enforcement for Webservices too
- allowing Basic Authentication for Webservices opens the possibility to a scenario of authenticating using Basic Authentication to a Webservice, and using the LtpaToken returned to access the console (without MFA being enforced then)

Possible solutions could be:
- running Webservices on a diffferent context as the console
- avoiding the returning of LtpaTokens for Basic Authentication logins

**Reporter**
Gerrit

**Comment by nielsm5** [comment]
Duplicate of #2294
