### ISSUE TITLE
NarayanaTS no longer working

### ISSUE THREAD

**Issue by nielsm5** [ibissource/iaf#2658]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
NarayanaTS is no longer working. Appears to be with all databases, btm is working fine, though practically the same setup is used. 

**Reporter**
Ricardo

**Comment by ricardovh** [comment]
[mysql.zip](https://github.com/ibissource/iaf/files/7912798/mysql.zip)
[mariadb.zip](https://github.com/ibissource/iaf/files/7912890/mariadb.zip)

**Comment by nielsm5** [comment]
Seems to be partially introduced by https://github.com/ibissource/iaf/pull/2508.
