### ISSUE TITLE
JmsSender within JmsListener causes fatal error

### ISSUE THREAD

**Issue by woutervdschoot** [ibissource/iaf#2673]
**Describe the issue**
When a JmsSender is placed within a JmsListener, the stubbing tool will comment them both out resulting in a comment within a comment. This causes a fatal error: the string "--" is not permitted within comments.

**Reporter**
Wouter van der Schoot

**Configuration**
Please provide the configuration of the Pipe or Receiver with the problem.

	<module>
		<adapter name="demo adapter">
			<receiver name="demo receiver">
				<listener className="nl.nn.adapterframework.jms.JmsListener"
					destinationName="demo.queue"
					lookupDestination="false"
					jmsRealm="qcf_tibco_p2p_rr">
					<sender 
						name="demo sender"
						className="nl.nn.adapterframework.jms.JmsSender"
						destinationName="demo.queue2"
						lookupDestination="false"
						deliveryMode="NON_PERSISTENT" 
						jmsRealm="qcf_tibco_p2p_rr" />
				</listener>
			</receiver>
			<pipeline firstPipe="exit"> 
				<exits>
					<exit path="EXIT" state="success"/>			
				</exits>
			        <pipe name="exit"
				        className="nl.nn.adapterframework.pipes.EchoPipe">
				        <forward name="success" path="EXIT"/>
			        </pipe>
		    </pipeline>
	    </adapter>
    </module>

**Comment by gvanbrakel** [comment]
Does the same problem occur in 7.7? Could you provide a PR for 7.7 too in that case?

**Comment by ricardovh** [comment]
In 7.7 it was already fixed with PR #1902.
