### ISSUE TITLE
wrappers and validators without name lead to warnings in the console

### ISSUE THREAD

**Issue by BonnoSmeele** [ibissource/iaf#2687]
**Describe the issue**
After upgrading the framework to the latest version warnings appear for all wrappers and validators in the console.

Attribute name is now mandatory on pipes, apparently this includes wrappers and validators.

**Reporter**
Bonno Smeele

**To Reproduce**
use a validator/wrapper without name attribute, look at console

**Screenshots**
![image](https://user-images.githubusercontent.com/73215587/151366886-f7a4c522-acfc-47ff-8e55-db2a0bd4851e.png)

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```
			<Json2XmlInputValidator 
				schemaLocation="urn:items /GetArrearsOnBP/xsd/GetArrearsOnBP.xsd" 
				root="parameters" 
				responseRoot="Result"
				name="validator">
				<Param name="Id"			sessionKey="Id"/>
				<Param name="Postalcode"	sessionKey="Postalcode"/>
				<Param name="HouseNumber"	sessionKey="HouseNumber"/>
				<Forward name="failure" 	  path="CreateValidatorErrorReply"/>
				<Forward name="outputFailure" path="CreateServerErrorReply"/>
			</Json2XmlInputValidator>

**Input**
```
NA
```

**Environment**
```
FF! 7.7-20220125.112844: ibis4salesforce
Running on LPZWNL000013838 using Apache Tomcat/9.0.56
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 402M, total JVM memory: 698M
Free disk space: 5GB, total disk space: 237GB
Up since: 2022-01-27 14:04:33 (16m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
I would like to suggest the following solution:
- create an javadoc or java 5 annotation 'ff.optional'. 
- Let the Frank!Doc process the ff.optional annotation by disabling the effect of a ff.mandatory annotation.
- the ff.optional attribute would then be set on `setName()` of  interfaces IValidator and IWrapperPipe
