### ISSUE TITLE
Timestamp filter in errorstore does not work correctly

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#2692]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The timestamp filter option does not work correctly
- if you put in a date only it does not select all records for this date 
- if you put in a complete timestamp it does not filter

in the old blue 

**Reporter**
JJansenvr

**To Reproduce**
1. Go to an adapter with a error or message store 
2. Click on Display Filters
3. Scroll down to fill out the timestamp filter field
4. See no (or no correct) filtering in the list

**Screenshots**

**Configuration**
```
na
```

**Input**
```
na
```

**Environment**
```


FF! 7.6: ibis4-----
Running on srtapp0000 using IBM WebSphere Application Server/9.0.5.7
Java Version: Java(TM) SE Runtime Environment (8.0.6.26 - pxa6480sr6fp26-20210216_01(SR6 FP26))
Heap size: 839M, total JVM memory: 1240M
Free disk space: 466MB, total disk space: 2GB
Up since: 2022-01-13 10:14:49 (14d)

```

**Additional Environment**
 - Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production Version 19.13.0.0.0] driver [Oracle JDBC driver] driver version [18.3.0.0.0]

 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**

**Comment by jjansenvr** [comment]
Workaround: the date or timestamp in the input field is used in a  > way so if you want to find records from the date 2022-01-07 use 2022-01-06 23:59 and you will be able to find the records

**Comment by gvanbrakel** [comment]
This it indeed the way it is implemented

**Comment by nielsm5** [comment]
- [ ] codebase pipe messagelog uses a different codebase then receiver error/messagestore
- [ ] fix the display columns
- [ ] total message count
- [ ] add `end timestamp` field
- [ ] add delay to search while typing (add debounce)
