### ISSUE TITLE
Attribute must appear on element 'MessageStoreListener' warning for several attributes with default values

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#2710]
**Describe the issue**
When you start Frank2Example3 (https://github.com/ibissource/frank-runner#frank2example3) with the Frank!Runner the console shows:

 Configuration [Example3] - Validation error in [classpath:Configuration.xml] at line [56] when validating against schema [/xml/xsd/FrankConfig-compatibility.xsd]: cvc-complex-type.4: Attribute 'tableName' must appear on element 'MessageStoreListener'.
Configuration [Example3] - Validation error in [classpath:Configuration.xml] at line [56] when validating against schema [/xml/xsd/FrankConfig-compatibility.xsd]: cvc-complex-type.4: Attribute 'statusField' must appear on element 'MessageStoreListener'.
Configuration [Example3] - Validation error in [classpath:Configuration.xml] at line [56] when validating against schema [/xml/xsd/FrankConfig-compatibility.xsd]: cvc-complex-type.4: Attribute 'statusValueError' must appear on element 'MessageStoreListener'.
Configuration [Example3] - Validation error in [classpath:Configuration.xml] at line [56] when validating against schema [/xml/xsd/FrankConfig-compatibility.xsd]: cvc-complex-type.4: Attribute 'statusValueProcessed' must appear on element 'MessageStoreListener'.

While the Frank!Doc says:

The following defaults apply: 
tableName | IBISSTORE
keyField | MESSAGEKEY
messageField | MESSAGE
messageFieldType | BLOB
blobSmartGet | true
statusField | TYPE
timestampField | MESSAGEDATE
commentField | COMMENTS
statusValueAvailable | M
statusValueProcessed | A
statusValueError | E

**Reporter**
Jaco de Groot

**To Reproduce**
1. Start Frank2Example3
2. Go to the Frank!Console
3. See warnings

**Screenshots**
\-

**Configuration**
https://github.com/ibissource/frank-runner/blob/master/examples/Frank2Example3/configurations/Example3/Configuration.xml

**Input**
\-

**Environment**
```
FF! 7.7-20220202.144505: Frank2Example3
Running on xxx using Apache Tomcat/7.0.103
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 292M, total JVM memory: 528M
Free disk space: 166GB, total disk space: 475GB
Up since: 2022-02-03 18:22:47 (9m) 
```

**Additional Environment**
\-

**Additional Context**
\-

**Comment by gvanbrakel** [comment]
Warning is caused by mandatory setting in parent class, while this class has default values.
It is probably enough to override setters including javadoc with @ff.default. 
It would be nice to be able to set the default without having to override the documentation text.
