### ISSUE TITLE
Possible backward compatibility issue - exit state "FAILURE" has become "ERROR"

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#2723]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
In the Frank!Manual Getting Started section, there was a configuration that used exit state "failure". When I wrote that text, I was keen to test the configurations I listed. Nevertheless, I saw a warning today when I loaded the configuration. The warning was: "Configuration [NewHorizons] - Validation error in [classpath:ConfigurationIngestBooking.xml] at line [14] when validating against schema [/xml/xsd/FrankConfig-compatibility.xsd]: cvc-datatype-valid.1.2.3: 'failure' is not a valid value of union type '#AnonType_stateExit'.".

This issue is not about fixing the Frank!Manual - I am happy to replace "failure" by "ERROR". The issue is that there may be other old configurations that use "failure". These old configurations may not work anymore with the newest version of the F!F, for example 7.7-20220202.144505.

I can think of the following options to handle this situation:
* Do nothing. Frank developers will be prompted by the warning.
* Improve the warning to tell that "failure" can be replaced by "ERROR". This can be implemented by adding enum value "FAILURE" to Java enum PipeLine.ExitState. This enum value should get a @Deprecated annotation. The code should be updated to replace FAILURE by ERROR.
* Document in the Q&A section of the Frank!Manual that "failure" should be replaced by "ERROR".
* Document in the Teams group "Frank!Framework support" that "failure" should be replaced by "ERROR". @gvanbrakel, in our phone call you said this was not a good idea.

**Reporter**
Martijn Dirkse

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
I suggest that when it appears to become a problem, we document it in the release notes
