### ISSUE TITLE
Result of XsltPipe is changed in 7.7 RC1

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#2747]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
In production we are running `FF! 7.7-20210525.083818` and we are currently working on upgrading to 7.7 RC1 / 7.8 snapshot to test the fix for the multipart issue.

During testing we noticed that the result of a XSLT transformation is different than on production whilst the configuration of the pipe is exactly the same.

The issue is with the two parameters indicating which characters should be replaced.

Production:
![image](https://user-images.githubusercontent.com/37303445/153578629-d060d3f3-4292-4ac5-a69d-e23e637064ff.png)
![image](https://user-images.githubusercontent.com/37303445/153578785-ab6ed06e-2601-42ab-8146-fe2e640b22cc.png)
![image](https://user-images.githubusercontent.com/37303445/153579009-821e620c-074f-4cfb-b4fa-8c33f1d1a58f.png)
![image](https://user-images.githubusercontent.com/37303445/153578668-b8ce0bb1-dcdb-47f3-b5f4-3911d1ccb4a3.png)

TST:
![image](https://user-images.githubusercontent.com/37303445/153578732-aaf8a00f-9d82-4c9c-b0ab-ae3f451fd36a.png)
![image](https://user-images.githubusercontent.com/37303445/153578904-dc69521e-1369-48db-ac53-98b172eef208.png)
![image](https://user-images.githubusercontent.com/37303445/153578934-88735310-9b50-4bc6-8b92-c262288bdc84.png)
![image](https://user-images.githubusercontent.com/37303445/153578753-c65f83d8-458e-44fb-904b-c3b68103f47a.png)

**Reporter**
Laurens

**To Reproduce**

Please contact me for the specific XSLT.

**Screenshots**

**Configuration**
```
<pipe className="nl.nn.adapterframework.pipes.XsltPipe" getInputFromFixedValue="&lt;dummy/&gt;" name="Limit_Document_Name_Length" storeResultInSessionKey="DOCUMENT_NAME" styleSheetName="Staging_POST/xsl/LimitDocumentNameLength.xsl">
	<param name="documentName" sessionKey="DOCUMENT_NAME"/>
	<param name="replaceCharacters" value="/:*?&quot;&lt;&gt;|"/>
	<param name="replaceCharactersHyphen" value="–"/>
	<forward name="success" path="Check_If_Should_Apply_Conversion"/>
</pipe>
```

**Environment**
```
FF! 7.8-20220210.122642: XXXX
Running on XXXX using IBM WebSphere Application Server/9.0.5.7
Java Version: Java(TM) SE Runtime Environment (8.0.6.26 - pxa6480sr6fp26-20210216_01(SR6 FP26))
Heap size: 1505M, total JVM memory: 2048M
Free disk space: 1GB, total disk space: 2GB
Up since: 2022-02-11 11:22:50 (31m) 
```

**Comment by gvanbrakel** [comment]
Could you provide copy-pastable versions of input, output and xslt?

**Comment by Laurens-makel** [comment]
```
<pipe className="nl.nn.adapterframework.pipes.XsltPipe" getInputFromFixedValue="&lt;dummy/&gt;" name="Limit_Document_Name_Length" storeResultInSessionKey="DOCUMENT_NAME" styleSheetName="Staging_POST/xsl/LimitDocumentNameLength.xsl">
	<param name="documentName" sessionKey="DOCUMENT_NAME"/>
	<param name="replaceCharacters" value="/:*?&quot;&lt;&gt;|"/>
	<param name="replaceCharactersHyphen" value="–"/>
	<forward name="success" path="Check_If_Should_Apply_Conversion"/>
</pipe>
```

documentName `proof.png`
replaceCharacters PRD `/:*?"<>|`
replaceCharacters TST `/:*?&quot;&lt;&gt;|`
replaceCharactersHyphen PRD `–`
replaceCharactersHyphen TST `&#8211;`

```
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="text" indent="yes" omit-xml-declaration="yes"/>

	<xsl:param name="documentName"/>
	<xsl:param name="replaceCharacters"/>
	<xsl:param name="replaceCharactersHyphen"/>

	<xsl:template match="/">
	  	<xsl:variable name="extension" select="'.pdf'"/>

		<xsl:variable name="document" select="translate(translate($documentName, $replaceCharactersHyphen, '-'), $replaceCharacters, '')"/>
		<xsl:choose>
			<xsl:when test="string-length($document) &gt; 97"><xsl:value-of select="concat( substring($document, 1, 97),  $extension)"/></xsl:when>
			<xsl:when test="string-length($document) &lt; 100 and contains($document, $extension)"><xsl:value-of select="$document"/></xsl:when>
			<xsl:otherwise><xsl:value-of select="concat($document, $extension)"/></xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	
</xsl:stylesheet>
```

output TST `prf.pn.pdf`
output PRD `proof.png.pdf`
