### ISSUE TITLE
Escaping < is broken, 7.7-RC1

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#2749]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
We have a SQL statement in a property. This SQL contains a `<` character, which had to be escaped to `&lt;` in the previous FF versions.
But when we execute the adapter now with 7.7-RC1, an exception is thrown because the `&lt;` is not recognized: 

nl.nn.adapterframework.core.SenderException: [nl.nn.adapterframework.jdbc.FixedQuerySender] [resetErrorRecords] cannot getQueryExecutionContext: (JdbcSQLException) SQLState [42000], errorCode [42000]: 
Syntax error in SQL statement "UPDATE table SET column = '' WHERE column [*] `&LT;` ? 
; SQL statement:

When I change the property from `&lt;` to the `<` character, the adapter will fail as well:

Could not parse configuration: (SAXParseException) line [67] column [317]: The value of attribute "query" associated with an element type "sender" must not contain the '`<`' character.

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**

**Configuration**
                `<FixedQuerySender
                        name="doSomething"
                        datasourceName="abc"
                        query="${abc.sql}"
                >
                    <Param name="value" value="${someValue}"/>
                </FixedQuerySender>
`
**Input**

**Environment**
7.7 RC1

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**

**Comment by gvanbrakel** [comment]
It appears to me that you used `&LT;` instead of `&lt;`

**Comment by Laurens-makel** [comment]
![image](https://user-images.githubusercontent.com/37303445/153630524-8890f626-5d3c-4dcf-b448-dc0c98e624ed.png)

Same happens to me, in the SQL error message everything appears in upper case although it is actually specified in lower case:
![image](https://user-images.githubusercontent.com/37303445/153630642-362baecd-940c-46f7-b39d-0aa828d259f6.png)

**Comment by gvanbrakel** [comment]
Observation:
I did a test and this works:
`<FixedQuerySender query="SELECT * FROM IBISTEMP WHERE TKEY &lt; ?" queryType="SELECT">`
This works too:
`<FixedQuerySender query="${dynamicQuery}" queryType="SELECT">`, with in a .properties file
`dynamicQuery=SELECT * FROM IBISTEMP WHERE TKEY < ?`
Note that in 7.7 the resolution of `${}` constructs is done after parsing, so escaping is not necessary for the query defined in a property

**Comment by Laurens-makel** [comment]
Escaping in properties which are referenced within configurations in general is not needed anymore, not only for queries I assume?

This could explain the root cause of https://github.com/ibissource/iaf/issues/2747.

Although I would consider this as a breaking change which should be communicated in the release notes.

**Comment by Laurens-makel** [comment]
Confirmed that the query execution with < or > in property references works.

Although in Ladybug something seems wrong:
![image](https://user-images.githubusercontent.com/37303445/153644017-b0a532b1-3ede-456d-ba98-9b02c6a5409f.png)
