### ISSUE TITLE
InputValidator inside pipe doesn't change what the sender sends.

### ISSUE THREAD

**Issue by lenardvandermaas** [ibissource/iaf#2753]
When using an input validator that changes the message, such as an Json2XmlInputValidator, inside a pipe, it doesn't forward this message to the pipe. When using a SenderPipe with a Json2XmlInputValidator and a sender and you give it an json input message, the validator will validate the input and return the message in xml format, but the sender doesn't take this input, but rather the input of the pipe.

Lenard

1. Make an adapter with the following pipe:
`<SenderPipe name="SenderPipe">
	<Json2XmlInputValidator
		schema="validateInput.xsd">
		<Forward name="failure" path="OK"/>
	</Json2XmlInputValidator>
	<FixedResultSender name="Sender"
		returnString="test"/>
	<Forward name="success" path="OK"/>
</SenderPipe>`
and the following xsd:
`<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" >
	<xs:element name="test" type="xs:string"/>
</xs:schema>`
2. Start the frank
3. Go to 'test a pipeline' in the console
4. Test the pipeline with the following json:
`{"test":"test"}`
5. Go to ladybug and open the record of the pipeline
6. Check the input of the pipe, the output of the inputValidator, and the input of the sender. You will see the output of the inputValidator is correct, but the input of the sender is the same as the input of the pipe, which not the expected behavior.

This happens in 7.7-RC1 and I've seen it many times before in older versions

**Comment by jacodg** [comment]
As a workaround you can put a Json2XmlValidatorPipe just before the SenderPipe instead of the validator inside the SenderPipe
