### ISSUE TITLE
PdfPipe combine throws NPE without charset attribute

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2755]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The PdfPipe throws an NPE when the charset attribute is not set.

Configuration+reproduction scenario will be provided by mail.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.8-20220211.135739: ****, but also observed in 7.6.4.
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by alisihab** [comment]
this won't be backported to 7.6
