### ISSUE TITLE
FR: fileSessionKey as param on CmisSender

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#2758]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
We are using the CmisSender in an archiving adapter with an apilistener who consumes multiparts.
The fileSessionKey on the CmisSender is now a fixed value, for example: fileSessionKey="attachment".
Therefore the incoming file in the multipart **must** have the name "attachment".

We would like to have the fileSessionKey as a Param so we can specify the name of the sessionKey ourselves.

Now new users of this adapter are not aware of this name "attachment" which can lead to errors.
If they specify another name for the file part, this adapter will fail.

In the incoming sessionkey multipartAttachments we can see what the part name of the file is, for example : 

`<parts>
<part name="body" type="text" value="" />
<part name="file" type="file" filename="edge DL.pdf" size="58456" sessionKey="file" charSet="ISO-8859-1" mimeType="application/pdf" />
</parts>`

In this example we would like to use the name "file" as the sessionkey and pass this name "file" as a param to the cmisSender.

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**

**Configuration**

**Input**

**Environment**

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**

**Comment by nielsm5** [comment]
As mentioned before, this has been solved in https://github.com/ibissource/iaf/pull/2782
