### ISSUE TITLE
filter on payload of errorstore/message log not user friendly in new GUI

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#2762]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
In "old GUI"  has the possibility to filter/search on the content of the messages in the errorstore. there is no search field for message in the new GUI.
the requested functionality is to be able to filter messages on based on the existence of a certain string in the message 

UPDATE
we were testing with 7.6 and the extra field is added.
the functionality works but is not clear to the user
- If you open a message and push the back button the filter is cleared (also in other interaction the filter is cleared
- there is no obvious trigger moment to start the filtering (should be more clear how this works)
- the processing message is not in your screen, if you scroll down you see a message not similar to the other "progress bar" images
- the total numbers do not change based on the filtered documents (fixed in 7.4) 

as we cannot upgrade and want to investigate a production issue a work around would be appreciated

** if available please provide workaround via SQL statement **

**Reporter**
jjansenvr on behalve of Fop

**To Reproduce**
1. Go to an adapter with errostor or messagelog
2. open filter section
3. no message filed to do a filter on message content

**Screenshots**
![image](https://user-images.githubusercontent.com/3921911/154089329-a7e2b0c3-875f-47c1-9dbf-d0ba48fd264b.png)

**Configuration**
```
n/a
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
IAF 7.6.x 
```

**Additional Environment**
 - DBMS:  Oracle
 - 
**Additional Context**

**Comment by alisihab** [comment]
This feature is supposed to be introduced in 7.6.1-20210915.155501. Is the regarding ibis using an older version of the framework?

**Comment by jacodg** [comment]
Can you check the latest F!F version for user friendliness and when not user friendly enough suggest what would need to be done to make it user friendly enough?

**Comment by jjansenvr** [comment]
UPDATE
we were testing with 7.6 and the extra field is added.
the functionality works but is not clear to the user

If you open a message and push the back button the filter is cleared (also in other interaction the filter is cleared
there is no obvious trigger moment to start the filtering (should be more clear how this works)
the processing message is not in your screen, if you scroll down you see a message not similar to the other "progress bar" images
