### ISSUE TITLE
CmisSender exception: 0x001a is not a legal XML character.

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#2779]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
In Seal there are documents with metadata fields containing control characters, for example:
"Documentsoort_TVAR_4_40": "intern, GSF, grote schade \u001a 2,5 mio",

When retreiving this metadata the CmisSender gives an exception:
org.jdom2.IllegalDataException: The data "intern, GSF, grote schade      ¿#26;     2,5 mio" is not legal for a JDOM character content: 0x001a is not a legal XML character.

We would like to retrieve the metadata regardless of these control characters.

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/35798481/154653091-d3d4d807-29da-45ac-86e1-d736e1a78a95.png)

**Configuration**
See ladybug report send via mail to Niels Meijer.

**Input**
Ladybug report send via mail to Niels Meijer.

**Environment**
Production

**Additional Environment**
FF! 7.6.3

**Additional Context**
See email for complete stacktrace....

org.jdom2.IllegalDataException: The data "intern, GSF, grote schade      ¿#26;     2,5 mio" is not legal for a JDOM character content: 0x001a is not a legal XML character.
at org.jdom2.Text.setText(Text.java:182)
at org.jdom2.Text.<init>(Text.java:112)
at org.jdom2.Element.setText(Element.java:691)
at nl.nn.adapterframework.util.XmlBuilder.setValue(XmlBuilder.java:133)
at nl.nn.adapterframework.extensions.cmis.CmisUtils.getPropertyXml(CmisUtils.java:229)
at nl.nn.adapterframework.extensions.cmis.CmisSender.sendMessageForActionFind(CmisSender.java:701)

**Comment by nielsm5** [comment]
I suggest we phase out the `XmlBuilder` and replace it with the `SaxElementBuilder`.
