### ISSUE TITLE
Xerces 12.2 has been released

### ISSUE THREAD

**Issue by nielsm5** [ibissource/iaf#2784]
**Describe the issue**
A new version of Xerces has been released:
- XML 1.0 (4th Edition)
- Namespaces in XML 1.0 (2nd Edition)
- XML 1.1 (2nd Edition)
- Namespaces in XML 1.1 (2nd Edition)
- W3C XML Schema 1.0 (2nd Edition)
- W3C XML Schema 1.1
- W3C XML Schema Definition Language (XSD): Component Designators (Candidate Recommendation, January 2010)
- XInclude 1.0 (2nd Edition)
- OASIS XML Catalogs 1.1
- SAX 2.0.2
- DOM Level 3 Core, Load and Save
- DOM Level 2 Core, Events, Traversal and Range
- Element Traversal (org.w3c.dom.ElementTraversal)
- JAXP 1.4
- StAX 1.0 Event API (javax.xml.stream.events)

Must have is the removal of the java 11 `ElementTraversal` class (or any other fix)

**Comment by gvanbrakel** [comment]
New 'frankified' version has been made. To build the jars:
- check out branch '2_12_2-xml-schema-1_1' from repository 'https://github.com/ibissource/xerces2-j.git'
- run 'build jars'
- jar and pom can be found in /build/maven
