### ISSUE TITLE
xs:any in xsd does not work

### ISSUE THREAD

**Issue by lenardvandermaas** [ibissource/iaf#2792]
When using the xs:any element inside an xsd to validate any element at that position, the Json2XmlValidatorPipe gives an error like: 
`Validation using Json2XmlValidator with 'xsd.xsd' failed: /root/data: No typeDefinition found for element [exampleelementname] in namespace [] qName [exampleelementname]`

**Reporter**
Lenard

1. Make an adapter like this:
```
<Configuration>
	<Adapter name="Test">
		<Receiver name="Test">
			<JavaListener name="Test"/>
		</Receiver>

		<Pipeline firstPipe="dummy">

			<Json2XmlInputValidator
				outputFormat="json"
				schema="xsd.xsd">
				<Forward name="failure" path="ERROR"/>
			</Json2XmlInputValidator>

			<FixedResultPipe name="dummy" returnString="dummy">
				<Forward name="success" path="EXIT"/>
			</FixedResultPipe>

			<Exit path="EXIT" state="success"/>
			<Exit path="ERROR" state="error"/>
		</Pipeline>
	</Adapter>
</Configuration>
```
2. Create the following xsd in the same directory as the adapter
```
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" >
	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="data" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:any maxOccurs="unbounded" processContents="skip"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
```
3. Start the Frank, go to Test a Pipeline in the console, and run the pipeline with input:
```
<root>
	<data>
		<test1>test content 1</test1>
	</data>
</root>
```
4. check error in ladybug

expected result would be:
```
{
	"data":
	[
		{
			"test1":"test content 1"
		}
	]
}
```

This happens in framework version 7.7-RC1

**Comment by nielsm5** [comment]
When using the Json2XmlInputValidator, I assume you want to validate the json content and convert it to XML.
In your example you're not sending json but a simple string.
What is it that you expect the validator to do here?

**Comment by lenardvandermaas** [comment]
Due to wrong formatting the xml snippets didn't show correctly. Should be fixed now. I'm trying to validate xml and convert it to json.

**Comment by gvanbrakel** [comment]
The Json2XmlValidator cannot know from an xsd:any tag how to convert the input to json.

**Comment by gvanbrakel** [comment]
PR #2802 enables the use of anyAttribute, and provides an example of label-value
