### ISSUE TITLE
Jenkins does not run iaf-test larva tests on 7.7 branch

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#2817]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The Jenkins build server appears to start iaf-test for the 7.7 branch framework build, but it is unlikely all tests are run in a below 1 second total runtime.

**Reporter**
Gerrit

**To Reproduce**
1. Go to https://jenkins.interpar.nl/view/Voor%20scherm%20core%20developers/job/Frank-Framework/job/7.7-release/
2. See unreasonably low run times for iaf-test

**Comment by jjansenvr** [comment]
The tests are disabled because of storage and performance problems on the server, this will be picked up after the new server is installed
