### ISSUE TITLE
iaf-test cannnot connect to ActiveMQ without transaction manager on Tomcat

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2820]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When running iaf-test on a Tomcat server without transaction manager with ActiveMQ, using the images in https://github.com/ibissource/iaf/tree/master/docker, the JMS adapters are not started as it throws errors like
`javax.naming.NameNotFoundException: Name [jms/i4testiaf_in] is not bound in this Context. Unable to find [jms]`

When setting a transaction manager via the application.server.type.custom environment variable, the adapters do start properly and tests can be performed without issue. When adding the springJms.xml import to https://github.com/ibissource/iaf/blob/master/core/src/main/resources/springTOMCAT.xml, the adapters start, but this still has 20 failing tests.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jjansenvr** [comment]
JMS requires a XA transaction manager.
