### ISSUE TITLE
Feature request: firstPipe attribute on receiver level

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#2823]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
We have services containing logic which are exposed with the use of an ApiListener and functional authorisation is handled by a sub adapter. 

We want to re-use the logic in the exposed adapter internally by other adapters without the call to the authorisation service happening.

A solution could be to isolate the logic within another adapter and have the adapter exposed with an ApiListener make use of this sub adapter.

This works although this requires some work and its not very intuitive for new developers, a work around could be to specify the firstPipe attribute on the receiver element.

In case of messages coming from the ApiListener receiver, firstPipe = authorisation service, in case of messages coming from a JavaListener receiver, firstpipe = first pipe of logic.

This would be more intuitive, less adapters and less work to make the above example possible. This happens to multiple adapters in several project, where we have to explain to non technical people that these extra _LOCAL adapters are tricks to make it work/isolate logic.

**Reporter**
Laurens

**Comment by Laurens-makel** [comment]
Another approach could be analyze present session keys to determine over which listener the message came, although this is not a nice solution.

A solution could be to introduce a new session key which will always contain the classname of the listener that received a message, making it easier to skip certain pipes with ifParam and ifValue

**Comment by jacodg** [comment]
https://github.com/ibissource/iaf/issues/4065
