### ISSUE TITLE
PipelineProcessor skips 2nd pipe when there are 2 consecutive XsltPipes with streaming

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#2827]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
An application has a pipeline with two consecutive XsltPipes. Both XsltPipes use a stylesheet and have no further configuration. If the attribute storeResultInSessionKey is set in the second pipe the pipeline is processed as expected.(no streaming)
In case the the streaming is enabled (by not setting the attribute storeResultInSessionKey) the pipelineProcessor skips the 2nd pipe and returns the response of the first pipe.

**Reporter**
Laura/Ali

FF! 7.7

**Comment by gvanbrakel** [comment]
Appears to be related to 'disable-output-escaping="yes"'
