### ISSUE TITLE
Ibis4testiaf fails to install on WebSphere

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#2829]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Ibis4TestIaf fails to install on WebSphere at NN. Last version that could be installed was 7.8-20220210.122642, first that could not be installed was 7.8-20220211.135739.

**Reporter**
Bastiaan

**Environment**
```
WebSphere 8.5 / 9
```

**Comment by jjansenvr** [comment]
spring ibis testool needs schema #2772
