### ISSUE TITLE
Add an option to the HttpSender to take query params from the input message and remove this as default behavior

### ISSUE THREAD

**Issue by lenardvandermaas** [ibissource/iaf#2835]
Currently, when using an HttpSender with method set to either `GET`, `POST` or `PUT`, the input message is appended to the URL as query parameters. I'm of the opinion that this is unnecessarily accommodating and not worth the hassle when you don't want this behavior to happen. The only way to avoid the input being appended to the url is using the `urlParam` attribute, but this is not intuitive, nor is it documented anywhere.

I would instead like for this behavior to be removed as default, and that instead a new attribute like `getParamsFromInput` is added to the HttpSender that will be false by default.

Currently, when you want to send a `GET` request to a fixed endpoint without query parameters, the pipe would look like this:
```
<SenderPipe name="GetRequest">
	<HttpSender name="GetRequest"
		urlParam="urlParam">
		<Param name="urlParam" value="http://any.endpoint.com"/>
	</HttpSender>
	<Forward name="success" path="OK"/>
	<Forward name="failure" path="ServerError"/>
</SenderPipe>
```
When after this change, it could look like this:
```
<SenderPipe name="GetRequest">
	<HttpSender name="GetRequest"
		url="http://any.endpoint.com"/>
	<Forward name="success" path="OK"/>
	<Forward name="failure" path="ServerError"/>
</SenderPipe>
```
Simply using the attribute `getInputFromFixedValue=""` on the containing pipe doesn't work because this attribute is ignored if empty.

Another reason to advocate for this change is that constructing an input message that is in the exact format that is currently required by the HttpSender often takes much more effort than adding the wanted query parameters using parameters in the sender. Using parameters is also way more logical and understandable when looking at the configuration.

**Reporter**
Lenard

**Comment by Laurens-makel** [comment]
Another way to prevent appending query parameters is to make use of `getInputFromFixedValue=""` on the sender pipe.

**Comment by lenardvandermaas** [comment]
I mentioned in the issue that using `getInputFromFixedValue=""` doesn't work because this attribute is ignored if it is empty. I'm not really sure what you mean by the rest of your comment.
