### ISSUE TITLE
We would like to log payload or process data to the messages log

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#2861]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
For tracing and auditability we would like to be able to add data from the input message or process to the messages log

preferably the selection can be done per adapter with minimum adjustment to the co0nfiguration. in the current solution the code is "polluted" by all the code needed for this logging

**Reporter**
Bonno Smeele / jjansenvr

**Current workaround**
code example Can be found in ibis4salesforce Configuration_PatchClaim.xml

**Comment by BonnoSmeele** [comment]
Adapter Input can be JSON as well.
