### ISSUE TITLE
Dropdowns drop under element

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2871]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
![image](https://user-images.githubusercontent.com/57142353/158403139-365a9374-bbcb-4b47-8fc4-199a636bb246.png)

**Reporter**
Please state your name. If we don't know who is reporting, a solution of the issue might be delayed.

**To Reproduce**
1. Go to (https://frank4example.frankframework.org/iaf/gui/#!/logging/settings)
2. Open the Level dropdown for the last element in either Log Definitions or Loggers
3. See menu not being completely visible

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.8-20220311.171822: Ibis4Example
Running on ae0c43ffe608 using Apache Tomcat/8.5.60
Java Version: OpenJDK Runtime Environment (1.8.0_275-b01)
Heap size: 1330M, total JVM memory: 1910M
Free disk space: 11GB, total disk space: 50GB
Up since: 2022-03-11 17:44:20 (3d)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
Work around is to scroll down, but yes, this is clumsy.
