### ISSUE TITLE
Larva does not replace properties in expected result

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2886]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When using properties in files used by Larva for .read/.write steps, property replacement is done only on the write steps, which can result in failures if such a property is also in a response that is compared in a .read step.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.8-20220315.180221: ibis4repro
Running on LPZWNL000033867 using Apache Tomcat/9.0.56
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 275M, total JVM memory: 491M
Free disk space: 79GB, total disk space: 237GB
Up since: 2022-03-18 08:27:47 (6m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
[src.zip](https://github.com/ibissource/iaf/files/8302471/src.zip)

**Comment by nielsm5** [comment]
We have discussed this in pr #730 where we concluded that this would break the save functionality. If such a property would be in the response the correct thing to do would be to ignore it using one of the many ignore/replace options.
