### ISSUE TITLE
Browse tables does not work with Postgres

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2903]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When using browse tables with Postgres as database, the data is not shown. The nr. of rows for the result is correctly initialized, the Web Developer Tools show that the data is returned from the internal API, it is just not shown.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
Field definitions are not included in the returned data, probably because they are not found in BrowseJdbcTable line 141/145.
These lines probably need a `qs.getDbmsSupport().getSchema(conn)` as the second parameter.
If so, PR #2826 need to be merged first
