### ISSUE TITLE
IAF_DatabaseChangelog.xml contains reserved word VALUE, H2 fails

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#2919]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When updating our local H2 version (2.1.210) we now get an error from the **IAF_DatabaseChangelog.xml** when liquibase runs it : 

SEVERE 3/24/22 10:10 AM: liquibase: IAF_DatabaseChangelog.xml: IAF_DatabaseChangelog.xml::IAF_Util:4::Niels Meijer: Change Set IAF_DatabaseChangelog.xml::
IAF_Util:4::Niels Meijer failed.  
Error: Syntax error in SQL statement "CREATE TABLE PUBLIC.IBISPROP (NAME VARCHAR(100) NOT NULL, **[*]VALUE VARCHAR(100)**, LASTMODDATE TIMESTAMP, LASTMODBY VARCHAR(32), CONSTRAINT PK_IBISPROP PRIMARY KEY (NAME))"; expected "identifier"; 

The reserved word VALUE should be escaped with single quotes in the XML.

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**

**Configuration**

**Input**

**Environment**

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
A quick fix, you might call it a work-around, is to add the parameter 'NON_KEYWORDS' to the database url, like:
`URL="jdbc:h2:file:./ibis4test;NON_KEYWORDS=VALUE;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;TRACE_LEVEL_FILE=0"`

**Comment by rvdstel** [comment]
Thanks for the tip, will try that.

Before changing the URL I ran into the next problem, when using the ManageDatabase adapter with an input XML in the larva tests.

`<manageDatabaseREQ>`
`<insert>`
       `<tableName>METADATA</tableName>`
        `<columns>`
        `<column><name>VALUE</name><value>Actief</value></column>`
                `</columns>`
    `</insert>`

SQLState [42001], errorCode [42001]: Syntax error in SQL statement "INSERT INTO METADATA (FILEID,BATCHID,QUERYID,SYSTEMNAME,**[*]VALUE**

**Comment by jacodg** [comment]
Checked whether NON_KEYWORDS needs to be added to the context.xml in the Frank!Runner. As the Frank!Runner determines the H2 version to use based on the F!F version this is not needed. See comment in build.xml:

\

Locally changed the build.xml to use H2 version 2 instead of 1 with F!F 7.6.3. In that case I get the same error as is described in this issue.
