### ISSUE TITLE
Missing non-backwards compatible change in releases

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2925]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
As indicated in #2788, the default XSLT version has changed which might break configurations during upgrade. This is not mentioned in the release notes, nor is the option to set the default to 1 in 7.7 and later.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Are you sure? This has been in the framework since the [7.5](https://github.com/ibissource/iaf/blame/d8a42290afa8ba58f08644e94639141d7a149193/core/src/main/java/nl/nn/adapterframework/util/XmlUtils.java#L122)...
