### ISSUE TITLE
IbisLocalSender does not throw an error or warning during startup when listener does not exist after waiting 60s

### ISSUE THREAD

**Issue by MLenterman** [ibissource/iaf#2926]
**Describe the issue**
IbisLocalSender does not throw an error or warning during startup when listener does not exist. After waiting for 60 seconds during startup for the listener to become available, it does not throw an error or warning when the waiting period ends and the listener is still not there. During execution of the sender it will still throw an exception, because the listener is not available.

**Reporter**
M. Lenterman

**To Reproduce**
1. Setup an IbisLocalSender to point to a non-existing javaListener
2. Start FF
3. Observe the adapter waiting 60s for the listener to become available
4. Observe the lack of an error/warning
5. Execute pipeline
6. Observe exception because the listener does not exist.

**Configuration**
``` XML
<Module
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../ibisdoc.xsd">
  
   	<Adapter name="adapterA"
		description="">

		<Receiver name="adapterA">
            <JavaListener name="adapterA"/>
        </Receiver>
      	<Pipeline>
			<SenderPipe
                name="senderPipe">
                <IbisLocalSender
                    name="localSender"
                    javaListener="listenerThatDoesNotExist">
                </IbisLocalSender>
                <Forward name="success" path="EXIT"/>
            </SenderPipe>
		<Exit path="EXIT" state="success"/>
	</Pipeline>
  </Adapter>
</Module>
```

**Environment**
```
FF! 7.8-20220324.163612: Frank2CircularXsd
Running on LAPTOP-UKAI1A6 using Apache Tomcat/9.0.56
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 347M, total JVM memory: 540M
Free disk space: 284GB, total disk space: 464GB
Up since: 2022-03-25 10:12:45 (1m) 
```

**Comment by nielsm5** [comment]
It may take a while before the error message shows up, especially on larger applications.
