### ISSUE TITLE
Streaming seems to break LocalFileSystemPipe

### ISSUE THREAD

**Issue by dinges2** [ibissource/iaf#2934]
**Describe the issue**
LocalFileSystemPipe deletes file contents when trying to write new file contents. This seems to be caused by streaming.

**Reporter**
Rob

**To Reproduce**
```
<XsltPipe name="NewInfo" 
    styleSheetName="xsl/newInfo.xsl">
    <Forward name="success" path="StoreInfo"/>
</XsltPipe>

<LocalFileSystemPipe name="StoreInfo" 
    action="write" 
    overwrite="true">
    <Param name="filename" pattern="examples\Frank2Example4\src\main\configurations\Test\test.xml" />
    <Forward name="success" path="EXIT" />
</LocalFileSystemPipe>
```
1. Run an adapter with these two pipes.
2. In the LadyBug, open the resulting LadyBug report
3. Check the error message, it should be something like: 
    nl.nn.adapterframework.core.PipeRunException: Pipe [NewTokenInfo] msgId [0a000093--13d42b53_17fd0969cc0_-7fae] Exception on transforming input: XsltSender [NewInfo] Exception on transforming input: XsltSender [NewInfo] Exception on creating transformerHandler chain: Parameter [oldInfo] could not parse result [PathMessage$$Lambda$323/939564738: nl.nn.adapterframework.stream.PathMessage$$Lambda$323/939564738@37c38df2] to XML document: (SAXParseException) Premature end of file.
4. Set streaming.auto in properties to false
5. Run the pipeline again and check the LadyBug report. It should be fixed now.

**Comment by gvanbrakel** [comment]
Could you please provide the ladybug reports?
Could you also provide the version of the framework that you are using?

**Comment by jjansenvr** [comment]
You could try XSLT1 which supports streaming

**Comment by dinges2** [comment]
I see, I didn't know that.
Thank you for the clarification and possible solutions!
