### ISSUE TITLE
Search filter count issue

### ISSUE THREAD

**Issue by laura-dimitra** [ibissource/iaf#2942]
Please open included screenshot. The result is "Showing 0 to 0 of 0 entries (filtered from 148 total entries)".
In this case it must count 2 results.

![search filter count issue](https://user-images.githubusercontent.com/30295058/160592185-4201bc88-31a5-490e-8004-688c3cf5cd0e.PNG)

**Comment by nielsm5** [comment]
Hey Laura, thanks for your feedback, Ali's been working on a fix in PR #https://github.com/ibissource/iaf/pull/2842.
 We hope to release this soon, though it might not be in the 7.7 final yet.
