### ISSUE TITLE
Search Filter is not working in messagelog for row "Message" in 7.7 (jmslistener)

### ISSUE THREAD

**Issue by laura-dimitra** [ibissource/iaf#2951]
This issue is for the user similar to issue #2837.

The difference Ali noted is that this uses a jmslistener. Please see image below.

![search werkt nog niet](https://user-images.githubusercontent.com/30295058/160834865-1e047ec7-30be-496d-88d4-0e94c0c6c952.PNG)

**Comment by alisihab** [comment]
Should have been fixed with #2991
