### ISSUE TITLE
Search Filter is not working in errorstore for row "Message" in 7.7 (ApiListener)

### ISSUE THREAD

**Issue by laura-dimitra** [ibissource/iaf#2952]
Same as #2837 and #2951 but in this case for the ApiListener

![search werkt nog niet api listener](https://user-images.githubusercontent.com/30295058/160840234-3f86237d-8943-4183-b374-e24667e74539.PNG)

**Comment by gvanbrakel** [comment]
This problem is due to an inadvertent change in the way Messages are serialized. To properly solve it, we would need to know with what version of the framework this message was written to the database.
