### ISSUE TITLE
Postgres with Narayana gives XA exceptions

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2955]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When running iaf-test with Narayana and postgres-xa as database, XA exceptions are thrown. Exceptions are like (see full log for all exceptions and stack traces).
```
2022-03-31 07:47:32,527 WARN [JdbcTableListener [Transacted, InProcess]-listener[6]] [mid [56893]] ats.jta - ARJUNA016061: TransactionImple.enlistResource - XAResource.start returned: XAException.XAER_RMERR for < formatId=131077, gtrid_length=28, bqual_length=36, tx_uid=0:ffffac110004:8ae5:62455a46:23bb, node_name=, branch_uid=0:ffffac110004:8ae5:62455a46:23f8, subordinatenodename=null, eis_name=0 >
org.postgresql.xa.PGXAException: Invalid protocol state requested. Attempted transaction interleaving is not supported. xid=< formatId=131077, gtrid_length=28, bqual_length=36, tx_uid=0:ffffac110004:8ae5:62455a46:23bb, node_name=, branch_uid=0:ffffac110004:8ae5:62455a46:23f8, subordinatenodename=null, eis_name=0 >, currentXid=< formatId=131077, gtrid_length=28, bqual_length=36, tx_uid=0:ffffac110004:8ae5:62455a46:23b7, node_name=, branch_uid=0:ffffac110004:8ae5:62455a46:23b8, subordinatenodename=null, eis_name=0 >, state=ENDED, flags=0
```

[postgres-logs.zip](https://github.com/ibissource/iaf/files/8387256/postgres-logs.zip)
[postgres-tomcat.log](https://github.com/ibissource/iaf/files/8387559/postgres-tomcat.log)

**Reporter**
Ricardo

**To Reproduce**
1. Run Docker container with `docker run -d -p 9080:8080 --add-host=host.docker.internal:host-gateway -e active.authentication=false -e jdbc.dbms.default=postgres-xa -e jms.provider.default=activemq -e CATALINA_OPTS=-Dlog.level=WARN -e application.server.type.custom=NARAYANA --name iaf-test-tomcat-NARAYANA-POSTGRES-XA-ACTIVEMQ iaf-test-tomcat`
2. Run all tests
3. Get failed tests
4. See errors in log

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.8-SNAPSHOT: Ibis4Test
Running on 34e2c5c3fad9 using Apache Tomcat/8.5.60
Java Version: OpenJDK Runtime Environment (1.8.0_275-b01)
Heap size: 383M, total JVM memory: 874M
Free disk space: 244GB, total disk space: 251GB
Up since: 2022-03-31 10:43:40 (11m) 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Fixed a while ago though I'm unsure in which pr.
