### ISSUE TITLE
returnedColumns doesn't work with PostGreSQL

### ISSUE THREAD

**Issue by lenardvandermaas** [ibissource/iaf#2966]
**Describe the issue**
When using the attribute 'columnsReturned' on a PostGreSQL database, it will cause an error like:
```
nl.nn.adapterframework.core.SenderException: [nl.nn.adapterframework.jdbc.FixedQuerySender] [DoStuff] got exception sending message: (PSQLException) SQLState [42703]: ERROR: column "COLUMN_NAME" does not exist
```

**Reporter**
Lenard

**To Reproduce**
1. Make an adapter with a pipe like:
```
<SenderPipe name="DoStuff">
        <FixedQuerySender name="DoStuff"
	        queryType="OTHER"
	        query="UPDATE THINGS SET COLUMN1_NAME = ? WHERE UUID = ?"
	        columnsReturned="COLUMN2_NAME"
	        scalar="true">
	        <Param name="UUID" sessionKey="uuid"/>
        </FixedQuerySender>
        <Forward name="success" path="READY"/>
        <Forward name="exception" path="ERROR"/>
</SenderPipe>
```
2. Go to the ladybug and see the error

This can probably be fixed using what's described here: https://www.arundhaj.com/blog/getGeneratedKeys-with-postgresql.html

**Comment by gvanbrakel** [comment]
As an alternative / work around, you could specifiy `resultQuery="SELECT COLUMN2_NAME FROM THINGS WHERE UUID = ?"

**Comment by jacodg** [comment]
Update Frank!Doc. This will only work for Oracle and some specific cases (document the cases). Warning in console for all other cases
