### ISSUE TITLE
ExchangeMailListener gives Cannot convert filename [<randomstring@randomstring.eurprd02.prod.outlook.com>] into an ItemId: (ServiceResponseException) Id is malformed.

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2988]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When using an ExchangeMailListener with checkForDuplicates=true on the receiver, mails cannot be processed with a ServiceResponseException. I investigated with Laurens, and removing the checkForDuplicates solves the issue.

It seems that the issue is that the messageId contains the <randomstring@randomstring.eurprd02.prod.outlook.com> instead of the filename.

Setting messageIdPropertyKey to filename (which should result in the correct ID), gives a different error however:
Caused by: nl.nn.adapterframework.filesystem.FileSystemException: Cannot convert filename [....] into an ItemId: (ServiceResponseException) The specified object was not found in the store., The process failed to get the correct properties.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
7.6.4, 7.7
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
It appears to me that you are trying to use the messageId as the filename.
messageIdPropertyKey should not be set to solve this issue.
It might be necessary to change messageType, but that should also not be necessary.
It could be that you are using the wrong session key to retrieve the filename.
