### ISSUE TITLE
ExchangeMailListener gives "Connection is still allocated"/"Connection not obtained from this manager" upon receiving message

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#3004]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When using a ExchangeMailListener, I get `Connection is still allocated` or `Connection not obtained from this manager` upon receiving a message for the first time. The mail is put in the inProcessFolder, but is not actually processed. Moving it back to the in folder does get the message processed.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
	<adapter name="ProcessTestEmail"
		active="${ProcessTestEmail.active}">
		<receiver name="ProcessTestEmail">
			<!-- Een Listener die lokaal emails ophaalt-->
			<listener name="ProcessTestEmail"
				className="nl.nn.adapterframework.receivers.ExchangeMailListener"
				mailAddress="${TestMail.mailAddress}"
				username="${TestMail.username}"
				password="${TestMail.password}"
				url="${TestMail.url}"
				inputFolder="${TestMail.inputFolder}"
				inProcessFolder="${TestMail.inProcess}"
				processedFolder="${TestMail.processed}"
				errorFolder="${TestMail.error}"
				logFolder="${TestMail.backup}"
				storeEmailAsStreamInSessionKey="file"
				simple="false"/>
		</receiver>
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.8-20220405.104615
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
[ConnectionNotObtainedFromThisManager.log](https://github.com/ibissource/iaf/files/8419254/ConnectionNotObtainedFromThisManager.log)
[ConnectionIsStillAllocated.log](https://github.com/ibissource/iaf/files/8419255/ConnectionIsStillAllocated.log)

**Comment by ricardovh** [comment]
Unfortunately did not solve the issue, tried with 7.7.1-20220406.144153, but issue is still present. Setting disableMessageBrowsers="true" did however seem to solve the issue, maybe it doesn't like it that the console is also browsing the folders?

**Comment by gvanbrakel** [comment]
There appears to be a threading issue in Microsoft EWS. Approaches to avoid this:
- set disableMessageBrowser="true", set maxThreads="1"
- try to use ImapListener instead of ExchangeMailListener.
