### ISSUE TITLE
xslt version issue in the FF version 7.7-RC2 (Connected to #2788)

### ISSUE THREAD

**Issue by CBiplab** [ibissource/iaf#3015]
**Describe the issue**
This is the same issue we already encountered before (ref issue no. #2788 ). This time we've upgraded the framework version to 7.7-RC2 and set the property 'xslt.version.default=1' to DeploymentSpecifics.properties. It looks that this property has no effect.
[Pipeline SetPortalSetUpMutation (3).zip](https://github.com/ibissource/iaf/files/8428913/Pipeline.SetPortalSetUpMutation.3.zip)

**Reporter**
Biplab Chakraborty

**To Reproduce**
1. Please check the attached ttr file.

**Screenshots**
![image](https://user-images.githubusercontent.com/38505235/162024794-146a7715-372d-4bb4-a3f2-f8febd964f9d.png)

**Configuration**
```
Please check the attached ttr file.
```

**Input**
```
Please check the attached ttr file.
```

**Environment**
```
FF! 7.7-RC2: Ibis4Baco
Running on <MyLocalMachine> using Apache Tomcat/9.0.27
Java Version: Java(TM) SE Runtime Environment (1.8.0_162-b12)
Heap size: 1736M, total JVM memory: 3073M
Free disk space: 161GB, total disk space: 475GB
Up since: 2022-04-06 18:28:20 (13m)
```

**Additional Environment**
 NA

**Additional Context**
Please check the attached ttr file.

**Comment by gvanbrakel** [comment]
Workaround is to set type="integer" for the parameters that are used to compare to integers

**Comment by gvanbrakel** [comment]
Acutal error is: 
`nl.nn.adapterframework.core.ListenerException: Pipe [checkFor:Updating_AccountRights] msgId [testmessage0ace0093--7aef2b3d_180183f9694_-7ff3] got exception on transformation: Parameter [pouMutChannel] exception on transformation to get parametervalue: (XPathException) line [1] column [256]: Can not convert #RTREEFRAG to a NodeList!`
That is another one than posted.

**Comment by gvanbrakel** [comment]
Please check different location (7.7 vs 7.8) of setting ignoreNamespaces=false in XmlUtils.createXPathEvaluatorSource. 
This might explain the problem that setting the default xslt version works differently than setting xsltVersion on the object
