### ISSUE TITLE
suppressing warning for SQL injections

### ISSUE THREAD

**Issue by CBiplab** [ibissource/iaf#3016]
**Describe the issue**
We would like to suppress all the warning messages appearing at the console due to DirectQuerySender. I've tried it using the following custom properties in DeploymentSpecifics.properties. Unfortunately nothing worked out. FYI, I'm using FF version 7.7-RC2.

warnings.suppress.sqlInjections.JdbcSenders=true
warnings.suppress.sqlInjections.ResultSetIteratingPipeTest=true
warnings.suppress.sqlInjections.BlockEnabledDirectQuerySender=true
warnings.suppress.sqlInjections.QuerySender=true
warnings.suppress.sqlInjections.XmlQuerySender=true
warnings.suppress.sqlInjections.ResultSetIteratingPipe=true
warnings.suppress.sqlInjections=true

**Reporter**
Biplab Chakraborty

**To Reproduce**
1. it happens for all DirectQuerySender.

**Screenshots**
![image](https://user-images.githubusercontent.com/38505235/162033342-58a594f3-2509-4431-8117-17eea63a1a56.png)

**Configuration**
```
Any configuration having DirectQuerySender.
```

**Input**
```
NA
```

**Environment**
```
FF! 7.7-RC2: Ibis4Baco
Running on <LocalEnvironment> using Apache Tomcat/9.0.27
Java Version: Java(TM) SE Runtime Environment (1.8.0_162-b12)
Heap size: 1332M, total JVM memory: 3701M
Free disk space: 161GB, total disk space: 475GB
Up since: 2022-04-06 19:13:32 (16m)
```

**Additional Environment**
 NA

**Additional Context**
In the older version of FF versions, we had this warning message only one per config project, but now in this version (7.7-RC2) it shows for all adapters and for all senders. Therefore, the number of such warning messages are much larger than before. Below is the warning message, we used to get before upgrading this FF version-

![image](https://user-images.githubusercontent.com/38505235/162035552-39ed6889-b58f-4a1d-89d4-8de5c3ff7fee.png)

**Comment by alisihab** [comment]
The convention would be `warnings.suppress.sqlInjections.{adapterName}=true`. For instance in above image I see an adapter called FindSuperUser suppressionKey in this case: `warnings.suppress.sqlInjections.FindSuperUser=true`. Could you try with this?
