### ISSUE TITLE
Allow XML without namespace for SoapInputValidator

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#3029]
**Describe the issue**
Trying to create an adapter that allows JSON, XML and SOAP message with a SoapInputValidator it is not possible to have the SoapInputValidator allow XML without a namespace while allowPlainXml="true" and for JSON no namespace is needed.

**Reporter**
Jaco de Groot

**To Reproduce**
1. Use the mentioned SoapInputValidator below
2. Test the adapter with JSON, XML and SOAP
3. See that for XML it is only possible to pass the validation when it contains a namespase

**Screenshots**
\-

**Configuration**
```
			<SoapInputValidator
				name="ValidateInput"
				schemaLocation="urn:hello-lines HelloLines/xsd/Lines.xsd"
				addNamespaceToSchema="true"
				soapBody="lines"
				allowPlainXml="true"
				rootElementSessionKey="receivedRootElement"
				reasonSessionKey="validatorMessage"
				>
				<Forward name="failure" path="Failure: Create example plain text message"/>
				<Forward name="exception" path="Exception: Replace error message with original plain text message"/>
			</SoapInputValidator>
```

**Input**
```
<lines xmlns="urn:hello-lines"><line1>Line One</line1><line2>Line Two</line2><line3>Line Three</line3><line4>Line Four</line4><line5>Line Five</line5></lines>
```

**Environment**
```
FF! 7.8-20220407.104516: Frank2Example4
Running on xxx using Apache Tomcat/9.0.60
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 235M, total JVM memory: 593M
Free disk space: 84GB, total disk space: 475GB
Up since: 2022-04-07 17:43:01 (1h) 
```

**Additional Environment**
\-

**Additional Context**
\-

**Comment by gvanbrakel** [comment]
Please set acceptNamespaceLessXml=true to obtain this behaviour

**Comment by jacodg** [comment]
Ah, thanks, didn't see that attribute. I replaced my workaround: https://github.com/ibissource/frank-runner/commit/1020f5462ee361093b1a7f61c5b364c154cf6b8e
