### ISSUE TITLE
Not all expected counters shown on status page

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#3031]
**Describe the issue**
When running Frank2Example3/configurations/Example3/Configuration.xml I see only one blue envelope on the overview page while more IbisStore related counters are available

**Reporter**
Jaco de Groot

**To Reproduce**
See screenshots...

**Screenshots**
See blue envelope:
![image](https://user-images.githubusercontent.com/2970084/162261060-b1ec03c1-7cbb-4ce7-bd2b-5d28d466b06a.png)
When you open adapter 01 and 02 you see they have a blue envelope available too:
![image](https://user-images.githubusercontent.com/2970084/162261256-49c326d2-806f-4bad-98fd-5b47abf49800.png)

**Configuration**
https://github.com/ibissource/frank-runner/blob/master/examples/Frank2Example3/configurations/Example3/Configuration.xml

**Input**
```
\-
```

**Environment**
```
FF! 7.8-20220407.104516: Frank2Example4
Running on xxx using Apache Tomcat/9.0.60
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 261M, total JVM memory: 587M
Free disk space: 84GB, total disk space: 475GB
Up since: 2022-04-07 17:43:01 (1h) 
```

**Additional Environment**
\-

**Additional Context**
\-

**Comment by jjansenvr** [comment]
new icon for outbound messagelog to be shown in collapsed view
