### ISSUE TITLE
Too many ConfigurationWarnings in IAF-Test

### ISSUE THREAD

**Issue by nielsm5** [ibissource/iaf#3061]
**Describe the issue**
There are too many irrelevant issues in IAF-Test. These all have have to with validations. The validation warnings should be elsewhere.
![image](https://user-images.githubusercontent.com/4375703/163217365-7f4dd94b-c3f3-4ca5-b7b7-909f5b66c297.png)

**Reporter**
Niels

**Comment by gvanbrakel** [comment]
This is related to a change in XmlValidator.getSchemas(boolean).
In the 7.7 version of this method, the schemas were (almost) always combined using 
```
					Map<String, Set<XSD>> xsdsGroupedByNamespace = SchemaUtils.getXsdsGroupedByNamespace(xsds, false);
					xsds = SchemaUtils.mergeXsdsGroupedByNamespaceToSchemasWithoutIncludes(this, xsdsGroupedByNamespace, null); // also handles addNamespaceToSchema
```
In the 7.8 version, this is done in less cases, to get the circular XSDs working.
