### ISSUE TITLE
Octetstream sessionkey is converted to string when returned to main adapter

### ISSUE THREAD

**Issue by BonnoSmeele** [ibissource/iaf#3100]
When receiving an octet stream(by HttpSender) in a SUB adapter, the sessionkey is switched to string type when returning to the MAIN adapter. This also happens when the octet stream is set as output for the subadapter.
When converted to Octet stream as output in the main adapter this results in an unusuable file.

**Reporter**
Bonno!

**To Reproduce**

**Screenshots**
When receiving the octetstream in the HTTP sender:
![image](https://user-images.githubusercontent.com/73215587/164702024-41f0d645-d72d-4d00-bd1a-b864baa9ab2e.png)
SessionKey is returned to main adapter:
![image](https://user-images.githubusercontent.com/73215587/164702167-ade7d68b-9de1-4f75-83f8-a790d96c2595.png)

**Configuration**
Config files used:
main adapter: https://gitlab.insim.biz/ibissource/salesforce/ibis4salesforce/ibis4salesforce_claim_document/-/blob/M99A947-main-patch-50880/src/main/configuration/claim_document/Configuration_GetClaimDocumentFile.xml
sub adapter: https://gitlab.insim.biz/ibissource/salesforce/ibis4salesforce/ibis4salesforce_claim_document/-/blob/M99A947-main-patch-50880/src/main/configuration/claim_document/Configuration_GetClaimDocumentFileBackEnd.xml

**Input**
[Pipeline GetClaimDocumentFileAdapter.zip](https://github.com/ibissource/iaf/files/8540333/Pipeline.GetClaimDocumentFileAdapter.zip)

**Environment**
FF! 7.7-20220202.144505: ibis4salesforce_claim_document
Running on ip-10-229-242-246.eu-west-1.compute.internal using Apache Tomcat/9.0.60
Java Version: OpenJDK Runtime Environment (1.8.0_322-b06)
Heap size: 339M, total JVM memory: 707M
Free disk space: 25GB, total disk space: 30GB
Up since: 2022-04-22 12:48:01 (8m)

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by alisihab** [comment]
It seems that it is fixed in 7.7. Could you upgrade framework to 7.7?

**Comment by alisihab** [comment]
Bonno confirmed that it works in 7.7
