### ISSUE TITLE
Lazyload CMIS servlets doesn't seem to work

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#3104]
**Describe the issue**

https://github.com/ibissource/iaf/pull/2697 doesn't seem to work. The logging shows several messages like:

servlet name [WebServices10] servletClass [nl.nn.adapterframework.extensions.cmis.servlets.WebServices10@255d9277] loadOnStartup [1]

When using the following system properties:
```
-Dservlet.WebServices10.loadOnStartup=-1 -Dservlet.BrowserBinding.loadOnStartup=-1 -Dservlet.AtomPub11.loadOnStartup=-1" -Dservlet.AtomPub10.loadOnStartup=-1" -Dservlet.WebServices11.loadOnStartup=-1" -Dservlet.WebServices10.loadOnStartup=-1"
```
Tomcat will start faster indicating the CMIS servlets didn't start this time. Although the logging still says loadOnStartup [1] but I think that is caused by loadOnStartup being logged instead of loadOnStartupCopy. I'll create a separate issue for this.

**Reporter**
Jaco de Groot

**To Reproduce**
1. Start Frank2Example1 using the Frank!Runner
2. See loadOnStartup [1] messages in the logfile
3. Disable the CMIS servlets using system properties
4. Start Frank2Example1 again and see a decrease in startup time

**Screenshots**
\-

**Configuration**
\-

**Input**
\-

**Environment**
```
FF! 7.8-20220421.162747: Frank2Example1
Running on xxx using Apache Tomcat/9.0.60
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 247M, total JVM memory: 800M
Free disk space: 89GB, total disk space: 475GB
Up since: 2022-04-22 17:32:11 (2m) 
```

**Additional Environment**
\-

**Additional Context**
\-

**Comment by nielsm5** [comment]
I see strange quotes in the startup arguments

**Comment by jacodg** [comment]
Copy/paste/edit error, this was the original code from my test script that does a number of runs with disable.ws=true and a number of runs with disable.ws}=false. I didn't want to make things confusing, but now I only made it more confusing with these strange quotes. :)

```
<arg value="-Dservlet.WebServices10.loadOnStartup=-1" if:true="${disable.ws}"/>
<arg value="-Dservlet.BrowserBinding.loadOnStartup=-1" if:true="${disable.ws}"/>
<arg value="-Dservlet.AtomPub11.loadOnStartup=-1" if:true="${disable.ws}"/>
<arg value="-Dservlet.AtomPub10.loadOnStartup=-1" if:true="${disable.ws}"/>
<arg value="-Dservlet.WebServices11.loadOnStartup=-1" if:true="${disable.ws}"/>
<arg value="-Dservlet.WebServices10.loadOnStartup=-1" if:true="${disable.ws}"/>
```

**Comment by jacodg** [comment]
For the wrong information being logged I created https://github.com/ibissource/iaf/issues/3106.

The default values don't seem to be -1 but 1 as when you specify -1 using system properties Tomcat doesn't show loadOnStartup [1] anymore and will startup faster (Frank logging still shows 1 for which I created https://github.com/ibissource/iaf/issues/3106 as mentioned above).
