### ISSUE TITLE
Ladybug StackOverflow error (7.7)

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#3108]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Might be related to #3035, in 7.7 I get a StackOverflowError, but instead of a Validator it is in a SenderPipe with a FixedQuerySender.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jjansenvr** [comment]
check if equal to issue #3035 then backport, otherwise solve
