### ISSUE TITLE
Http connection reset when doing multiple calls to the same target system.

### ISSUE THREAD

**Issue by BonnoSmeele** [ibissource/iaf#3109]
**Describe the issue**
I'm using an adapter that uses a a lot of http senders to connect to a salesforce system. After a few successfull calls the adapter throws an error: 

Suppressed: java.net.SocketException: Broken pipe (Write failed)
Caused by: java.net.SocketException: Connection reset

Niels thinks that the connection might be closed on the target system but is still open in de ibis connection pool.

**Reporter**
Bonno!

**To Reproduce**

**Screenshots**

**Configuration**

Please provide the configuration of the Pipe or Receiver with the problem.

**Input**

[Pipeline HandleClaimsSoapAdapter.zip](https://github.com/ibissource/iaf/files/8555408/Pipeline.HandleClaimsSoapAdapter.zip)

**Environment**
FF! 7.7-20220202.144505: ibis4salesforce_claim
Running on ip-10-186-220-162.eu-west-1.compute.internal using Apache Tomcat/9.0.41
Java Version: OpenJDK Runtime Environment (1.8.0_312-b07)
Heap size: 171M, total JVM memory: 859M
Free disk space: 25GB, total disk space: 30GB
Up since: 2022-04-21 22:10:05 (3d)
**Describe the issue**

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**

**Comment by nielsm5** [comment]
See https://stackoverflow.com/questions/66299813/apache-httpclient-4-5-13-java-net-socketexception-broken-pipe-write-failed

**Comment by nielsm5** [comment]
After looking at the logs, it originates after the OAuthAccessTokenManager token refresh...
org.apache.http.impl.auth.HttpAuthenticator - OAUTH2 [complete=false] authentication error: (SSLException): (SocketException) Connection reset
