### ISSUE TITLE
DatabaseJob should not be in the Frank!Doc

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#3122]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The DatabaseJob is a special job that users can create from the GUI, and should not be part of the XML Configuration. Therefore I would also not expect it to be part of the Frank!Doc (and XSD).

**Reporter**
Ricardo

**To Reproduce**
1. Go to https://frankdoc.frankframework.org/#!/Job/DatabaseJob
2. Should not be there

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
FrankDoc has been modified, see: https://github.com/ibissource/frank-doc/pull/120
