### ISSUE TITLE
parentConfig only works on application level

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#3127]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
I have several applications that use configurations.database.autoLoad to dynamically load configurations from the database (as to not have a complete application deployment every time a configuration is added). In some of those applications, there is a common configuration with common XSLTs and files that apply to all configurations and those files can be accessed via the classpath when the common configuration is set as parentConfig.

Setting the common as parentConfig of another configuration is only possible from the application level, which would still result in a complete application deployment to define the parentConfig relation for those configurations. Setting it on the configuration itself does not result in warnings, but it cannot load files from the classpath (indicating that the parentConfig property is not working). 

I would expect that setting the parentConfig property works the same whether it is defined on application or configuration level.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7
FF! 7.8-20220426.180610
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
This is by design
