### ISSUE TITLE
Add xslt3 support as supported in Saxon HE version

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#3130]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The saxon product includes XSLT3 support from version 9.7 allowing for json mappings

**Reporter**
jjansenvr

**Additional Context**
https://www.saxonica.com/products/PD11/SaxonJ-HE.pdf

### 1.1 XSLT 3.0 Basic Processor
Provides all mandatory features from the XSLT 3.0 specification (including try/catch, iterate, accumulators, maps, named modes, content value templates,and extended patterns, as well as features retained from XSLT 2.0).
### 1.2 XSLT 3.0 Serialization 
Provides the serialization feature: specifically, the ability to convert the
result trees produced as output of an XSLT transformation to lexical XML,
or other formats including HTML, JSON, and plain text, under the control of
serialization parameters defined in the stylesheet or via an external API.
### 1.3 XSLT 3.0 Compatibility
Provides XSLT 1.0 compatibility mode as defined in the XSLT 3.0 specification. If a stylesheet specifies version="1.0", this causes certain constructs to behave in a way that retains the XSLT 1.0 behavior.
### 1.4 XSLT 3.0 Dynamic Evaluation
Provides use of the XSLT 3.0 instruction xsl:evaluate, which allows dynamic evaluation of XPath expressions.
### 1.5 XSLT 3.0 XPath 3.1 Feature
Provides full use of XPath 3.1 features, including XPath 3.1 functions, and maps and arrays. Note: Saxon supports XPath 3.1 unconditionally in XSLT 3.0 stylesheets, it does not offer a processing mode in which XPath is restricted to version 3.0.
### 1.6 XSLT 3.0 Higher-Order Functions
Provides higher-order functions: specifically, the ability to use functions as values, including dynamic function calls, inline functions, partial function application, and the standard higher-order functions defined in the XPath 3.1 function library.

## Optional features not provided: XSLT 3.0 Schema Awareness, XSLT 3.0 Streaming.

**Comment by nielsm5** [comment]
Fixed in #3361
