### ISSUE TITLE
QuerySender resultQuery does not work with parameters

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#3135]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
It is not possible to use parameters with resultQuery on a QuerySender. When using the below configuration, the error is:
`(JdbcSQLDataException) SQLState [90012], errorCode [90012]: Parameter &quot;#1&quot; is not set; SQL statement:&#10;SELECT * FROM IBISPROP WHERE NAME=? [90012-210]`

When adding a param to the sender (so that it has 3 params), results in the following error:
`(JdbcSQLDataException) SQLState [90008], errorCode [90008]: Invalid value &quot;3&quot; for parameter &quot;parameterIndex&quot; [90008-210]`

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
<module>	
	<adapter name="Repro">
		<receiver name="Repro">
			<listener name="Repro" className="nl.nn.adapterframework.receivers.JavaListener"/>
		</receiver>	

		<pipeline>
			<exits>
				<exit path="EXIT" state="success"/>
			</exits>

			<pipe name="Repro"
				className="nl.nn.adapterframework.pipes.SenderPipe">
				<sender className="nl.nn.adapterframework.jdbc.FixedQuerySender"
					query='INSERT INTO IBISPROP(NAME,"VALUE") VALUES(?,?)'
					resultQuery="SELECT * FROM IBISPROP WHERE NAME=?">
					<param name="Name" value="Repro"/>
					<param name="Value" value="Demo"/>
				</sender>
				<forward name="success" path="EXIT"/>
			</pipe>
		</pipeline>
	</adapter>
</module>
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
Do you have a real use-case? Does it have priority?
