### ISSUE TITLE
Add attribute "deleteEmptyDirectory" to LocalFileSystemPipe

### ISSUE THREAD

**Issue by laura-dimitra** [ibissource/iaf#3160]
To remove a warning I have to replace the FilePipe to a LocalFileSystemPipe.

But the LocalFileSystemPipe doesn't have the attribute "deleteEmptyDirectory", which the ibis is using in the FilePipe.

The only alternative I see in the documentation is "removeNonEmptyFolder". But there's a big difference by deleting an empty or non-empty folder of course.

Can you please add the "deleteEmptyDirectory" attribute to the LocalFileSystemPipe?

(I'm using the newest FF:  7.7.1-20220509.174858)

**Comment by Laurens-makel** [comment]
A possible workaround is to add some pipes:

- LocalFileSystemPipe to list the amount of files in the desired directory
- XmlIfPipe to check if it's empty
- If not empty, continue normal flow
- If empty, LocalFileSystemPipe that deletes the directory, continue normal flow

**Comment by laura-dimitra** [comment]
Hi Laurens,
Thanks. I discussed this yesterday with Ali and he told me they will implement this feature.

**Comment by rvdstel** [comment]
Why not use this pipe for cleaning directories? 

`			<CleanupOldFilesPipe name="deleteFilesystem"
				filePatternSessionKey="destination" subdirectories="true"
				deleteEmptySubdirectories="true" lastModifiedDelta="-1">
				<Forward name="success" path="uploadFiles" />
			</CleanupOldFilesPipe>`
