### ISSUE TITLE
Undocumented renaming and ordering behavior for WsdlXmlInputValidator

### ISSUE THREAD

**Issue by MLenterman** [ibissource/iaf#3166]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The [WsdlXmlInputValidator](https://github.com/ibissource/iaf/wiki/WsdlXmlInputValidator) seems to get renamed under the hood to "InputValidator". It is also forced as the first pipe in the pipeline, regardless of the pipeline "firstPipe" attribute being set to some other pipe or ordering of the pipe within the pipeline. 

This behavior does not seem to be documented anywhere. There might be other pipes that have similar behavior with this missing documentation.

Besides describing the behavior, it might also help if the FrankConfig.xsd forces pipes with this behavior to be the first pipe in the pipeline. That way it's much harder to run into hard-to-find issues when trying to use conditional forwarding in front of it.

**Reporter**
Marcel Lenterman

**To Reproduce**
1. Put any pipe in front of the [WsdlXmlInputValidator](https://github.com/ibissource/iaf/wiki/WsdlXmlInputValidator) that would normally be executed first.
2. Observe [WsdlXmlInputValidator](https://github.com/ibissource/iaf/wiki/WsdlXmlInputValidator) being executed first anyways.
3. Observe the pipe being named "InputValidator" in Ladybug.

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.8-20220512.131203: Frank2zgw
Running on LAPTOP-UKAI1A6 using Apache Tomcat/9.0.56
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 682M, total JVM memory: 968M
Free disk space: 284GB, total disk space: 464GB
Up since: 2022-05-12 14:21:56 (1h) 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox] 

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by MLenterman** [comment]
Turns out my IDE ran out of memory and stopped checking the FrankConfig.xsd. The schema does not allow using it in the way described above. The framework is not throwing any errors for non-existing or illegal pipes though.

**Comment by jacodg** [comment]
The checks by the F!F are less strict indeed (to be backwards compatible).

Which IDE are you using?

**Comment by MLenterman** [comment]
> The checks by the F!F are less strict indeed (to be backwards compatible).
> 
> Which IDE are you using?

I'm using Visual Studio Code with the "XML Tools" extension for schema checking. The extension runs in JVM, which by default only has 512M assigned. In The Visual Studio Code "settings.json" this can be increased, so that the extension does not run out of memory anymore.
