### ISSUE TITLE
Sessionkey is not returned from subadapter

### ISSUE THREAD

**Issue by VBPham** [ibissource/iaf#3242]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Sessionkey is not returned from subadapter. IbislocalSender calls adapter with javalistener with returnedSessionKeys="multipart1". In subadapter multipart sessionkey is set with stream. When back in main adapter multipart sessionkey is null.

**Reporter**
Vinh

**To Reproduce**
Configure adapter with subadapter where sessionkey is set with stream. See in log that sessionkey is null

**Screenshots**

![multipart1_null](https://user-images.githubusercontent.com/24545406/169824447-6331e2de-a0ef-4cec-bdc2-7cffbc56c225.png)

**Configuration**

**Input**
[Pipeline PortalGetDocument_GET_lege_multipart1_sessionkey.zip](https://github.com/ibissource/iaf/files/8754637/Pipeline.PortalGetDocument_GET_lege_multipart1_sessionkey.zip)

**Environment**

FF! 7.7.1: Ibis4Archive
Running on LPZWNL000033000 using Apache Tomcat/8.5.40
Java Version: Java(TM) SE Runtime Environment (1.8.0_172-b11)
Heap size: 435M, total JVM memory: 1476M
Free disk space: 16GB, total disk space: 236GB
Up since: 2022-05-23 10:05:13 (4h)

**Additional Environment**

**Additional Context**

**Comment by ricardovh** [comment]
Is the returnedSessionKeys attribute also set on the receiver of the subadapter? That should also write some lines to the log, but those are not in your logging.

**Comment by VBPham** [comment]
yes this has always worked. I am working on a upgrade from FF  7.6-20200416.110009 to FF 7.7.1
![image](https://user-images.githubusercontent.com/24545406/169963970-2ae8823c-d218-4319-a980-301d463c56ff.png)

**Comment by VBPham** [comment]
![Uploading image.png…]()
yes this has always worked. I am working on a upgrade from FF  7.6-20200416.110009 to FF 7.7.1

**Comment by VBPham** [comment]
Discussed with Ricardo, returnedSessionkeys attributed is moved to receiver not to be configured on listener. Issue can be closed
