### ISSUE TITLE
Messagelog browsing only first page available (7.6.4 only)

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#3256]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When running 7.6.4, messagelog browsing does not work. Only the first page is loaded, the Previous and Next buttons are disabled, no pages are shown and the bottom text shows `Showing 0 to 0 of 0 entries (filtered from 196 total entries)`. This does not happen in 7.6.3, 7.7 and later versions, but is still present in 7.6.5-20220516.103047.

**Reporter**
Ricardo

**To Reproduce**
1. Load the attached configuration
2. Wait some time (a scheduler will run the adapter every second)
3. Open the messagelog
4. Browsing to next page is not possible

**Screenshots**

**Configuration**
```
<module>	
	<adapter name="Repro">
		<receiver name="Repro">
			<listener name="Repro" className="nl.nn.adapterframework.receivers.JavaListener"/>
			<messageLog className="nl.nn.adapterframework.jdbc.JdbcTransactionalStorage"
				jmsRealm="jdbc" 
				slotId="${applicationId}/Repro"/>
		</receiver>	

		<pipeline>
			<exits>
				<exit path="EXIT" state="success"/>
			</exits>

			<pipe name="Repro"
				className="nl.nn.adapterframework.pipes.SenderPipe">
				<sender className="nl.nn.adapterframework.senders.FixedResultSender"
					returnString="Test hideRegex"/>
				<forward name="success" path="EXIT"/>
			</pipe>
		</pipeline>
	</adapter>

	<scheduler>
		<job name="Repro" 
			function="sendMessage" 
			adapterName="Repro" 
			receiverName="Repro" 
			cronExpression="* * * ? * * *" 
			description="Repro">
		</job>
	</scheduler>
</module>
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by alisihab** [comment]
Closed with #3275
