### ISSUE TITLE
GenericMessageSendingPipe with the combination of sender and listener is not working

### ISSUE THREAD

**Issue by CBiplab** [ibissource/iaf#3257]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
GenericMessageSendingPipe is unable to receive a message when it is with the combination of sender and listener. sender is sending the message correctly but the listener seems not consuming the message correctly.

**Reporter**
Biplab Chakraborty

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/38505235/170218531-6824aab6-de75-4604-8a0f-42615fd396e0.png)
[Pipeline SILProxyService.zip](https://github.com/ibissource/iaf/files/8769334/Pipeline.SILProxyService.zip)

**Configuration**
```
Attached ttr.
```

**Input**
```
Attached ttr.
```

**Environment**
```
FF! 7.7.1: Ibis4Baco
Running on SRDZZAPP0479.insim.biz using IBM WebSphere Application Server/9.0.5.10
Java Version: Java(TM) SE Runtime Environment (8.0.7.0 - pxa6480sr7-20211025_01(SR7))
Heap size: 1395M, total JVM memory: 2048M
Free disk space: 886MB, total disk space: 2GB
Up since: 2022-05-21 18:02:00 (3d) 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
It appears that this problem was related to to a number of conflicting unnecessary additional dependencies. It was no longer present when #3366 was solved (by cleaning up the application projects pom.xml)
