### ISSUE TITLE
Configuration should continue after ConfigurationException is thrown

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#3306]
**Describe the issue**
If a ConfigurationException is thrown when configuring a Pipe in a PipeLine, configuration should continue, to check the configuration of remaining pipes. This will speed up the development cycle, as multiple faults can be found and solved in each startup attempt

**Reporter**
Gerrit

**Comment by nielsm5** [comment]
Has been fixed in #4181
