### ISSUE TITLE
JsonPipe incorrectly translates a json null to a XML string <obj>null</obj> instead of <obj xsi:nil="true" />

### ISSUE THREAD

**Issue by MLenterman** [ibissource/iaf#3318]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
JsonPipe incorrectly translates a json null to a XML string `<obj>null</obj>` instead of `<obj xsi:nil="true" />`. This breaks all xslt/xpath functions that do anything based on null or empty nodes, as the translated json null is now not empty anymore and also isn't considered null in XML because the xsi:nil is missing.

**Reporter**
Marcel

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.8-20220607.121930: Frank2zgw
Running on LAPTOP-UKAI1A6 using Apache Tomcat/9.0.56
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 727M, total JVM memory: 937M
Free disk space: 271GB, total disk space: 464GB
Up since: 2022-06-08 18:03:55 (30m) 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jjansenvr** [comment]
it should also wordt the otherway around
