### ISSUE TITLE
Bump of Saxon version from PR #3291 breaks "skipEmptyTags" feature on XsltPipe when there is an empty tag present to skip

### ISSUE THREAD

**Issue by MLenterman** [ibissource/iaf#3334]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Bump of Saxon version from PR #3291 breaks "skipEmptyTags" feature on XsltPipe when there is an empty tag present to skip. The issues is not present when there are no empty tags to skip.

**Reporter**
Marcel

**To Reproduce**
1. Create any XsltPipe and set skipEmptyTags="true"
2. Setup a scenario that produces an empty tag to skip
3. Run pipe
4. See Error

**Screenshots**
``` 
Caused by: java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at java.util.Stack.pop(Stack.java:84)
	at nl.nn.adapterframework.xml.XmlWriter.endPrefixMapping(XmlWriter.java:149)
	at org.xml.sax.helpers.XMLFilterImpl.endPrefixMapping(XMLFilterImpl.java:530)
	at org.xml.sax.helpers.XMLFilterImpl.endPrefixMapping(XMLFilterImpl.java:530)
	**at nl.nn.adapterframework.xml.SkipEmptyTagsFilter.endPrefixMapping(SkipEmptyTagsFilter.java:136)**
	at org.xml.sax.helpers.XMLFilterImpl.endPrefixMapping(XMLFilterImpl.java:530)
	at nl.nn.adapterframework.xml.ExceptionCatchingFilter.endPrefixMapping(ExceptionCatchingFilter.java:155)
```

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.8-20220610.121041: Frank2zgw
Running on LAPTOP-UKAI1A6 using Apache Tomcat/9.0.56
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 799M, total JVM memory: 985M
Free disk space: 265GB, total disk space: 464GB
Up since: 2022-06-10 14:05:18 (10m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
I am not able to reproduce this problem. Please provide a ladybug report, or your configuration and input

**Comment by MLenterman** [comment]
Sent an email with the reports!
