### ISSUE TITLE
Json2XmlInputValidator incorrectly interprets all child elements of a `xs:choice` with minOccurs 0 and maxOccurs unbounded as a json array

### ISSUE THREAD

**Issue by MLenterman** [ibissource/iaf#3352]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Json2XmlInputValidator incorrectly interprets all child elements of a `xs:choice` with minOccurs 0 and maxOccurs unbounded as a json array.

**Reporter**
Marcel

**To Reproduce**

**Screenshots**

**Xsd**
[XSD.txt](https://github.com/ibissource/iaf/files/8899087/XSD.txt)

**Input**

**Environment**
```
FF! 7.8-20220613.124303: Frank2zgw
Running on LAPTOP-UKAI1A6 using Apache Tomcat/9.0.56
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 714M, total JVM memory: 958M
Free disk space: 263GB, total disk space: 464GB
Up since: 2022-06-13 15:07:01 (3h) 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
[Pipeline SoapEndpointRouter_OntvangAsynchroon_ChoiceAsArrayIssue.zip](https://github.com/ibissource/iaf/files/8899096/Pipeline.SoapEndpointRouter_OntvangAsynchroon_ChoiceAsArrayIssue.zip)

**Comment by gvanbrakel** [comment]
Problem can probably be solved easily by replacing constructs like:
```
	<xsd:element name="Options">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:choice minOccurs="0" maxOccurs="unbounded">
					<xsd:element name="a" type="xsd:string" minOccurs="0" maxOccurs="1"/>
					<xsd:element name="b" type="xsd:string" minOccurs="0" maxOccurs="1"/>
					<xsd:element name="c" type="xsd:string" minOccurs="1" maxOccurs="1"/>
					<xsd:element name="d" type="xsd:string" minOccurs="1" maxOccurs="1" nillable="true"/>
				</xsd:choice>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
```
with:
```
	<xsd:element name="Options">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="a" type="xsd:string" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="b" type="xsd:string" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="c" type="xsd:string" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="d" type="xsd:string" minOccurs="0" maxOccurs="1" nillable="true"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
```

**Comment by gvanbrakel** [comment]
Requested feature is Json2XmlValidator to be able to accept XML sequences in any order, i.e. like xsd:any, but without the restriction on multiplicity of elements.
