### ISSUE TITLE
LinkageError: loading constraint violation (7.7.2-20220602.172629)

### ISSUE THREAD

**Issue by CBiplab** [ibissource/iaf#3366]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Empty console, no config is loaded.

**Reporter**
Biplab

**Screenshots**
![image](https://user-images.githubusercontent.com/38505235/174041918-703cd0ac-6ca9-47cf-b2c6-35fae2bbfe64.png)

**Input**
```
Caused by: java.lang.LinkageError: loading constraint violation when overriding method "javax/xml/datatype/XMLGregorianCalendar.getXMLSchemaType()Ljavax/xml/namespace/QName;" during creation of class "org/apache/xerces/jaxp/datatype/XMLGregorianCalendarImpl": loader
```

**Comment by gvanbrakel** [comment]
I sent the following message to Jagdish Gaurha, of the WebSphere team:
The LinkageError problem that we are facing appears to come down as a conflict between two versions of a class of the Xerces parser: one in the “BootstrapClassLoader” and one in a “CompoundClassLoader”. Considering the BootstrapClassLoader, I see on https://srtzzapp0476.insim.biz/ibis4bacobeheer/showEnvironmentVariables.do (the TST environment of baco beheer) a setting for org.osgi.framework.bootdelegation that contains org.apache.xerces.jaxp.datatype, among a lot of other settings. On other machines, the bootdelegation setting appears to be set to ‘*’. Is my observation right that this a special setting for this project? Is it on purpose? If not, can it be set similar to other projects settings?

**Comment by gvanbrakel** [comment]
Problem has been solved by removing a number of unnecesary dependencies from the projects pom.xml to build the war file.
