### ISSUE TITLE
DataTables warning

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#3392]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When opening a messagelog, sometimes a pop-up is generated that there is a DataTables warning (see screenshot). Pressing OK results in the page loading normally.

I have no clear reproduction of when it happens, it does not happen for all messagelogs, I have an application where it seems to happen consistently for sender message logs, but I also got reports for another application where it happens for receiver message logs.

I have only seen this in 7.6.4.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/57142353/174759105-a29224ed-73d4-44af-87e9-b3901e60a6a0.png)

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by ricardovh** [comment]
Can no longer reproduce, only observed on old versions.

**Comment by nielsm5** [comment]
I was able to reproduce this!
