### ISSUE TITLE
Space character at the end of a value in database column dissappears when using FixedQuerySender 

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#3402]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
In the database I have 'Aankoopnota ' but in pipeline 'Aankoopnota' is returned.

Select executed in console
![image](https://user-images.githubusercontent.com/37303445/175037665-5896d5c0-71a5-43b2-a62c-51791bf2d026.png)

Select executed in pipeline
![image](https://user-images.githubusercontent.com/37303445/175037745-8ca61094-8627-4f2e-a35e-ec274ddeb844.png)

**Reporter**
Laurens

**Configuration**
```
<pipe className="nl.nn.adapterframework.pipes.SenderPipe" name="getValuelistDB" storeResultInSessionKey="ValuelistDB">
	<sender className="nl.nn.adapterframework.jdbc.FixedQuerySender" datasourceName="jdbc/ibis4navigator" name="getValuelistDB" query="SELECT * FROM VALUE_LIST WHERE PROP_ID=?" queryType="SELECT">
		<param name="PROP_ID" sessionKey="originalMessage" xpathExpression="Property/PropertyID"/>
	</sender>
	<forward name="success" path="filterValuelist"/>
</pipe>
```

**Environment**
```
FF! 7.7: XXXX
Running on XXX.XXX.XXX using IBM WebSphere Application Server/9.0.5.10
Java Version: Java(TM) SE Runtime Environment (8.0.7.0 - pxa6480sr7-20211025_01(SR7))
Heap size: 1458M, total JVM memory: 4096M
Free disk space: 1GB, total disk space: 2GB
Up since: 2022-06-20 17:01:57 (1d)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL] Oracle

**Comment by gvanbrakel** [comment]
This can be fixed by setting trimSpaces="false"

**Comment by Laurens-makel** [comment]
Ah, correct indeed.

I wasn't aware of this setting yet, thanks for pointing out.
