### ISSUE TITLE
Larva breaks inputs with diacritics

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#3418]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When running a test where a text/json is send to an adapter, and that text contains diacritics such as ä, the diacritic is not send to the adapter as it is in the file.

.xml-files are not affected.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.8-20220624.101938: ibis4repro
Running on LPZWNL000033867 using Apache Tomcat/9.0.56
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 190M, total JVM memory: 566M
Free disk space: 65GB, total disk space: 237GB
Up since: 2022-06-24 14:02:13 (4m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)
[Pipeline Repro.zip](https://github.com/ibissource/iaf/files/8975980/Pipeline.Repro.zip)

**Comment by gvanbrakel** [comment]
A 'workaround' is to use the extension ".utf8"
