### ISSUE TITLE
Healthcheck should ignore manually stopped adapters

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#3428]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When manually stopping an adapter/receiver, the healthcheck endpoint on api/server/health goes from 200 OK to 503 Service Unavailable. When using this endpoint for a healthcheck in a container orchestration platform, this would mark the container as unhealthy and might trigger a new instance of the image to be started with the adapter started again.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
In a container orchestration platform we might disable the possibility to manually stop and start adapters

**Comment by ricardovh** [comment]
Replaced by more generic issue #4114
