### ISSUE TITLE
Adapter does not become red when errors appear in the error store

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#3444]
**Describe the issue**
I have an adapter that has a receiver with a MessageStoreListener (Adapter 03 of Frank2Example3 of the Frank!Runner). The receiver has an error store. Adapter 03 delegates to adapter 04, so errors can be created by stopping adapter 04. I sent a message to some upstream adapter (adapter 01) and got an error in the error store as intended. However, adapter 03 did not become red.

**Reporter**
Martijn Dirkse

**Screenshots**
![image](https://user-images.githubusercontent.com/6784732/176461131-a6f6a385-c66b-4a72-8d3c-174252a68282.png)
![image](https://user-images.githubusercontent.com/6784732/176461314-ea42fb38-9443-4cc3-95fe-9d425f626760.png)

**Comment by nielsm5** [comment]
I can see that it used to be orange (warning) https://github.com/ibissource/iaf/commit/0e5b0a56ef8c942b02fae74dc4462c3f9c1e26dc
