### ISSUE TITLE
Subadapter response no longer available if using error exit

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#3454]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When a subadapter goes to an error exit, the sender will throw an exception, but the response of the subadapter is no longer available anywhere.

Usecase: I have a subadapter that inserts some data in several tables in a database, which needs to roll back if there is an error (which is accomplished with the error-state exit) but also gives back a description of what was wrong to create a message that can be shown to the user. However, that message becomes unavailable as it is replaced by the exception of the sender.

**Reporter**
Ricardo

**To Reproduce**
1. Start the configuration below
2. Use test a pipeline to send a message to it
3. Verify that the returnString of the child is not available in the parent adapter

**Screenshots**

**Configuration**
```
<module>	
	<adapter name="Repro">
		<receiver name="Repro">
			<listener name="Repro" className="nl.nn.adapterframework.receivers.JavaListener"/>
		</receiver>	

		<pipeline>
			<exits>
				<exit path="EXIT" state="success"/>
			</exits>

			<pipe name="Repro" className="nl.nn.adapterframework.pipes.SenderPipe">
				<sender className="nl.nn.adapterframework.senders.IbisLocalSender"
					javaListener="Repro-Child"/>
				<forward name="success" path="EXIT"/>
				<forward name="exception" path="EXIT"/>
			</pipe>
		</pipeline>
	</adapter>

	<adapter name="Repro-Child">
		<receiver name="Repro-Child">
			<listener name="Repro-Child" className="nl.nn.adapterframework.receivers.JavaListener"/>
		</receiver>	

		<pipeline>
			<exits>
				<exit path="EXIT" state="success"/>
				<exit path="ERROR" state="error"/>
			</exits>

			<pipe name="Repro-Child" className="nl.nn.adapterframework.pipes.FixedResultPipe"
				returnString="Where do I go?">
				<forward name="success" path="ERROR"/>
			</pipe>
		</pipeline>
	</adapter>
</module>
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
We could provide a 'CallPipe', that is to be used as a replacement of the SenderPipe+IbisLocalSender. To be configured like:
```
<pipe name="Repro" className="nl.nn.adapterframework.pipes.CallPipe" javaListener="Repro-Child">
	<forward name="success" path="EXIT"/>
	<forward name="exception" path="EXIT"/> <!-- names of forward refer to names of exits of pipeline of JavaListener -->
</pipe>
```
