### ISSUE TITLE
reset connection error when using a token solution

### ISSUE THREAD

**Issue by BonnoSmeele** [ibissource/iaf#3472]
**Describe the issue**
When using a http sender with a token endpoint the ibis will occasionally come up with a connection reset error:

nl.nn.adapterframework.core.SenderException: (SSLException): (SocketException) Connection reset

**Reporter**
Bonno Smeele

**Screenshots**

**Configuration**

			<SenderPipe 
				name="CallSalesForcePostClaimDocument"
				storeResultInSessionKey="PostContentVersionResults">
				<HttpSender  
					truststore="ibis4salesforce_truststore.jks"
					truststoreAuthAlias="salesforce_truststore"
					allowSelfSignedCertificates="true"

					tokenEndpoint="${salesforce.url.base}/${salesforce.url.oauth_service}"
					clientAlias="salesforce_client"
					authAlias="salesforce"
					
					headersParams="Accept"
					urlParam="postDocumentURL"
					methodType="POST"
					timeout="${salesforce.timeout}"
					resultStatusCodeSessionKey="resultCode"

					multipartXmlSessionKey="multiPartXML"
					postType="FORMDATA"
										
				/>
				<Param name="Accept" 			value="application/xml" />
				<Param name="postDocumentURL" 	sessionKey="postDocumentURL" />
				<Forward name="timeout" 	path="TimeOut" />
				<Forward name="success" 	path="RoutePostClaimDocumentResults" />
				<Forward name="exception"	path="BackEndError" />
			</SenderPipe>

**Input**

[Pipeline PostClaimDocumentAdapter (2).zip](https://github.com/ibissource/iaf/files/9039420/Pipeline.PostClaimDocumentAdapter.2.zip)

**Environment**
FF! 7.8-20220601.133926: ibis4salesforce_claim_document
Running on ip-10-186-217-4.eu-west-1.compute.internal using Apache Tomcat/9.0.60
Java Version: OpenJDK Runtime Environment (1.8.0_332-b09)
Heap size: 441M, total JVM memory: 782M
Free disk space: 25GB, total disk space: 30GB
Up since: 2022-06-29 16:55:52 (4d)

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
see farther up

**Comment by gvanbrakel** [comment]
When we were earlier confronted with the SocketException problem, we did not really address it, but circumvented it with a retry mechanism. This retry mechanism does, however, only work in a limited number of cases. Some types of requests (or responses?) appear to be not retryable. 
I think we now need to really analyse and fix the SocketException problem, to really reduce the number of occurrences of then. This also holds for #3471

**Comment by gvanbrakel** [comment]
suggested to set tokenExpiry="10000"

**Comment by jjansenvr** [comment]
@BonnoSmeele is this fixed by the setting so we can close this issue?

**Comment by nielsm5** [comment]
Seems to have been fixed? If not, please re-open this issue and provide us with more information.
