### ISSUE TITLE
JDBCQueryListener is not working properly with IAF version 7.7.2-20220624.150623

### ISSUE THREAD

**Issue by CBiplab** [ibissource/iaf#3538]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
JDBCQueryListener is picking up the initial record from the database and the adapter starts processing. But the processing stops after sometimes without finishing entire transactions. FYI, this works fine with IAF version: 7.0-RC3
![console](https://user-images.githubusercontent.com/38505235/181207438-5198650d-3ccd-48b0-84fc-1f0ec0581acb.JPG)
![ladybug](https://user-images.githubusercontent.com/38505235/181207450-46232315-56e8-4570-b23e-8d42e95b3f0f.JPG)
[Logs_JdbcQueryListener.zip](https://github.com/ibissource/iaf/files/9196746/Logs_JdbcQueryListener.zip)
[Pipeline HandleGPAMessage (7).zip](https://github.com/ibissource/iaf/files/9196750/Pipeline.HandleGPAMessage.7.zip)
[SystemOut.txt](https://github.com/ibissource/iaf/files/9196751/SystemOut.txt)

**Reporter**
Biplab Chakraborty

**Screenshots**
nl.nn.adapterframework.core.SenderException: [nl.nn.adapterframework.jdbc.FixedQuerySender] [Insert ContactPointUsage into Address table-sender] got exception executing query [INSERT INTO ADDRESS(PERSONID,PPMODIFICATIONDATETIME,ADDRESSID,CONTACTTYPE, CONTACTUSES,ADDRESSCHECKIND,STREET,HOUSENUMBER,HOUSENUMBERADDITION,POSTALCODE,CITY,COUNTRY) VALUES(?,TO_DATE(?,'YYYY-MM-DD HH24:MI:SS'),SEQ_ADDRESS.NEXTVAL,1,3,?,?,?,?,?,?,?)]: (StaleConnectionException): (SQLRecoverableException) SQLState [08006], errorCode [17002]: IO-fout: (InterruptedIOException) Socket read interrupted

---------------------------------
![image](https://user-images.githubusercontent.com/38505235/181206563-f997a60f-eac7-42c8-a1e8-8f1ae372164a.png)

**Configuration**
```
Please find the attachments.
```

**Input**
```
Please find the attachments.
```

**Environment**
```
FF! 7.7.2-20220624.150623: Ibis4Baco
Running on srdzzapp0479.insim.biz using IBM WebSphere Application Server/9.0.5.10
Java Version: Java(TM) SE Runtime Environment (8.0.7.0 - pxa6480sr7-20211025_01(SR7))
Heap size: 1192M, total JVM memory: 2048M
Free disk space: 762MB, total disk space: 2GB
Up since: 2022-07-26 17:48:22 (17h)
```

**Additional Environment**
 - DBMS: [Oracle]
 - Browser: [Chrome, Edge]

**Comment by gvanbrakel** [comment]
The logs in [Logs_JdbcQueryListener.zip](https://github.com/ibissource/iaf/files/9196746/Logs_JdbcQueryListener.zip) are two months older than the issue

**Comment by gvanbrakel** [comment]
I am able to reproduce the problem with the configuration:
```
<pipeline transactionAttribute="RequiresNew">
	<SenderPipe name="prepareTable1" >
		<FixedQuerySender 
			queryType="other"
			query="DELETE FROM IBISTEMP WHERE TKEY = 2639"
		/>
	</SenderPipe>
	<SenderPipe name="prepareTable2" >
		<FixedQuerySender 
			queryType="other"
			query="INSERT INTO IBISTEMP (TKEY, TCHAR, TVARCHAR) VALUES (2639,'A','regel')"
		/>
	</SenderPipe>
	<XsltPipe name="createDocument1" styleSheetName="TransactedOutputStreaming/createDocument.xslt" />
	<ForEachChildElementPipe name="iterate">
		<FixedQuerySender 
			queryType="other"
			query="UPDATE IBISTEMP SET TCHAR='Y' WHERE TKEY=2639"
		/>
	</ForEachChildElementPipe>
</pipeline>

```
It appears that when performing output streaming, there is no proper call to beginChildThread()
