### ISSUE TITLE
HttpSender configuration improvement

### ISSUE THREAD

**Issue by dirkjanp** [ibissource/iaf#3579]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Currently when a new property is defined to be used by a SenderPipe of type HttpSender to a certain backend, you have to add this property also in the code in every place where you have a HttpSender to this backend.
It would be easier if you only have to define the property in the DeploymentSpecifics.properties and that all HttpSenders to the backend that need this property automatically use this property. This also reduces the chances for mistakes or forgetting setting the property in the HttpSender.
Ideally it should still be possible to override the global property in the DeploymentSpecifics.properties by adding it in the HttpSender.

**Reporter**
Dirk-Jan Petersen

**Additional Context**
Discussed today (17-8-2022) in a call with Jeroen and he already has some ideas about this.

**Comment by jjansenvr** [comment]
We discussed in the core meeting to look at a concept where http sender can implement a connection pool like realm. using the same settings but also reusing tokens and connections when possible
