### ISSUE TITLE
JavaListener reference became case-sensitive after upgrade to FF 7.7.2

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#3603]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
After upgrading to 7.7.2 a javalistener reference in a scheduler could not find the apropriate listener

error while executing job [SendMessageJob name [start-sapcd-vta-023-034] jobGroup [collections] cronExpression [0 15 10,11,12,13,14,15,16,17,18,19,20,21,22,23 ? * * *]] (as part of scheduled job execution): unable to send message to javaListener [SAPCD-VTA-023-034]: could not find JavaListener [SAPCD-VTA-023-034]

after correcting the case of the java listener the process is working fine.

I have not seen a backward compatibility issue mentioned in the release notes so I guess this is a bug

**Reporter**
Jjansenvr

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7.3-20220818.151908: ibis4solife
Running on srtzzapp0446.insim.biz using IBM WebSphere Application Server/9.0.5.10
Java Version: Java(TM) SE Runtime Environment (8.0.7.0 - pxa6480sr7-20211025_01(SR7))
Heap size: 746M, total JVM memory: 1240M
Free disk space: 2GB, total disk space: 2GB
Up since: 2022-08-22 16:39:48 (1d)```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
I do not believe this behavior has been changed, are you sure nobody changed the listener's name?

**Comment by ricardovh** [comment]
This was an developer error during upgrade, the job attributes changed from adapterName+receiverName pre-7.7 to javaListener, so during the upgrade the attributes where replaced, but the value was not updated.
