### ISSUE TITLE
Maven warning on Delombok

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#3671]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
During build, the following warning is generated:
```
/core/src/main/java/nl/nn/adapterframework/pipes/MessageSendingPipe.java:140: warning: Not generating setHideMethod(): A method with that name already exists
16:50:59  	private @Getter @Setter HideMethod hideMethod = HideMethod.ALL;
```

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
removing the @Setter annotation from the field will solve this issue
