### ISSUE TITLE
BW5 feature set and get variable

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#3685]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
During the BW5 migration we see the use of get and set variable. This stores structured information ourtside of the scope of a running thread, 

example: 
onstartup of the component a (complex) value is obtained from the database.
onshedule every 15 minutes the database call is executed to update the variable from the database
All running processes use the information from the variable

**Reporter**
JJansenvr

**Comment by jacodg** [comment]
FileSystemPipe and scheduler with interval="0" to run at start-up
