### ISSUE TITLE
JdbcTableListener : CommentField always contains last message from pipeline

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#3695]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The JdbcTableListener populates the commentField with the error message. When there are no exceptions, this field is also populated now with the exitState SUCCESS and the last message from the pipeline :

`exitState [SUCCESS], result [String: <result><fielddefinition><field name="GENERATED_KEYS" type="NUMERIC" columnDisplaySize="40" precision="38" scale="0" isCurrency="false" columnTypeName="NUMERIC" columnClassName="java.math.BigDecimal"/></fielddefinition><rowset><row number="0"><field name="GENERATED_KEYS">10873911</field></row></rowset></result>]`

This causes a lot of background noise.

Before the 7.7 release the comment field was only populated with the error message from the exception, when an exception occurred. 
When the pipeline ended successfully, there was no message written in this column.

We would like to see the commentField only being populated with the exception message if an exception occurs.
And preferably empty if the processing ended successfully.

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**

**Configuration**

**Input**

**Environment**

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**

**Comment by gvanbrakel** [comment]
Oracle treats empty string as null, will change value to null to be consistent over databases
