### ISSUE TITLE
File with tab on local filesystem not found when using canonicalName

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#3696]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**

Considering the following LFS pipe:
![image](https://user-images.githubusercontent.com/37303445/189855253-0ad8e0da-9c0e-4445-8a88-720757b07a8c.png)

With fileName parameter that resolves to:
![image](https://user-images.githubusercontent.com/37303445/189855481-98bbf207-27ce-4322-a9c5-c0efab2e68a9.png)

Output of LFS pipe:
![image](https://user-images.githubusercontent.com/37303445/189855738-0409a1e0-c608-43b6-9ad3-800e5bc4e9b1.png)

Considering the following parameter definition for an XSLT pipe:
![image](https://user-images.githubusercontent.com/37303445/189855889-b3e64828-a259-4826-bde4-2700265315bd.png)

The parameter resolves to:
![image](https://user-images.githubusercontent.com/37303445/189856100-cf30154a-9008-494e-aeac-b43f43ffde87.png)

Considering the following LFS pipe to read the file:
![image](https://user-images.githubusercontent.com/37303445/189856347-9a0551d5-b7e6-4d81-a308-3169b381dda0.png)

Which eventually leads to a file not found exception when trying to read the file in another adapter:
![image](https://user-images.githubusercontent.com/37303445/189856529-2dc63d09-181e-48be-9857-ece870382b68.png)

![image](https://user-images.githubusercontent.com/37303445/189856748-008f6f19-e77e-4a4f-840f-c047d60f9121.png)

**Reporter**
Laurens

**Environment**
```
FF! 7.7: Ibis4X
Running on xxxx.biz using IBM WebSphere Application Server/9.0.5.10
Java Version: Java(TM) SE Runtime Environment (8.0.7.0 - pxa6480sr7-20211025_01(SR7))
Heap size: 689M, total JVM memory: 2048M
Free disk space: 10GB, total disk space: 12GB
Up since: 2022-09-01 09:16:54 (12d)
```

**Comment by gvanbrakel** [comment]
https://docs.microsoft.com/nl-nl/windows/win32/fileio/naming-a-file says that control characters are illegal in file names. This makes this issue hard to reproduce on a laptop.

**Comment by ricardovh** [comment]
Problem is not the filename itself (or that the ibis cannot read the file if the name contains tabs, it actually can), but the fact that XML parsers will normalize attribute values as per https://www.w3.org/TR/xml/#AVNormalize, which is also done on the input XML for XSLT. So when reading file/@canonicalName, the tabs are replaced by spaces, resulting in a difference.

Reproduction adapter:
```
<Module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../FrankConfig.xsd">	
	<Adapter name="Tabs">
		<Receiver name="Tabs">
			<JavaListener name="Tabs"/>
		</Receiver>

		<Pipeline>
			<Exits>
				<Exit name="EXIT" state="SUCCESS" />
			</Exits>

			<FixedResultPipe name="GetTabs"
				filename="xml/Tabs.xml"
				storeResultInSessionKey="XML">
			</FixedResultPipe>

			<LocalFileSystemPipe name="WriteXML"
				root="${log.dir}"
				action="append"
				filename="reprotest.txt"
				writeLineSeparator="true">
			</LocalFileSystemPipe>

			<PutInSessionPipe name="ParamStuff"
				getInputFromSessionKey="XML">
				<Param name="xPathElement" xpathExpression="Test/element"/>
				<Param name="xPathAttribute" xpathExpression="Test/@attribute"/>
			</PutInSessionPipe>

			<LocalFileSystemPipe name="WriteElement"
				root="${log.dir}"
				action="append"
				filename="reprotest.txt"
				writeLineSeparator="true">
				<Param name="contents" sessionKey="xPathElement"/>
			</LocalFileSystemPipe>

			<LocalFileSystemPipe name="WriteAttribute"
				root="${log.dir}"
				action="append"
				filename="reprotest.txt"
				writeLineSeparator="true">
				<Param name="contents" sessionKey="xPathAttribute"/>
			</LocalFileSystemPipe>
			
			<LocalFileSystemPipe name="WriteElementFromXML"
				root="${log.dir}"
				action="append"
				filename="reprotest.txt"
				writeLineSeparator="true">
				<Param name="contents" sessionKey="XML" xpathExpression="Test/element"/>
			</LocalFileSystemPipe>
			
			<LocalFileSystemPipe name="WriteAttributeFromXML"
				root="${log.dir}"
				action="append"
				filename="reprotest.txt"
				writeLineSeparator="true">
				<Param name="contents" sessionKey="XML" xpathExpression="Test/@attribute"/>
			</LocalFileSystemPipe>
			
			<LocalFileSystemPipe name="WriteValuesFromXSLT"
				root="${log.dir}"
				action="append"
				filename="reprotest.txt"
				writeLineSeparator="true">
				<Param name="contents" sessionKey="XML" styleSheetName="xsl/GetAttributeFromMessage.xsl"/>
			</LocalFileSystemPipe>
		</Pipeline>
	</Adapter>
</Module>
```

Contents of Tabs.xml (added as .txt as .xml is not allowed and Github removes the tabs from it):
[Tabs.txt](https://github.com/ibissource/iaf/files/9605338/Tabs.txt)

Content of GetAttributeFromMessage.xsl:
```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
	<xsl:output method="text"/>

	<xsl:template match="/"><xsl:value-of select="Test/element"/><xsl:value-of select="Test/@attribute"/></xsl:template>
</xsl:stylesheet>
```

reprotest.txt output:
[reprotest.txt](https://github.com/ibissource/iaf/files/9605327/reprotest.txt)

**Comment by jacodg** [comment]
Change F!F Aspose code to not use the subject as a filename

**Comment by gvanbrakel** [comment]
Waar komt die filenaam vandaan dan?

**Comment by gvanbrakel** [comment]
Je kan de file ook ${cid} noemen in plaats van ${DOCUMENTNAME}

**Comment by gvanbrakel** [comment]
Er wordt geen illegale XML geproduceerd, daardoor treedt juist de FileNotFoundException op. De filename wordt aangeleverd aan de LocalFileSystemPipe via een sessionKey. Die schrijft de gevraagde file. Vervolgens wordt de canonical filename in een XML attribuut teruggegeven. In dat attribuut wordt de waarde genormaliseerd volgens de XML regels.

**Comment by gvanbrakel** [comment]
Het is in/uit principe geen goed idee om de filenames die je gebruikt te laten bepalen door user input. Het geeft de gebruiker de mogelijkheid om willekeurige files te schrijven op je filesysteem, dat is een security risico.
