### ISSUE TITLE
Parameter or session variable with name [CurrentVersion] in pattern [{Hash}-{CurrentVersion}] cannot be resolved when session key is empty

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#3703]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**

I execute a select query with scalar=true and storeResultInSessionKey=CurrentVersion. This query may return an empty result, later in the pipeline I would like to make use of the pattern attribute on a parameter to concat this value with another.

Whenever the query returns an empty result, the pattern session key resolving fails whilst the session key is there:

![image](https://user-images.githubusercontent.com/37303445/189909210-35deb4fc-cd02-4786-bc2a-9cac64222cb1.png)

I would expect an empty value to be resolved and not this error.

EDIT:
I thought I could implement a work around by adding a PutInSessionPipe after this step with the following parameter:

``<Param name="CurrentVersion" sessionKey="CurrentVersion" defaultValue="None" />``

This results in same error, appearently the defaultValue is not applied since the session key exists here and is considered as not empty.

![image](https://user-images.githubusercontent.com/37303445/189911713-cc94d79f-c8c5-4e3a-8b3e-51c034875a34.png)
![image](https://user-images.githubusercontent.com/37303445/189911890-2dcc0dea-777d-41a4-bec7-e93ce6ab34e1.png)

**Reporter**
Laurens

**Environment**
```
FF! 7.7: Ibis4X
Running on X using Apache Tomcat/9.0.65
Java Version: Java(TM) SE Runtime Environment (1.8.0_341-b10)
Heap size: 876M, total JVM memory: 1748M
Free disk space: 336GB, total disk space: 476GB
Up since: 2022-09-13 14:41:59 (29m)
```

**Comment by gvanbrakel** [comment]
Could you please add the full test report to the issue?
