### ISSUE TITLE
JdbcTableListeners keep on polling on the database while the adapter is stopped.

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#3757]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
We observe that when we stop a config including all adapters, the JdbcTableListeners keep on polling on the database.
Sometimes we need to do maintenance on the database and these queries are interfering that.
Why do the JdbcTableListeners stay active while the adapter is stopped? We expected that when we stop an adapter the JdbcTableListener is also stopped.

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**

**Configuration**

**Input**

**Environment**

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
This is probably due to the console querying the number of records in the process states inProcess, done, error etc.
It should help to close all console windows.
