### ISSUE TITLE
Job without cronExpression or interval is not displayed in IbisConsole

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#3779]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Job without cronExpression or interval is not displayed in IbisConsole

**Reporter**
Gerrit

**To Reproduce**
1. Add a job definition to your configuation like `<SendMessageJob name="testSendMessage" javaListener="xyz" />`
2. Start the application
3. Go to 'Scheduler'
4. See that the job is not in the overview, and there are no warnings.

**Environment**
```
FF! 7.9-SNAPSHOT: Ibis4Test
Running on LPZWNL000040524 using Apache Tomcat/9.0.60
Java Version: OpenJDK Runtime Environment (1.8.0_312-b07)
Heap size: 363M, total JVM memory: 582M
Free disk space: 92GB, total disk space: 476GB
Up since: 2022-09-28 15:22:50 (3m)
```

**Comment by nielsm5** [comment]
Add test to JobDef#configure() to validate either attribute exists :)

**Comment by gvanbrakel** [comment]
It could also be valid to have jobs without interval or cronExpression, to be triggered from the console
