### ISSUE TITLE
SoapWrapper duplicate onlyIf/unless/if functionality

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#3802]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
All FixedForwardPipes have the attributes ifParam and ifValue to enable skipping execution, but on top of that the SoapWrapperPipes (which are also FixedForwardPipes) have additional attributes onlyIfSessionKey/Value and unlessSessionKey/Value, resulting in three methods to achieve the same functionality of skipping (un)wrapping.

I propose to remove the duplicate functionality from the SoapWrapperPipes and only use ifParam/Value as it is more flexible, or move them to the FixedForwardPipe and improve the documentation as to why the different methods exist and when to use which.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
The sessionKey variants can operate without a value, determinine yes or no by the existence of the key
The sessionKey variants do not interfere with the other parameters of the pipe
