### ISSUE TITLE
IncompatibleClassChange error on Production

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#3816]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
After bringing a 7.7.3 version of ibis4titan to production a lot of IncompatibleClassChangeErrors appeared.
Appears be the same as #3395 

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
7.7.3
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Flagged as similar to https://github.com/ibissource/iaf/issues/3395.
