### ISSUE TITLE
parentConfig doesnt work with wrong order of configs in configurations.names

### ISSUE THREAD

**Issue by woutervdschoot** [ibissource/iaf#3843]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**

See title.

Example:

properties in DeploymentSpecifics.properties:
```
configurations.duploimport.parentConfig=COMMON
configurations.REGW.parentConfig=COMMON
configurations.LEGO.parentConfig=COMMON
```

property that is automatically filled:
`configurations.names=ibis4duploos,LEGO,LEGOoutbound,COMMON,duploimport,REGW`

duploimport and REGW have no problems but REGW does and gets the following error:

` error instantiating ClassLoader: failed to locate parent configuration [COMMON]`

**Reporter**
Wouter van der Schoot

**Environment**
```
FF! 7.7.2: ibis4duploos
Running on LPZWNL000032967 using Apache Tomcat/9.0.50
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 484M, total JVM memory: 802M
Free disk space: 131GB, total disk space: 237GB
Up since: 2022-10-11 15:21:35 (1m)
```

**Additional Environment**
 - DBMS: [Oracle]
 - Browser: [Chrome]

**Comment by nielsm5** [comment]
There is not much we can do about this. You cannot build a house unless the required foundation is present.
In this case think of each configuration as a floor in a house, and while constructing the house you wish to build the 3rd floor without having a 2nd floor.

**Comment by woutervdschoot** [comment]
ok, then in cases like this we have to go back to placing the full configurations.names in the deploymentspecifics.properties instead of relying on the automated version
