### ISSUE TITLE
metrics configuration throws exception if authAlias cannot be found

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#3871]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
If management.metrics.export.influx.enabled=true, but no authAlias influx is configured (at least on WebSphere), startup fails with 
```
javax.servlet.ServletException: Filter [springSecurityFilterChain]: could not be initialized
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metricsRegistry' defined in class path resource [SpringEnvironmentContext.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [nl.nn.adapterframework.metrics.MetricsRegistry]: Constructor threw exception; nested exception is java.util.NoSuchElementException: cannot obtain credentials from authentication alias [influx]
```

**Reporter**
Gerrit

**Comment by ricardovh** [comment]
Tomcat:
`2022-10-18 07:12:32,335 FATAL [localhost-startStop-1] {} lifecycle.IbisApplicationInitializer - IBIS ApplicationInitializer failed to initialize
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metricsRegistry' defined in class path resource [SpringEnvironmentContext.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [nl.nn.adapterframework.metrics.MetricsRegistry]: Constructor threw exception; nested exception is java.util.NoSuchElementException: cannot obtain credentials from authentication alias [influx]: alias not found
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1334) ~[spring-beans-5.3.23.jar:5.3.23]`

Wildfly:
`07:15:34,622 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 89) MSC000001: Failed to start service jboss.deployment.unit."iaf-test.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.unit."iaf-test.war".undertow-deployment: java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metricsRegistry' defined in class path resource [SpringEnvironmentContext.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [nl.nn.adapterframework.metrics.MetricsRegistry]: Constructor threw exception; nested exception is io.micrometer.core.instrument.config.validate.ValidationException: influx.apiVersion was 'V2' but it requires 'token' is also configured`

**Comment by gvanbrakel** [comment]
This exception is thrown if the configuration refers to an authentication alias that cannot be found, and no default username or password are configured.
