### ISSUE TITLE
Error on multipart upload to Salesforce INVALID_MULTIPART_REQUEST Cannot include more than one binary part

### ISSUE THREAD

**Issue by nnicovos** [ibissource/iaf#3917]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Using 7.8-RC2 we get the error ><Error><errorCode>INVALID_MULTIPART_REQUEST</errorCode><message>Cannot include more than one binary part</message></Error>on a multipart upload to Salesforce. The same request with 7.8-20220723.114417 works fine.

**Reporter**
Nico Vos

**To Reproduce**

**Screenshots**

**Configuration**

			<pipe name="CallSalesForcePostClaimDocument" storeResultInSessionKey="PostContentVersionResults" className="nl.nn.adapterframework.pipes.SenderPipe">
				<sender truststore="ibis4salesforce_truststore.jks" truststoreAuthAlias="salesforce_truststore" allowSelfSignedCertificates="true" tokenExpiry="10000" tokenEndpoint="https://test.salesforce.com/services/oauth2/token" clientAlias="salesforce_client" authAlias="salesforce" headersParams="Accept" urlParam="postDocumentURL" methodType="POST" timeout="20000" resultStatusCodeSessionKey="resultCode" multipartXmlSessionKey="multiPartXML" postType="FORMDATA" connectionTimeToLive="250" className="nl.nn.adapterframework.http.HttpSender"/>
				<param name="Accept" value="application/xml"/>
				<param name="postDocumentURL" sessionKey="postDocumentURL"/>
				<forward name="timeout" path="TimeOut"/>
				<forward name="success" path="RoutePostClaimDocumentResults"/>
				<forward name="exception" path="BackEndError"/>
			</pipe>

**Input**
See ladybug report

**Environment**
FF! 7.8-RC2: ibis4salesforce_claim_document
Running on ip-10-229-244-165.eu-west-1.compute.internal using Apache Tomcat/9.0.60
Java Version: OpenJDK Runtime Environment (1.8.0_332-b09)
Heap size: 272M, total JVM memory: 706M
Free disk space: 25GB, total disk space: 30GB
Up since: 2022-10-25 14:46:14 (21h)

**Additional Environment**

**Additional Context**

**Comment by gvanbrakel** [comment]
In the fix for this issue the name attribute of the part element has been made optional. Omitting the name attribute avoids a filename being included in the multipart message. The multipart-xml needs to change from:
```
<parts>
	<part name="entity_document" sessionKey="entity_document" mimeType="application/xml"/>
	<part name="versiondata" sessionKey="versiondata" mimeType="image/png"/>
</parts>
```
into:
```
<parts>
	<part sessionKey="entity_document" mimeType="application/xml"/>
	<part name="versiondata" sessionKey="versiondata" mimeType="image/png"/>
</parts>
```
