### ISSUE TITLE
Ladybug report not grouping on pipeline

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#4010]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Sometimes the Ladybug does not correctly group pipes, causing individual pipes being reported, instead of a single pipeline. I don't know what triggers it and it does not happen consistently, but from memory I only see it in cases where a subadapter is involved.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/57142353/202218988-8c59cd5d-b6d1-4be8-aaf7-d1bf32536d64.png)

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7.4
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
Maybe this is fixed with https://github.com/ibissource/iaf/issues/4224
As this issue doesn't tell how to reproduce it I will close it
