### ISSUE TITLE
Adapters with same name in different configurations not handled properly

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#4018]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When having 2 adapters with the same name but in different configurations, no errors are generated, but it does result in erroneous behavior. One adapter is not shown in the console, but might be processing messages. I would expect that loading 2 adapters with the same name in different configurations result in the same error message as when they are in the same configuration.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
- [x] #3964
- [ ] #4046
- [ ] Change adapters endpoint to include configuration information

**Comment by nielsm5** [comment]
> if(StringUtils.isEmpty(configuration)) --> dikke fout. Zie [ShowConfigurationStatus.java](https://github.com/ibissource/iaf/blob/c7e7ed23995db5a9389c79d5c0fd2efa5c960e26/console/backend/src/main/java/nl/nn/adapterframework/management/web/ShowConfigurationStatus.java#L73)

Waarom dan?
