### ISSUE TITLE
JDBC String on security items page used to display host and database user

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#4063]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
![image](https://user-images.githubusercontent.com/37303445/203725777-e42d87de-65de-4617-8c00-8829954c929c.png)

This page used to display here the full JDBC string, including host and database user. 

**Reporter**
Laurens

**Comment by nielsm5** [comment]
I require a bit more information, what's the log level set to? And do you see any warnings in the logging?

**Comment by nielsm5** [comment]
Ah, yea in the 7.7 release you can only see the info when using loglevel INFO
https://github.com/ibissource/iaf/blob/7.7-release/core/src/main/java/nl/nn/adapterframework/jndi/TransactionalDbmsSupportAwareDataSourceProxy.java#L98
