### ISSUE TITLE
TransactionalStorage MessageLog option to exclude elements/parts of the message

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#4154]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Currently the messagelog either stores the complete message or nothing (depending on `storeFullMessage`), it is possible to mask certain parts (depending on `hideRegex`), but it is not easily possible to omit parts of it.

Usecase: I'm sending XML with base64 encoded files in it, and for traceability I want to store the sent XML in the messagelog but without the base64 parts to reduce storage requirements. 

In this specific case I was able to work around it by storing both XMLs in separate session keys and use a SenderWrapperSender to get the full XML to the sender, but this complicates the pipeline and does not work for receiver messagelogs. 

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.8-RC3-20221206.094959: Frank4*****
Running on LPZWNL000033867 using Apache Tomcat/9.0.56
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 136M, total JVM memory: 386M
Free disk space: 60GB, total disk space: 237GB
Up since: 2022-12-08 15:06:14 (18m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
It could be an option to use the LogContextPipe to put the required part of the message in a log context key

**Comment by jacodg** [comment]
Workaround available (we close the issue until more people need it):
<SenderPipe name="SendTo..." getInputFromSessionKey="MessageWithoutBase64">
	<JdbcMessageLog slotId="..."/>
	<SenderWrapperSender getInputFromSessionKey="MessageWithBase64">
