### ISSUE TITLE
LoadDatabaseSchedules deletes not stored schedules

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#4161]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When having loadDatabaseSchedules.active=true, there is the option to add schedules, and that page has the option to `Store in Database`. Deselecting that option results in the job being deleted by the LoadDatabaseSchedules job that runs every minute by default. I would expect that either my manually added job would survive the LoadDatabaseSchedules job (at least until my added job fired at least once), or that I just don't have the option to deselect `Store in Database` in database.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.9-20221207.174335: ibis4repro
Running on LPZWNL000033867 using Apache Tomcat/9.0.56
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 301M, total JVM memory: 572M
Free disk space: 63GB, total disk space: 237GB
Up since: 2022-12-09 15:46:02 (20m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
Remove store in database checkbox (always store)
