### ISSUE TITLE
Not stored job gets stored on edit

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#4162]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When manually adding a schedule when loadDatabaseSchedules.active=true, it is possible to not store it in the database. When editing the job after creating it without Store in Database, it is stored in the database. The checkbox for Store in Database is disabled but checked on the edit screen, I suspect that that one is not correctly set during page load and then sends it state to save the schedule in the database on save.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.9-20221207.174335: ibis4repro
Running on LPZWNL000033867 using Apache Tomcat/9.0.56
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 301M, total JVM memory: 572M
Free disk space: 63GB, total disk space: 237GB
Up since: 2022-12-09 15:46:02 (20m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
Resolved when select is removed as described in #4161
