### ISSUE TITLE
actively  detecting JMS problems when no messages have been processed for x period of time

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#4171]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When jms is not able to push messages on JMS due to authorisation no message is displayed
When reading from a queue and getting authorisation error the ibis does not know and adapters stay green, reload triggers the errors

**Reporter**
jjansenvr

**possible solution**
actively test jms connections

**Comment by nielsm5** [comment]
Dit zou de pollguard moeten doen?
