### ISSUE TITLE
can streaming disabled by default and an option to turn on?

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#4172]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Streaming makes the debugging with ladybug impossible, i do not see what is happening, in most cases I do not want to use streaming as I do not have anything to stream to.

**Reporter**
jjansenvr

**Comment by jacodg** [comment]
Done!
