### ISSUE TITLE
Why are un-authenticated OPTIONS calls towards FF API allowed but not towards API exposed by adapters?

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#4237]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
In the web.xml provided by the framework there is a certain statement that un-authenticated HTTP OPTIONS are allowed towards the FF API. 

Shouldn't the framework also provide the same for `/api/*`? We are currently in the process of detaching our frontend from our backend and are running into CORS errors, which are fixed when the following is added to web.xml:

```
	<security-constraint>
		<web-resource-collection>
			<web-resource-name>FFAPI</web-resource-name>
			<description></description>
			<url-pattern>/api/*</url-pattern>
			<http-method>OPTIONS</http-method>
		</web-resource-collection>
	</security-constraint>
```

**Reporter**
Laurens

**Comment by nielsm5** [comment]
```
        List<HttpMethodConstraintElement> methodConstraints = new ArrayList<>();
        methodConstraints.add(new HttpMethodConstraintElement("OPTIONS"));
        return new ServletSecurityElement(httpConstraintElement, methodConstraints);
```
Will allow all options requests, though if we do this, both TODO statements in the `ApiListenerServlet` also must be implemented.
NB, this should only be set for the `ApiListenerServlet` and no other servlets.

**Comment by Laurens-makel** [comment]
@nielsm5 @jacodg 
What about this issue?

We are running into another situation in which we would have to add the statement from the original post, whilst we would rather not have a custom web.xml, it always results in wasted time debugging silly issues during upgrrades.

**Comment by nielsm5** [comment]
We're doing the best we can to plough through the current list of [issues for the 7.9](https://github.com/orgs/ibissource/projects/3/views/6). We're desperate to keep this list as small as possible in order to get a move on with our next release. This issue IS on that very list, and we're hoping to finalize the 7.9 release Q4 this year.
