### ISSUE TITLE
Apilistener consumes=JSON also allows XML inputs

### ISSUE THREAD

**Issue by dirkjanp** [ibissource/iaf#4241]
**Describe the issue**
An Apilistener adapter with property consumes=JSON also processes XML an input body. I would expect a bad_request.

**Reporter**
Dirk-Jan

**To Reproduce**
1. Create an Apilistener adapter with consumes=JSON property
2. Send an XML body input to the adapter

**Comment by tnleeuw** [comment]
@dirkjanp Can you please give me a bit more information?
Do you have a sample-XML file
How do you offer the XML to the ApiListener in your request?

**Comment by tnleeuw** [comment]
As far as I can see from the provided information, the cause of the issue is that the "Content-Type" header is not set in the request.
When this header is not provided, any content is accepted (no content type derivation is done on the actual content in the request).

@nielsm5 Should we add derivation of content-type using Apache Tika when the "Content-Type" header is not provided in the request?

**Comment by nielsm5** [comment]
I think that when you explicitly provide the consume attribute, the request must match. If no Content-Type is provided it should reject the message. 
If the goal is to detect the Content-Type you have set the consume attribute to `DETECT`. I don't think this has been implemented for consumes, only for produces. (I'd expect listener.processRequest to detect it before processing the request)

**Comment by tnleeuw** [comment]
But if you set the "consume" attribute to `DETECT` then you cannot enforce that content-type must match JSON, XML, or any other, right? So that is different functionality.

**Comment by nielsm5** [comment]
I agree, though I do think it would be handy to have such functionality, but I agree this is not the correct place. I Just did a few small tests, and did notice a small bug when no ContentType has been provided.
As for the the current issue at hand, the message should be rejected when no Content-Type header is present and consumes has been set :)
