### ISSUE TITLE
Suppress "SQL Injections" warning is not possible

### ISSUE THREAD

**Issue by laura-dimitra** [ibissource/iaf#4257]
I cannot suppress the "SQL Injections"-warning in my ibis (IAF 7.7.5).

![warning sql injections](https://user-images.githubusercontent.com/30295058/210232278-43f2aa8f-f714-441e-a449-123bca1e644c.PNG)

My adapters are not using the DirectQuerySender, so it's probably coming from the framework. On Localhost I don't see the warning, but in DEV/TEST it's present.

The warnings.suppress.sqlInjections.ManageDatabase=true in WAR, DeploymentSpecifics.properties doesn't solve this problem as well.
Ali advised me to create a ticket because it's probably a bug.

**Comment by tnleeuw** [comment]
The exact text of the warning as it is given here will be given when the `DirectQuerySender` is used outside the context of an Adapter and thus the suppression of warning with adapter-name in the configuration does not work.

The most likely place from which this warning is triggered, is from the "Security Items" page in 7.7 / 7.8.

@gvanbrakel Looking at the code for `ShowSecurityItems.java` I do not see a way that this actually has any risk of SQL Injections so it should be safe to always suppress that warning from code?
