### ISSUE TITLE
"Cannot start new transaction" when using multiple threads, receiver not transacted

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#428]
**Describe the bug**
Ik ben voor Ibis4SapHCM bezig met aanpassingen aan hoe de Ibis naar een DB schrijft en er weer uit leest om de performance te verbeteren (of in ieder geval met meer threads tegelijk zijn werk kan doen). Nu loop ik er tegenaan dat ik van de database de melding krijg dat het starten van een nieuwe transactie niet mogelijk is. Als ik op internet zoek naar de foutmelding, zou de oorzaak zijn dat de sessie al bezig is met een transactie.

Wordt er vanuit de Ibis een database sessie gedeeld tussen de verschillende pipes/listeners/senders en kan ik dat gedrag overschrijven binnen de Ibis, of zit dat ergens anders?

**Category**
 - Frank Framework

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - Application server (f.e. Tomcat/websphere/JBOSS/Jetty)
 - IAF Version 7.5 RC1

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test) 
[Stacktrace.txt](https://github.com/ibissource/iaf/files/4224064/Stacktrace.txt)

**Comment by ricardovh** [comment]
[Pipeline ExportComposeAndProduceDocuments.zip](https://github.com/ibissource/iaf/files/4225233/Pipeline.ExportComposeAndProduceDocuments.zip)

[ibis4saphcm.log.txt](https://github.com/ibissource/iaf/files/4225244/ibis4saphcm.log.txt)

**Comment by gvanbrakel** [comment]
After reading (https://www.ibm.com/support/pages/dsra0304e-xa-error-xaerproto-oracle-error-code-24776-when-ltc-used-select-update) I suggested to put the receiver in a transaction

**Comment by ricardovh** [comment]
> After reading (https://www.ibm.com/support/pages/dsra0304e-xa-error-xaerproto-oracle-error-code-24776-when-ltc-used-select-update) I suggested to put the receiver in a transaction

Just ran a test, putting the receivers in a transaction seems to have solved the issue.
