### ISSUE TITLE
JQuery 'script-src' can't be fetched due to the Content Security Policy

### ISSUE THREAD

**Issue by philipsens** [ibissource/iaf#4293]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Unable to upload a configuration in the console

**Reporter**
@philipsens @nielsm5 

**To Reproduce**
1. Go to Manage configurations;
2. Click on Browse files;
3. Select configuration;
4. Nothing happens

**Additional Context**
cspheader prevends the upload. The filtes fixes it.

**Comment by Jeffreyon** [comment]
Hi i would like to work on this but I'm having trouble locating the file since I don't know how to setup this project locally to see the bug

I do know how to use Javascript though, and I've come across this issue in a project of mine
