### ISSUE TITLE
OpenAPI 3.0 links are not directing to the right urlMapping

### ISSUE THREAD

**Issue by philipsens** [ibissource/iaf#4299]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
If servlet.ApiListenerServlet.urlMapping is changed, the OpenAPI links will still direct to /api/*

**Reporter**
@philipsens @nielsm5 

**To Reproduce**
1. Set property servlet.ApiListenerServlet.urlMapping to a different url than /api/*
2. Go to webservices in the console
3. Click on a OpenAPI 3.0 link

**Comment by nielsm5** [comment]
Seems to has been partially implemented in #3183
