### ISSUE TITLE
XML2Json pipe does not encode json data 

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#43]
when supplying an XML message 
```
<xml>
<someElement>this will deliver "invalid" json<someElement>
</xml> 
```

{someElement: "this will deliver "invalid" json"}

**Comment by gvanbrakel** [comment]
Duidelijk, ik pak het op. 

groeten,

Gerrit
--
Gerrit van Brakel
[t] +31 6 55 804644 
[e] gerrit@flux-it.nl

**Comment by gvanbrakel** [comment]
is inmiddels opgelost
