### ISSUE TITLE
The same stack trace is logged twice both by the adapter and the receiver

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#4340]
Both the adapter and the receiver log the same error event. Then the receiver logs the same stacktrace with a slightly different message again with warning level.  
Example log file will be emailed.

Todo: reduce the verbose logging or duplication.

**Reporter**
Ali

FF version:
7.8-RC3-20230106.175410

**Comment by tnleeuw** [comment]
The logfile mentioned by Ali would be helpful!

**Comment by jkosternl** [comment]
Got this log file (sanitized it myself) [log.log](https://github.com/ibissource/iaf/files/12578467/log.log)
It contains 3 separate stacktraces: error, error, warning.
