### ISSUE TITLE
Analysis: Replace FileHandler and MoveFilePipe with LocalFileSystemPipe

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#435]
Proof they are compatible, then make MoveFilePipe deprecated
Start with compiling a list of different behaviours of the MoveFilePipe and LocalFileSystemPipe with move-action

**Comment by jjansenvr** [comment]
from what version I can use localfilesystem pipe with option=move?

**Comment by nielsm5** [comment]
Roughly anything later then Sep 17, 2019

**Comment by nielsm5** [comment]
The FileHandler needs to get a deprecation warning as well

**Comment by nielsm5** [comment]
UploadFilePipe should be replaced with LocalFileSystem upload + unzip pipe?

**Comment by alisihab** [comment]
After analysis I concluded that MoveFilePipe has 2 features which are not supported by LocalFileSystemPipe. 
- wildcard => iterate over files that matches with the wildcard (there you may use suffix or prefix to name the files in destination)
- deleteEmptyDirectory => After moving the files delete the directory (might be useful, no additional action is required to remove empty directory)
