### ISSUE TITLE
configuration version not shown for WebAppClassLoader configs

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#4354]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
I would like to see the configuration version of a webclassloader project in the ibis console under manage configurations

**Reporter**
jjansenvr

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/3921911/212654355-862ce2c9-aa71-4ca7-a6c0-1fb7193a34b5.png)

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.8-RC3-20221215.133916: frank2*******_contractpayment
Running on
Java Version: OpenJDK Runtime Environment (1.8.0_352-b08)
Heap size: 222M, total JVM memory: 731M
Free disk space: 26GB, total disk space: 30GB
Up since: 2023-01-16 05:01:54 (6h)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Is the configuration version actually stored in the BuildInfo.properties file?

**Comment by buckmaz** [comment]
The BuildInfo.properties files present in the projects were using old variable names that no longer got correctly resolved in the pipeline. I fixed this and the pipeline is now by default using a central BuildInfo.properties for a easier maintenance and a consequent version syntax for all ibisses (that use the pipeline). Optionally, projects can still add there own BuildInfo.properties and overwrite the default one.

Thanks @nielsm5 for pointing out the existence of this file, which was forgotten by ondergetekende. This issue can be closed.

**Comment by nielsm5** [comment]
For database configurations this is a requirement, for 'normal' configurations it is not. So I can understand why/how it was forgotten. We'll try to document this better as well to hopefully prevent this from happening for other users. 😄

**Comment by VBPham** [comment]
Documentation of the importance and contents of the BuildInfo.properties has been updated with this PR on the 
Frank-manual https://github.com/ibissource/frank-manual/pull/92
