### ISSUE TITLE
Frankdoc shows unresolved @value 

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#4355]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Frankdoc shows  <html>
<body>

datasourceName | The MongoDB datasource | {@value JndiMongoClientFactory#DEFAULT_DATASOURCE_NAME_PROPERTY} |  
database | Database to connect to. Can be overridden by parameter {@value #PARAM_DATABASE}

<br class="Apple-interchange-newline">
</body>
</html>

**Reporter**
jjansenvr

version FF! 7.9-20230111.162530

**Comment by nielsm5** [comment]
Should be fixed in ibissource/frank-doc#146

**Comment by nielsm5** [comment]
Updated and published ;)
