### ISSUE TITLE
MoveFilePipe NullPointerException

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#436]
**Describe the bug**
MoveFilePipe throws NullPointerException. 
I use two different adapters which have the almost same MoveFilePipe configured.
MoveFilePipe in the first adapter(FxfReceiver) works without problems. 
It has a sessionKey restOfthePath set for move2fileSessionKey. This sessionkey is stored in the message store and used in the following pipe(IDV_Publishing_Builder) to set move2fileSessionKey attribute. In IDV_Publishing_Builder MoveFilePipe throws NullPointerException.

**Category**
 - Frank Framework

**To Reproduce**

**Expected behavior**
MoveFilePipe should just work.

**Environment:**
 -7.5-20200211.154830

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test) 
[st.txt](https://github.com/ibissource/iaf/files/4225723/st.txt)

rest of the files has been sent by email

**Comment by nielsm5** [comment]
The movefilepipe has been deprecated. Please try using the localfilesystempipe with action move :)
