### ISSUE TITLE
CXF vulnerabilities backport to 7.7

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#4360]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Upgrade org.apache.cxf:cxf-rt-transports-http to version 3.4.10, 3.5.5 or higher.
Upgrade org.apache.cxf:cxf-core to version 3.4.10, 3.5.5 or higher.

**Reporter**
jjansenvr

**Comment by nielsm5** [comment]
This will break file uploads. The CXF related changes from #3066 need to be backported in order to fix this.
