### ISSUE TITLE
Soap wrapper uses CDATA to wrap reason field 

### ISSUE THREAD

**Issue by BonnoSmeele** [ibissource/iaf#4364]
**Describe the issue**

The output wrapper generates xml wrapped in a CDATA tag if the "errorReason" sessionkey is filled:

 <Result xmlns="http://nn.nl/XSD/Generic/MessageHeader/2">
      <Status>ERROR</Status>
      <ErrorList>
         <Error>
            <Code>ERR6001</Code>
            <Reason><![CDATA[Invalid Request Message]]></Reason>
            <Service>
               <Name>BusinessRulesMortgage</Name>
               <Context/>
               <Action>
                  <Paradigm>Request</Paradigm>
                  <Name>ValidateDepotDeclaration</Name>
                  <Version>1</Version>
               </Action>
            </Service>
         </Error>
      </ErrorList>
   </Result>

I think this CDATA tag should be removed. 

**Reporter**
Bonno!

**To Reproduce**

**Screenshots**

**Configuration**

			<EsbSoapOutputWrapper 
				cmhVersion="2"
				addOutputNamespace="true">
				<Param name="errorCode" sessionKey="errorCode"/>
				<Param name="errorReason" sessionKey="errorReason"/> 
				<Param name="destination" value="${ValidateDepotDeclaration_1.queue}" />
			</EsbSoapOutputWrapper>

**Input**

You can recreate the situation by using a soapwrapperpipe and filling the errorreason and errorcode sessionkeys.

**Environment**
FF! 7.8-RC3-20230106.175410: frank2mortgages
Running on LPZWNL000013838 using Apache Tomcat/9.0.56
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 197M, total JVM memory: 364M
Free disk space: 34GB, total disk space: 237GB
Up since: 2023-01-16 15:18:00 (2d)

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
The usage of CDATA in the stylesheets in /iaf-core/src/main/resources/xml/xsl/esb should be reconsidered
