### ISSUE TITLE
Is warnings.suppress.defaultvalue key no longer supported ?

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#4373]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
I have a frank application which has some default value configuration warnings. When I try to suppress them using by setting the property warnings.suppress.defaultvalue=true I still see the warnings in the console. Is it no longer supported by the framework?
![image](https://user-images.githubusercontent.com/10929856/213508413-a81463c7-bcc6-4966-a4fa-81d6d0ea667e.png)

I don't see an indication of the key being used to suppress the warnings if I search for the occurrences of DEFAULT_VALUE_SUPPRESS_KEY https://github.com/ibissource/iaf/search?q=DEFAULT_VALUE_SUPPRESS_KEY

I faced with this issue in ff version 7.8-RC3-20230106.175410. But the link to the search is in master branch so I believe it is also in 7.9 

**Reporter**
Ali

**Comment by tnleeuw** [comment]
If this had been supported, that support was already not present in 7.7. I think it has never been supported for generic attribute default values, only for the `cacheMode` attribute in the `EsbJmsListener`.

It should be easy to add this support however.

**Comment by alisihab** [comment]
I see that it was there long time ago https://github.com/ibissource/iaf/pull/760. Refactoring must have broken it

**Comment by tnleeuw** [comment]
> I see that it was there long time ago #760. Refactoring must have broken it

I see that this code has been completely rewritten over time and this check is now done in `ValidateAttributeRule`, but the suppression is not checked there.
