### ISSUE TITLE
ibisdoc.xsd flags <XmlValidatorPipe> element and jmsRealm attribute as errors, but the config works

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#441]
I have a Frank config with the following XML:

    <Module
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="./ibisdoc.xsd">
      <Adapter name="IngestBooking">
        <Receiver name="input">
          <ApiListener
              name="inputListener"
              uriPattern="booking"
              method="POST"/>
        </Receiver>
        <Pipeline firstPipe="checkInput"
            transactionAttribute="RequiresNew" >
          <Exit path="Exit" state="success" code="201" />
          <Exit path="ServerError" state="failure" code="500" />
          <XmlValidatorPipe
              name="checkInput"
              root="booking"
              schema="booking.xsd">
            <Forward name="success" path="insertBooking" />
            <Forward name="failure" path="makeInvalidBookingError" />
          </XmlValidatorPipe>
          <FixedResultPipe
              name="makeInvalidBookingError"
              returnString="Input booking does not satisfy booking.xsd">
            <Forward name="success" path="ServerError"/>
          </FixedResultPipe>
          <SenderPipe
              name="insertBooking">
            <FixedQuerySender
                name="insertBookingSender"
                query="INSERT INTO booking VALUES(?, ?, ?, ?)"
                jmsRealm="jdbc">
              <Param name="id" xpathExpression="/booking/@id" />
              <Param name="travelerId" xpathExpression="/booking/travelerId" />
              <Param name="price" xpathExpression="/booking/price" />
              <Param name="fee" xpathExpression="/booking/fee" />
            </FixedQuerySender>
            <Forward name="success" path="getDestinations" />
            <Forward name="failure" path="ServerError" />
          </SenderPipe>
          <XsltPipe
              name="getDestinations"
              styleSheetName="booking2destinations.xsl"
              getInputFromSessionKey="originalMessage">
            <Forward name="success" path="iterateDestinations"/>
            <Forward name="failure" path="ServerError"/>
          </XsltPipe>
          <ForEachChildElementPipe
              name="iterateDestinations"
              elementXPathExpression="/destinations/destination">
            <FixedQuerySender
                name="insertVisitSender"
                query="INSERT INTO visit VALUES(?, ?, ?, ?, ?, ?, ?)"
                jmsRealm="jdbc">
              <Param name="bookingId" xpathExpression="/destination/bookingId" />
              <Param name="seq" xpathExpression="/destination/seq" />
              <Param name="hostId" xpathExpression="/destination/hostId" />
              <Param name="productId" xpathExpression="/destination/productId" />
              <Param name="startDate" xpathExpression="/destination/startDate" />
              <Param name="endDate" xpathExpression="/destination/endDate" />
              <Param name="price" xpathExpression="/destination/price" />
            </FixedQuerySender>
            <Forward name="success" path="Exit"/>
            <Forward name="failure" path="ServerError"/>
          </ForEachChildElementPipe>
        </Pipeline>
      </Adapter>
    </Module>

When I view this adapter in Visual Studio Code with XML schema checking, then there are two errors. First, a red line is shown under the XmlValidatorPipe. Second, red lines are shown below the two jmsRealm attributes. These are not errors because the Frank config works.

The red line below XmlValidatorPipe vanishes if the <Exit> tags are moved to the end of the pipeline.

**Category**
Frank Framework

**To Reproduce**
Copy/paste the mentioned XML into Visual Studio Code or Eclipse. Configure the chosen text editor to validate against the XSD. Get ibisdoc.xsd from Frank!Framework version 7.5-RC1.

**Expected behavior**
There are no XSD violations.

**Environment:**
 - Application server: n/a
 - Browser: n/a
 - IAF Version: 7.5-RC1

**Comment by jjansenvr** [comment]
outdated, please retest against new xsd, if persits please create issue for frankdoc
