### ISSUE TITLE
Broken pipe error 

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#4425]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Once in a while framework logs IOException with Broken pipe message. No clue when and why it happens. I attached the log files.

**Reporter**
Ali

**Environment**
```
AWS
using Apache Tomcat/9.0.60
Java Version: OpenJDK Runtime Environment (1.8.0_352-b08)
```

ff versions:
7.8-RC3-20230123.094613
7.8-RC3-20230106.175410

[st_brokenpipe_2.log](https://github.com/ibissource/iaf/files/10520788/st_brokenpipe_2.log)
[st_brokenpipe.log](https://github.com/ibissource/iaf/files/10520789/st_brokenpipe.log)

**Comment by jacodg** [comment]
The nl.nn.adapterframework.webcontrol.api.ServletDispatcher part in the stacktrace shows this is about a user using the F!F console. The user might have shut down the browser or any other reason for the connection to be broken before F!F was able to send the complete response to the browser. Not something we can fix.
