### ISSUE TITLE
FileViewer readability

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#4426]
**Describe the issue**
It would be nice if the readability of files viewed from the console could be improved, as it is sometimes the only source of information to analyse problems. I would like to suggest:
- to reduce the font size; The font size of the legacy struts console was nice: clear enough to be readable, small enough to fit quite long lines unwrapped on the screen;
- support to toggle between wrapping lines and unwrapped lines (with a possibility to scroll horizontally)

**Reporter**
Gerrit

**Comment by nielsm5** [comment]
Then the file wont be able to load 'streaming'.

**Comment by jacodg** [comment]
In \<link rel="stylesheet" type="text/css" href="ie4.css"> we should prefix ie4.css with iaf/ for AWS loadbalancer
