### ISSUE TITLE
Inconsequent use of Configuration(s) in menu, breadcrum and tabs

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#448]
**Describe the bug**

Sometimes GUI 3.0 is using Configuratio**n** and sometimes Configuratio**ns**.

The menu shows:

Configuratio**n**
  Show Configuratio**n**
  Manage Configuratio**ns**

The breadcrum shows:

Configuratio**ns** > Show (also add Configurations here? Breadcrum should reflect menu items?)
Configuratio**ns** > Manage (also add Configurations here? Breadcrum should reflect menu items?)

At the top of the body page (below the tabs) you see:

Configuratio**n** (also add Show here?)
Manage Configuratio**ns**

**Category**
 - Frank Console

**To Reproduce**
1. Run any recent framework version. For example clone and start Frank!Runner.

**Expected behavior**

Menu:

Configurations
  Show Configuratios
  Manage Configurations

Breadcrum:

Configurations > Show Configurations
Configurations > Manage Configurations

At the top of the body page (below the tabs):

Show Configurations or remove this line as it is already in the breadcrum. Hmm, I see other pages have this too but the names are not 1 on 1 the same as in the menu. For example "Test Pipeline" vs "Test > PipeLine" vs "Test a Pipeline". Would be better to sync menu breadcrum and page title.
Manage Configurations

**Screenshots**

![image](https://user-images.githubusercontent.com/2970084/75192042-c8252100-5753-11ea-9501-6dfbc307002f.png)

**Environment:**
 - Application server: all
 - Browser: all
 - IAF Version: I think already a lot of old version but at least 7.5-20200214.142106

**Additional context**
None

**Comment by nielsm5** [comment]
For now, show configuration has been edited so the breadcrum is consistent with the menu item. The unnecessarily top line has also been removed.
