### ISSUE TITLE
Return response body to pipeline when http sender status code is 4XX or 5XX

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#4487]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Normal behaviour of http based senders is that the response body is returned to pipeline when a success response code is returned, although this does not occur when the external application responds with a status code in the 4XX or 5XX range, in these cases a stacktrace is returned to the pipeline.

![image](https://user-images.githubusercontent.com/37303445/218115754-1686958f-5a99-485b-aa98-2646572dcca8.png)

In a certain use case I want to extract the message from the response body, which is surely possible by applying some tricks and weird xpath expressions, although this should not be required.

I'd like to access the XML in the response body just like I can when the external application responds with a 2XX code.

**Reporter**
Laurens

**Comment by jacodg** [comment]
Probably already possible, need to look at it and improve documentation

**Comment by Laurens-makel** [comment]
@jacodg When inspecting the source code it seems that setting the `resultStatusCodeSessionKey` controls wether an exception is thrown or not.

In my opinion it is a little odd that I have to store the result status code in session to extract the result body....

**Comment by jacodg** [comment]
Sorry, too much work to backport
