### ISSUE TITLE
FtpFileSystemListener and FtpFileSystemSender are missing some attributes

### ISSUE THREAD

**Issue by RayetSena** [ibissource/iaf#4492]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

Describe the issue
FtpFileSystemListener does not have attribute host, port, username, password, remoteDirectory. I was using FtpFileSystemSender now also this one does not have these attributes.
![image](https://user-images.githubusercontent.com/55273803/218424128-b5d341a9-521d-426c-b1df-48ec1ccc507c.png)
![image](https://user-images.githubusercontent.com/55273803/218424393-383520e7-e902-4140-8ce5-45aab298aa13.png)

Reporter
Sena

**Comment by gvanbrakel** [comment]
This appears to be a problem in the FrankDoc generator. The attributes 'host', 'port', 'username', 'password' and 'remoteDirectory' are all present in the interface FtpFileSystemDelegator, that is implemented by the FtpFileSystemListener and the FtpFileSystemSender.

**Comment by RayetSena** [comment]
My problems with Ftp FileSystem Listener still persist. It warns about attributes of FtpFileSystemListener.
ff.version=7.9-20230317.140044
```
<FtpFileSystemListener
                host="localhost"
                port="21"
                username="wearefrank"
                password="pass_123"
                remoteDirectory="/home/wearefrank/dir"
                wildcard="*.csv"
            />     
```         
![image](https://user-images.githubusercontent.com/55273803/226600579-8dfb94af-0b80-439f-8c4e-d1b40ef5852e.png)
![image](https://user-images.githubusercontent.com/55273803/226600845-a3c3271c-7b05-45b4-8e2a-a9eeb5bd0ea4.png)

**Comment by nielsm5** [comment]
Appears to be related to setting the bean properties as well
