### ISSUE TITLE
Gateway time-out when downloading Frank!Doc XSD from Frank!Doc website

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#4499]
**Describe the issue**
When you go to https://frankdoc.frankframework.org/#!/All/XmlSwitch and press the button to download the XSD, you get an error page in your browser. It says: "504 Gateway Time-out".

**Reporter**
Martijn Dirkse

**To Reproduce**
See above.

**Screenshots**
![image](https://user-images.githubusercontent.com/6784732/218765452-a0b3ae0a-fc5e-4486-b618-ed3802b8c90b.png)

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Network issue, not an issue related to the framework.
