### ISSUE TITLE
Improvement suggestions on Manage configurations

### ISSUE THREAD

**Issue by pswapnil1987** [ibissource/iaf#455]
I would like to suggest 4 improvements for under Manage configurations in new GUI:.

1.	Upload config screen: In the “Name” field, values of existing configs should be pre-populated. Many a times , while uploading config, user is not considering case-sensitiveness of the field which results in success message and no desired result. If we pre-populate this field as list of values, user can just select correct config and upload.

2.	Upload config screen: It would be really helpful if we can put artifactory URL of JAR to be uploaded rather than current flow of downloading JAR from artifactory and uploading it again in IBIS. I know we are also planning of CD implementation. Bu till then this feature would help, especially TCT/SM folks who are uploading in ACC/PROD.

3.	Upload config screen: Selecting datasource or realm to JDBC can be avoided. I think this is already fixed in v7.5-RC1.

4.	Manage configurations -> version history : I think we have discussed this before and version numbers need to be sorted in ascending order

**Comment by nielsm5** [comment]
Hi,

1 - this should be done, name and version are now automatically detected.
2 - This may not work as servers do not have access to external resources such as artifactory.
3 - This field is now pre-populated with the default datasource
4 - The latest version is on top, as this is usually the version that's active. Is that what you mean?

**Comment by pswapnil1987** [comment]
4-Although, latest version is on top, remaining versions should be sorted. Currently inactive versions are listed in random order.

**Comment by nielsm5** [comment]
Hey,

Could you give me an example of what it looks like? I've tried multiple version/names and random inserts and deletes but for me the order is always the same.
It should be from new to old, regardless of which version is 'active'.

**Comment by pswapnil1987** [comment]
![version history unsorted](https://user-images.githubusercontent.com/38174443/84854708-f2427c00-b07f-11ea-8733-466eda92e51c.JPG)

Hi Neils,

Please refer to attached file from one of the application. This is from one of the snapshot version of 7.5, not sure if has been fixed in further revisions.

**Comment by nielsm5** [comment]
The reason this is happening is because of JavaScript's default ordering method, as it cannot parse the version as a string, first it sorts the first character [0-1][A-Z], then the 2nd etc etc.
