### ISSUE TITLE
Security Items page shows too much info for qcfs when tm is narayana

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#4561]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
A stacktrace and connections are shown in the gui. The current pool size that is shown in btm is missing

`creationStackTrace=java.lang.Exception at org.apache.commons.pool2.impl.BaseGenericObjectPool.<init>(BaseGenericObjectPool.java:407) at org.apache.commons.pool2.impl.GenericKeyedObjectPool.<init>(GenericKeyedObjectPool.java:263) at org.messaginghub.pooled.jms.JmsPoolConnectionFactory.initConnectionsPool(JmsPoolConnectionFactory.java:104) at org.messaginghub.pooled.jms.JmsPoolConnectionFactory.getConnectionsPool(JmsPoolConnectionFactory.java:602) at org.messaginghub.pooled.jms.JmsPoolConnectionFactory.setMaxConnections(JmsPoolConnectionFactory.java:421) at nl.nn.adapterframework.jta.narayana.NarayanaConnectionFactoryFactory.createConnectionFactoryPool(NarayanaConnectionFactoryFactory.java:65) at nl.nn.adapterframework.jta.narayana.NarayanaConnectionFactoryFactory.augment(NarayanaConnectionFactoryFactory.java:49) at nl.nn.adapterframework.jta.narayana.NarayanaConnectionFactoryFactory.augment(NarayanaConnectionFactoryFactory.java:33) at nl.nn.adapterframework.jndi.ObjectFactoryBase.compute(ObjectFactoryBase.java:66) at nl.nn.adapterframework.jndi.ObjectFactoryBase.lambda$get$0(ObjectFactoryBase.java:61) at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) at nl.nn.adapterframework.jndi.ObjectFactoryBase.get(ObjectFactoryBase.java:61) at nl.nn.adapterframework.jndi.JndiConnectionFactoryFactory.getConnectionFactory(JndiConnectionFactoryFactory.java:40) at nl.nn.adapterframework.jms.JmsMessagingSourceFactory.createConnectionFactory(JmsMessagingSourceFactory.java:84) at nl.nn.adapterframework.jms.MessagingSourceFactory.getConnectionFactory(MessagingSourceFactory.java:70) at nl.nn.adapterframework.jms.JmsMessagingSourceFactory.createMessagingSource(JmsMessagingSourceFactory.java:66) at nl.nn.adapterframework.jms.MessagingSourceFactory.getMessagingSource(MessagingSourceFactory.java:51) at nl.nn.adapterframework.jms.JMSFacade.getMessagingSource(JMSFacade.java:227) at nl.nn.adapterframework.jms.JMSFacade.getJmsMessagingSource(JMSFacade.java:204) at nl.nn.adapterframework.jms.JMSFacade.computeDestination(JMSFacade.java:368) at nl.nn.adapterframework.jms.JMSFacade.lambda$getDestination$0(JMSFacade.java:346) at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) at nl.nn.adapterframework.jms.JMSFacade.getDestination(JMSFacade.java:346) at nl.nn.adapterframework.jms.JMSFacade.getDestination(JMSFacade.java:342) at nl.nn.adapterframework.jms.JMSFacade.getPhysicalDestinationShortName(JMSFacade.java:454) at nl.nn.adapterframework.jms.JMSFacade.getPhysicalDestinationShortName(JMSFacade.java:441) at nl.nn.adapterframework.jms.JMSFacade.getPhysicalDestinationName(JMSFacade.java:473) at nl.nn.adapterframework.jms.JMSFacade$$FastClassBySpringCGLIB$$1a6ea0eb.invoke(<generated>) at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) at nl.nn.adapterframework.extensions.esb.EsbJmsSender$$EnhancerBySpringCGLIB$$82e75dff.getPhysicalDestinationName(<generated>) at nl.nn.adapterframework.pipes.MessageSendingPipe.configure(MessageSendingPipe.java:241) at nl.nn.adapterframework.pipes.MessageSendingPipe$$FastClassBySpringCGLIB$$b131b2cb.invoke(<generated>) at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) at nl.nn.adapterframework.pipes.SenderPipe$$EnhancerBySpringCGLIB$$d80768ed.configure(<generated>) at nl.nn.adapterframework.core.PipeLine.configure(PipeLine.java:321) at nl.nn.adapterframework.core.PipeLine.configure(PipeLine.java:209) at nl.nn.adapterframework.core.Adapter.configure(Adapter.java:176) at nl.nn.adapterframework.configuration.AdapterManager.configure(AdapterManager.java:138) at nl.nn.adapterframework.lifecycle.ConfiguringLifecycleProcessor.configure(ConfiguringLifecycleProcessor.java:33) at nl.nn.adapterframework.configuration.Configuration.configure(Configuration.java:276) at nl.nn.adapterframework.configuration.IbisContext.createAndConfigureConfigurationWithClassLoader(IbisContext.java:367) at nl.nn.adapterframework.configuration.IbisContext.load(IbisContext.java:297) at nl.nn.adapterframework.configuration.IbisContext.load(IbisContext.java:250) at nl.nn.adapterframework.configuration.IbisContext.init(IbisContext.java:130) at nl.nn.adapterframework.configuration.IbisContext.init(IbisContext.java:95) at nl.nn.adapterframework.lifecycle.IbisApplicationServlet.init(IbisApplicationServlet.java:79) at javax.servlet.GenericServlet.init(GenericServlet.java:158) at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1164) at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1117) at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1010) at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4957) at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5264) at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726) at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698) at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696) at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:690) at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1889) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112) at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:583) at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:473) at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1618) at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:319) at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123) at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423) at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366) at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946) at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835) at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396) at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919) at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263) at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432) at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927) at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) at org.apache.catalina.startup.Catalina.start(Catalina.java:772) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345) at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476) , borrowedCount=13625, returnedCount=13625, createdCount=100, destroyedCount=0, destroyedByEvictorCount=0, destroyedByBorrowValidationCount=0, activeTimes=StatsStore [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], size=100, index=25], idleTimes=StatsStore [[6132, 7342, 7343, 7344, 7344, 7344, 7343, 7329, 7061, 6178, 6178, 6178, 6181, 6189, 6189, 6219, 6220, 6215, 6218, 6267, 6664, 7989, 7976, 7976, 7977]], size=100, index=25], waitTimes=StatsStore [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], size=100, index=38], maxBorrowWaitDuration=PT0.02S, swallowedExceptionListener=null, maxIdlePerKey=100, minIdlePerKey=1, maxTotalPerKey=100, factory=org.messaginghub.pooled.jms.JmsPoolConnectionFactory$1@5ee79318, fairness=false, poolMap={org.messaginghub.pooled.jms.pool.PooledConnectionKey@e8be0=ObjectDeque [idleObjects=[Object: ConnectionPool[XAQueueConnection[ClientId=null, Connected=MASKED, URL=MASKED,MASKED]], State: IDLE, Object: ConnectionPool[XAQueueConnection[ClientId=null, Connected=MASKED, URL=MASKED,MASKED]], State: IDLE, Object: ConnectionPool[XAQueueConnection[ClientId=null, Connected=MASKED, URL=MASKED,MASKED]], State: IDLE, Object: ConnectionPool[XAQueueConnection[ClientId=null, Connected=MASKED, URL=MASKED,MASKED]], State: IDLE, Object: ConnectionPool[XAQueueConnection[ClientId=null, Connected=MASKED,.......`
**Reporter**
Ali

ff: 7.8-RC3-20230221.160953

**Comment by nielsm5** [comment]
See https://github.com/ibissource/iaf/pull/5142 for the fix in the master branch.
