### ISSUE TITLE
HTTP RestListener does not handle Content-Type correctly

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#458]
**Describe the bug**
The HTTP RestListener does not handle the HTTP Content-Type Header correctly. On the request-side it is not set in the contentType SessionKey, and on the output side it is not (correctly) set, resulting in character set errors.

**Category**
 - Frank Framework

**To Reproduce**
1. Load the attached ConfigurationRESTTest (rename file to .xml)
2. Use SOAPUI or similar to send a message to this adapter (SOAPUI automatically sets the Content-Header to text/xml;charset=UTF-8
3. Open the message in Ladybug
4. SessionKey contentType is empty
5. SOAPUI does not parse response correctly in XML view
6. Content-Type header is not returned to SOAPUI

**Expected behavior**
The contentType SessionKey  and Content-Type HTTP header of the response to be set

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/websphere/JBOSS/Jetty): Tomcat, Websphere
 - Browser [e.g. chrome, safari]: N/A
 - IAF Version [e.g. 7.4]: 7.5-RC1

**Additional context**
[Pipeline RESTTest.zip](https://github.com/ibissource/iaf/files/4256852/Pipeline.RESTTest.zip)
[ConfigurationRESTTest.txt](https://github.com/ibissource/iaf/files/4256857/ConfigurationRESTTest.txt)
Example input: <Test>äbcdéfghîjklmnòpqrstuvwxyz</Test>

**Comment by ricardovh** [comment]
A workaround is available, setting the contentTypeSessionKey on the RestListener and have a PutParamInSessionKey-pipe to set that session key to the required value.

**Comment by nielsm5** [comment]
The contentTypeSessionKey is not set by default. If you wan't to set a contentType you will have to set the attribute on the listener and somehow provide the value in your pipeline as you already figured out.

The contentType sessionkey will be populated with the request contentType. See: 
![image](https://user-images.githubusercontent.com/4375703/84749675-8d711e00-afba-11ea-9adb-732fb0371b7f.png)

**Comment by ricardovh** [comment]
See workaround in comments above.
