### ISSUE TITLE
Feature Request: Configurable label in Ladybug

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#459]
**Is your feature request related to a problem? Please describe.**
If I have a pipeline that serves as central entrypoint to route messages to different adapters, I get a lot of entries in the Ladybug that have the same Pipe. From another team I got the request to have a way to differentiate requests with some label determined from the content of the input message.

**Describe the solution you'd like**
An additional column that can be filled with a value from the input message using XPath. This way there is freedom to put in some functional description and allows searching on specific messages.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nielsm5** [comment]
Could you add your issue/feature request to the ladybug project? We can't do this through the FF!

**Comment by ricardovh** [comment]
Feature already exists
