### ISSUE TITLE
Add xmlns:xs declaration to ForEachChildElementPipe

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#4658]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When a Frank developer would like to make use of functions in the xs namespace such as `xs:date()` and `xs:dayTimeDuration('P1D')` to select elements to iterate over in the `elementXpathExpression` attribute, an error will be thrown that the xs declaration is missing.

An example configuration that does not work:

```
            <ForEachChildElementPipe name="Iterate over files to delete" xsltVersion="2"
				elementXPathExpression="/directory/file[xs:date(@modificationDate) &lt; current-date()-5*xs:dayTimeDuration('P1D')]">
				...

				<Forward name="success" path="READY"/>
			</ForEachChildElementPipe>
```

This is simply solved when the following is added to the ForEachChildElementPipe:

![image](https://user-images.githubusercontent.com/37303445/226575015-43983f43-f044-4ddf-88f4-e7736d630cf8.png)

This issue applies to all running releases: 7.7, 7.8 and master 7.9.

**Reporter**
Laurens

**Comment by jacodg** [comment]
Isn't it possible to use namespaceDefs?

**Comment by Laurens-makel** [comment]
It was a bit hard to figure out the desired syntax but the following works
`namespaceDefs="xs=http://www.w3.org/2001/XMLSchema"`
