### ISSUE TITLE
GUI 3.0 freezing on Firefox

### ISSUE THREAD

**Issue by dansebmey** [ibissource/iaf#467]
**Describe the bug**
At seemingly random moments, the GUI 3.0 interface seems to get stuck while loading. This is paired with an infinitely looping loading animation in the top-right corner of the interface, and all tab items appearing slightly different, expanded and unclickable (see screenshot).

The link to GUI 1.2 does work; most of the console's functionality seems to work here, too. However, loading the Ladybug after experiencing this freeze causes it too to never stop loading. This might suggest that the freeze could be related to some part of the Ladybug's loading process?

**Category**
 - Frank Console

**To Reproduce**
1. Go to any Frank's console in Firefox
2. It either loads correctly or doesn't

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/28776293/75881849-333fb900-5e20-11ea-95d0-2bc57c5deeac.png)

**Environment:**
 - Tomcat, WebSphere
 - Firefox
 - F!F 7.6-20200224.113724

**Additional context**
N/A

**Comment by nielsm5** [comment]
Hello, are you still experiencing this issue? Have you checked the logs? 
Is there a way for us to reproduce this?

**Comment by nielsm5** [comment]
Hello,
I'm closing this issue as we've not heard anything for over a month. If you are still experiencing this on the latest version, please reopen the issue!
