### ISSUE TITLE
JSON validator gives error mapping repeating group

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#468]
**Describe the bug**
When xml  message is converted to JSON using the jsonXML validator it runs into a problem on repeating datablocks 

**Category**
 - 
 - Frank Framework

**To Reproduce**
1. open file in ladybug
[Pipeline GetPartiesOnAgreement_7(GET).zip](https://github.com/ibissource/iaf/files/4287653/Pipeline.GetPartiesOnAgreement_7.GET.zip)

**Expected behavior**
groups should be repeating in the json 

**Environment:**
 - IAF Version 7.5-RC1

**Comment by gvanbrakel** [comment]
Error is actually caused by the message not being in the proper namespace.
