### ISSUE TITLE
One of CI build variants should test with "streaming.auto=true"

### ISSUE THREAD

**Issue by tnleeuw** [ibissource/iaf#4731]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**

The default-value for property `streaming.auto` has been changed from `true` to `false`. This changes some fundamental system behaviour.

Previously we always tested with this property `true` but we recommended users to run with it set `false`.

Now we run all CI tests with `streaming.auto=false` but we should configure at least one of the CI builds to run with the property set to `true` explicitly; only in 7.9 (master).

This should be a new variant in the CI so that we can isolate issues caused by the output-streaming. I'm not sure if it matters much which appserver/db/queue combination is used but I would recommend tomcat+narayana / activemq / postgres_xa.

**Reporter**
Core Team

**Comment by philipsens** [comment]
I added it like you asked. 
You can look at `job/ff-ci/job/i-and-t/1848` in Jenkins to view the results.

**Comment by philipsens** [comment]
I've created a separate list to test this against all appservers. `job/ff-ci/job/matrix-optionals/`
