### ISSUE TITLE
XML download in graphical Ladybug can do without languages

### ISSUE THREAD

**Issue by Geert-Jan-DH** [ibissource/iaf#4748]
When downloading an XML wht the graphical Ladybug I'd like to exclude all the language XML-elements.

The XML is much better to read without these language elements, which seems not necessary in must of the cases. Maybe it can be made optional?

The lines are like these:

`<root>
  <row>
    <English>Afar</English>
    <French>afar</French>
    <alpha2>aa</alpha2>
    <alpha3-b>aar</alpha3-b>
    <alpha3-t/>
  </row>
  <row>
    <English>Abkhazian</English>
    <French>abkhaze</French>
    <alpha2>ab</alpha2>
    <alpha3-b>abk</alpha3-b>
    <alpha3-t/>
  </row>
  <row>
    ---`

**Comment by jacodg** [comment]
Can you email me an xml / report with these languages? Then I will add it to the backlog of ZaakBrug
