### ISSUE TITLE
QuartzSchedulerThread DEBUG messages in system out

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#475]
**Describe the bug**
Since 7.6-20200221.172003 messages like the following appear in system out:

19:35:19.128 [scheduler_QuartzSchedulerThread] DEBUG org.quartz.core.QuartzSchedulerThread - batch acquisition of 0 triggers

**Category**
 - Frank Framework

**To Reproduce**
1. Clone Frank!Runner
2. Create build.properties with ff.version=7.6-20200221.172003
3. Start Frank!Runner
4. See the output in the Tomcat window after Tomcat has started (might need to wait a minute)
5. Redo the same steps with ff.version=7.6-20200221.151426 to verify the previous version doesn't have this output

**Expected behavior**
No difference between ff.version=7.6-20200221.172003 and ff.version=7.6-20200221.151426

**Screenshots**
![image](https://user-images.githubusercontent.com/2970084/76151070-06560500-60b1-11ea-871d-5a9993516616.png)

**Environment:**
 - Frank!Runner
 - Browser not applicable
 - IAF Version 7.6-20200221.172003

**Additional context**
-

**Comment by nielsm5** [comment]
Are there any exceptions in the ibis log files? It looks like a faulty cron expression.
It's a bit strange this occurred when we introduced the pgp pipe.

**Comment by gvanbrakel** [comment]
The pgp-pipe introduced the bouncy-gpg library, that has logback as a dependency.
