### ISSUE TITLE
Log line when moving a message to error store

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#4753]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
I'd like to see a log line whenever a message is moved to errorstore. It would be nice to have some metadata in the log event like slotId 

**Reporter**
Ali

[7.8,)

**Comment by jjansenvr** [comment]
it could also be part of the messages log (logcontext) as it needs to be available at all loglevels
