### ISSUE TITLE
XmlValidatorPipe does not work with forward "exception"

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#4839]
**Describe the issue**
I learned that forward `exception` is the generic forward to implement unhappy flows. If anything unexpected happens, for example a negative HTTP response code, forward `exception` is followed. Presently this does not apply for `XmlValidatorPipe`. If the input message does not satisfy the XSD, then forward `failure` is followed. If you put an `XmlValidatorPipe` in your configuration without forward `failure` and with forward `exception`, the adapter does not start and you see an error message in the Frank!Console.

I would expect that it would be possible to omit forward `failure` if forward `exception` is present. If in this case the message does not satisfy the XML schema, the F!F should follow forward `exception`.

**Reporter**
Martijn Dirkse

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
I discovered this when I worked on an exercise in the Frank!Manual. My work now uses forward `failure`, so it would take time to reproduce the problem. I hope this issue is clear as-is, without all the details requested in this form. If not, please give me a note and I will reproduce the issue. I probably have some 7.9 snapshot release.

**Comment by jjansenvr** [comment]
The validator (pipe) has a mandatory failure forward, a functional failure should not be "upgraded" to a exception by default this can be achieved by adding a failure forward pointing to an exception pipe or the exception path
