### ISSUE TITLE
Browse Tables with psql fails on column rownum

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#488]
**Describe the bug**
When using Browse Tables with a PostgreSQL database, browsing fails because column rownum does not exist:
(PSQLException) SQLState [42703]: ERROR: column "rownum" does not exist Position: 45

Using SELECT * FROM <TABLE> on EXECUTE QUERY does work properly.

**Category**
 - Frank Console

**To Reproduce**
1. Go to 'Browse Tables'
2. Fill in a table that exists
3. Send the request

**Expected behavior**
Browsing tables works properly when using PostgreSQL

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/websphere/JBOSS/Jetty): Tomcat
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.4]: 7.5-RC1

**Additional context**
N/A

**Comment by jjansenvr** [comment]
PostgreSQL is not supported yet it is on the list to add

We now support (DB2)/Oracle/MSSQL/MySQL/MariaDB(except XA and multithreaded jdbclisteners)
