### ISSUE TITLE
Restpath property in REST listener is not documented

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#4888]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The restListener has a property restPath that has a default value " /rest "  (this is not mentioned in the frankdoc)

Next to this the restpath is only possible if this is defined in the servlet mapping (xml or properties)

**Reporter**
jjansenvr

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
IAF 7.7 >
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Was fixed in #4916.
