### ISSUE TITLE
Datasource empty in "Browse a JDBC Table" while not empty in "Execute JDBC Query"

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#490]
**Describe the bug**
Datasource empty in Browse a JDBC Table while not empty in Execute JDBC Query.

**Category**
 - Frank Console

**To Reproduce**
1. Go to 'https://***/ibis4oma/iaf/gui/#!/jdbc/execute-query'
2. Datasource list contains jdbc/ibis4oma and jdbc/ibis4oma_mgr
3. Go to 'https://***/ibis4oma/iaf/gui/#!/jdbc/browse-tables'
4. Datasource list is empty

**Expected behavior**
Datasource list at browse-tables should also contain jdbc/ibis4oma and jdbc/ibis4oma_mgr

**Screenshots**
Difficult to make a screenshot of the dropdown list

**Environment:**
 - IBM WebSphere Application Server/8.5
 - Java Version: Java(TM) SE Runtime Environment 8.0.5.27
 - Firefox
 - IAF 7.6-20200224.113724

**Additional context**
-

**Comment by nielsm5** [comment]
Both pages in the GUI use the same API endpoint, so it would be strange that one works while the other doesn't. 
Could you please upgrade to the latest version, and make sure you don't have any custom code that might interfere.

**Comment by nielsm5** [comment]
I'm assuming this has been fixed by upgrading to a newer FF! version?

I'm closing the issue, if this is still happening and is reproducable, please reopen the issue.
