### ISSUE TITLE
As a developer I'd like to be able to access the available Jms properties that are sent as a part of a jms message in pipeline session 

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#4914]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
It would be a nice addition to have an attribute in JmsListener to be able to specify which jms properties need to be in the pipeline session. Just like the headerParams in apiListener. 

**Reporter**
Ali

FF: 7.8, 7.9

**Comment by jacodg** [comment]
Properties are available in the message context see [contextKey](https://github.com/ibissource/iaf/issues/4208#issuecomment-1373788615)
