### ISSUE TITLE
Adding CICS support 

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#497]
**Is your feature request related to a problem? Please describe.**
We would like to be able to integratie with legacy mainframe applications by supporting CICS

**Describe the solution you'd like**
I would like to be able to call the mainframe or be called by the mainframe. 
https://www.ibm.com/support/knowledgecenter/SSGMCP_5.2.0/com.ibm.cics.ts.java.doc/topics/dfhpjlp.html 

We would also need a way to interpret and map the cobol copy book format to xml  
https://www.ibm.com/support/knowledgecenter/en/SSMQ4D_3.0.0/documentation/cobol_rcg_examplecopybook.html

**Describe alternatives you've considered**
none

**Additional context**
https://github.com/camel-extra/camel-extra/tree/master/components/camel-cics/src/main/java/org/apacheextras/camel/component/cics

**Comment by ricardovh** [comment]
IBM uses DFDL to interpret and map XML to/from the Cobol copy book format (and other formats).

https://en.wikipedia.org/wiki/Data_Format_Description_Language

**Comment by jjansenvr** [comment]
no bussiness ned at this moment, wil create new request when it comes up
