### ISSUE TITLE
IOException when encoding with Base64Pipe - IOException: Attempted read on closed stream

### ISSUE THREAD

**Issue by MLenterman** [ibissource/iaf#4972]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
An IOException is being thrown when encoding with the Base64Pipe. The exact configuration was still working with the F!F Docker container from Nexus around 2023-04-17 7.9-SNAPSHOT. 2023-05-23 was the time our end-to-end test failed on this error.

The issue seems to happen in the pipe called `EncodeInhoud`, returning an empty string, while it should return a base64 string. The actual error seems to be thrown in the adapter calling the sub-adapter that executes the `EncodeInhoud` pipe.

**Reporter**
Marcel Lenterman

**To Reproduce**
[zaakbrug.log](https://github.com/ibissource/iaf/files/11704777/zaakbrug.log)
[zaakbrug.log.1.log](https://github.com/ibissource/iaf/files/11704796/zaakbrug.log.1.log)
[Pipeline GetBas64Inhoud and 1 more.zip](https://github.com/ibissource/iaf/files/11704783/Pipeline.GetBas64Inhoud.and.1.more.zip)

**Screenshots**

**Configuration**
https://github.dev/ibissource/zaakbrug/blob/ab08568891a020a7b47df09019d7fba1fc2db232/src/main/configurations/Translate/Configuration_GetBas64Inhoud.xml#L41-L42

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.9-20230607.190024: ZaakBrug
Running on f2c4ca8485e2 using Apache Tomcat/8.5.85
Java Version: OpenJDK Runtime Environment (1.8.0_362-b09)
Heap size: 396M, total JVM memory: 868M
Free disk space: 230GB, total disk space: 251GB
Up since: 2023-06-08 17:26:21 (18h) 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by tnleeuw** [comment]
The cause of this exception must be in the result of the HttpSender that fetches the data.
