### ISSUE TITLE
Backport S3 changes in #4978 to 7.8 release

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#4987]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Appearently #4854 got closed because #4978 was merged into master, but the problem persists in the 7.8 release...

Please backport the S3 related changes in #4978 to the 7.8 release, especially the change regarding closing `f`.

**Reporter**
Laurens

**Comment by jacodg** [comment]
We will give it a try (see if it's not too much work)  but we would rather put energy in releasing 7.9
