### ISSUE TITLE
No link for ibisdoc available in Webservices

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#503]
In the Webservices page of the Frank!Framework, the link is missing to get the Frank!Doc and ibisdoc.xsd.

**Category:** Frank Console

**To Reproduce**
1. Start the Frank!Framework with the Frank!Runner.
2. In the main menu, click "Webservices".

**Expected behavior**
There is a link with a name like "ibisdoc". If you open it, you have links to the Frank!Doc and to ibisdoc.xsd.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/6784732/76761887-8571ca00-6790-11ea-9dbf-7e2ba7171e5b.png)

**Environment:**
 - Frank!Runner
 - Firefox
 - Windows
- IAF version 7.6.20200311.144331

**Additional context**
-

**Comment by nielsm5** [comment]
Can you make sure the adapter has been started?

**Comment by mhdirkse** [comment]
I started the Frank!Runner using start.bat. I observed that adapter WebControlWebservices is running. The ibisdoc link is still missing however.

**Comment by nielsm5** [comment]
I meant the ibisdoc adapter :)

**Comment by mhdirkse** [comment]
This adapter is not present. The word "ibisdoc" does not appear anywhere on the Adapter Status page.

**Comment by nielsm5** [comment]
There's a property which enables/disables the adapter. The property is called 'ibisDoc.active'
If you go to the Environment Variables page, you can see whether this property has been defined, or is set to false. If so, setting it to true will turn on the adapter and thus the IbisDoc.

**Comment by mhdirkse** [comment]
On a local branch, I updated the Frank!Runner to set this property. After starting the Frank!Runner, I could see that the property was set: Copy/pasting from the Environment Variables page gives: 
ibisDoc.active | true. This does not fix the problem.

In the IAF repository, I could also see that ibisDoc.active is set in AppConstants.properties

**Comment by nielsm5** [comment]
I'm afraid I can't really help with this issue, it works on my machine and it works on the ibis4example. Maybe you can compare the configurations/adapters and environment variables?

**Comment by jacodg** [comment]
Did you follow the "To Reproduce"? Then it should not work on your machine. :)

I would say this is related to #509 as the IbisDoc adapter is part of the IAF_Util configuration which is not started, hence the IbisDoc adapter isn't started and the link will not show up under Webservices.

**Comment by mhdirkse** [comment]
Fixed because configuration IAF_Util now works. This is the fix of issue 509.
