### ISSUE TITLE
JMS Acknowledgment not sent

### ISSUE THREAD

**Issue by nielsm5** [ibissource/iaf#5149]
**Describe the issue**
JMS Ack in unreachable code
(https://github.com/ibissource/iaf/blob/master/core/src/main/java/nl/nn/adapterframework/jms/JmsListenerBase.java#L322)

**Reporter**
Ali

**Comment by tnleeuw** [comment]
@alisihab Am I correct that you have set `acknowledgeMode=CLIENT_ACKNOWLEDGE` in your configuration?

I believe the bug of missing ACK / reply-message is only triggered under those conditions.

Also, according to the documentation, this should also only be triggered when not running in transacted mode.

Am I correct on both conclusions?

**Comment by alisihab** [comment]
I was testing with different configurations but that was one of them yes. This is my commit reverting that change:
![image](https://github.com/ibissource/iaf/assets/10929856/6623da3b-4b34-4306-b4ad-20f00fb6cec8)
It has RR protocol thus not transacted


Then I also saw the following line in the log file but not sure with which configuration
https://github.com/ibissource/iaf/blob/master/core/src/main/java/nl/nn/adapterframework/jms/JmsListenerBase.java#L282

the message type was MessageWrapper...

**Comment by tnleeuw** [comment]
The check in code was wrong b/c it should have been `rawMessage.getRawMessage() instanceof javax.jms.Message`

**Comment by alisihab** [comment]
If getRawMessage method exists in rawMessage instance maybe rawMessage is not really a raw message then :)

**Comment by tnleeuw** [comment]
> If getRawMessage method exists in rawMessage instance maybe rawMessage is not really a raw message then :)

Nope the parameter should be renamed `rawMessageWrapper`! 🤣

**Comment by tnleeuw** [comment]
Hi @alisihab ,

Would you be able to help me and provide a small test-case for inclusion in IAF-Test that reproduces the issue?

I've tried to reproduce the problem by making some changes to some existing configurations in IAF-Test but was not able to reproduce.

If you can add a reproducing test, I would highly appreciate.
