### ISSUE TITLE
Manual deployment of the Frank!Framework should work without modifying the deployed webapp

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#519]
**Is your feature request related to a problem? Please describe.**
In the Frank!Manual, it is explained how you can deploy the Frank!Framework manually on an Apache Tomcat application server. If we can document this, we can persuade potential customers that our framework can cooperate with their infrastructure. The student now has to modify the deployed webapplication, because a Frank cannot work without a classes directory.

**Describe the solution you'd like**
It would be nice if the Frank could work without a classes folder, because then the deployed webapplication does not have to be changed.

**Describe alternatives you've considered**
-

**Additional context**
The following procedure should work:
* Create a Docker container with Tomcat 7.0.99.
* Apply the attached shell script within the Docker container (docker exec -it my-container bash)
* On the container, create a directory /home/root/Downloads and clone the Frank!Runner GitHub repository there. We do not use the Frank!Runner, only an example config.
* In /usr/local/tomcat/conf/catalina.properties, set configurations.directory=/home/root/Downloads/frank-runner/examples/Frank2Example1/configurations
* Restart the docker container.

[downloadLibraries.txt](https://github.com/ibissource/iaf/files/4348215/downloadLibraries.txt)

**Comment by nielsm5** [comment]
Part of the PR is the removal of the IAF_Util classloader dependencies
