### ISSUE TITLE
Empty soapHeader sessionKey when soap ns is 1.2 

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#5193]
I use a soapwrapper in a pipeline. When I test the pipeline with soap 1.1 message I can see the `soapHeader ` sessionKey content. However, the session key is empty when soap is 1.2.

config: 
![image](https://github.com/ibissource/iaf/assets/10929856/5b5f22af-fa08-42e5-a2ea-ddc56b936028)

**Reporter**
Ali

FF:  7.9-20230718.190024

**Comment by jkosternl** [comment]
Root cause was that the code always assumed the SOAP version is 1.1 while parsing the header. Now, the parsing of the header is specific on the version found while parsing the message body.
