### ISSUE TITLE
SoapVersion in soapwrapper is ignored when wrapping

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#5207]
I use soap input and output wrappers in a pipeline. SoapInputWrapper has default soapVersion(auto). The outputwrapper has hardcoded soapVersion=1.1. It might be strange that the incoming message could have both soap versions but the outgoing could only have 1.1 (this is another discussion point I think). However, in the outputwrapper I have the flexibility to set the soapVersion to 1.1. I would expect the soapWrapper to look at the soapVersion when adding the soapNamespace instead of getting it from the soapNamespace sessionKey which was filled by the InputWrapper. Therefore, when there is a hardcoded soapVersion in the wrapper the wrapper must take that into account first. If no soapVersion then use soapNamespace sessionkey.

![image](https://github.com/ibissource/iaf/assets/10929856/e57fa061-6486-4934-b4a3-cc3f04a7196c)

**Reporter**
Ali

FF: 7.9-20230802.192100

**Comment by jkosternl** [comment]
Hello @alisihab, I am trying to resolve your issue, but I can not get it reproduced somehow in unit tests, running 2 pipes (unwrapping and wrapping again, specifying the specs you're using). 

Can you please supply me with more information? I'd like to have:

1. full pipeline in XML (as text please), with the <Soap*> tags inside
2. the sent input message for the Soap Pipe, which you used (as text please) 
3. the received output messages which proves this works incorrectly atm (as text please) 

You can add the extra input as attachments or as comment in here. 

Thanks in advance!

**Comment by alisihab** [comment]
I created a unit test to reproduce the issue 
https://github.com/ibissource/iaf/commit/96d50cd05d4a7f08118b4e26dc284f90d3be37fa#diff-830289ae47cee111bf20610f7c398185aa09bca16572236538629bcef97d8191R318

**Comment by jkosternl** [comment]
Thanks @alisihab, I got it fixed and improved now. Used your unit test to add an unit test covering multiple (almost similar) scenario's.
