### ISSUE TITLE
WsdlXmlInputValidator namespace double occurence warning

### ISSUE THREAD

**Issue by BonnoSmeele** [ibissource/iaf#5217]
WsdlXmlInputValidator shows the following warnings in the console

![image](https://github.com/ibissource/iaf/assets/73215587/49969afe-cf93-44f6-9036-9c23bc70b98d)

console:
https://gui-app.tst.ibis.nnbe-mdw-tst.aws.insim.biz/
then go to frank-contract-app

Ali spent a lot of time trying to fix it but it seems to be a bug in the validator. Maybe an import of similarly named XSDs in ibis somewhere?

**Reporter**
Bonno Smeele

**To Reproduce**
1. clone https://gitlab.insim.biz/be_middleware_frank/frank-source/frank2mwp
2. start config contract with batfile
3. see warnigns in console

**Screenshots**

**Configuration**

			<WsdlXmlInputValidator 
				wsdl="Generic/wsdl/ContractDataService.wsdl"
				soapBody="FindPlanForParticipantRequest"
				outputSoapBody="FindPlanForParticipantResponse,Fault"
				reasonSessionKey="errorMsg"
				soapVersion="auto"
				ignoreUnknownNamespaces="true"
				allowPlainXml="true"
				>
				<Forward name="failure" path="RequestValidationFailure"/>
				<Forward name="parserError" path="InvalidXmlError"/>
			</WsdlXmlInputValidator>

**Input**
```
NA
```

**Environment**
FF! 7.9-20230718.190024: frank2mwp_contract
Running on ip-10-233-232-144.eu-west-1.compute.internal using Apache Tomcat/9.0.60
Java Version: OpenJDK Runtime Environment (1.8.0_372-b07)
Heap size: 265M, total JVM memory: 875M
Free disk space: 25GB, total disk space: 30GB
Up since: 2023-08-08 10:32:26 (22m)

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by tnleeuw** [comment]
@BonnoSmeele I will need to know something about the structure of the XSD files to improve either the handling, or the error reporting.

Since these are private, can you send me those in mail or teams?
