### ISSUE TITLE
JdbcQueryListener does not update status

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#523]
**Describe the bug**
When using the JdbcQueryListener, the updateStatusToProcessedQuery and updateStatusToErrorQuery are not executed, resulting in continuous execution of the Listener if filtering on something set in the updateStatus-queries.

**Category**
 - Frank Framework

**To Reproduce**
1. Create a database table with the attached database script
2. Start the attached configuration
3. Add a row to the database table
4. See the adapter running almost continuously
5. Browse the database table and see the status field not being set

**Expected behavior**
the updateStatus-queries are executed correctly.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/websphere/JBOSS/Jetty): Tomcat and Websphere
 - Database: Oracle
 - Browser [e.g. chrome, safari]: N/A
 - IAF Version [e.g. 7.4]: 7.5-RC2

**Additional context**
N/A

[ConfigurationJDBCQueryListenerError.txt](https://github.com/ibissource/iaf/files/4358311/ConfigurationJDBCQueryListenerError.txt) 
[DB-script.txt](https://github.com/ibissource/iaf/files/4358314/DB-script.txt)

**Comment by ricardovh** [comment]
7.5-RC1 does not have this problem.

**Comment by gvanbrakel** [comment]
The configuration is very similar to the JdbcQueryListener configuration in iaf-test.
There the observed behaviour was seen in between 7.5 RC1 and 7.5 RC2 in the scenario \JdbcQueryListener\scenario01 and has been addressed then.
