### ISSUE TITLE
Parameter names must be unique since 7.8 is not mentioned in non-backwards compatible changes

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#5250]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Ran into the following when upgrading to 7.8.1:
![image](https://github.com/ibissource/iaf/assets/37303445/49118bac-ac85-447c-90cc-a263dfb5f0dd)

Even though it's easy to workaround this, I wonder why this is not communicated in the release notes and if this behaviour could be controlled with a property.

For a fixed query sender its quite common to have duplicate parameter names when the same parameter occurs twice in the query executed..

**Comment by nielsm5** [comment]
The code allows duplicate parameter names if useNamedParams is explicitly set to false.
I'll add this to the release notes!

**Comment by Laurens-makel** [comment]
![image](https://github.com/ibissource/iaf/assets/37303445/31a0fd2d-6fef-4b52-afbc-1eb273cd3ae2)

De detectie werkt ook niet top, ik gebruik geen named parameters....

**Comment by Laurens-makel** [comment]
Waarom moet het een `Boolean` type zijn...? een type `boolean` en dus impliciet `false` als default had toch ook gewerkt?

Waarom moet `usedNamedParams` expliciet op false gezet worden?

**Comment by nielsm5** [comment]
Het is een boolean type omdat het gedetecteerd zou moeten worden, wanneer het is niet expliciet gezet is moet het framework dat doen.. ik zie dat dit niet echt gebeurd...
