### ISSUE TITLE
Accept value */*, text/html; causes Json2XmlValidator to return XML instead of JSON

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#5252]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When having an ApiListener with `produces="JSON"` and using the Json2XmlInputValidator to handle data conversion, we would like to respond with JSON.

When a consumer specifies the following Accept header: `*/*;text/html` the consumes check succeeds due to `*/*` but the following code block fails here and will return `text/html` as outputFormat.

Causing errors when translating response that text/html is not a valid value, should be JSON or XML.

Introduced in #5127:
![image](https://github.com/ibissource/iaf/assets/37303445/24346004-cf33-401c-a130-f825ddac7e7d)

![image](https://github.com/ibissource/iaf/assets/37303445/33f81da3-326f-46a6-b870-db0e3f2b62db)

**Comment by nielsm5** [comment]
Accept values are separated by a comma, not a semi-colon. Your accept header appears to be invalid.

**Comment by Laurens-makel** [comment]
Jeroen noticed today that a double Accept header is used in the screenshot, I've double checked and with only Accept set to to `*/*, text/html`, the issue still occurs. 

In the code block of the `Json2XmlValidator` from the original post, if a multi valued Accept header is provided then `*/*` is ignored and the first valid value is accepted without testing if this complies with `produces` attribute of the `ApiListener`.

In my opinion the `*/*` in a multi valued Accept header should not be ignored when all of the other specified content types do not comply with the `produces` attribute. In this case we should comply with `*/*` since we cannot deliver any of the preferred formats, but considering that the consumer also specified `*/*` we should fall-back to our preferred type, which should be derived from the `produces` attribute.

**Comment by Laurens-makel** [comment]
> Accept values are separated by a comma, not a semi-colon. Your accept header appears to be invalid.

I was thinking, the framework accepts the invalid Accept header without any problems. When I specify a `Content-Type` header which does not correspond to the `consumes` attribute when sending a POST/PUT/PATCH, I get a wonderful `415 Unsupported Media Type` error.

When I specify an Accept header which does not match the `produces` attribute, no error is thrown at all. In this case a `406 Not Acceptable` would be a perfect fit. 

I haven't tested the behaviour of specifying an invalid `Content-Type` header, but I kinda assume it will return a 415 as well.

**Comment by jjansenvr** [comment]
After some testing I have the following conclusion:
- API listener detects if the accept header is in sync with the produces tag.  (as Laurens states above) and works correctly
- Json2XmlValidator does the same but does not take in account the produces tag from the api listener.

The nicest solution would be that the api listener takes the incoming accept header and filters out any of the accept headers not compliant with the produces tag

A work around for Laurens (have not tested it) is setting the outputFormat of the Json2XmlValidator to JSON
<html>
<body>


outputFormat | Default format of the result, that is used if the format cannot be found from outputFormatSessionKey or from inputFormatSessionKey (when validating responses and autoFormat=true)Possible values: XML, JSON | XML | enum
-- | -- | -- | --



</body>
</html>

**Comment by Laurens-makel** [comment]
> After some testing I have the following conclusion:
> 
> * API listener detects if the accept header is in sync with the produces tag.  (as Laurens states above) and works correctly
> * Json2XmlValidator does the same but does not take in account the produces tag from the api listener.
> 
> The nicest solution would be that the api listener takes the incoming accept header and filters out any of the accept headers not compliant with the produces tag and forward this to the validator
> 
> A work around for Laurens (have not tested it) is setting the outputFormat of the Json2XmlValidator to JSON
> 
> outputFormat	Default format of the result, that is used if the format cannot be found from outputFormatSessionKey or from inputFormatSessionKey (when validating responses and autoFormat=true)Possible values: XML, JSON	XML	enum

The work around suggested does not work.

We are using a `Json2XmlInputValidator`, which is supposed to do translation of incoming message to XML and translation of the response to a desired format.

By specifying `outputFormat="JSON"`, the incoming message will also be translated to JSON instead of XML...

The only work around applicable here is to refactor the single instance of the `Json2XmlInputValidator` to three separate instances of the `Json2XmlValidatorPipe` (request,  happy flow & error handling), with some tricks the happy flow & error handling ones could possibly be combined into one, but still...

**Comment by jjansenvr** [comment]
As the JSON2XMLvalidator only has 2 different outcomes (TEXT of JSON) I think we should only check for application/xml and application/json all other we should ignore.

Use the first we find, fallback to the default (defined in outputType)
