### ISSUE TITLE
Image to PDF conversion results in empty PDF due to reading inputStream twice (7.8)

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#5254]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
In `PdfImageConvertor.java` class `message.asInputStream()` is called twice.
![image](https://github.com/ibissource/iaf/assets/37303445/18768308-7c0c-4f49-994f-ab71857da1cc)

**7.8.1 behaviour:**
First time:
![image](https://github.com/ibissource/iaf/assets/37303445/428b2a74-aa89-478c-97f5-0e5bbfec3285)

Second time, position is already at last byte...:
![image](https://github.com/ibissource/iaf/assets/37303445/b7457526-485a-4b9d-a14e-70cf14f113bf)

Resulting in an empty file, which is supposed to be a copy of the image.....
![image](https://github.com/ibissource/iaf/assets/37303445/10076e52-feed-42a4-b836-19bffd33ef1c)

Resulting in an empyt pdf...
![image](https://github.com/ibissource/iaf/assets/37303445/5ebe2a10-982e-432e-83ee-ea353ebde61a)

**7.7 behaviour:**
First time:
![image](https://github.com/ibissource/iaf/assets/37303445/547efe8a-062f-4498-b0d1-70a660758729)

Second time:
![image](https://github.com/ibissource/iaf/assets/37303445/fb3384e3-0832-4439-bcde-a7e6fa2c9a29)

**Comment by nielsm5** [comment]
Hmm, maar die code kan ook iets beter geschreven worden...

**Comment by jacodg** [comment]
Quick fix for 7.8
