### ISSUE TITLE
log4j-web-2.20.0.jar (Too many open files)

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#5267]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
An error I came across while doing maintenance on prod.

**Reporter**
Ali

[st.txt](https://github.com/ibissource/iaf/files/12369066/st.txt)

ff- IAF 7.8.1-20230501.190146

**Comment by jacodg** [comment]
This is a limitation of the OS. Are you using CentOS?

**Comment by alisihab** [comment]
Yes, it is CentOS

**Comment by ramanjulu-decos** [comment]
One way to fix this issue is by increasing the File Descriptor limits.

To check current limit
$ ulimit -n 
1024

Below command to check currently opened files
$ lsof  |  wc  -l

Increase the limit with below command
$ ulimit -n 4096
