### ISSUE TITLE
SessionKey empty on 2nd interation when retrieved by HttpSender and not when retrieved by FixedResultPipe

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#5287]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
We have an adapter which retrieves a large XML file using the `HttpSender` and iterates over the results using a `ForEachChildElementPipe` to call a sub adapter.

After upgrading to the 7.8.1 release, this adapter started giving strange errors:

`Caused by: nl.nn.adapterframework.core.SenderException: IbisLocalSender [UpdateArchivesAndSchemas] exception calling JavaListener [UpdateArchivesAndSchemas]: Pipe [Determine_Archive_Type] msgId [testmessage0ace0a6f--3b97492a_18a279551b5_afa] got null input`

After some investigation, it turned out that this occurred on the second iteration.  

I've decided to swap-out the `HttpSender` for a `FixedResultPipe`, which returns the exact same XML and suddenly the error does not occur anymore.

Main adapter:
![image](https://github.com/ibissource/iaf/assets/37303445/0d4baa01-9fcf-4bda-9721-40b71aea9a91)

Sub adapter, highlighted pipe throws exception on second iteration when XML is retrieved by http sender, not when retrieved by fixedresultpipe
![image](https://github.com/ibissource/iaf/assets/37303445/ecc61159-5299-4b79-8243-7b095754b223)

**Comment by MLenterman** [comment]
We have a similar issue with ZaakBrug. For us it only happens with sessionkeys above ~500kb in size and only when overwriting the sessionkey. I have 2 Ladybug reports of the same adapter, one where the sessionkey is under 500kb and it succeeds and one where the sessionkey is above 500kb and it fails. Unfortunatly the report is too big to share on GitHub.

**Comment by Laurens-makel** [comment]
> We have a similar issue with ZaakBrug. For us it only happens with sessionkeys above ~500kb in size and only when overwriting the sessionkey. I have 2 Ladybug reports of the same adapter, one where the sessionkey is under 500kb and it succeeds and one where the sessionkey is above 500kb and it fails. Unfortunatly the report is too big to share on GitHub.

Interesting, some differences:

In my case size does not seem to be of an issue, or haven't really tested it so to say, it sounds feasible that the XML I'm working with exceeds 500kb since it's quite big. Will check later to confirm. 

Another noticable difference is that in my case I set the sessionKey only once and never overwrite it.

**Comment by tnleeuw** [comment]
@Laurens-makel We know the root cause of the issues and I will be looking into a fix this week.

It will be good to have a number of different cases in which it occurs though, so that we can thoroughly test our fixes against all scenarios.

**Comment by tnleeuw** [comment]
@MLenterman @Laurens-makel We do know the cause but not yet all places where that problem is triggered.

So while I'm still doing some investigation into the issue can you please test for me the following:
1. Does the issue still happen when the IBIS Debugger / Ladybug test tool is disabled?
2. Can you work around the issue by specifying the session key in the `returnedSessionKeys` of the sub-adapters which have these session keys are input parameters?
