### ISSUE TITLE
removeCompactMsgNamespaces doesn't remove namespaces on attributes resulting in invalid XML

### ISSUE THREAD

**Issue by MLenterman** [ibissource/iaf#5290]
It happens pretty much everywhere, when the CompactSaxHandler is used. The removeCompactMsgNamespaces attribute also seems to be true by default, at least for the EchoPipe it is. Because attributes still retain their namespace prefixes, but all namespace definitions are removed, it results in invalid XML and will throw errors in any pipe that expects XML as input. Correcting the issues in a later pipe by ignoring or removing namespaces doesn't work either, because the XML is already invalid.

In CompactSaxHandler.java I noticed that "isRemoveCompactMsgNamespaces" is not being checked to determine if the qName or localName should be used.
![image](https://github.com/ibissource/iaf/assets/9280762/4fc703b2-fc33-40e6-bfcc-d7efbc2587c6)

Ladybug report:
[Pipeline SoapEndpointRouter_OntvangAsynchroon - Attribute namespaces not removed.zip](https://github.com/ibissource/iaf/files/12438149/Pipeline.SoapEndpointRouter_OntvangAsynchroon.-.Attribute.namespaces.not.removed.zip)

**Reporter**
M. Lenterman

**Environment**
```
FF! 7.9-20230810.190012: ZaakBrug
Running on 4d7daa431431 using Apache Tomcat/8.5.90
Java Version: OpenJDK Runtime Environment (11.0.20+8)
Heap size: 1233M, total JVM memory: 1520M
Free disk space: 231GB, total disk space: 251GB
Up since: 2023-08-25 11:51:57 (31m) 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Comment by tnleeuw** [comment]
@MLenterman Marcel, since you already did a deep-dive into the code, do you perhaps have a patch that can fix the issue as well?
That would be appreciated and speed up us getting a fix delivered, as we are busy with a number of other important bugs!

**Comment by jkosternl** [comment]
Good finding and thanks for the good screenshot and analyses @MLenterman 
I've just solved it and added some unit tests, proving it (and keeping it proven).
