### ISSUE TITLE
Feature request: Option to hide default adapters from console

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#532]
**Is your feature request related to a problem? Please describe.**
Currently, the console shows all adapters that are loaded. This includes the default adapters for WebControl- and others. These default adapters are not really relevant to show for regular operations and clutters the interface.

**Describe the solution you'd like**
I think these adapters should be hidden by default, and should only become visible when setting a toggle on the console.

Maybe this can be an attribute on the adapter, although it is not really necessary to hide adapters other than the default ones.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nielsm5** [comment]
Once we remove the old GUI all those adapters will disappear!

**Comment by nielsm5** [comment]
It is now possible to turn off the struts console by setting `strutsConsole.enabled=false`.
Does this solution work for you?

**Comment by ricardovh** [comment]
Yes, that will work for me.
