### ISSUE TITLE
Infopoint in validator with: File not found: urn:hello-lines

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#5320]
**Describe the issue**
An extra checkpoint is created in 7.9 that has a message like: File not found: urn:hello-lines
This is not the case with 7.8.1

**Reporter**
Jaco de Groot

**To Reproduce**
1. Run an adapter with a SoapInputValidator with schemaLocation="urn:hello-lines HelloLines/xsd/Lines.xsd" (like in https://github.com/ibissource/frank-runner/blob/master/examples/Frank2Example4/src/main/configurations/Hello%20World)/ConfigurationHelloLines.xml#L35
2. Open the report in Ladybug
3. See checkpoint urn:hello-lines with: File not found: urn:hello-lines

**Screenshots**
\-

**Configuration**
\-

**Input**
\-

**Environment**
```
FF! 7.9-SNAPSHOT: webapp
Running on xxx using Apache Tomcat/9.0.74
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 206M, total JVM memory: 871M
Free disk space: 15GB, total disk space: 475GB
Up since: 2023-08-31 17:33:08 (32m) 
```

**Additional Environment**
\-

**Additional Context**
\-

**Comment by nielsm5** [comment]
Broken since #5095
