### ISSUE TITLE
Support for JMS bytemessage 

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#5444]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
We need to be able to receive and send byte messages over JMS 

**Reporter**
jjansenvr

**Comment by nielsm5** [comment]
Duplicate of #2022

**Comment by tnleeuw** [comment]
I'm treating this as a sub-issue of #2022 since the other issue has a broader scope. That's why I'll put this now in progress.
