### ISSUE TITLE
jfileserver-enterprise dependency not available in nexus repository

### ISSUE THREAD

**Issue by ramanjulu-decos** [ibissource/iaf#5453]
Hi Team,
     Below is the dependency added in iaf-core, which is not available in the nexus repository of frank. How can I resolve this? as I am getting build issue like below

		<dependency>
			<groupId>org.filesys</groupId>
			<artifactId>jfileserver-enterprise</artifactId>
			<version>1.2.15</version>
			<scope>test</scope>
		</dependency>

[ERROR] Failed to execute goal on project ibis-adapterframework-core: Could not resolve dependencies for project org.ibissource:ibis-adapterframework-core:jar:7.9-SNAPSHOT: The following artifacts could not be resolved: org.filesys:jfileserver-enterprise:jar:1.2.15 (absent): Could not find artifact org.filesys:jfileserver-enterprise:jar:1.2.15 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

As per the below attached image nexus repository of frank doesn't have a jfileserver-enterprise dependency

<img width="622" alt="image" src="https://github.com/ibissource/iaf/assets/138098789/b0055a57-17a2-4ed7-8403-01df9e0eb2e8">

**Comment by nielsm5** [comment]
When was the last time you pulled from the master?

**Comment by ramanjulu-decos** [comment]
A week ago

**Comment by nielsm5** [comment]
The file should be in our nexus, proxied via the public repo:
![image](https://github.com/ibissource/iaf/assets/4375703/6dd6bd1b-297b-48dc-bc08-f347595f4518)

**Comment by ramanjulu-decos** [comment]
Got it, Thanks

**Comment by nielsm5** [comment]
I've linked the fix that solve this a few weeks ago :)
