### ISSUE TITLE
Add HeapDumpOnOutOfMemoryError

### ISSUE THREAD

**Issue by nielsm5** [ibissource/iaf#5473]
**Describe the issue**
Add `-XX:+HeapDumpOnOutOfMemoryError` and `-XX:HeapDumpPath=log.dir` to our docker tomcat container.
See our Jenkins WildFly config for more info.

De Java 8 manier van GC kan aan op Java 11: `-XX:+UseParNewGC`
Er zijn verschillende:
```
-XX:+UseSerialGC
-XX:+UseParallelGC
-XX:+USeParNewGC
-XX:+UseG1GC
```

**Reporter**
Core Team

**Comment by philipsens** [comment]
I'll implement it for the Java 8 `frankframework` image.

**Comment by philipsens** [comment]
Add -XX:+HeapDumpOnOutOfMemoryError and -XX:HeapDumpPath=log.dir to our Docker test images.

- [ ] WebSphere
- [ ] WildFly
- [ ] JBoss

**Comment by philipsens** [comment]
Add GC properties for Java 11

```
-XX:+UseSerialGC
-XX:+UseParallelGC
-XX:+USeParNewGC
-XX:+UseG1GC
```
 Or Java 8 method: `-XX:+UseParNewGC`
