### ISSUE TITLE
Upgrade FF! from Java 8 to Java 11

### ISSUE THREAD

**Issue by jkosternl** [ibissource/iaf#5485]
As noted in issue #3503 Java 8 is getting out of support. Therefore we prefer to firstly move our project to Java 11, and later to Java 17. 

**Goal**: move code base and minimum compatibility to Java 11
**Upgrade**: try upgrading a few dependencies which were hold back, because they require Java 11 as a minimum. 
**Not do**: Spring Framework 6+ require Java 17 as a minimum. They moved to the jakarta namespace. This is not possible yet.

**Comment by nielsm5** [comment]
Duplicate issue of #3503.
