### ISSUE TITLE
Empty string parameter fixed value not possible

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#551]
**Describe the bug**
It is not possible to set a parameter value to an empty string "", as it is overwritten by the input message. For example, when using an XsltPipe in which parameters are concatenated this will result in a wrong concatenation if the property which is used for the parameter is the empty string even though the XSLT could handle it.

**Category**
 - Frank Framework

**To Reproduce**
1. PR https://github.com/ibissource/iaf/pull/550 introduces property errorreport.mailaddresses.error
2. In CreateMail.xsl this is concatenated after the other email addresses, and then tokenized (and thus skipped when the property has the empty string)
3. Default value for errorreport.mailaddresses.error is empty and might not be filled (everyone always gets the report regardless of errors)
4. If value is left empty, <dummy/> is filled as parameter value

**Expected behavior**
The possibility to use the empty string as parameter value when setting a fixed value.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/websphere/JBOSS/Jetty): Tomcat
 - Browser [e.g. chrome, safari]: N/A
 - IAF Version [e.g. 7.4]: 7.6-SNAPSHOT (master as of 30-3-2020)

**Additional context**
N/A

**Comment by gvanbrakel** [comment]
A solution / workaround is to configure a non-existing session variable and an empty defaultValue:
sessionKey="dummy" defaultValue=""

**Comment by nielsm5** [comment]
Parameters with no value should get their input from their parent (pipe/sender)

**Comment by ricardovh** [comment]
See workaround in comments above.
