### ISSUE TITLE
replyTo does nothing in MailSender

### ISSUE THREAD

**Issue by Bibi0803** [ibissource/iaf#5611]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
While you are using MailSender to send emails, there is a "replyTo" field in the XML message, in principle when a person wants to reply this email, the email address in "replyTo" field should be selected in stead of "from".

**Reporter**
Bibi

**Environment**
```
FF! 7.7.5: ibis4XXXX
Running on srpzzapp0648.insim.biz using IBM WebSphere Application Server/9.0.5.15
Java Version: Java(TM) SE Runtime Environment (8.0.8.0 - pxa6480sr8-20230314_01(SR8))
Heap size: 1324M, total JVM memory: 2048M
Free disk space: 10GB, total disk space: 12GB
Up since: 2023-09-27 18:40:10 (26d) 
```

**Additional Context**
https://learn.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/bb426434(v=exchg.140)

**Comment by tnleeuw** [comment]
@Bibi0803 In the Frank which has the problem, is the mail message constructed using Sender Parameters, or only using an XML input message?

**Comment by Bibi0803** [comment]
only using an XML input message
