### ISSUE TITLE
The elementToMove on EchoPipe doesn't work anymore

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#5625]
**Describe the issue**
The following was working with 7.9-20230905.223421 but doesn't work anymore with 7.9-20231006.001807:
```
<pipe className="nl.nn.adapterframework.pipes.EchoPipe" elementToMove="inhoud" name="StoreInhoud" removeCompactMsgNamespaces="false">
	<forward name="success" path="ReplaceInhoudRefWithBase64EncodedRef"/>
</pipe>
```
The session key isn't created anymore, see screenshot.

**Reporter**
Jaco de Groot

**To Reproduce**
See the configuration and input below.

**Screenshots**
![image](https://github.com/ibissource/iaf/assets/2970084/21669437-2f1b-4521-a03f-c90d567e4801)

**Configuration**
```
<pipe className="nl.nn.adapterframework.pipes.EchoPipe" elementToMove="inhoud" name="StoreInhoud" removeCompactMsgNamespaces="false">
	<forward name="success" path="ReplaceInhoudRefWithBase64EncodedRef"/>
</pipe>
```

**Input**
```
<inhoud><![CDATA[ some base64 data ]]></inhoud>
```

**Environment**
```
FF! 7.9-20231006.001807: zaakbrug
Running on zaakbrug-5f4c5457-7zkjw using Apache Tomcat/8.5.90
Java Version: OpenJDK Runtime Environment (11.0.20.1+1)
Heap size: 812M, total JVM memory: 2845M
Free disk space: 197GB, total disk space: 248GB
Up since: 2023-10-26 10:54:51 (9m)
```

**Additional Environment**
\-

**Additional Context**
\-

**Comment by tnleeuw** [comment]
@jacodg The fix for this should be in the nightly build of 20231026, with another small improvement to the CDATA handling for restoreElement coming in the 20231027 nightly / 7.9-RC1.

**Comment by jacodg** [comment]
Thanks! Locally it seems to work we are now building and shipping to the client for a test. :)
