### ISSUE TITLE
MultipartUtils.parseParameterField method is not a safe method, throws StringOutOfBoundException or ArrayOutOfBoundException 

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#5718]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The ApiListenerServlet tries to determine if a multipart part is of binary type by checking the filename attribute of the related Content-Disposition header.

When the related Content-Disposition header is incorrectly specified, i.e: `Content-Disposition: attachment; filename=` or `Content-Disposition: attachment; filename="`, the `MultipartUtils.parseParameterField` throws different type of exceptions, resulting in 500 internal server error responses..

![image](https://github.com/ibissource/iaf/assets/37303445/0477430f-a5aa-4b39-b706-9b464a549dad)
![image](https://github.com/ibissource/iaf/assets/37303445/4f07894e-dbca-43da-9d1e-b6c202567216)

Besides that, it also seems to handle filenames which contain the `=` or `;` characters incorrectly:
![image](https://github.com/ibissource/iaf/assets/37303445/59601799-2f61-4b1d-b86d-40755a94d091)
![image](https://github.com/ibissource/iaf/assets/37303445/4919ecc5-3d3c-4332-a98c-0e244ffba18d)

I believe that the framework should validate the attribute before trying to parse it. If it's invalid, it should reply with a 400 Bad Request and a clear message which part of the request is invalid.

**Reporter**
Laurens

**Comment by Laurens-makel** [comment]
Appearently when a filename starts with `=` character, the error related to the stacktrace can be reproduced

![image](https://github.com/ibissource/iaf/assets/37303445/3cc2a004-a401-43c7-b0d3-1df093315e7c)

**Comment by nielsm5** [comment]
Eens, het 'parsen' of lezen van multipart berichten kan sowieso wel een likje krijgen...

**Comment by tnleeuw** [comment]
Fix is in 7.8.3-hotfix4, and will be in 7.9-RC1-hotfix5.
