### ISSUE TITLE
message.log lines have different format in FF 7.8 than in FF 7.7 causing Splunk queries not to work anymore

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#5729]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The formatting of the log lines in message.log are different than before. Our Splunk queries were written with the [] bracket style to retrieve the information, and now these queries/dashboards no longer work.
Why was this changed? As far as I can see, it was not mentioned in the release notes.

FF 7.8.4 message.log line:
2023-11-09 15:11:42,958 [WebContainer : 27] Adapter Success {adapter=TS_XYZ_4, exitState=SUCCESS, listener=TS_XYZ_4-WS, listener.type=WebServiceListener, pipeline.duration=488, result.size=1KB} []
 
FF 7.7.5 message.log line:
2023-11-09 16:12:13,823 [WebContainer : 38] Adapter [TS_XYZ] messageId [0ace18d2-65df28a5_18bb4a3cf50_-792a] duration [1744ms] got exit-state [SUCCESS] and result [SIZE=1KB] from PipeLine

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**

**Configuration**

**Input**

**Environment**

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Extra info:
Receiver doet nu
getAdapter().logToMessageLogWithMessageContentsOrSize(Level.INFO, "Adapter "+(!messageInError ? "Success" : "Error"), "result", result);

Die logt vrij weinig, maar dat komt omdat de meeste log info in de ThreadContext zit.

De messages.log 'appender' zou de threadcontext op de oude manier moeten toepassen key [value] ipv {key=value}

Ik denk dat een eigen thread context pattern nodig is. Denk aan de oude [IbisNdcPatternConverter](https://github.com/ibissource/iaf/blob/7.7-release/core/src/main/java/nl/nn/adapterframework/logging/IbisNdcPatternConverter.java).

**Comment by rvdstel** [comment]
Ik zie dat in de 7.8.4 logging de messageId mist !
In de 7.7.5 logginf staat bijvoorbeeld.: messageId [0ace18d2-65df28a5_18bb4a3cf50_-792a]
In een andere Splunk query gebruiken we namelijk het messageId om een bepaald bericht terug te kunnen zoeken.
Waarom wordt het messageId niet meer gelogd?

**Comment by nielsm5** [comment]
Hij kan alleen een message id toevoegen wanneer die bestaat. Ik zal even moeten kijken hoe het er vroeger uit zag.

**Comment by nielsm5** [comment]
Ik zie dat messageId nu mid en het correlationId cid heet.
