### ISSUE TITLE
Rerun in Ladybug gives error: "First checkpoint isn't a pipeline"

### ISSUE THREAD

**Issue by githubapreinders** [ibissource/iaf#579]
On IAF 7.5-RC2 a rerun in Ladybug gives us the error, while choosing a message from the exceptionlog. A rollback to IAF 7.4 give's a normal response after a rerun.

![Capture](https://user-images.githubusercontent.com/6153602/78347836-57b6be80-75a1-11ea-9786-872322968109.PNG)

**Comment by nielsm5** [comment]
Custom code in the application breaks the framework code that's supposed to trigger the resend
