### ISSUE TITLE
When you forget to check "Active Config", it is difficult to correct

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#586]
**Is your feature request related to a problem? Please describe.**
This is about uploading Frank configs to the database. When you upload the first version of a config, you have to check "Active Config". If you forget, the Frank!Console does not provide an option to activate it. As a workaround, you can issue an SQL query to set field activeconfig, but this requires knowledge about the implementation. This workaround is not suited for operators.

**Describe the solution you'd like**
There should be an option to activate configurations that do not have any active version yet.

**Describe alternatives you've considered**
The "Active Config" checkbox may be checked and disabled when you upload the first version of a configuration.

**Additional context**
This issue was discovered using the Frank!Runner. It applies to Frank!Framework version 7.6-20200403.165415.

**Comment by Laurens-makel** [comment]
Hi Martijn,

Actually you can manually activate a configuration in GUI 3.0 without executing an SQL query. 

You can do so by navigating to **Configurations > Manage** page. Find your desired configuration and click on the name of the configuration. This will lead you to a page that shows you a list of all versions for the specified configuration found in the database.

Find your desired configuration version and check the **Startup Config** checkbox to set that version as the version that will load when you will perform a reload on the specified configuration.

**Comment by mhdirkse** [comment]
Hello Laurens,

I guess your description on how to activate a configuration version applies when you already have some versions of your configurations. This bug is about uploading the first version of a configuration.

Regards,

Martijn Dirkse

**Comment by nielsm5** [comment]
Indirectly the same issue as #705 this has now been fixed.

**Comment by mhdirkse** [comment]
Hello Niels. This issue still occurs on my laptop. Can you reopen it?

**Comment by mhdirkse** [comment]
Hello Niels,

To produce this issue, I do the following:

- Execute query "DROP ALL OBJECTS"
- Restart the Frank!Framework
- Go to Upload Configuration page. Select some config. Uncheck "Activate Config".
- Press "Send".
- Go to the Manage Configurations page. The link to the config is still red, so you cannot use the GUI to activate the config. You can use an SQL query on table ibisconfig, but this is not a user-friendly approach.

I see two possible solutions:

i) The Upload Configuration page detects when you are uploading the first version of a config. In that case, the "Activate Config" checkbox is disabled and checked. Maybe a wizard is needed in this case instead of a single dialog. You first choose the .zip you want to upload. In the next screen, you then have the checkboxes. The Frank!Framework knows what you are going to upload and can use that information to disable "Activate Config".

ii) In the Manage Configurations screen every config can become a link, also configs that have not been uploaded yet.

Regards,

Martijn
