### ISSUE TITLE
Warning about nl.nn.adapterframework.jdbc.XmlQuerySender

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#607]
**Describe the bug**
When you start the Frank!Framework with only an empty classpath configuration, you still see the following warning in the Adapter Status page: "The class [nl.nn.adapterframework.jdbc.XmlQuerySender] is used one or more times. Please change to [nl.nn.adapterframework.jdbc.FixedQuerySender] to avoid potential SQL injections!"

**Category**
 - Frank Framework

**To Reproduce**
1. In your classes directory, put the following configuration:

       <Configuration>
           <jmsRealms>
               <jmsRealm datasourceName="jdbc/frank2manual" realmName="jdbc"/>
           </jmsRealms>
       </Configuration>

2. Start the Frank!Runner with the following line: `start.bat -Djdbc.migrator.active=true -Dconfigurations.names="${instance.name.lc},ibisstore" -Dconfigurations.autoDatabaseClassLoader=true`
3. Watch the Adapter Status page. The warning appears in yellow. Don't mind the error about configuration "ibisstore". It is expected because this configuration is still to be uploaded.

**Expected behavior**
I did not expect the mentioned warning, because I had no adapters using class XmlQuerySender.

**Screenshots**

![image](https://user-images.githubusercontent.com/6784732/79429822-57b6b580-7fc8-11ea-86c6-eaba23eb04b9.png)

**Environment:**
 - Frank!Runner
 - Microsoft Edge
 - IAF version 7.6-20200415.172935

**Additional context**
I hope the above is clear by itself.

**Comment by nielsm5** [comment]
This has to do with the ManageDatabase adapter, which allows you to execute 'raw' sql queries. You can disable the ManageDatabase by using the property `manageDatabase.active=true`.

Typically this adapter is only active on LOC environments for testing purposes.
