### ISSUE TITLE
ibisdoc.xsd does not support BatchFileTransformerPipe

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#611]
**Describe the bug**
The Frank!Framework offers a pipe BatchFileTransformerPipe. This pipe contains special tags, for example `<manager>` and `<flow>`. These are not recognized by ibisdoc.xsd. Therefore you see XSD violations when you use the BatchFileTransformerPipe as intended.

**Category**
 - Frank Framework

**To Reproduce**
1. Configure Visual Studio Code or Eclipse to support checking against ibisdoc.xsd.
2. Download ibisdoc.xsd
3. As a brother of ibisdoc.xsd, write `ConfigurationDestinations.xml` and give it the following contents:

       <Module
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="./ibisdoc.xsd">
           <Adapter name="adapterGetDestinations">
               <Receiver name="receiverGetDestinations">
                   <DirectoryListener
                       name="listenerDestinationsDirectory"
                       root="${work}"
                       inputFolder="input"
                       inProcessFolder="processing"
                       processedFolder="processed"
                       errorFolder="error"
                       createFolders="false"/>
               </Receiver>
               <Pipeline firstPipe="pipeParseCSV">
                   <BatchFileTransformerPipe
                       name="pipeParseCSV">
                       <manager>
                           <flow>
                           </flow>
                       </manager>
                       <Forward name="success" path="EXIT"/>
                   </BatchFileTransformerPipe>
                   <Exit path="EXIT" state="success" code="200"/>
               </Pipeline>
           </Adapter>
       </Module>

4. You will an XSD violation for `<manager>`.

**Expected behavior**
You should be able to use this pipe without violations of ibisdoc.xsd.

**Screenshots**

**Environment:**
- Visual Studio Code
- ibisdoc.xsd from April 16 2020 or April 15 2020.

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
PR #613 did not solve this issue, because it is not related to the lookup table. 
Instead, the generation of the ibisdoc.xsd should be modified to incorporate the above structure.

**Comment by jjansenvr** [comment]
outdated, please retest against new xsd, if persist please create issue for frankdoc
