### ISSUE TITLE
When doing Test Pipeline is forbidden, you are notified with an empty red bar

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#617]
**Describe the bug**
When you do not have rights to do Test Pipeline, you do not get a proper error message. After pressing "Send", you have the following feedback:
- At the top of the screen, you get a red bar. It does not have any text however. You thus only see that something went wrong.
- With F12 (Google Chrome), I brought up the console. There I could see a red log message with the words "Forbidden" and "403"

**Category**
 - Frank Console

**To Reproduce**
1. Start from a running instance of the Frank!Framework with security disabled.
2. Edit frank-runner\build\apache-tomcat-7.0.100\webapps\ROOT\WEB-INF\web.xml. This file has at its bottom a lot of security stuff. Uncomment it.
3. Edit frank-runner\build\apache-tomcat-7.0.100\conf\tomcat-users.xml. Following the examples you see, create a user with role "IbisObserver".
4. Edit frank-runner\build\apache-tomcat-7.0.100\conf\server.xml. Uncomment the piece `<Connector port="8443"...`.
5. Change directory to frank-runner\build\openjdk-8u232-b09\bin. Execute the following command there: `keytool -genkey -alias tomcat -keyalg RSA`
6. Start the Frank!Runner.
7. Try the Test Pipeline page.

**Expected behavior**
The red bar you see should contain text that explains that access if denied.

**Screenshots**

![image](https://user-images.githubusercontent.com/6784732/79594871-229c8700-80de-11ea-9578-67539fc5aa89.png)

**Environment:**
 - Frank!Framework.
 - Google Chrome.
 - IAF Version 7.6-20200416.110009

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
Martijn still has an issue

**Comment by mhdirkse** [comment]
I tested with Frank!Framework version 7.6-20200505.175722 whether this issue was fixed. I saw the same behavior as I described in the issue: an empty red bar. The issue should still be open.

**Comment by nielsm5** [comment]
Please clear your cache and try it again...

**Comment by mhdirkse** [comment]
I cleared the cache and tried again. I still have this issue. My browser when retrying was Microsoft Edge. My Frank!Framework version when retrying was 7.6-20200512.092218.

**Comment by nielsm5** [comment]
After a long struggle I found a way to reproduce this! 
I will be working on a fix and keep you updated.

**Comment by mhdirkse** [comment]
Thanks!

**Comment by mhdirkse** [comment]
I have verified that this issue indeed has been fixed. I have updated the manual accordingly.
