### ISSUE TITLE
No option found to logout of the Frank!Framework

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#618]
**Is your feature request related to a problem? Please describe.**
I was experimenting with security roles in the Frank!Framework. I created multiple users with different roles. I wanted to logout to be able to login again with another user. I could only do so by clearing the history of my browser.

**Describe the solution you'd like**
At the top-right, I would like an "Account" link, like you see in other websites. It should have a logout option.

**Describe alternatives you've considered**
Support for the web address https://<my server>:8443/logout.

**Additional context**

**Comment by jjansenvr** [comment]
If you are logged in the logout button appears

![logout_Capture](https://user-images.githubusercontent.com/3921911/84772715-a2aa7480-afdb-11ea-9225-5640ad566f23.PNG)

url should have been
/iaf/gui/#!/logout

Are you sure you logged in because you are working at your local environment

**Comment by mhdirkse** [comment]
When I created this issue, I was working with the Frank!Runner, but I had edited web.xml to enable security. My way of working is in the Frank!Manual, see https://frank-manual.readthedocs.io/en/latest/deploying/security.html.

**Comment by jjansenvr** [comment]
I have seen the logout page an login page work in all DTAP environments is this still an issue? @mhdirkse

**Comment by mhdirkse** [comment]
For me it still does not work. I have this:

![image](https://user-images.githubusercontent.com/6784732/93224844-dc714f80-f771-11ea-934b-7fc28e05cf76.png)

**Comment by jacodg** [comment]
Niels can explain when the logout is available and when not so you can document it.
