### ISSUE TITLE
Database connection is not released after using browse table function in GUI 1.0

### ISSUE THREAD

**Issue by NickKW1** [ibissource/iaf#623]
**Describe the bug**
After using the browse a table function (see screenshot:
![image](https://user-images.githubusercontent.com/64085300/79872604-474a7480-83e6-11ea-96cd-7d88b3d23fe3.png) )
database connections are not released. Thus if this is done often enough there are no managed connections available and a restart is needed to make the application function again.

**Category**
 - Frank Console

**To Reproduce**
1. Go to 'Browse a table function as in previous screenshot'
2. Enter the fields so a query on a relevant table can be executed.
3. Click the browse function
4. Repeat untill poolsize is completly filled up

**Expected behavior**
Connection should be released and thus it should be possible to use the 'browse a table' function without limitations

**Screenshots**
See above

**Environment:**
 - JBOSS
 - Chrome and IE
 - IAF 7.0-RC3-SNAPSHOT

**Additional context**
See attached files for the logging where we reproduced the issue on our acceptance server.
[errors-1e-test.log](https://github.com/ibissource/iaf/files/4510340/errors-1e-test.log)
[errors-browse.log](https://github.com/ibissource/iaf/files/4510341/errors-browse.log)

**Comment by gvanbrakel** [comment]
The observation is correct. Both webcontrol.action.BrowseJdbcTableExecute (GUI 1.2, line 127 and 129) and webcontrol.api.BrowsJdbcTable (GUI 3.0, line 130 and 132) open one or even two connections to obtain metadata, and do not close those connections. 
Roughly similar behaviour (but less dangerous) is seen in:
- webcontrol.api.ShowScheduler: line 615 should be before line 614, idem line 673 and 672
- webcontrol.pipes.ShowConfigExe: should have fullClose() before line 111, idem line 145
