### ISSUE TITLE
When you open a logfile in Google Chrome, you need to refresh the page before you see it

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#629]
**Describe the bug**
When you open a logfile in Google Chrome, you see an animation that the logfile is loading. The logfile does not appear then, unless you refresh your browser page. Only after refreshing, the logfile appears.

**Category**
 - Frank Console

**To Reproduce**
1. Start the Frank!Runner again. To produce this error, the Frank!Runner was executed earlier resulting in some log files.
2. Open Google Chrome and browse to http://localhost.
3. In the main menu, click "Logging".
4. Click some logfile.
5. An animation is shown that the logfile is being loaded. That animation does not go away and the logfile does not appear yet.
6. Refresh your browser. Now the logfile appears.

**Expected behavior**
Refreshing your browser should not be necessary for the logfile to appear.

**Screenshots**

**Environment:**
* Frank!Runner
* Google Chrome
* Frank!Framework version 7.6-20200422.121508

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
I was finally able to reproduce this by using FireFox. The problem is due to the cpu cycles being faster then a 50ms timeout that was previously set, causing a property to be set too late and therefore not being called. Added it to #643 as well!

**Comment by mhdirkse** [comment]
Verified.
