### ISSUE TITLE
After upgrading ibis4publishing, I got in dev some MQ errors

### ISSUE THREAD

**Issue by laura-dimitra** [ibissource/iaf#630]
Error:

Pipe [To NNCP Archive] msgId [0102060000981587631971509785063] caught exception: (DetailedInvalidDestinationException) JMSWMQ2008: Failed to open MQ queue 'ALIASQ.DOSM.NNCP_PUB_M2RBE_MSG'.: (MQException) JMSCMQ0001: WebSphere MQ call failed with compcode '2' ('MQCC_FAILED') reason '2082' ('MQRC_UNKNOWN_ALIAS_BASE_Q')
--

Gerrit already received the 2 ladybug reports.  dev (iaf 7.5-rc2) gives in some cases an MQ error, test (iaf 6.1-RC3) doesn't have any problems

**Comment by laura-dimitra** [comment]
Here's the logging:
[logging.txt](https://github.com/ibissource/iaf/files/4521725/logging.txt)

**Comment by laura-dimitra** [comment]
I don't know this is helpful, but this information I found on the internet: https://www.ibm.com/support/knowledgecenter/SSFKSJ_7.5.0/com.ibm.mq.tro.doc/q039210_.htm

**Comment by gvanbrakel** [comment]
Laura schreef:
Vanuit Websphere was alles in orde en leek alles er goed uit te zien. Het probleem zat ‘m echter in MQ.
Schijnbaar heeft niemand dit voorheen ooit goed getest en kreeg nu viel het de testers helaas pas op na de iaf-upgrade.

Opgelost dus.
