### ISSUE TITLE
Scheduler gives error while sending message

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#637]
**Describe the bug**
The scheduler with function SendMessage gives an error: 
"error while sending message (as part of scheduled job execution): JTA transaction unexpectedly rolled back (maybe due to a timeout); nested exception is javax.transaction.RollbackException"
The database is MSSQL.
Is the scheduler doing its work transacted? 

**Category**
 - Frank Framework

**To Reproduce**
1. create a schedule for an adapter with a function SendMessage
2. when the scheduler fires the trigger, after some time this error occurs.
3. go to the schedule page

**Expected behavior**
No exceptions at all.

**Screenshots**
See ibis4titan PRD: https://srpzzapp0517.insim.biz/ibis4titan/iaf/gui/#!/scheduler
See stacktrace.txt + see error.docx

**Environment:**
 - Application server : websphere
 - Browser : chrome
 - IAF Version : 7.6-20200330.192854

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test) 
[stacktrace.txt](https://github.com/ibissource/iaf/files/4523283/stacktrace.txt)
[error.docx](https://github.com/ibissource/iaf/files/4523293/error.docx)

**Comment by nielsm5** [comment]
Could you please confirm this issue is still present in the latest version? We believe this has been fixed in #583.

**Comment by jjansenvr** [comment]
@rvdstel Hi Richard can you confirm the fix so I could close this issue? the possible fix was merged on 15 Apr

**Comment by rvdstel** [comment]
We are now using IAF 7.6-20200603.093311 and this error is fixed.
