### ISSUE TITLE
Add copy/paste capabilities to the Frank!Console page that displays a logfile

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#638]
**Is your feature request related to a problem? Please describe.**
When you open a logfile in the Frank!Console, you cannot copy/past the text.

**Describe the solution you'd like**
When you are seeing a logfile in the Frank!Console, it would be nice if you could select text and copy it.

**Describe alternatives you've considered**
This issue becomes less problematic when issue #631. Then at least you are seeing the full path of the file, allowing you to open it in a text editor.

**Additional context**
I am working on the Frank!Manual, a chapter for operators. When an operator opens a logfile in the Frank!Console, the only thing she can really do with it is sending it to a Frank developer. To do this, she has to copy/past it to her mail or chat program.

**Comment by nielsm5** [comment]
You can copy the path (and filename with #631) or click the copy icon, see:
![Untitled](https://user-images.githubusercontent.com/4375703/80218827-f767e980-8641-11ea-8724-26269d4de83b.png)

It is also possible to send the logging's page url to others. This will directly display the directory or file.

**Comment by mhdirkse** [comment]
I checked that I can select text and use right-click. Then you get a menu and you can select Copy. You can then paste the selected text somewhere.
