### ISSUE TITLE
Custom uglify_lookup.xml is ignored when no custom uglify.xsl is present 

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#641]
**Describe the bug**
Usually by overwriting .properties/.xsl/.xml files in the classes or src/main/resources folder would result in overwriting the file that comes with the framework. For example the usage of having a custom stub4testtool.xsl would result in using the custom .xsl file to stub adapters.

When overwriting uglify_lookup.xml without overwriting uglify.xsl it seems that the default framework file is still being used.

**Category**
 - Frank Framework

**To Reproduce**
1. Download https://github.com/ibissource/iaf/blob/master/core/src/main/resources/xml/xsl/uglify_lookup.xml to src/main/resources/xml/xsl or classes/xml/xsl
2. Open uglify_lookup.xml and make the following change to the first block:
<Element>
      <Name>ApiListener</Name>
      <Type>listener</Type>
      <ClassName>nl.nn.adapterframework.http.rest.ietswatnietklopt</ClassName>
    </Element>
3. Create an adapter in beautiful syntax with an ApiListener
4. Start the framework, navigate to console and your listener still starts whilst it shouldn't.

**Expected behavior**
I'd expect that the uglify_lookup.xml works without overwriting uglify.xsl

**Screenshots**
None

**Environment:**
 - Application server (f.e. Tomcat/websphere/JBOSS/Jetty) : Tomcat
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.4]: Tested with latest and 7.5RC-1

**Additional context**
-

**Comment by jjansenvr** [comment]
This defect is outdated
