### ISSUE TITLE
Tests use fixed path to C:/temp

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#654]
**Describe the bug**
The tests in [test](https://github.com/ibissource/iaf/tree/master/test) use a fixed path to C:/temp when initializing and for the inputs of adapters, and it tries to do a replacement of ${log.dir} to C:/temp.

On Linux this setup fails because C:/temp is a Windows folder structure, so the adapters get inputs to look for files in non-existing locations. When running Tomcat from Eclipse the log.dir contains a .. in the path while the Ibis outputs the complete path when reading directory lists, which make the replacement fail.

**Category**
 - Frank Framework
 - Larva (unit test tool)

**To Reproduce**

**Expected behavior**
Tests do not depend on a fixed Windows path and can be run from all environments with only setting some properties.

**Screenshots**

**Environment:**
 - Application server (f.e. Tomcat/websphere/JBOSS/Jetty): Tomcat and Websphere
 - Browser [e.g. chrome, safari]: N/A
 - IAF Version [e.g. 7.4]: 7.6-20200428.084202

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
@mhdirkse and @Laurens-makel are working on this issue

**Comment by mhdirkse** [comment]
Hello Gerrit. Can you reopen this issue? We did a first step with the pull request #851, but this is not done yet. With kind regards, Martijn Dirkse
