### ISSUE TITLE
Cannot login when using Edge

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#673]
**Describe the bug**
When using the latest Edge browser at NN, it appear to be impossible to login to the FrankConsole.
Work around appears to be to use Chrome.

**Category**
 - Frank Console
 - Frank Framework

**To Reproduce**
1. Go to any Ibis at NN using Edge
2. Try to login.

**Expected behavior**
It should be possible to login with any browser.

**Screenshots**

**Environment:**
 - Edge browser at NN
 - IAF Version 7.5, 7.6

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Causes were either;
- Basic authentication popup was suppressed by company policies (which has been resolved, by presenting a custom login form)
- Some applications were flagged to run on a IE11-emulation from within Edge. The cause appeared to be another company policy, which can be observed by looking if there is an IE icon directly on the left of the address bar.
