### ISSUE TITLE
Senders in Senders are not stubbed

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#674]
**Describe the bug**
When stubbing for local testing, Senders that are not a direct child of a Pipe are not stubbed. This applies to Senders that are part of a SenderSeries or a ParallelSenders (and possibly others).

**Category**
 - Frank Framework

**To Reproduce**
1. Have an adapter with a SenderSeries in it and a Sender that would normally be stubbed
2. Let this adapter be stubbed
3. Open the loaded configuration
4. Sender is not stubbed

**Expected behavior**
Senders that are not a direct child of a Pipe are also stubbed.

**Screenshots**

**Environment:**
 - Application server (f.e. Tomcat/websphere/JBOSS/Jetty): Tomcat
 - Browser [e.g. chrome, safari]: N/A
 - IAF Version [e.g. 7.4]: 7.6-20200421.151810

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jjansenvr** [comment]
I guess we need to update the stufortestool xsl for this
@ricardovh can you supply an example configuration for my unit test?

**Comment by ricardovh** [comment]
Unfortunately I don't have an example configuration available at the moment.
