### ISSUE TITLE
Upload Configuration page, checkbox Activate Config, switches on after pressing Send

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#698]
**Describe the bug**
This issue is about uploading a configuration to the database. This is done with the Upload Configuration page. This page remains there after you press send, echoing the values you entered. However, the Activate Config checkbox gets checked, even when the configuration was uploaded with Activate Config unchecked. This is very confusing for the user.

**Category**
 - Frank Console

**To Reproduce**
1. Start the Frank!Runner with `start.bat -Djdbc.migrator.active=true -Dconfigurations.names="${instance.name.lc},NewHorizons" -Dconfigurations.NewHorizons.classLoaderType=DatabaseClassLoader -Dwork=work`
2. In JDBC | Execute Query, perform query `DROP ALL OBJECTS`
3. Restart the Frank!Runner.
4. Upload Frank config [forFrankConsole.zip](https://github.com/ibissource/iaf/files/4608246/forFrankConsole.zip) with Activate Config checked, other checkboxes unchecked.
5. Go to the Adapter Status page.
6. Return to the Update Configuration page. Prepare it to upload [forFrankConsole_2.zip](https://github.com/ibissource/iaf/files/4608245/forFrankConsole_2.zip) but do not press Send yet. Your page should look as shown:
![image](https://user-images.githubusercontent.com/6784732/81538178-add00c00-936e-11ea-9cd5-3d7befa6859e.png)
7. Press Send. The page becomes as shown:
![image](https://user-images.githubusercontent.com/6784732/81538279-d6580600-936e-11ea-92c7-db49cad09ecc.png)
8. The Activate Config checkbox is checked here, even though it was not before Send was pressed.

**Expected behavior**
The Activate Config checkbox should be the same as before Send was pressed.

**Screenshots**
Already shown.

**Environment:**
 - Frank!Runner
 - Microsoft Edge
 - IAF version 7.6-20200511.081459

**Additional context**
This issue makes it difficult for me to document how to upload configurations. I see behaviour that is very hard to explain. I would also be helped if the Upload Configuration page would be removed after Send is pressed.

**Comment by mhdirkse** [comment]
This issue still occurs on my laptop. I cleared my history and my cache, but that did not help. Can this issue be reopened?

**Comment by gvanbrakel** [comment]
Martijn zegt:
Kan je dit issue heropenen? Ik zie het issue nog op mijn laptop. Ik heb hierover al een comment toegevoegd, maar ik heb geen rechten om te reopenen.

**Comment by nielsm5** [comment]
De tickbox staat standaard aan. Het scherm reset na een upload, dat houdt in; alle velden worden geleegd en teruggezet naar hun default waardes. in dit geval is staat 'active' dus standaard aan.
