### ISSUE TITLE
Must be possible to generate WSDL from WsdlValidating pipeline.

### ISSUE THREAD

**Issue by mihxil** [ibissource/iaf#7]
<inputValidator
				className="nl.nn.adapterframework.pipes.WsdlXmlValidator"
				wsdl="/GetPolicyAndPartyDetails/wsdl/PolicyNL_GPAPD_Concrete_20140502_API.wsdl"
				soapBody="GetPolicyDetailsForCustomer_Request"
				schemaLocation=
					"
					http://nn.nl/XSD/Generic/MessageHeader/1 schema1
					http://api.nn.nl/GetPolicyDetailsForCustomer schema2
					"
				addNamespaceToSchema="true"
				throwException="true"
			/>
			<outputValidator
				className="nl.nn.adapterframework.pipes.WsdlXmlValidator"
				wsdl="/GetPolicyAndPartyDetails/wsdl/PolicyNL_GPAPD_Concrete_20140502_API.wsdl"
				soapBody="GetPolicyDetailsForCustomer_Response"
				schemaLocation=
					"
					http://nn.nl/XSD/Generic/MessageHeader/1 schema1
					http://api.nn.nl/GetPolicyDetailsForCustomer schema2
					"
				addNamespaceToSchema="true"
				throwException="true"
			/>

**Comment by jacodg** [comment]
Done
