### ISSUE TITLE
Message "Could not get <config> from database" does not vanish after upload and reload

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#704]
**Describe the bug**
When you have a Frank config with classLoaderType "DatabaseClassLoader", you see a message "Could not get <config> from database". This is correct when the Frank config is not present in the database. However, after uploading the config and reloading it, the message does not vanish. The Adapter Status page then looks as shown:

![image](https://user-images.githubusercontent.com/6784732/81656604-72e5db00-9437-11ea-8ac7-0cd71d5897a1.png)

**Category**
 - Frank Console

**To Reproduce**
1. Install the Frank!Runner. To the `classes` folder of your instance, add a Frank config to define the standard `<jmsRealm>` named `jdbc`. You need it to have database access before any Frank config has been loaded.
2. Start the Frank!Runner as follows: `start.bat -Djdbc.migrator.active=true -Dconfigurations.names="${instance.name.lc},NewHorizons" -Dconfigurations.NewHorizons.classLoaderType=DatabaseClassLoader -Dwork=work`
3. Using Manage Configurations, upload the following Frank config: [forFrankConsole.zip](https://github.com/ibissource/iaf/files/4614154/forFrankConsole.zip). Take care to select checkbox "Activate Config".
4. Go to the Adapter Status page and press the Reload button.
5. The error message is not gone, but the configuration is green as was shown before.

**Expected behavior**
After uploading, there are no error messages anymore in the Adapter Status page.

**Screenshots**
Already shown.

**Environment:**
 - Frank!Runner
 - Microsoft Edge
 - IAF Version 7.6-20200511.081459

**Additional context**
An operator looks at the Frank!Console to see whether there are any issues. If a red flag remains after an issue has been fixed (i.e. the config has been uploaded), the work of the operator becomes more difficult.

**Comment by nielsm5** [comment]
Je kijkt naar de configuratie loghistory. Na het uploaden van een nieuwe versie wordt de log niet opgeschoond. Dit omdat er nog belangrijke informatie in kan staan.

**Comment by mhdirkse** [comment]
I agree. I will close this issue and update the Frank!Manual accordingly.
