### ISSUE TITLE
Aspose uses JDK1.6

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#715]
**Describe the bug**
The Aspose dependencies in https://github.com/ibissource/iaf/blob/master/aspose/pom.xml#L230 are JDK1.6 instead of a newer version.

**Category**
 - Frank Framework

**To Reproduce**
N/A

**Expected behavior**
Use the most recent version.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/websphere/JBOSS/Jetty): N/A
 - Browser [e.g. chrome, safari]: N/A
 - IAF Version [e.g. 7.4]: 7.6 (see current repo)

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by ricardovh** [comment]
Only for Words there is a JDK 1.7 version, others only have a JDK 1.6 version.

For the other dependencies, most are on 19.1, maybe look at upgrading to a more recent version?

**Comment by nielsm5** [comment]
It all depends on what license you use. If you want to use newer versions, you will need to have a compatible license. If this is no problem we will upgrade the Aspose version.

**Comment by ricardovh** [comment]
After further discussion, upgrade is not needed.
