### ISSUE TITLE
When you upload the first verion of a Frank config, the Automatic Reload checkbox does not work

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#717]
**Describe the bug**
When you upload the first verion of a Frank config, the Automatic Reload checkbox does not work. Even though you checked this checkbox in the Upload Configuration dialog, you need to press Reload in the Adapter Status page before the config is found in the database.

**Category**
 - Frank Framework

**To Reproduce**
1. Start the Frank!Runner with: `start.bat -Djdbc.migrator.active=true -Dconfigurations.names="${instance.name.lc},NewHorizons" -Dconfigurations.NewHorizons.classLoaderType=DatabaseClassLoader -Dwork=work -DloadDatabaseSchedules.active=true`
2. Ensure that no configs have been uploaded so far.
3. Download this config: 
[forFrankConsole.zip](https://github.com/ibissource/iaf/files/4627737/forFrankConsole.zip)
4. Go to Configuration | Manage Configurations | Upload Config. Browse to the zipfile you downloaded. Check "Activate Config" and "Automatic Reload".
5. Press Send. The "Back".
6. Wait more than a minute and refresh your browser page.
7. The NewHorizons entry within the Manage Configurations page remains red, indicating it was not loaded.
8. Go to the Adapter Status pate and press Reload. Now you can see the config was loaded/

**Expected behavior**
After step 6, the NewHorizons config should become a link instead of staying red.

**Screenshots**
I hope it is clear this way.

**Environment:**
 - Frank!Runner
 - Microsoft Edge
 - Frank!Framework version 7.6-20200512.092218.

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by mhdirkse** [comment]
This issue only has been fixed partly. I did the following:
- DROP ALL OBJECTS.
- Restart Frank!Runner.
- Upload first version of configuration with "Activate Config" and "Automatic Reload" checked.
- Go to Adapter Status page. To the top there is a red bar.
- Wait about two minutes, the red bar does not vanish.

When I refreshed my browser page, the red bar did vanish. But this is not sufficient I think. The red bar should go away without the need for a browser refresh.

**Comment by gvanbrakel** [comment]
Marijn zegt:
Issue 717 is niet helemaal gefixed. Je moet nog steeds je browser refreshen in de Adapter Status pagina, voordat je ziet dat automatic reload effect heeft gehad. Kunnen jullie dit issue heropenen?

**Comment by nielsm5** [comment]
Cannot reproduce, can you provide a screenshot of the red bar you're talking about?

**Comment by mhdirkse** [comment]
I tried to reproduce with version IAF 7.6-20200519.180727, but I could not. The red bar I talked about does vanish.

**Comment by mhdirkse** [comment]
I updated the Frank!Manual to remove the reference to this issue.
