### ISSUE TITLE
Suprresion atrribute

### ISSUE THREAD

**Issue by bonnoiaf** [ibissource/iaf#719]
**Is your feature request related to a problem? Please describe.**
For some ibis systems there are a lot of warnings in the console, like this:
GenericReceiver [SplitMessageReceiver] sets transactionAttribute=Required, but has no errorSender or errorStorage. Messages processed with errors will be lost.

Sometimes i get questions about them, sometimes they clutter up the entire screen.

**Describe the solution you'd like**
I would like to have an surpression attribute on pipes so i can choose to disable particular warnings.

**Comment by jjansenvr** [comment]
i agree
