### ISSUE TITLE
After a timeout connection is not restored directly 

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#728]
**Describe the bug**
This adapter reads from our database records and after transformation they are all sent to titan (rest api updateByQuery)
We see that sometimes a timeout occurs, but the problem is that immediately afterwards all subsequent records also get a timeout.

It seems as if the connection has been lost due to the timeout and after that no more attempts are made to establish a connection.
I did not specify a timeout parameter because I assumed the default timeout is 10 seconds.

Why doesn't every rest call have its own timeout of 10 seconds?

**Category**
 - Frank Framework

**To Reproduce**
1. Have an adapter that listens to records and makes an rest api call
2. Insert a bunch of records
3. Hope for a timeout on one of the calls and see what happens to the following ones.

**Expected behavior**
Each individual call should have it's own timeout state and should not be affected by other calls executed shortly before or after.

**Screenshots**
![image](https://user-images.githubusercontent.com/37303445/82227858-9bcf0a00-9928-11ea-8747-8d23bc7e2a0b.png)

**Environment:**
 - Application server (f.e. Tomcat/websphere/JBOSS/Jetty): Websphere
 - Browser [e.g. chrome, safari]: Not related
 - IAF Version [e.g. 7.4]: IAF 7.6-20200330.192854

**Additional context**
- none

**Comment by nielsm5** [comment]
Seems to be related to this issue: #993

**Comment by gvanbrakel** [comment]
It appears to me that the screenshot does not show subsequent messages, but each time the same message, that is tried again and again.

**Comment by nielsm5** [comment]
Does not look like this is an actual issue, I'm closing this.
