### ISSUE TITLE
Mapping xml to json fails for repeating elements

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#747]
**Describe the bug**
error: Alignment of XML to JSON failed: (IllegalStateException) already created map for element [label]

when trying to parse 
```
<MetaData>
<label name="authorizedTo">Soapui</label>
<label name="documentType">12345678901234567890123456789012345678901234567890</label>
<label name="descriptionProductGroup">1234567890123456789012345678901234567890</label>
```

**Category**
 - Frank Framework

**To Reproduce**
use validator 

<pipe className="nl.nn.adapterframework.pipes.Json2XmlValidator" name="Response_To_Json" outputFormat="json" schema="validate.xsd" root="GetDocumentAndAttributes_Response">
--

**Expected behavior**
```
<metadata>
<label name="documentType">123</label>
<label name="descriptionProductGroup">abc</label>
</metadata>

```

This should result in a valid json
```
metadata:{
"documentType":"123",
"descriptionProductGroup":"abc"
}
```
or 
```
metadata: {
{"label": "123", 
"@name": "documentType"} ,
{"label": "123", 
"@name": "descriptionProductGroup"} ,
}
```

or any other valid json 

**Environment:**
 - IAF 7.6-20200522.153155

**Additional context**
added the xml and xsd

[input.xml.txt](https://github.com/ibissource/iaf/files/4673116/input.xml.txt)
[validate.xsd.txt](https://github.com/ibissource/iaf/files/4673117/validate.xsd.txt)

**Comment by gvanbrakel** [comment]
label is a repeating element, and therefor must be an array. Without the name attribute, the result would be:
```
metadata:{
  label: [
  	"123", "abc"
  ]
}
```

introducing the name attribute requires the values to get a label, e.g. "text"
```
metadata:{
  label: [
  	{"name":"documentType", "text":"123"}, 
  	{"name": "productGroup", "text": "abc"}
  ]
}
```
