### ISSUE TITLE
System out gets flooded with log4j errors

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#748]
**Describe the bug**
I'm using the Aspose extension to convert documents to PDF, I tried upgrading to the latest version available and all is working well but I see some errors in system out log that give the indication that something isn't going so well.

This is what I get during startup:
![image](https://user-images.githubusercontent.com/37303445/82784154-3ca95200-9e60-11ea-9407-bc91df95bbce.png)

This is what I see when I retrieve the converted document:
(I think this might be related that I have a custom apiListener / apiListenerServlet due having to serve charset ISO-8859-1 and overwrite the default UTF-8)
![image](https://user-images.githubusercontent.com/37303445/82784194-5185e580-9e60-11ea-9d7e-3401822bc954.png)

![image](https://user-images.githubusercontent.com/37303445/82784228-5d71a780-9e60-11ea-84b9-58034cada607.png)

**Category**
 - Frank Framework

**To Reproduce**
1. Add attached adapter to your Frank! 
[Configuration_Document_GET_viewpdf.zip](https://github.com/ibissource/iaf/files/4675509/Configuration_Document_GET_viewpdf.zip)

2. Create the DB table
3. Store a PDF in the table
4. Try to retrieve it over HTTP and see the error

**Expected behavior**
No errors

**Screenshots**

**Environment:**
 - Application server (f.e. Tomcat/websphere/JBOSS/Jetty): Tomcat
 - Browser [e.g. chrome, safari]: Chrome (not related to issue)
 - IAF Version [e.g. 7.4]: 7.6-20200522.153155

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by Laurens-makel** [comment]
Okay I resolved the first error by replacing IOS-Adaptering with configuration and replacing the attribute configurationName to name in some configuration.xml files.

The second error hasn't been resolved.

**Comment by nielsm5** [comment]
Hi Laurens,

The first image is because of the use of IOS-Adaptering instead of Module (or module).

The 2nd image is a string representation of the content. It looks like binary context which is not always displayed properly. If you are having issues parsing the content you indeed have to look at the Character set used to encode and reuse the same to decode.

In this issue will focus on the 3 image which contains a log parsing problem.

**Comment by Laurens-makel** [comment]
Hi Niels,

Thanks for clearifying the first two images. I'm quite sure that the third error is coming from using ISO-8859-1 as a charset on the ApiListener (yes custom ApiListener, it's not possible to configure the charset on the default framework ApiListener).

We have discussed this change to the ApiListener before but I still think is a valid feature to support older charsets aswell. It's even in the [w3schools specs..](https://www.w3schools.com/html/html_charset.asp).

![image](https://user-images.githubusercontent.com/37303445/82871351-b8270400-9f31-11ea-868d-aeabd8584268.png)

**Comment by nielsm5** [comment]
There is no charset value applicable. PDF is a binary format which handles character encodings internally, in a way that's not relevant to MIME types at all. Saying that however I don't think it's a bad idea to add some form of character encoding to the contentType header..

**Comment by Laurens-makel** [comment]
Hi Niels,

Okay but in that case the Frank developer should have an option available to omit the charset attribute from the response.

Because in the case of PDF files, you shouldn't even provide a charset value but the framework ALWAYS sets UTF-8 which breaks loading PDF's, because when there is no charset definied, the browser will try to figure it out itself and then it'll use ISO-8859-1.

Currently in my custom case, im still providing a value for the charset, but charset should not be included in the response.

https://stackoverflow.com/questions/23163089/what-is-the-correct-charset-for-a-application-pdf-content-type-http-response-hea
