### ISSUE TITLE
New attribute principal pipe to set which security handler to use

### ISSUE THREAD

**Issue by VBPham** [ibissource/iaf#756]
**Is your feature request related to a problem? Please describe.**
principal pipe seems to automatically derive which security handler to use. In some cases you'd want to set a different security handler then is chosen by this pipe. In our use case we would like to get the http basic auth http header prinicpal information in a cmis listener instead of the wsse header principal.

**Describe the solution you'd like**
I'd like to be able to set an extra attribute on this pipe to choose which security handler it will use and therefore which principal information it returns. something like this:

securityHandlerType=[http|cmis|...|derive(default)] derive being the default which will make it so it works like before this feature request gets implemented.

**Comment by nielsm5** [comment]
Added `cmis.securityHandler.type=basic/wsse/none`
