### ISSUE TITLE
Json2XmlValidatorPipe validates different for json and xml output type

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#758]
**Describe the bug**
when debugging a validation error with output set to json, I changed it to xml and got a xml response. 
I found out that i made a mistake in the namespace of the message that was detected in json mode but not in xml mode

```
 <Json2XmlValidatorPipe name="Response_To_Json" 
                outputFormat="json" 
                schema="xsd/GetPartiesOnAgreement_7.xsd" 
                root="GetPartiesOnAgreement_Response"
                acceptNamespaceLessXml="true">

                <Forward name="success" path="READY" />
                <Forward name="failure" path="ServerError" />
                <Forward name="exception" path="ServerError"/>
            </Json2XmlValidatorPipe>
```

**namespace of my stub message**
<GetPartiesOnAgreement_Response
xmlns="http://nn.nl/XSD/CustomerAdministration/Party/1/GetPartiesOnAgreement/6">

**Category**
 - Frank Framework

**To Reproduce**

**Expected behavior**
if I validate an xml it should not matter if my output becomes json or xml the validation should be based on the input xml

**Screenshots**

**Environment:**
 - IAF 7.6-20200525.101351:

**Additional context**
[Pipeline GetPartiesOnAgreement_7(GET).zip](https://github.com/ibissource/iaf/files/4678494/Pipeline.GetPartiesOnAgreement_7.GET.zip)

**Comment by gvanbrakel** [comment]
I copied this setup into a unit test. In both cases the validation fails, the error messages are:
xml:

> Validation using Json2XmlValidator with '/Align/758/schema.xsd' failed:
/: at (1,346): cvc-elt.1.a: Cannot find the declaration of element 'GetPartiesOnAgreement_Response'.

json:

> Validation using Json2XmlValidator with '/Align/758/schema.xsd' failed:
/: at (1,346): cvc-elt.1.a: Cannot find the declaration of element 'GetPartiesOnAgreement_Response'.
/: No typeDefinition found for element [GetPartiesOnAgreement_Response] in namespace [http://nn.nl/XSD/CustomerAdministration/Party/1/GetPartiesOnAgreement/6] qName [GetPartiesOnAgreement_Response]

The additional error message is added by the XmlAligner that is used for conversion to Json. The XmlAligner is not used when no conversion to or from XML is done, i.e. XML in/XML out.
