### ISSUE TITLE
Cookie preferences not stored

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#773]
**Describe the bug**
Cookie preferences appear to be not stored

**Reporter**
Gerrit

**Category**
 - Frank Console

**To Reproduce**
1. Start ibis
2. Open console
3. Save Cookie Preferences
4. Refresh browser, e.g. by pressing F5
5. See that the Cookie Preference dialog reappears

**Expected behavior**
Cookie preference set and remembered once saved.

**Environment:**
 - Application server TomCat, running om my laptop
 - Browser Chrome
 - IAF Version 7.6 SNAPSHOT

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Do you happen to have cookies disabled or have a cookie blocker plugin? I can't reproduce this. Tested with Edge, Firefox and Chrome

**Comment by jjansenvr** [comment]
For using a framework  like this the organisation using this should be the party that accepts cookies not the individual user. So for me this option can be removed from the GUI and be added as a remark in the readme of the project

**Comment by nielsm5** [comment]
Analytics er uit, cookie beschrijving houden, geen melding meer weergeven
