### ISSUE TITLE
Sender series sender gives different results on 7.5-RC1 and 7.6-XX

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#797]
**Describe the bug**
Please consider this adapter, and have a look at CreateSharedValues:

[src_main_configuration_Mailbox_ConfigurationCreateExcel.zip](https://github.com/ibissource/iaf/files/4747285/src_main_configuration_Mailbox_ConfigurationCreateExcel.zip)

What happens in 7.6-XX is:
Input is send to CreateSharedValues sender first, output of CreateSharedValues is the input for StoreSharedValues and will also be the input for the next pipe due to preserveInput attribute on sender series sender.

What happens in 7.5-RC1 is:
Input is send to CreateSharedValues sender first, output is ignored probably due preserveInput and original input is also the input for StoreSharedValues and is the input for the next pipe.

**Reporter**
Laurens, me

**Category**
 - Frank Framework

**To Reproduce**
Too much to explain... please contact me for more details.

**Expected behavior**
Not really sure, both situations are kinda skeptic about the preserveInput attribute imo.

**Screenshots**

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty) Websphere / Tomcat
 - Browser [e.g. chrome, safari] Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6] 7.5-RC1 & IAF 7.6-20200603.093311:

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
There was a bug in the 7.6 version, the input from sessionkey or fixedValue was not really used.
This is fixed in PR #855. 
The IbisDoc is also made more clear
