### ISSUE TITLE
test-pipeline does not work with file upload

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#798]
**Describe the bug**
When using the test a pipeline it does not work with a file upload in the new GUI 

**Reporter**
JJansenvr

**Category**
 - Frank Console
 
**To Reproduce**
1. Go to test-a-pipeline
2. Click on file upload button
3. Select your xml or zip file
4. see error "Please specify a file or message!" at the top of the page

**Expected behavior**
selecting a file should result in testing the pipeline with the contents of the file 
when a zip is selected every file from the zip should be tested with test a pipeline

**Screenshots**
![Capture](https://user-images.githubusercontent.com/3921911/84124210-33f97400-aa3b-11ea-91c8-436baf140a99.PNG)

**Environment:**
 - Browser Chrome
 - tested on local (IAF 7.6-20200608.143400) 
- also tested on test environment (IAF 7.6-20200529.175744)
- also tested on production IAF 7.5-RC2:

**Comment by Laurens-makel** [comment]
As far as I am aware it does work, although it should be in a .zip file. 

This way you could upload multiple messages at once and run them, although I do think that it should be possible to upload a single (xml) file aswell.
