### ISSUE TITLE
errorStorage deleteSelected does not work

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#810]
**Describe the bug**
errorStorage  deleteSelected does not work

**Reporter**
Ali

**Category**
 - Frank Console

**To Reproduce**
1. Go to error storage
2. select a message
3. Click delete selected

**Expected behavior**

**Screenshots**

**Environment:**
 - Application server (WebSphere)
 - Browser [Chrome]
 - IAF Version IAF 7.6-20200608.143400: ibis4oma

**Additional context**
Please have the same functionality for messageLog

**Comment by nielsm5** [comment]
Can't reproduce, what is the issue? Are there any errors?
