### ISSUE TITLE
JsonPipe doesn't convert large json file to xml properly

### ISSUE THREAD

**Issue by francisgw** [ibissource/iaf#827]
**Describe the bug**
When using the JsonPipe, it seems that large json files aren't properly converted to xml. 

**Category**
 - Frank Framework
 
**To Reproduce**
1. Build a test adapter to input json with
2. Use as input a large json file. For example ibisdoc.json
3. Test adapter

**Expected behavior**
A correct xml output

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/67001993/84769452-22cddb80-afd6-11ea-8e0e-ed01779471ee.jpg)
![Untitled2](https://user-images.githubusercontent.com/67001993/84771785-42ff9980-afda-11ea-8f84-e5a171b2cc4c.jpg)

**Additional context**
If you take a smaller portion from the ibisdoc.json, like for example the listeners part, the pipe works fine (see 2nd screenshot)

**Environment**
- apache-tomcat-7.0.100
- Edge
- IAF 7.6-20200615.130305

**Comment by francisgw** [comment]
The limit of file size for this JsonPipe seems to be 400 Kb.

**Comment by nielsm5** [comment]
I don't see any errors? What appears to be broken/missing?
There is a block of Javadoc in your XML which has been correctly escaped...

**Comment by francisgw** [comment]
You are right, it's not an error and I now see why &lt; and &gt; were in my result.
