### ISSUE TITLE
Show ibisstore summary in GUI 3.0 invalid qeury result

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#842]
**Describe the bug**
When I click on send button I get Invalid query result.
![image](https://user-images.githubusercontent.com/10929856/84999706-cdb6d480-b151-11ea-92e5-6a07a8c995bf.png)

I think the content handler is not registered properly before parsing the xml. 

**Reporter**
Ali

**Category**
 - Frank Framework

**To Reproduce**
Go to ibis4oma dev and browse ibisstore in gui 3. 

**Expected behavior**
Display ibisstore table.

**Comment by gvanbrakel** [comment]
webcontrol.api.ShowIbisstoreSummary uses QueryOutputToMap, but the IbisstoreSummaryQuerySender uses a dedicated XML format, that QueryOutputToMap cannot handle

**Comment by jjansenvr** [comment]
okay found the same issue, is this fixed in #873 ?
