### ISSUE TITLE
Stopped filter also shows adapters with messages in the error log

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#859]
**Describe the bug**
On the adapter status page, there are buttons to filter adapters based on state. When clicking the Started and Warning buttons, so that only Stopped adapters are shown (/status?filter=stopped), adapters with messages in the error store are also shown. Refreshing the page does filter them out.

**Reporter**
Ricardo

**Category**
 - Frank Console

**To Reproduce**
1. Have an adapter with some messages in the error store
2. Go to the adapter status page
3. Filter out Started and Warning adapters
4. See adapter still being shown
5. Refresh page
6. Adapter is hidden

**Expected behavior**
No refresh needed to filter out adapters with messages in the error store.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Websphere
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.5-RC3

**Additional context**
N/A

**Comment by Laurens-makel** [comment]
As far as I can see GUI 3 seems to consider adapters with messages in the error store as stopped messages...

This was probably done as a shortcut.. I'll have a look at what I can do

![image](https://user-images.githubusercontent.com/37303445/85394910-9d0adc80-b54f-11ea-8467-9b52cfab3942.png)

**Comment by ricardovh** [comment]
Small correction, after a refresh the adapters do show if they have something in their error store, but because it takes some time loading it, it seems empty.

Maybe change the and reorder the buttons to Running, Warning and Error (instead of Started, Warning and Stopped)? Maybe adapters for which adapters have failed messages (but without error store) should then also be put under Error.
