### ISSUE TITLE
test a pipeline does not show the output of the adapter

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#862]
**Describe the bug**
When using test a pipeline (in this case with JSON output) 
it returns {"binary":false,"empty":false}
instead of the output of the pipeline

**Reporter**
Jjansenvr

**Category**

 - Frank Framework / console

**To Reproduce**
use a adapter with a api listener with json output and use test a pipeline

**Expected behavior**
i would expect the output of the adapter instead of {"binary":false,"empty":false}

**Screenshots**

**Environment:**
 - Application server (WebSphere)
 -  FF! 7.6-20200622.103044:

![testapipeline_error_ladybug_outcome](https://user-images.githubusercontent.com/3921911/85376175-ac7e2b80-b537-11ea-9d44-e2ad08035cf4.PNG)
![testapipeline_error](https://user-images.githubusercontent.com/3921911/85376177-ad16c200-b537-11ea-8c6b-411a6e1ff8fc.PNG)

**Comment by mhdirkse** [comment]
I am having a similar issue. In my case, the output is not JSON but just a number. The similarity is that I see the correct output in Ladybug, while in Test Pipeline I see "{"binary":false, "empty":false}" (I typed this over, do not search for this literally). I observed that I do not have this issue with older issues of the FF!. I am trying different versions now (binary search) to see which version introduces the issue.

**Comment by mhdirkse** [comment]
I found which FF! version introduced the issue:
7.6-20200619.094149 OK
7.6-20200619.153012 NOT OK

**Comment by Laurens-makel** [comment]
Should be solved in PR #864

**Comment by mhdirkse** [comment]
Verified.
