### ISSUE TITLE
Ladybug randomly stops report generation

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#875]
**Describe the bug**
When having the ladybug enabled (both "Report generator enabled" and "Enable Ladybug Debugger" are Yes/checked), the ladybug randomly stops report generation.

**Reporter**
Ricardo

**Category**
 - Ladybug (debugging tool)

**To Reproduce**
Reproduction steps are unknown, behavior seems random, although it has been observed on the same node twice.

**Expected behavior**
Report generation in the ladybug continues functioning correctly.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Websphere
 - Browser [e.g. chrome, safari]: N/A
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.5-RC3

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Hi Ricardo,
Wanneer er meer dan 2500 regels in staan wordt het report afgekapt.

**Comment by ricardovh** [comment]
Het gaat niet over het afkappen, hij genereert geen nieuwe reports meer, terwijl de opties allemaal aan staan. In de logging is helaas niets meer te zien van het moment dat het genereren gestopt is, dit blijkt al een week te spelen en ondertussen is door een loadtest de meeste logging overschreven.

Het enige dat in de logging te zien is rond dat tijdstip, is in de ibis-security.log:
2020-06-19 15:30:32,508 [WebContainer : 24] requestUri [/iaf/api/server/log] params [] method [PUT] remoteHost [localhost.localdomain] remoteAddress [127.0.0.1] remoteUser [******]
2020-06-19 15:30:32,508 [WebContainer : 24] host[localhost.localdomain] tried to access uri[/iaf/api/server/log] with origin[*****] but was blocked due to CORS restrictions

Om 15:30:32.348 is het laatste report gegenereerd, en volgens mij hoort deze PUT bij de instellingen van de Ladybug vanaf Environment variables. Deze gebruiker is IbisTester en IbisDataAdmin en zou het dus aan moeten kunnen passen. Maar als we in de GUI kijken staat het vinkje gewoon aan, dus zouden de reports gegenereerd moeten worden.

**Comment by nielsm5** [comment]
Is this a possible duplicate of #1034 ?

**Comment by ricardovh** [comment]
Very likely this is indeed a duplicate.
