### ISSUE TITLE
Feature Request: Deprecated/internal pipes etc. in IbisDoc

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#877]
**Reporter**
Ricardo

**Is your feature request related to a problem? Please describe.**
In the IbisDoc, all pipes etc. are shown, while a  lot of pipes have been deprecated or are for some internal use and should never be used in a configuration. In the IbisDoc there is no clear distinction between those pipes, and pipes that are not deprecated. Currently that information is only in the JavaDoc or in warnings when the Ibis is started, while for developers the IbisDoc will be the first stop to get information about the pipe.

**Describe the solution you'd like**
A way to identify which pipes are deprecated and what their replacement is, and a filters for deprecated pipes and for the internal pipes so that they are by default not shown in the IbisDoc. Deprecated pipes should still be able to be displayed for maintenance on older ibis, internal ones should not be shown.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gvanbrakel** [comment]
Fully agree

**Comment by ricardovh** [comment]
#904 excludes the internal pipes from the IbisDoc and implements half of this feature request. Filtering out deprecated pipes is still open.

**Comment by jacodg** [comment]
Solved in the new Frank!Doc
