### ISSUE TITLE
Reload All configurations hangs websphere server

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#878]
**Describe the bug**
When  the reload all configuration button is pushed the websphere machine gets into problems

  

**Reporter**
@jjansenvr 

**Category**
 - Frank Console

**To Reproduce**

**Expected behavior**
It would be nice if reload all configs would work on websphere but for now I would like to have the possibility to disable the button on websphere servers

**Screenshots**

**Environment:**
 - Application server WebSphere

**Additional context**

**Comment by jacodg** [comment]
Seems to work now in version 7.6-20201028.131511
