### ISSUE TITLE
RecordXmlTransformer with XSLT does not produce output

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#882]
**Describe the bug**
When using the RecordXmlTransformer with an XSLT to transform the record, no output is generated for the record.

**Reporter**
Ricardo

**Category**
 - Frank Framework

**To Reproduce**
1. Start a server with the attached configurations
2. Use Test a pipeline to send the absolute path to the file resources/test.txt to the adapter "RecordTransformer"
3. Open the Ladybug and select the record with the name "Sender sender of record_writer"
4. See that the input is empty

**Expected behavior**
The XSLT transformation being carried out correctly and resulting in output.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Tomcat
 - Browser [e.g. chrome, safari]: N/A
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.5-RC3

**Additional context**
The record before transformation is logged, using XMLSpy with the same XSLT as the Ibis does result in the correct output. Adding an additional log statement to also log the record after transformation, shows an empty string.

[ibis4recordtransformerreproduction.zip](https://github.com/ibissource/iaf/files/4869166/ibis4recordtransformerreproduction.zip)

**Comment by ricardovh** [comment]
Is fixed already in 7.6, but this should also be fixed in 7.5.

**Comment by jacodg** [comment]
Discussed with Ricardo. For 7.5 he has a workaround so we better spent our time on other things than backporting.

**Comment by ricardovh** [comment]
Workaround is to process the entire message from the sender in the resulthandler (either as XsltSender or in the next adapter). This requires some modifications to the XSLT to process the entire message.
