### ISSUE TITLE
"String:" in output pipe ResultSetIteratingPipe

### ISSUE THREAD

**Issue by VBPham** [ibissource/iaf#884]
**Describe the bug**
ResultSetIteratingPipe seems to preprend "String:" in output

**Reporter**
Vinh Ban Pham

**Category**
 - Frank Framework

**To Reproduce**
Configure adapter with ResultSetIteratingPipe and result will contain "String:"

**Expected behavior**
no "String:" in output result

**Screenshots**
na

**Environment:**
 - IAF Version 7.6-20200624.152104

**Additional context**
2020-06-25 15:31:26,195 DEBUG [Thread-11] mid [Test Tool correlation id] processors.MonitoringPipeProcessor - Pipeline of adapter [HandleScannedDocumentsOut_ProcessXmlFile_Child] messageId [Test Tool correlation id] is about to call pipe [addDocumentFilesToZipStream] current result (Message) [String: <Document>

in the configuration addDocumentFilesToZipStream is a ResultSetIteratingPipe. But now that i look at the logging again i am not sure if its the ResultSetIteratingPipe. Pipe that gives that result is before addDocumentFilesToZipStream is an XsltPipe which seems unlikely aswell. Please let me know if those pipes are not it, I will check at a later time. Probably somewhere a toString instead of asString according to Niels

**Comment by gvanbrakel** [comment]
In the given context, i.e. a log line, the use of toString() and therefor the prefix 'String:' is expected.
Please check the case using the Ladybug debugger.
