### ISSUE TITLE
IAF-Test fails on sequences

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#885]
**Describe the bug**
When running IAF-Test using a database which is not Oracle, testcases fail on the use of sequences in the configurations, as the other databases do not recognize the sequences. This behavior has been observed for MySQL and PostgreSQL, and might apply to other databases to.

**Reporter**
Ricardo

**Category**
 - Frank Framework

**To Reproduce**
1. Install another database type and create the necessary users and schemas
2. Add the database info to the necessary files of IAF-TEst
2. Start the IAF-Test
3. Run the Larva tests
4. See failures on all database-testcases that use sequences

**Expected behavior**
All testcases can be executed independent of the used database, either by translating the queries, having generic testcases that do not depend on the used database, or run specific tests only on specific databases.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Tomcat
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6 SNAPSHOT

**Additional context**
N/A

**Comment by gvanbrakel** [comment]
All scenarios pass for all databases now.
