### ISSUE TITLE
Inconsistent capitalization for database table and column names

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#898]
**Describe the bug**
The capitalization for the table and column names is inconsistent, which can lead to problems if the used database is case sensitive. 

In nl.nn.adapterframework.jdbc.JdbcTransactionalStorage (ibisstore) the table is lowercase, columnnames are camelcase, in the description it is uppercase Oracle and MSSQL but lowercase/camelcase for other databases, in the IAF_DatabaseChangelog.xml it is again uppercase.

In nl.nn.adapterframework.util.Locker (ibislock) the description and IAF_DatabaseChangelog.xml are all uppercase, but in the queries it is camelCase.

IBISCONFIG seems to have everything uppercase.

**Reporter**
Ricardo

**Category**
 - Frank Framework

**To Reproduce**
1. Clone this repository
2. Search for the various table names
3. Compare the various results

**Expected behavior**
Consistent naming so that case sensitive databases do not run into problems.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Tomcat
 - Browser [e.g. chrome, safari]: N/A
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6 SNAPSHOT

Case sensitive issues confirmed with MySQL 8.0.20 on Linux and IAF-Test (set-up from #897 used).

**Additional context**
N/A

**Comment by jacodg** [comment]
We think it's fixed but needs to be tested

**Comment by alisihab** [comment]
verified with the supported databases that the issue is no longer valid
