### ISSUE TITLE
When you stop an adapter, you have to refresh your browser before you see it has stopped

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#900]
**Describe the bug**
In the Frank!Console, I stopped an adapter. The adapter stop button turned into an orange cog as expected. However, the orange cog was not automatically replaced by a green adapter start button. I had to refresh my browser before this happened.

**Reporter**
Martijn Dirkse

**Category**
 - Frank Console

**To Reproduce**
1. Start the Frank!Runner with some config.
2. Expand an adapter on the Adapter Status page.
3. Press its stop button.
4. Wait some time. The orange cog remains there.
5. Refresh your browser page. Only now you see the green adapter start button.

**Expected behavior**
The orange cog should turn into the green adapter start button automatically.

**Screenshots**
![image](https://user-images.githubusercontent.com/6784732/86337950-1098a200-bc52-11ea-86e4-281d33aca995.png)

![image](https://user-images.githubusercontent.com/6784732/86338014-1db59100-bc52-11ea-8ceb-cafbb148dce4.png)

**Environment:**
 - Frank!Runner
 - Microsoft Edge
 - FF! 7.6-20200701.142340

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
It seems to be working fine on all the applications I've tested. How long did you wait? Sometimes it can take longer then 5 seconds before it updates.

**Comment by mhdirkse** [comment]
I have not seen this issue anymore.

**Comment by mhdirkse** [comment]
I tested one more time and I did not reproduce the issue. I did this by loading Frank2Example3 and stopping and starting all adapters. I mean adapter 01 to adapter 04 inclusive.
