### ISSUE TITLE
Our ibis4example website is no longer accessible because it requires authorization

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#920]
**Describe the bug**
When you browse to ibis4example.ibissource.org, you no longer get access to the Frank!Framework. You need to enter a user/password combination. This is a pity, because http://ibis4example.ibissource.org was a useful portal to the Frank!Doc.

**Reporter**
Martijn Dirkse

**Category**
 - Frank Framework

**To Reproduce**
1. Browse to http://ibis4example.ibissource.org 
2. You see a login screen now.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6784732/86949297-b8c8d200-c14e-11ea-87dc-1ab3a23eb88c.png)

**Environment:**
 - Apache Tomcat
 - Microsoft Edge.
 - Unknown, probably a recent version.

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by mhdirkse** [comment]
This also applies to starting the Frank!Framework with the Frank!Runner and accessing it on localhost.

**Comment by Laurens-makel** [comment]
You can still access IbisDoc by using the direct link: https://ibis4example.ibissource.org/iaf/ibisdoc/

**Comment by mhdirkse** [comment]
Thanks, Laurens.

**Comment by mhdirkse** [comment]
Verified.
