### ISSUE TITLE
ForEachChildElement pipe does not show iterations in Ladybug

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#943]
**Describe the bug**
When using a ForEachChildElement pipe, the iterations are not shown in Ladybug. This makes debugging processes in sub adapters really difficult.

![image](https://user-images.githubusercontent.com/37303445/87680953-58edaf00-c77e-11ea-9a08-edf9b5ca2689.png)

**Reporter**
Laurens/Bonno

**Category**
 - Ladybug (debugging tool)

**To Reproduce**
1. Create adapter with ForEachChildElementPipe that iterates atleast over 1 record
2. Call adapter
3. See Ladybug

**Expected behavior**
It should show up in Ladybug.

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Any
 - Browser [e.g. chrome, safari]: Any
 - IAF Version [e.g. 7.5 RC3, 7.6]: Confirmed on 7.6-20200619.094149 - Latest

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by gvanbrakel** [comment]
Could you please share a configuration in which this situation occurs? 
The problem is not found in iaf-test Scenario '\ForEachChildElementPipe\scenario01'

**Comment by bonnoiaf** [comment]
Problem ahppened beause of a namespace in the XML input. Issue can be closed.

**Comment by Laurens-makel** [comment]
Hmm this is weird, exact same configuration is running on two TST nodes, 401 and 416 and sometimes it will show the actual calls to sub adapters and sometimes it wont...

This is on 416:
![image](https://user-images.githubusercontent.com/37303445/87762311-38bbff80-c813-11ea-8607-bc38de24dac3.png)

This is on 401:
![image](https://user-images.githubusercontent.com/37303445/87762379-55583780-c813-11ea-8345-8ba256a08b2b.png)


It's regarding this configuration
[Configuration_UpdateArchivesAndSchemas.zip](https://github.com/ibissource/iaf/files/4936437/Configuration_UpdateArchivesAndSchemas.zip)

**Comment by gvanbrakel** [comment]
I tested in the current 7.6, the iterations are shown normally in Ladybug
