### ISSUE TITLE
Developers should be able to configure to the output type of LocalFileSystemPipe 

### ISSUE THREAD

**Issue by Laurens-makel** [ibissource/iaf#945]
**Reporter**
Laurens/Bonno

**Is your feature request related to a problem? Please describe.**
When looking at the IbisDoc and at the [FileSystemActor class](https://github.com/ibissource/iaf/blob/2eabacadd942924d527fadf0d14027f06853c5ef/core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemActor.java) it seems that the result is always returned as a stream when action="read"

Streams are great, but sometimes you actually want to read the contents of a file instead of passing the stream along.

![image](https://user-images.githubusercontent.com/37303445/87681416-efba6b80-c77e-11ea-936d-26f625d5dedc.png)

**Describe the solution you'd like**
I'd like to see an option to either have a stream or string/text output type.

**Describe alternatives you've considered**
There are some work-arounds possible, but are super ugly. Such as converting to base64 and converting base64 to text or to use the older file pipe..

**Additional context**

**Comment by gvanbrakel** [comment]
Reading the contents should be transparent. If the contents is used multiple times, e.g. also in a parameter, the input is automatically preserved as a String or byte array.
In case you still see a problem, please provide a case that does not work as expected, or works in an undesirable way.

**Comment by Laurens-makel** [comment]
So passing the stream to an xslt pipe would actually be no problem?

**Comment by gvanbrakel** [comment]
Yes, it would be no problem

**Comment by nielsm5** [comment]
Cool! Solved 👍
