### ISSUE TITLE
Without access to our Nexus repository you cannot run the FF! in Eclipse, but connecting to our Nexus repository is not documented

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#946]
**Describe the bug**
I started a new Ubuntu Virtual Machine (Hyper-V under Windows). Then I installed Java and Eclipse and imported the FF! sources. I get a build error that artifact org.ibissource:ibis-ladybug.jar:2.0.15-20200624.163950 is not available. I looked on Maven Central whether this artifact was present. It was not on Maven Central. I expect it to be in our Nexus repository. But in CONTRIBUTING.md, there are no instructions on configuring settings.xml to access our Nexus repository.

**Reporter**
Martijn Dirkse

**Category**
 - Frank Framework

**To Reproduce**
1. Follow the instructions in CONTRIBUTING.md to import the FF! into Eclipse.
2. After Maven Update, view the build errors.

**Expected behavior**
The build should succeed.

**Screenshots**

**Environment:**
 - Ubuntu 18.03, Eclipse 2020-06.
 - Browser not applicable
 - FF! commit 2eabacadd942924d527fadf0d14027f06853c5ef

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by mhdirkse** [comment]
I see two ways to address this issue:
i) We can extend CONTRIBUTING.md with instructions to connect to our Nexus repository. We have to tell then what to put into `~/.m2/settings.xml`. Or
ii) We can make a proper Ladybug release. This solution will only work if the FF! will always reference real Ladybug releases, not versions with a timestamp.

Which solution do we prefer?

**Comment by nielsm5** [comment]
Our `CONTRIBUTING.md` states that we use our own repository for snapshot builds, see: [CONTRIBUTING.md](https://github.com/ibissource/iaf/blob/master/CONTRIBUTING.md#we-use-our-own-repository-manager-for-snapshot-builds-either-use-our-public-ibissource-or-private-proprietary-profile-when-running-maven).
