### ISSUE TITLE
Cannot stop adapter that cannot start

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#970]
**Describe the bug**
I have an adapter that cannot be started because of some missing property. As this adapter is no longer used and will be removed in a next release, there is no need to fix it or have it start anymore. However, every 5 minutes an attempt is done to start the adapter again, resulting in errors in the logging. There is no option to stop the adapter in the interface.

**Reporter**
Ricardo

**Category**
 - Frank Console

**To Reproduce**
1. Have an adapter that cannot start (missing connections)
2. See that there is no stop button
3. The adapter will attempt to be started every 5 minutes

**Expected behavior**
A stop button so I can stop the adapter from being started every 5 minutes

**Screenshots**
![Stop](https://user-images.githubusercontent.com/57142353/88298225-2e14d500-cd01-11ea-8bc7-0c73fd391b1c.png)

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): WebSphere
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.5-RC3

**Additional context**
N/A

**Comment by nielsm5** [comment]
The real error is that the adapter should not be in a 'recovering loop' when it cannot configure.
