### ISSUE TITLE
Limit database operations in Execute query

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#984]
**Reporter**
Ricardo

**Is your feature request related to a problem? Please describe.**
I have a datasource with full access to a database (for liquibase scripts), but I don't want to have users that have the ibisdataadmin role to have the ability to accidentally dropping or modifying tables.

**Describe the solution you'd like**
The possibility to limit which operations can be executed on the Execute Query page, so that DROP and ALTER statements are not allowed.

**Describe alternatives you've considered**
An option on the datasource to hide/disable datasources to be used in the Execute Query page and any associated API's. Then I could have 2 datasources for the same database, 1 with a db-user with all the rights to use for the liquibase script (and other places where the additional rights are needed in the configurations) that fails when used from the GUI/API and 1 with a db-user with limited rights that can only do the 'safe' queries that is available in the GUI and API.

**Additional context**
N/A

**Comment by jacodg** [comment]
It would be better to not have ibisdataadmin enabled in A and P. In case you use ibisdataadmin you should be careful. In case the user cannot be careful you could create a custom view for the actions that are allowed.
