### ISSUE TITLE
Configuration flow not scaled in Firefox on localhost

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#985]
**Describe the bug**
In Firefox the Configuration Flow image in GUI 3.0 is not scaled giving the Configuration Summary a horizontal scrollbar. This happens when running Ibis4Example locally while on https://ibis4example.ibissource.org/iaf/gui/#!/status it works as expected.

**Reporter**
Jaco de Groot

**Category** 
Use following Tags to categorize your bug report
 - Frank Console

**To Reproduce**
1. Start Ibis4Example on local development environment
2. Open the console in Firefox (http://localhost/iaf/gui/#!/status)
3. See the large Configuration Flow image and the horizontal scrollbar at the Configuration Summary

**Expected behavior**
A scaled image without scrollbar like you see in Chrove and on https://ibis4example.ibissource.org/iaf/gui/#!/status

**Screenshots**
![image](https://user-images.githubusercontent.com/2970084/90121144-ed3a3a00-dd5b-11ea-9671-b34d567f990d.png)

**Environment:**
 - Tomcat on localhost
 - Firefox 79.0
 - FF! 7.6-SNAPSHOT

**Additional context**
-

**Comment by nielsm5** [comment]
I had a similar issue when I upgraded my Frank!, I solved it by clearing my cache!
Seems to be a caching issue rather then a browser issue
