### ISSUE TITLE
Show trailing spaces in database values

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#992]
**Describe the bug**
Database values appear to be trimmed, which makes it hard to detect that these values contain trailing spaces or not

**Reporter**
Tarik

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
1. Insert a value with trailing spaces in database
2. Select the value from the console
3. See that trailing spaces are trimmed.

**Expected behavior**

**Screenshots**

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty)
 - IAF Version [e.g. 7.5 RC3, 7.6]

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
@alisihab can you contact Tarik and get some more info on the context
