### ISSUE TITLE
Give better error message in Larva when you do "import" instead of "include"

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#994]
**Reporter**
Martijn Dirkse

**Is your feature request related to a problem? Please describe.**
I was creating a Larva test, but I made a mistake. I used the erroneous property definition "import = common.properties" instead of the correct "include = common.properties". I was seeing an error message that did not help me: "
Property 'adapter.printBridge.className' not found or not valid". I kept on looking to the name of that property and to its value.

**Describe the solution you'd like**
When you have a property without dots and it is not named "include", then report an error like "Please use property 'include' to include a file".

**Describe alternatives you've considered**

**Additional context**

**Comment by jacodg** [comment]
Difficult to fix because it's hard to know when a property is not used (you could also be defining a var)
