### ISSUE TITLE
Upgrade to Spring 5

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#995]
**Reporter**
Jaco de Groot

**Is your feature request related to a problem? Please describe.**
Now we are on Java 8 we can upgrade to Spring 5. Let's do so. :-)

**Describe the solution you'd like**
Upgrade Spring to version 5.

**Describe alternatives you've considered**
\-

**Additional context**
\-

**Comment by nielsm5** [comment]
Currently unable to upgrade to Spring 5 as they broke AnnotationUtils - inherited "java." annotations on superclasses
See https://github.com/spring-projects/spring-framework/issues/23929 for more info about this issue on `AnnotationUtils.findAnnotation(Class, Annotation)` we're using `AnnotationUtils.findAnnotation(Method, Annotation)` where this has not been fixed.
